### ISSUE TITLE
[create-theme]: Tab Radius

### ISSUE THREAD

**Issue by rohankid1** [zen-browser/theme-store#1005]
### Name

Tab Radius

### Description

Lets you set a custom border radius for each side of the tab.

### Homepage

https://github.com/rohankid1/Zen-TabRadius/

### Image

https://i.imgur.com/I687wB8.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
.tabbrowser-tab {
    border-top-left-radius: var(--theme-tabradius-top-left) !important;
    border-top-right-radius: var(--theme-tabradius-top-right) !important;
    border-bottom-left-radius: var(--theme-tabradius-bottom-left) !important;
    border-bottom-right-radius: var(--theme-tabradius-bottom-right) !important;

    &:active {
        & .tab-background {
            border-top-left-radius: var(--theme-tabradius-active-top-left) !important;
            border-top-right-radius: var(--theme-tabradius-active-top-right) !important;
            border-bottom-left-radius: var(--theme-tabradius-active-bottom-left) !important;
            border-bottom-right-radius: var(--theme-tabradius-active-bottom-right) !important;
        }
    }
}
```

### Readme

```markdown
# Tab Radius

This mod allows you to set a custom radius value for the tabs.
You can also customise the border when the tab is active/held on
by the mouse.
```

### Preferences

```json
[
    {
        "property": "theme.tabradius.top.left",
        "type": "string",
        "label": "Set the top left radius",
        "defaultValue": "10px"
    },
    {
        "property": "theme.tabradius.top.right",
        "type": "string",
        "label": "Set the top right radius",
        "defaultValue": "10px"
    },
    {
        "property": "theme.tabradius.bottom.left",
        "type": "string",
        "label": "Set the bottom left radius",
        "defaultValue": "10px"
    },
    {
        "property": "theme.tabradius.bottom.right",
        "type": "string",
        "label": "Set the bottom right radius",
        "defaultValue": "10px"
    },
    {
        "property": "theme.tabradius.active.top.left",
        "type": "string",
        "label": "Set the top left radius when the tab is activated/held on",
        "defaultValue": "10px"
    },
    {
        "property": "theme.tabradius.active.top.right",
        "type": "string",
        "label": "Set the top right radius when the tab is activated/held on",
        "defaultValue": "10px"
    },
    {
        "property": "theme.tabradius.active.bottom.left",
        "type": "string",
        "label": "Set the bottom left radius when the tab is activated/held on",
        "defaultValue": "10px"
    },
    {
        "property": "theme.tabradius.active.bottom.right",
        "type": "string",
        "label": "Set the bottom right radius when the tab is activated/held on",
        "defaultValue": "10px"
    }
]
```
