### ISSUE TITLE
[create-theme]: Hide Bars

### ISSUE THREAD

**Issue by kirillram** [zen-browser/theme-store#1007]
### Name

Hide Bars

### Description

A mod that lets you hide bars even when you are not in the compact mode

### Image

https://kirillram.github.io/images/zen-browser/hidebars.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#urlbar-container {
    background: transparent !important;
}

html[zen-compact-mode="false"] {
    #zen-appcontent-navbar-container[zen-user-show] {
        height: var(--zen-element-separation) !important;
        
        toolbarbutton {
            opacity: 0 !important;
        }
        
        .titlebar-buttonbox-container {
            opacity: 0 !important;
        }
        
        #urlbar:not([open]) {
            opacity: 0 !important;   
            height: 0 !important;
            width: 0 !important;
        }
    }

    #navigator-toolbox[zen-user-show] {
        display: none !important;
        
        html:not([zen-right-side="true"]) & ~ #zen-appcontent-wrapper .titlebar-buttonbox-container {
            margin-left: -6px !important;
        }
        

        &[zen-sidebar-expanded="true"] {
            ~ #zen-sidebar-splitter {
                display: none !important;
            }

            ~ #zen-appcontent-wrapper {
                padding-left: var(--zen-element-separation);
            }

            html[zen-right-side="true"] & ~ #zen-appcontent-wrapper {
                padding-right: var(--zen-element-separation);
                padding-left: 0;
            }
        }

        ~ #zen-appcontent-wrapper {
            padding-left: var(--zen-element-separation);
        }

        html[zen-right-side="true"] & ~ #zen-appcontent-wrapper {
            padding-right: var(--zen-element-separation);
            padding-left: 0;
        }
    }
}
```

### Readme

```markdown
To hide the bars use the same shortcuts as in compact mode.
```

### Preferences

```json

```
