### ISSUE TITLE
[create-theme]: Zero Padding Sidebar

### ISSUE THREAD

**Issue by gunir** [zen-browser/theme-store#102]
### Name

Zero Padding Sidebar

### Description

Remove padding from the sidebar.

### Homepage

https://github.com/gunir/theme-store/tree/mine/mine/absolutezero

### Image

https://raw.githubusercontent.com/gunir/theme-store/mine/mine/absolutezero/image.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
:root * {
  --zen-sidebar-action-button-width:36px !important;
  --toolbarbutton-inner-padding: unset!important;
  --zen-tabbrowser-padding: 0px!important;
  --tab-min-width: 36px!important;
}

/* Fix scrollbar visible issue when having a lot of tabs */
#tabbrowser-arrowscrollbox {
  scrollbar-width: none
}

#zen-workspaces-button {
  border: unset!important;
}

.tabbrowser-tab, .toolbarbutton-1 {
  margin: unset!important;
  padding: unset!important;
  margin-left: 0px!important;
}

#zen-sidebar-icons-wrapper {
  align-items: unset!important;
}
```

### Readme

```markdown
Remove padding from the sidebar.
```
