### ISSUE TITLE
[create-theme]: ShadowBlue

### ISSUE THREAD

**Issue by Mohab0P** [zen-browser/theme-store#1025]
### Name

ShadowBlue

### Description

A dark theme with cyan glow and a sleek, modern look.

### Homepage

https://github.com/Mohab0P/Zen-Theme-ShadowBlue

### Image

https://imgur.com/a/hFRhzhl

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
:root {
      --background-color: #0a0a0a !important;
      --text-color: #ffffff !important;
      --primary-accent: #00d9ff !important;
      --secondary-accent: #ff6d6d !important;
      --glow-effect: 0 0 8px rgba(0, 217, 255, 0.253) !important;
      --border-color: rgba(0, 217, 255, 0.8) !important;
      --zen-colors-primary: #ff6d6d !important;
      --zen-colors-secondary: #ff6d6d !important;
      --zen-colors-tertiary: #0a0a0a !important;
      --zen-colors-border: rgba(7, 164, 236, 0.568) !important;
      --zen-dialog-background: #0a0a0a !important;
  }

  /* Button Styles */
  button, .button {
      background-color: var(--zen-colors-border) !important;
      border: 1px solid var(--border-color) !important;
      color: var(--text-color) !important;
      padding: 10px 20px !important;
      border-radius: 8px !important;
      cursor: pointer !important;
      box-shadow: var(--glow-effect) !important;
      transition: transform 0.2s ease-in-out, background-color 0.3s ease-in-out !important;
  }
    
  button:hover, .button:hover {
      transform: scale(1.05) !important;
      background-color: var(--secondary-accent) !important;
  }

  /* Navbar & Toolbar */
  #navigator-toolbox, #nav-bar, #PersonalToolbar {
      border: 1px solid var(--zen-colors-border) !important;
      border-radius: 8px !important;
      margin: 2px !important;
      padding: 4px !important;
  }

  #nav-bar, #TabsToolbar, #zen-sidebar-top-buttons {
      background-color: var(--background-color) !important;
  }

  /* Titlebar Button Styling */
  hbox.titlebar-buttonbox-container:nth-child(8) {
      color: var(--primary-accent) !important;
  }

  /* Toolbar Field Focus */
  toolbarbutton, #urlbar {
      color: var(--zen-colors-border) !important;
  }

  /* Active Tab Indicator */
  .tab-background[selected]::after {
      content: "" !important;
      background-color: var(--primary-accent) !important;
      position: absolute !important;
      left: 0 !important;
      width: 4px !important;
      height: 100% !important;
      border-radius: 2px !important;
  }
```

### Readme

```markdown
ShadowBlue is a sleek dark theme with vibrant cyan highlights.
```

### Preferences

```json

```
