### ISSUE TITLE
[create-theme]: Hide Current Workspace Indicator

### ISSUE THREAD

**Issue by michaellauwereys** [zen-browser/theme-store#1033]
### Name

Hide Current Workspace

### Description

Hide the current workspace indicator from the sidebar.

### Image

https://i.imgur.com/Pigx3bV.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#zen-current-workspace-indicator {
    display: none !important;
}
```

### Readme

```markdown
# Hide Current Workspace Indicator

Hide the current workspace indicator from the sidebar. This saves some space for more tabs.
```

### Preferences

```json

```
