### ISSUE TITLE
[create-theme]: Inner Peace

### ISSUE THREAD

**Issue by Lancear** [zen-browser/theme-store#1036]
### Name

Inner Peace

### Description

Easily unify, hide, and tweak the most common features in Zen. · Fully customizable · See GitHub for details ·

### Homepage

https://github.com/Lancear/zen-inner-peace

### Image

https://github.com/Lancear/zen-inner-peace/blob/main/thumbnail.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
/*
Interesting advanced settings:
- zen.view.sidebar-collapsed.hide-mute-button => false
- browser.tabs.allow_transparent_browser => false
- zen.workspaces.show-workspace-indicator => false
- zen.urlbar.replace-newtab
*/



/* ----- Typeahead Find ----- */

/* Open full find with all options */
.findbar-container > checkbox[hidden] {
  display: flex !important;
}



/* ----- Urlbar ----- */

/* Center url in (non floating) urlbar */
#urlbar-input:not([aria-expanded="true"]) {
  text-align: center !important;
}



/* ----- Mute Tab Button ----- */

/* Resize */
.tab-icon-overlay {
  width: 14px !important;
  height: 14px !important;
}

/* Reposition */
.tab-icon-overlay {
  top: -8px !important;
  right: -6px !important;
}



/* ----- Close Tab Button ----- */

/* Close tab button in the style of the mute button */
:root:not([zen-sidebar-expanded]) tab:hover .tab-close-button {
  display: inline-flex !important;
  
  width: 0.1px !important;
  height: 0.1px !important;
  padding: 0.02px !important;
  transform: scale(140);
  
  position: relative;
  top: -9px;
  right: 2.5px;
  
  background: #ffffff;
  margin-inline: 0 !important;
}

:root:not([zen-sidebar-expanded]) tab:hover .tab-close-button:hover {
  background: #ffffff !important;
}

/* Rescale */
:root:not([zen-sidebar-expanded]) tab:hover .tab-close-button {
  transform: scale(140);
}

/* Reposition */
:root:not([zen-sidebar-expanded]) tab:hover .tab-close-button {
  top: -9px;
  right: 2.5px;
}



/* ----- Clean up spacing ----- */

/* Add vertical spacing around the toolbar */
:root:not([zen-single-toolbar]) #zen-appcontent-navbar-container {
  padding-top: 4px;
  padding-bottom: 4px;
}

/* Horizontally align the toolbar */
:root:not([zen-sidebar-expanded]) #nav-bar {
  margin-left: 0 !important;
}

:root:not([zen-sidebar-expanded]) #PersonalToolbar,
:root:not([zen-right-side="true"]) #PersonalToolbar {
  padding-inline-start: 0px !important;
}

:root:not([zen-compact-mode="true"]) #PersonalToolbar {
  padding-inline-end: 0px !important;
}

#nav-bar #PanelUI-button:last-of-type toolbarbutton {
  padding-right: 0 !important;
}

#nav-bar #nav-bar-overflow-button {
  padding-right: 0px !important;  
}

/* Add horizontal spacing around the sidebar */
:root:not([zen-sidebar-expanded]) {
  --zen-toolbox-padding: 5px !important;
}

:root[zen-right-side="true"] #zen-tabbox-wrapper {
  padding-right: 2px;
}

:root:not([zen-right-side="true"]) #zen-tabbox-wrapper {
  padding-left: 2px;
}

/* Vertically align the sidebar */
#zen-main-app-wrapper:has(#PersonalToolbar[collapsed="true"]) {
  --personal-toolbar-height: 0px;
}

#zen-main-app-wrapper:has(#PersonalToolbar[collapsed="false"]) {
  --personal-toolbar-height: 28px;
}

:root:not([zen-single-toolbar]):not([zen-sidebar-expanded]) #navigator-toolbox {
  padding-top: calc(8px + var(--personal-toolbar-height)) !important;
}

:root:not([zen-single-toolbar])[zen-sidebar-expanded] #zen-sidebar-top-buttons {
  margin-bottom: calc(4px + var(--personal-toolbar-height)) !important;
}

/* Add small spacing on the right of the window buttons */
.titlebar-buttonbox-container {
  padding-right: 4px;
}



/* ----- Hide Anything ----- */

/* 
#back-button {
  display: none;
}

#forward-button {
  display: none;
}

#identity-box {
  display: none;
}

.urlbar-input-box {
  padding-left: 6px;
}

#nav-bar {
  margin-left: 0 !important;;
}

#tracking-protection-icon-container {
  display: none;
}

#unified-extensions-button {
  display: none;
}

#PanelUI-menu-button {
  display: none;
}

.titlebar-min {
  display: none;
}

.titlebar-restore {
  display: none;
}

.titlebar-close {
  display: none;
}

#contextual-feature-recommendation {
  display: none;
}

#userContext-label {
  display: none;
}

#userContext-indicator {
  display: none;
}
 */
#userContext-icons {
  display: none;
}
/* 
#reader-mode-button {
  display: none;
}

#picture-in-picture-button {
  display: none;
}

#translations-button {
  display: none;
}

#shopping-sidebar-button {
  display: none;
}

#urlbar-zoom-button {
  display: none;
}

#pageActionButton {
  display: none;
}

#zen-split-views-button {
  display: none;
}

#star-button-box {
  display: none;
} */

/* remove workspace button from toolbar */
/* #zen-workspaces-button {
  display: none !important;
} */


/* hide pinned tab reset button */
/* .tab-reset-button {
  display: none !important;
} */

/* hide close tab button */
/* .tab-close-button {
  display: none !important;
} */

.tab-icon-pending {
/*   display: none !important; */
}

.tab-throbber {
/*   display: none !important; */
}

.tab-icon-image[sharing] {
/*   animation: none !important; */
}

.tab-sharing-icon-overlay {
/*   display: none !important; */
}

.tab-icon-overlay {
/*   display: none !important; */
}

.tab-icon-stack {
/*   display: none !important; */
}

.tab-content {
/*   background: none !important; */
/*   padding-left: 10px !important; */
}



/* ----- WIP macos window buttons ----- */

/* macos inspired window buttons */
/* .titlebar-buttonbox {
  padding-right: 12px;
  
  display: flex !important;
  align-items: center;
  gap: 6px;
} */

/* macos inspired window buttons */
/* .titlebar-button {
  padding: 0 !important;
  
  height: 14px;
  width: 14px;
  
  border-radius: 100%;
  background: #aaaaaa !important;
} */

/* macos inspired window buttons */
/* .titlebar-min:hover {
  background: #1aab29 !important;
}
 */
/* macos inspired window buttons */
/* .titlebar-restore:hover {
  background: #ffbd2e !important;
}
 */
/* macos inspired window buttons */
/* .titlebar-close:hover {
  background: #e0443e !important;
}
 */
/* macos inspired window buttons */
/* .titlebar-button .toolbarbutton-icon {
  display: none !important;
} */
```

### Readme

```markdown
# Lancear's Inner Peace [Zen Mod]
Easily unify, hide, and tweak the most common features in Zen.<br>
· Fully customizable · See GitHub for details ·

![Thumbnail](./thumbnail.png)

## Features
- [Unify Gaps / Spacing](#unify-gaps--spacing)
- [Remove anything from urlbar / toolbar / tabs](#remove-anything-from-urlbar--toolbar--tabs)
- [Show all find options in quick find](#show-all-find-options-in-quick-find)
- [Mute tab button / Audio playing indicator](#mute-tab-button--audio-playing-indicator)
- [Close tab button in collapsed toolbar](#close-tab-button-in-collapsed-toolbar)
- [Center url in urlbar](#center-url-in-urlbar)

## Unify Gaps / Spacing
- Adds vertical spacing around the toolbar
- Adds horizontal spacing around the sidebar
- Aligns the right side of the personal toolbar with the right side of the browser content (see history button).
- Aligns the top of the sidebar with the top of the browser content (adjusts for personal toolbar if enabled).

Before:
![Before](https://github.com/user-attachments/assets/489563d0-6506-4282-9e34-3b9edbafe21e)

After:
![After](https://github.com/user-attachments/assets/a4abddbf-fcf7-4afa-9afb-56375704c26a)
![After without bookmarks](https://github.com/user-attachments/assets/22566c36-49e8-44b9-84fc-6ea6bc335783)
![After with left sidebar](https://github.com/user-attachments/assets/1741ac0c-736c-4a75-8221-5b5c4ddecfa0)

## Remove anything from urlbar / toolbar / tabs
Remove literally anything. If you find something that I forgot, please let me know!

![Empty urlbar and toolbar](https://github.com/user-attachments/assets/7b400476-2af2-458e-96ac-2b1dc71d73b6)
![No indicators and buttons on tabs](https://github.com/user-attachments/assets/365fe8d5-1a1b-40d7-a396-777b6fc30997)

## Show all find options in quick find
Shows you all the options, even in quick find.

![Where to enable quick find](https://github.com/user-attachments/assets/75dd9c81-2efe-44d8-b9c9-d8469d8dce52)

Before:
![Before](https://github.com/user-attachments/assets/eadc11c2-8cfb-4943-bf18-6b17b9725556)

After:
![After](https://github.com/user-attachments/assets/d010632c-032e-4404-bbfa-27628cd5b900)

## Mute tab button / Audio playing indicator
Allows you to move and style the mute button, even in the collaped toolbar.<br>
Comes with some positioning and styling options so it can be nicely combined with the close tab button.

![Adjusted mute tab icon](https://github.com/user-attachments/assets/2b7e02c7-3027-4756-93c5-e2c0044c4f00)

## Close tab button in collapsed toolbar
Shows a close button on tabs in the collapsed toolbar.<br>
Comes with some positioning and styling options so it can be nicely combined with the mute tab button.

![Close tab icon in collapsed toolbar](https://github.com/user-attachments/assets/ce3f377d-293c-468b-a461-bff1f497be41)

## Center url in urlbar
Simply centers the url in the urlbar when not floating.

![Centered url in urlbar](https://github.com/user-attachments/assets/c5f98dda-1caa-4aaa-b195-ad92d17f0102)
```

### Preferences

```json
[
  {
    "property": "lancear.inner-peace.typeahead-find",
    "label": "· Typeahead Find ·",
    "type": "checkbox",
    "defaultValue": true,
    "disabledOn": ["windows", "linux", "macos"]
  },
  {
    "property": "lancear.inner-peace.typeahead-find.show-full-find",
    "label": "Open full find with all options",
    "type": "checkbox",
  },
  {
    "property": "lancear.inner-peace.urlbar",
    "label": "· Urlbar ·",
    "type": "checkbox",
    "defaultValue": true,
    "disabledOn": ["windows", "linux", "macos"]
  },
  {
    "property": "lancear.inner-peace.urlbar.center-url",
    "label": "Center url in (non floating) urlbar",
    "type": "checkbox",
  },
  {
    "property": "lancear.inner-peace.mute-tab-button",
    "label": "· Mute Tab Button ·",
    "type": "checkbox",
    "defaultValue": true,
    "disabledOn": ["windows", "linux", "macos"]
  },
  {
    "property": "lancear.inner-peace.mute-tab-button.resize",
    "label": "Resize",
    "type": "checkbox",
  },
  {
    "property": "lancear.inner-peace.mute-tab-button.size",
    "label": "Size",
    "type": "string",
    "defaultValue": "16px",
  },
  {
    "property": "lancear.inner-peace.mute-tab-button.reposition",
    "label": "Reposition",
    "type": "checkbox",
  },
  {
    "property": "lancear.inner-peace.mute-tab-button.resize",
    "label": "Top",
    "type": "string",
    "defaultValue": "-8px",
  },
  {
    "property": "lancear.inner-peace.mute-tab-button.resize",
    "label": "Right",
    "type": "string",
    "defaultValue": "-6px",
  },
  {
    "property": "lancear.inner-peace.close-tab-button",
    "label": "· Mute Tab Button ·",
    "type": "checkbox",
    "defaultValue": true,
    "disabledOn": ["windows", "linux", "macos"]
  },
  {
    "property": "lancear.inner-peace.close-tab-button.show",
    "label": "Show",
    "type": "checkbox",
  },
  {
    "property": "lancear.inner-peace.close-tab-button.resize",
    "label": "Resize",
    "type": "checkbox",
  },
  {
    "property": "lancear.inner-peace.close-tab-button.size",
    "label": "Size (px * 10 without 'px' suffix)",
    "type": "string",
    "defaultValue": "140",
  },
  {
    "property": "lancear.inner-peace.close-tab-button.reposition",
    "label": "Reposition",
    "type": "checkbox",
  },
  {
    "property": "lancear.inner-peace.close-tab-button.resize",
    "label": "Top",
    "type": "string",
    "defaultValue": "-9px",
  },
  {
    "property": "lancear.inner-peace.close-tab-button.resize",
    "label": "Right",
    "type": "string",
    "defaultValue": "2.5px",
  },
  {
    "property": "lancear.inner-peace.clean-up-spacing",
    "label": "· Clean Up Spacing ·",
    "type": "checkbox",
    "defaultValue": true,
    "disabledOn": ["windows", "linux", "macos"]
  },
  {
    "property": "lancear.inner-peace.clean-up-spacing.vertical-toolbar-spacing",
    "label": "Add vertical spacing around the toolbar",
    "type": "checkbox"
  },
  {
    "property": "lancear.inner-peace.clean-up-spacing.horizontal-toolbar-alignment",
    "label": "Horizontally align the toolbar",
    "type": "checkbox"
  },
  {
    "property": "lancear.inner-peace.clean-up-spacing.horizontal-sidebar-spacing",
    "label": "Add horizontal spacing around the sidebar",
    "type": "checkbox"
  },
  {
    "property": "lancear.inner-peace.clean-up-spacing.vertical-sidebar-alignment",
    "label": "Vertically align the sidebar",
    "type": "checkbox"
  },
  {
    "property": "lancear.inner-peace.clean-up-spacing.horizontal-sidebar-spacing",
    "label": "Personal / Bookmarks toolbar height",
    "type": "string",
    "defaultValue": "28px"
  },
  {
    "property": "lancear.inner-peace.clean-up-spacing.right-window-buttons-spacing",
    "label": "Add small spacing on the right of the window buttons",
    "type": "checkbox"
  },
]
```
