### ISSUE TITLE
[create-theme]: Allow Toolbar Theming

### ISSUE THREAD

**Issue by ch4og** [zen-browser/theme-store#104]
### Name

Allow Toolbar Theming

### Description

This allows you to use Firefox themes to customize your toolbar

### Homepage

https://github.com/ch4og/zenbrowser-themes/tree/main/Allow%20Toolbar%20Theming

### Image

https://raw.githubusercontent.com/ch4og/zenbrowser-themes/main/Allow%20Toolbar%20Theming/image.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@media (-moz-bool-pref: "zen.tabs.vertical") {
  #navigator-toolbox {
    --zen-navigator-toolbox-background: var(--lwt-additional-images);
  }
}
```

### Readme

```markdown
This allows you to use Firefox themes to customize your toolbar
```
