### ISSUE TITLE
[create-theme]: Zenimations

### ISSUE THREAD

**Issue by sameerasw** [zen-browser/theme-store#1048]
### Name

Zenimations

### Description

Zen + Animations to improve the browsing experience

### Homepage

https://github.com/sameerasw/zen-themes/tree/main/Zenimations

### Image

https://github.com/sameerasw/zen-themes/blob/main/Zenimations/zenimations-logo.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
.browserStack browser{
		transition: all 0.3s cubic-bezier(0.175, 0.885, 0.32, 1.1) 0.1s !important;
}

.browserStack:has(#historySwipeAnimationPreviousArrow:not([style="translate: none;"]  )) browser  {
	scale: 0.95 !important;
	transform: translateX(3%) !important;    
	border-radius: 2em !important;
}


.browserStack:has(#historySwipeAnimationNextArrow:not([style="translate: none;"]  )) browser  {
	scale: 0.95 !important;
	transform: translateX(-3%) !important;  
	border-radius: 2em !important;
}
```

### Readme

```markdown
Zen + Animations to improve the browsing experience

- Zen trackpad forward/ back navigation gesture
```

### Preferences

```json

```
