### ISSUE TITLE
[create-theme]: Immersive Search

### ISSUE THREAD

**Issue by LucHermkens** [zen-browser/theme-store#1053]
### Name

Immersive Search

### Description

Transforms the look of the URL bar in your Zen Browser to have a dark and blurry background.

### Homepage

https://github.com/LucHermkens/immersive-search

### Image

https://i.imgur.com/yU1xKVa.png

### Type

- [x] JSON Color Theme

### Theme Styles

```css
#urlbar[open][zen-floating-urlbar="true"] {
    top: 50% !important;
    transform: translateX(calc(var(--zen-sidebar-width, 273px) / 2)) translateY(-50%) !important;
}

.browserContainer {
    will-change: filter;
    transition: filter 0.2s ease-out;
}

#zen-appcontent-wrapper:has(#urlbar[zen-floating-urlbar="true"]) .browserContainer {
    filter: blur(5px);
}

#tabbrowser-tabbox::before {
    content: "";
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    user-select: none;
    pointer-events: none;
    border-radius: var(--zen-native-inner-radius);

    will-change: background-color;
    background-color: rgba(0, 0, 0, 0);
    transition: background-color 0.2s ease-out;
}

#zen-appcontent-wrapper:has(#urlbar[zen-floating-urlbar="true"]) #tabbrowser-tabbox::before {
    background-color: rgba(0, 0, 0, 0.5);
}
```

### Readme

```markdown
# Immersive Search

Transforms the look of the URL bar in your Zen Browser to have a dark and blurry background.
```

### Preferences

```json

```
