### ISSUE TITLE
[create-theme]: NoFlash

### ISSUE THREAD

**Issue by ndit-dev** [zen-browser/theme-store#1058]
### Name

NoFlash

### Description

Prevents white screen flashes during page loads when using dark mode extensions.

### Homepage

https://github.com/ndit-dev/NoFlash

### Image

https://github.com/ndit-dev/NoFlash/blob/main/image.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@-moz-document url("about:newtab") {
  body {
    background-color: #1A1A1A !important;
  }
}
@-moz-document url(chrome://browser/content/browser.xhtml) {
  browser[type="content-primary"] {background: #1A1A1A !important}
}
```

### Readme

```markdown
Eliminate the jarring white flash that occurs during page loads when using dark mode. This mod ensures a seamless dark browsing experience by maintaining a dark background during page transitions, preventing unexpected bright flashes that can strain your eyes.
```

### Preferences

```json

```
