### ISSUE TITLE
[create-theme]: PDF Dark Mode

### ISSUE THREAD

**Issue by ndit-dev** [zen-browser/theme-store#1060]
### Name

PDF Dark Mode

### Description

View PDFs in dark mode for comfortable reading and reduced eye strain

### Homepage

https://github.com/ndit-dev/PDF-Dark-Mode

### Image

https://raw.githubusercontent.com/ndit-dev/PDF-Dark-Mode/refs/heads/main/image.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#viewerContainer > #viewer > .page > .canvasWrapper > canvas {
  background-color: #1a1a1a !important; 
  filter: invert(94%) hue-rotate(180deg);
}
```

### Readme

```markdown
Eliminate the jarring white flash that occurs during page loads when using dark mode. This mod ensures a seamless dark browsing experience by maintaining a dark background during page transitions, preventing unexpected bright flashes that can strain your eyes.
```

### Preferences

```json

```
