### ISSUE TITLE
[create-theme]: Hide Browser Buttons

### ISSUE THREAD

**Issue by x4132** [zen-browser/theme-store#1065]
### Name

Hide Browser Buttons

### Description

Allows you to hide the page action buttons in the browser URL bar, such as the reader and bookmark buttons.

### Homepage

Allows you to hide the page action buttons in the browser URL bar.

### Image

https://img.x4132.dev/01JKYB5VT4XNN6F0X4MZXPN7EM/promo_image.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@media (-moz-bool-pref: "mod.hidden_action_buttons.bookmarks") {
  #star-button-box {
    visibility: hidden;
    display: none;
  }
}

@media (-moz-bool-pref: "mod.hidden_action_buttons.readermode") {
    #reader-mode-button {
        visibility: hidden;
        display: none;
    }
}

@media (-moz-bool-pref: "mod.hidden_action_buttons.picture_in_picture") {
    #picture-in-picture-button {
        visibility: hidden;
        display: none;
    }
}

@media (-moz-bool-pref: "mod.hidden_action_buttons.translations") {
    #translations-button {
        visibility: hidden;
        display: none;
    }
}

@media (-moz-bool-pref: "mod.hidden_action_buttons.shopping_sidebar") {
    #shopping-sidebar-button {
        visibility: hidden;
        display: none;
    }
}

@media (-moz-bool-pref: "mod.hidden_action_buttons.page_action") {
    #pageActionButton {
        visibility: hidden;
        display: none;
    }
}

@media (-moz-bool-pref: "mod.hidden_action_buttons.zen_split_views") {
    #zen-split-views-box {
        visibility: hidden;
        display: none;
    }
}
```

### Readme

```markdown
# Hide Browser Buttons

Allows you to hide the page action buttons in the browser URL bar.
This includes the bookmarks button, reader mode, picture in picture, translator, shopping sidebar and split views buttons.
```

### Preferences

```json
[
    {
        "property": "mod.hidden_action_buttons.bookmarks",
        "label": "Hide Bookmark Button",
        "type": "checkbox"
    },
    {
        "property": "mod.hidden_action_buttons.readermode",
        "label": "Hide Reader Mode Button",
        "type": "checkbox"
    },
    {
        "property": "mod.hidden_action_buttons.picture_in_picture",
        "label": "Hide Picture in Picture Button",
        "type": "checkbox"
    },
    {
        "property": "mod.hidden_action_buttons.translations",
        "label": "Hide Translations Button",
        "type": "checkbox"
    },
    {
        "property": "mod.hidden_action_buttons.shopping_sidebar",
        "label": "Hide Shopping Sidebar Button",
        "type": "checkbox"
    },
    {
        "property": "mod.hidden_action_buttons.page_action",
        "label": "Hide Page Action Button",
        "type": "checkbox"
    },
    {
        "property": "mod.hidden_action_buttons.zen_split_views",
        "label": "Hide Zen Split Views Button",
        "type": "checkbox"
    }
]
```
