### ISSUE TITLE
[create-theme]: Minimal Bookmarks

### ISSUE THREAD

**Issue by Ranamzes** [zen-browser/theme-store#1069]
### Name

Minimal Bookmarks

### Description

A minimal theme that hides bookmark text in the bookmarks bar, showing only icons for a cleaner look.

### Homepage

https://github.com/Ranamzes/ZenBrowser-Mods/tree/main/minimal-bookmarks

### Image

https://github.com/Ranamzes/ZenBrowser-Mods/blob/main/minimal-bookmarks/preview.png?raw=true

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@-moz-document url-prefix('chrome://') {
    /* Hide text in bookmarks bar */
    #PlacesToolbarItems > .bookmark-item .toolbarbutton-text {
        display: none !important;
    }
    #PlacesToolbarItems > .bookmark-item {
        padding-right: 0 !important;
    }
}
```

### Readme

```markdown
# Minimal Bookmarks for Zen Browser

A minimal theme that hides bookmark text in the bookmarks bar, showing only icons for a cleaner look.

## Features
- Clean bookmarks bar with icons only
- Space-efficient design
- Perfect for minimalist setups
- Compatible with both light and dark themes

## Preview
![Minimal Bookmarks Theme Preview](preview.png)

## Development
This theme is open source and available on GitHub. Feel free to contribute!

## Author
Re•MART
```

### Preferences

```json

```
