### ISSUE TITLE
[create-theme]: Tiny Compact Mode

### ISSUE THREAD

**Issue by n7itro** [zen-browser/theme-store#107]
### Name

Tiny Compact Mode

### Description

An even more compact Compact Mode!

### Homepage

https://github.com/n7itro/Zen-Themes

### Image

https://i.imgur.com/ujvQeeN.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
/* Reduced space from edge */   
@media (-moz-bool-pref: "uc.sidebar.no-edge-padding") and (-moz-bool-pref: "zen.view.compact") {
    :root[sizemode="maximized"] #navigator-toolbox {
        --zen-compact-toolbox-margin-single: 0px !important;
    }
}

/* Reduced tab sidebar height */
@media (-moz-bool-pref: "uc.sidebar.reduced-height") and (-moz-bool-pref: "zen.view.compact") {
    #navigator-toolbox {
        padding-top: 12.5vh !important;
        height: 75vh !important;
    }
}

@media (-moz-bool-pref "uc.sidebar.hide-expand-compact") and (-moz-bool-pref: "zen.view.compact") {
   #zen-expand-sidebar-button {
      display: none !important;
   }
}

@media (-moz-bool-pref "uc.sidebar.hide-history-compact") and (-moz-bool-pref: "zen.view.compact") {
   #zen-history-button {
     display: none !important;
   }
}

@media (-moz-bool-pref "uc.sidebar.hide-profile-compact") and (-moz-bool-pref: "zen.view.compact") {
   #zen-profile-button {
     display: none !important;
   }
}
   
@media (-moz-bool-pref "uc.sidebar.hide-bookmark-compact") and (-moz-bool-pref: "zen.view.compact") {
   #zen-bookmark-button {
     display: none !important;
   }
}

@media (-moz-bool-pref "uc.sidebar.hide-preferences-compact") and (-moz-bool-pref: "zen.view.compact") {
   #zen-preferences-button {
     display: none !important;
   }
}

@media (-moz-bool-pref "uc.sidebar.hide-sidepanel-compact") and (-moz-bool-pref: "zen.view.compact") {
   #zen-sidepanel-button {
     display: none !important;
   }
}

@media (-moz-bool-pref "uc.sidebar.hide-alltabs-compact") and (-moz-bool-pref: "zen.view.compact") {
   #alltabs-button {
     display: none;
   }
}
```

### Readme

```markdown
With this theme you can make the compact mode even more compact!
- Hide buttons on the sidebar while in compact mode
- Reduce the height of the compact sidebar
- More!

Each of these options can be enabled separately by changing the configuration in the settings page.
```

### Preferences

```json
{
  "uc.sidebar.no-edge-padding": "Remove space between screen edge and tab sidebar while in compact mode",
  "uc.sidebar.reduced-height": "Reduce tab sidebar height while in compact mode",
  "uc.sidebar.hide-expand-compact": "Hide the expand sidebar button while in compact mode",
  "uc.sidebar.hide-history-compact": "Hide the history button while in compact mode",
  "uc.sidebar.hide-profile-compact": "Hide the profile button while in compact mode",
  "uc.sidebar.hide-bookmark-compact": "Hide the bookmark button while in compact mode",
  "uc.sidebar.hide-preferences-compact": "Hide the preferences button while in compact mode",
  "uc.sidebar.hide-sidepanel-compact": "Hide the show sidepanel button while in compact mode",
  "uc.sidebar.hide-alltabs-compact": "Hide the show all tabs button while in compact mode"
}
```
