### ISSUE TITLE
[create-theme]: Modern Audio Indicator

### ISSUE THREAD

**Issue by M1ke000** [zen-browser/theme-store#1076]
### Name

Modern Audio Indicator

### Description

Small tweaks to make the audio indicator look cleaner and more visible

### Image

https://i.ibb.co/4b8pHmj/zen-Av9v9-Kvw-Ja.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
.tab-icon-overlay {
  border: none !important;
  background-color: transparent !important;
  transform: scale(1.4) !important;
  &:hover {
    transform: scale(1.7) !important;
    transition: transform 200ms ease-in-out, fill 100ms ease-in-out
  }
}
```

### Readme

```markdown
# Modern Audio Indicator

Removes the ugly background from the indicator, makes it bigger and expands when hovered.
```

### Preferences

```json

```
