### ISSUE TITLE
[create-theme]: Only Reset Pinned Tabs (Hide the option to remove pinned tabs)

### ISSUE THREAD

**Issue by send-me-a-ticket** [zen-browser/theme-store#1082]
### Name

OnlyReset

### Description

Removes the close button from pinned tabs, preventing accidental closure. Only reset is allowed.

### Homepage

https://github.com/send-me-a-ticket/zen-browser-only-reset-pinned-tabs/

### Image

https://raw.githubusercontent.com/send-me-a-ticket/zen-browser-only-reset-pinned-tabs/refs/heads/main/zen-mods-onlyreset-pinnedtabs.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#tabbrowser-tabs {
  & .tabbrowser-tab {
    &[pinned]:not([zen-essential]):hover .tab-close-button,
    &[pinned][visuallyselected]:not([zen-essential]) .tab-close-button {
      display: none !important;
    }
    &[pinned]:not([zen-essential]):hover .tab-reset-button {
      display: block !important;
    }
    &[pinned]:not([zen-essential]) .tab-reset-button {
      display: none !important;
    }
  }
}
```

### Readme

```markdown
# OnlyReset – Non-Removable Pinned Tabs

OnlyReset enhances Zen Browser by removing the "close tab" button from pinned tabs, ensuring they remain permanently available in your workspace. With this mod, the only option for pinned tabs is to reset them, preventing accidental closures and improving workflow efficiency.

✅ Prevents accidental tab closures
✅ Reset the tab to original state
✅ Save memory to improve performance
✅ Use right-click menu to close tab when needed

Install OnlyReset today and keep your pinned tabs secure!
```

### Preferences

```json

```
