### ISSUE TITLE
[create-theme]: Floating Blur

### ISSUE THREAD

**Issue by S42yt** [zen-browser/theme-store#1089]
### Name

Floating Blur

### Description

This Mod/Theme animates the Floating URL Bar in Zen and also blurs the background when its opened.

### Homepage

https://github.com/S42yt/Zen-Mods

### Image

https://imgur.com/a/yQnvSJZ

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#browser:has(#urlbar[open][zen-floating-urlbar="true"], #searchbar:focus-within) .browserContainer {
    pointer-events: none;
    transform-origin: center;
    filter: blur(10px) brightness(70%) saturate(50%) opacity(70%) !important;
    transition: all 0.3s cubic-bezier(0.19, 1, 0.22, 1) !important;
}

#urlbar[open][zen-floating-urlbar="true"],
#searchbar:focus-within {
    animation: urlbarFloat 0.3s cubic-bezier(0.19, 1, 0.22, 1) forwards;
    backdrop-filter: blur(8px);
    transform-origin: top;
}

@keyframes urlbarFloat {
    0% {
        transform: translateY(-5px) scale(0.98);
        opacity: 0;
    }
    100% {
        transform: translateY(0) scale(1);
        opacity: 1;
    }
}

#urlbar[zen-floating-urlbar="true"],
#searchbar {
    transition: all 0.3s cubic-bezier(0.19, 1, 0.22, 1);
}

.browserContainer {
    transition: all 0.3s cubic-bezier(0.19, 1, 0.22, 1) !important;
}
```

### Readme

```markdown
# Floating Blur

This Mod/Theme animates the Floating URL Bar in Zen and also blurs the background when its opened.


<img>![Floating Blur](../assets/floating_blur.png)</img>
```

### Preferences

```json

```
