### ISSUE TITLE
[create-theme]: Minimal sidebar

### ISSUE THREAD

**Issue by Venca321** [zen-browser/theme-store#109]
### Name

Minimal sidebar

### Description

With this Zen theme, you can remove the buttons from the sidebar and make more space for your tabs 

### Homepage

https://github.com/Venca321/Zen-Minimal-Sidebar-Theme

### Image

https://github.com/Venca321/Zen-Minimal-Sidebar-Theme/blob/main/image.png?raw=true

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@media (-moz-bool-pref: "uc.minimal-sidebar.hide-alltabs-button.enabled") {
  #alltabs-button {
    display: none !important;
  }
}

@media (-moz-bool-pref: "uc.minimal-sidebar.hide-profile-button.enabled") {
  #zen-profile-button {
    display: none !important;
  }
}

@media (-moz-bool-pref: "uc.minimal-sidebar.hide-expand-sidebar-button.enabled") {
  #zen-expand-sidebar-button {
    display: none !important;
  }
}

@media (-moz-bool-pref: "uc.minimal-sidebar.hide-bookmark-button.enabled") {
  #zen-bookmark-button {
    display: none !important;
  }
}

@media (-moz-bool-pref: "uc.minimal-sidebar.hide-history-button.enabled") {
  #zen-history-button {
    display: none !important;
  }
}

@media (-moz-bool-pref: "uc.minimal-sidebar.hide-preferences-button.enabled") {
  #zen-preferences-button {
    display: none !important;
  }
}

@media (-moz-bool-pref: "uc.minimal-sidebar.compact-spacing.enabled") {
  #zen-sidebar-icons-wrapper {
    padding-top: 0px !important;
  }
}
```

### Readme

```markdown
# Zen-Minimal-Sidebar-Theme

With this theme, you can hide the buttons in the sidebar and make it minimalistic.

The following buttons can be hidden:

- All tabs button
- Profile button
- Expand sidebar button
- Bookmarks button
- History button
- Preference button
```

### Preferences

```json
{
  "uc.minimal-sidebar.hide-alltabs-button.enabled": "Hide the alltabs button",
  "uc.minimal-sidebar.hide-profile-button.enabled": "Hide the profile button",
  "uc.minimal-sidebar.hide-expand-sidebar-button.enabled": "Hide the expand sidebar button",
  "uc.minimal-sidebar.hide-bookmark-button.enabled": "Hide the bookmarks button",
  "uc.minimal-sidebar.hide-history-button.enabled": "Hide the history button",
  "uc.minimal-sidebar.hide-preferences-button.enabled": "Hide the preferences button",
  "uc.minimal-sidebar.compact-spacing.enabled": "Make padding above the remaining buttons smaller"
}
```
