### ISSUE TITLE
[create-theme]: cleaner-bookmark-menu

### ISSUE THREAD

**Issue by Pkcarreno** [zen-browser/theme-store#1095]
### Name

https://github.com/Pkcarreno/cleaner-bookmark-menu

### Description

Remove unnecessary buttons from the toolbar bookmarks button.

### Homepage

https://github.com/Pkcarreno/cleaner-bookmark-menu

### Image

https://github.com/Pkcarreno/cleaner-bookmark-menu/blob/6b8878f1c5ffc7009a944faf8124d3c1cf7998e2/cleaner-bookmark-menu.png?raw=true

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#BMB_viewBookmarksSidebar,
#BMB_searchBookmarks,
#BMB_bookmarksShowAllTop,
#BMB_bookmarksShowAll {
  display: none !important;
}

#bookmarks-menu-button #BMB_viewBookmarksToolbar {
  display: none !important;
}
```

### Readme

```markdown
# cleaner-bookmark-menu
Remove unnecessary buttons from the toolbar bookmarks button.

![image](https://github.com/Pkcarreno/cleaner-bookmark-menu/blob/6b8878f1c5ffc7009a944faf8124d3c1cf7998e2/cleaner-bookmark-menu.png)
```

### Preferences

```json

```
