### ISSUE TITLE
[create-theme]: Add new tab icon to urlbar

### ISSUE THREAD

**Issue by Evthestrike** [zen-browser/theme-store#1103]
### Name

Add new tab icon to urlbar

### Description

Adds an icon and the text "open in new tab" to the urlbar when it is opened by pressing the "New Tab" button or by pressing "Ctrl+T" so that it is easy to differentiate between when you are editing a URL and opening a new tab.

### Homepage

https://github.com/Evthestrike/zen-browser-add-new-tab-icon-to-urlbar

### Image

https://github.com/Evthestrike/zen-browser-add-new-tab-icon-to-urlbar/blob/363dff93a00bbaa8ea2e1296e349fd5de88edf8d/Add_new_tab_icon_to_urlbar.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#urlbar[zen-newtab="true"] {
  #identity-icon {
    list-style-image: url("chrome://browser/skin/zen-icons/new-tab-image.svg") !important;
    filter: opacity(0.5) !important;
  }

  &[open] #identity-icon-box::after {
    content: "open in new tab" !important;
    filter: opacity(0.5) !important;
    padding-left: 6px !important;
  }
}
```

### Readme

```markdown
# Add new tab icon to urlbar
Adds an icon and the text "open in new tab" to the urlbar when it is opened by pressing the "New Tab" button or by pressing "Ctrl+T" so that it is easy to differentiate between when you are editing a URL and opening a new tab.
```

### Preferences

```json

```
