### ISSUE TITLE
[create-theme]: Add new tab urlbar icon

### ISSUE THREAD

**Issue by Evthestrike** [zen-browser/theme-store#1105]
### Name

Add new tab urlbar icon

### Description

Adds an icon and the text "open in new tab" to the urlbar if opened by pressing "New Tab" or Ctrl+T

### Homepage

https://github.com/Evthestrike/zen-browser-add-new-tab-icon-to-urlbar

### Image

https://github.com/Evthestrike/zen-browser-add-new-tab-icon-to-urlbar/blob/3267cd0ee117216e48dd1b1fb8143fba86631fc1/Add_new_tab_icon_to_urlbar.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#urlbar[zen-newtab="true"] {
  #identity-icon {
    list-style-image: url("chrome://browser/skin/zen-icons/new-tab-image.svg") !important;
    filter: opacity(0.5) !important;
  }

  &[open] #identity-icon-box::after {
    content: "open in new tab" !important;
    filter: opacity(0.5) !important;
    padding-left: 6px !important;
  }
}
```

### Readme

```markdown
# Add new tab urlbar icon
Adds an icon and the text "open in new tab" to the urlbar when it is opened by pressing the "New Tab" button or by pressing "Ctrl+T" so that it is easy to differentiate between when you are editing a URL and opening a new tab.
```

### Preferences

```json

```
