### ISSUE TITLE
[create-theme]: Better Customize Toolbar

### ISSUE THREAD

**Issue by Tanay-Kar** [zen-browser/theme-store#1108]
### Name

Better Customize Toolbar

### Description

Creates a cohesive customize toolbar UI

### Homepage

https://github.com/Tanay-Kar/Zen-Themes/tree/main/Customization%20Panel

### Image

https://github.com/user-attachments/assets/082f0bf6-007f-476b-b402-40fdcec4dbc5

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#customization-container {
  position: absolute;
  z-index: 10;
  bottom: 10px;
  right: 10px;
  height: 80%;
  width: 70%;
  border-radius: 12px;
  
  padding: 10px;
  background: light-dark(rgba(255,255,255,0.32),rgba(0,0,0,0.3)) !important;
}

@media (-moz-bool-pref: "zen.tabs.vertical.right-side") {
  #customization-container {
    left: 10px;
  }
  
  #customization-container #customization-content-container {
    flex-direction: row-reverse;
  }
}

#customization-container #customization-panel-container {
  padding: 10px !important;
}


#customization-container #customization-panelWrapper {
  --panel-arrow-offset: 0px;
}

#customization-container .panel-arrowbox {
  display: none !important;
}

#customization-container .panel-arrowcontent {
  height: 100% !important;
  background: light-dark(rgba(255,255,255,0.8),rgba(0,0,0,0.4)) !important;
  border: none !important;
  margin: 0px !important;
  border-radius: 8px;
}
```

### Readme

```markdown
# Better Customization Panel

Creates a cohesive customize toolbar UI

![image](https://github.com/user-attachments/assets/082f0bf6-007f-476b-b402-40fdcec4dbc5)
```

### Preferences

```json

```
