### ISSUE TITLE
[create-theme]: web-panel-sidebar-tweaks

### ISSUE THREAD

**Issue by tywil04** [zen-browser/theme-store#1114]
### Name

Web Panel Sidebar Tweaks

### Description

Pins web panel sidebar to the right and tweaks web panel sidebar toolbar color and search bar margin

### Homepage

https://github.com/tywil04/zen-web-panel-sidebar-tweaks

### Image

https://raw.githubusercontent.com/tywil04/zen-web-panel-sidebar-tweaks/refs/heads/main/image-small.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@media (-moz-bool-pref: "uc.web-panel-sidebar-tweaks.enable-pinning-web-panel-sidebar-to-right") {
  /* Make the web panel side bar the right-most item */
  #zen-sidebar-web-panel-wrapper:has(#zen-sidebar-web-panel:not([pinned="true"])) {
    order: 1000 !important;
  }

  /* Enable the resize handle on the left of the web panel sidebar */
  #zen-sidebar-web-panel:not([pinned="true"]) .zen-sidebar-web-panel-splitter[side="left"] {
    display: inherit !important;;
    margin: inherit !important;;
  }

  /* Disable the resize handle on the right of the web panel sidebar */
  #zen-sidebar-web-panel:not([pinned="true"]) .zen-sidebar-web-panel-splitter[side="right"] {
    display: none !important;;
    margin: 0 !important;;
  }
}

@media (-moz-bool-pref: "uc.web-panel-sidebar-tweaks.enable-tweaked-sidebar-toolbar-colors") {
  /* Make the web panel sidebar toolbar colors fit in with zen better */
  #zen-sidebar-web-panel:not([pinned="true"]) {
    background: color-mix(in srgb, var(--toolbarbutton-hover-background) 50%, transparent 50%) !important;
  }
}

@media (-moz-bool-pref: "uc.web-panel-sidebar-tweaks.enable-tweaked-searchbar-margin") {
  /* Make searchbar margin the same as everything else */
  #nav-bar {
    margin-bottom: 2px !important;
    margin-top: 3px !important;
  }
}
```

### Readme

```markdown
# Zen Web Panel Sidebar Tweaks

This theme makes a few tweaks to the web panel sidebar. 

This theme:
- Makes the web panel sidebar pin to the right
- Tweaks web panel sidebar toolbar colors to better fit in with zen
- Makes the margin around the search bar match spacing between main view and web panel sidebar

All of the features can be enabled/disabled in theme preferences.
```

### Preferences

```json
[
    {
        "property": "uc.web-panel-sidebar-tweaks.enable-pinning-web-panel-sidebar-to-right",
        "label": "Enable pinning the web panel sidebar to the right",
        "type": "checkbox",
        "defaultValue": true
    },
    {
        "property": "uc.web-panel-sidebar-tweaks.enable-tweaked-sidebar-toolbar-colors",
        "label": "Enable tweaked web panel sidebar toolbar colours",
        "type": "checkbox",
        "defaultValue": true
    },
    {
        "property": "uc.web-panel-sidebar-tweaks.enable-tweaked-searchbar-margin",
        "label": "Enable tweaked searchbar margin",
        "type": "checkbox",
        "defaultValue": true
    }
]
```
