### ISSUE TITLE
[create-theme]: Zen Mod − Hide URL bar buttons

### ISSUE THREAD

**Issue by YouriCode** [zen-browser/theme-store#1124]
### Name

Hide URL bar buttons

### Description

Mod for Zen Browser that hides icons of your choice in the URL bar.

### Homepage

https://github.com/YouriCode/ZenModHideURLBarIcons

### Image

https://github.com/user-attachments/assets/8d02c552-c165-46c9-9d68-4f0f5c7f6a68

### Type

- [x] JSON Color Theme

### Theme Styles

```css
@-moz-document url-prefix("chrome:") {

  @media (-moz-bool-pref: "mod.urlbar-icons.bookmark.disable") {
    #star-button-box {display: none;}
  }
  
  @media (-moz-bool-pref: "mod.urlbar-icons.translation.disable") {
    #translations-button {display: none;}
  }
  
  @media (-moz-bool-pref: "mod.urlbar-icons.reader-mode.disable") {
    #reader-mode-button {display: none;}
  }
  
  @media (-moz-bool-pref: "mod.urlbar-icons.pip.disable") {
    #picture-in-picture-button {display: none;}
  }
  
  @media (-moz-bool-pref: "mod.urlbar-icons.addons.disable") {
    .urlbar-addon-page-action {display: none;}
  }
  
  @media (-moz-bool-pref: "mod.urlbar-icons.identity.disable") {
    #identity-icon-box {display: none;}
    #urlbar-input {margin-left: 4px;}
  }
  
  @media (-moz-bool-pref: "mod.urlbar-icons.permissions.disable") {
    #identity-permission-box {display: none !important;}
  }
  
  @media (-moz-bool-pref: "mod.urlbar-icons.tracking-protection.disable") {
    #tracking-protection-icon-container {display: none;}
  }
  
}
```

### Readme

```markdown
# Hide URL bar buttons

Want to click your URL bar but surprise buttons appear at the last moment?

This mod allows you to **hide the buttons in the URL bar**, especially the ones that appear on hover! No more frustration.

## Setup

Set the buttons you want to show or hide via *Settings > Zen Mods*.

### Hidden by default
These are **hidden by default** as there are alternatives to access their menus: 
- **Bookmark** *(you can bookmark a page by right-clicking a tab/a page and by using a keyboard shortcut [default: Ctrl+D])*
- **Translate** *(you can access Translation via the main menu over the URL bar)*
- **Reader Mode** *(you can activate Reader Mode when available by using a keyboard shortcut [default: F9])*
- **Picture-In-Picture** *(PIP automatically starts when switching tab)*
- **Addon-related actions** *(you can access Addons Options via the Addons button over the URL bar)*

### Danger zone

You can also choose to hide other icons to have an URL bar only showing the URL. However, **disabling these is not recommended** as they provide safety and confidentiality information about the websites you visit:
- **Website Identity**
- **Permissions**
- **Tracking Protection**
```

### Preferences

```json
[    {
        "property": "mod.urlbar-icons.bookmark.disable",
        "label": "Hide Bookmark icon (you can bookmark a page by right-clicking a tab/a page and by using a keyboard shortcut [default: Ctrl+D])",
        "type": "checkbox",
        "defaultValue": true
    },    
    {
        "property": "mod.urlbar-icons.translation.disable",
        "label": "Hide Translation icon (you can access Translation via the ··· menu over the URL bar)",
        "type": "checkbox",
        "defaultValue": true
    },
    {
        "property": "mod.urlbar-icons.reader-mode.disable",
        "label": "Hide Reader Mode icon (you can activate Reader Mode when available by using a keyboard shortcut [default: F9])",
        "type": "checkbox",
        "defaultValue": true
    },
    {
        "property": "mod.urlbar-icons.pip.disable",
        "label": "Hide Picture-In-Picture icon (PIP automatically starts when switching tab)",
        "type": "checkbox",
        "defaultValue": true
    },    
    {
        "property": "mod.urlbar-icons.addons.disable",
        "label": "Hide Addons icons (you can access Addons Options via the Addons button over the URL bar)",
        "type": "checkbox",
        "defaultValue": true
    },
    {
        "property": "mod.urlbar-icons.identity.disable",
        "label": "/!\\ Hide Website Identity icon (CAREFUL: this icon is IMPORTANT as it indicates if a website is trustable. This menu CANNOT be accessed from somewhere else. Hide it at your own risk.)",
        "type": "checkbox",
        "defaultValue": false
    },
    {
        "property": "mod.urlbar-icons.permissions.disable",
        "label": "/!\\ Hide Website Permissions icon (CAREFUL: this icon is important as it indicates if a website has (unusual) permissions over your device. This menu CANNOT be accessed from somewhere else. Hide it at your own risk.)",
        "type": "checkbox",
        "defaultValue": false
    },
    {
        "property": "mod.urlbar-icons.tracking-protection.disable",
        "label": "/!\\ Hide Website Tracking Protection icon (CAREFUL: this icon is important as it indicates if a website is tracking you. This menu CANNOT be accessed from somewhere else. Hide it at your own risk.)",
        "type": "checkbox",
        "defaultValue": false
    }
]
```
