### ISSUE TITLE
Au70's

### ISSUE THREAD

**Issue by Hover117** [zen-browser/theme-store#1126]
### Name

otto-mk1

### Description

testing

### Image

https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTABbXr4i-QODqhy7tofHYmTYh05rYPktzacw&s

### Type

- [x] JSON Color Theme

### Theme Styles

```css
@-moz-document url-prefix("chrome:") {
  #statuspanel {
    margin: var(--theme-customstatusbar-margin) !important;
  }
  
  #statuspanel-label {
    border-radius: var(--theme-customstatusbar-radius) !important;
    padding: 2px 10px !important;
    border: var(--theme-customstatusbar-border_thickness) solid
      var(--theme-customstatusbar-color_border) !important;
    background: var(--theme-customstatusbar-color_background) !important;
    color: var(--theme-customstatusbar-text_color) !important; /* Text color */
  }
  
}
```

### Readme

```markdown
i'm just testing it for personal use
```

### Preferences

```json
[
    {
        "property": "theme.customstatusbar.radius",
        "label": "Round the corners. (default: 1000px)",
        "type": "string",
        "defaultValue": "1000px",
        "placeholder": "1000px",
        "disabledOn": []
    },
    {
        "property": "theme.customstatusbar.margin",
        "label": "Set the margin. (default: 8px)",
        "type": "string",
        "defaultValue": "8px",
        "placeholder": "8px",
        "disabledOn": []
    },
    {
        "property": "theme.customstatusbar.border_thickness",
        "label": "Set the thickness of the border. '2px'",
        "type": "string",
        "defaultValue": "2px",
        "placeholder": "2px",
        "disabledOn": []
    },
    {
        "property": "theme.customstatusbar.color_border",
        "label": "Set the border color. '#0e03ad' or 'var(--zen-colors-border)'",
        "type": "string",
        "defaultValue": "var(--zen-colors-border)",
        "placeholder": "var(--zen-colors-border)",
        "disabledOn": []
    },
    {
        "property": "theme.customstatusbar.color_background",
        "label": "Set the background color. '#a403ad' or 'var(--zen-colors-tertiary)'",
        "type": "string",
        "defaultValue": "var(--zen-colors-tertiary)",
        "placeholder": "var(--zen-colors-tertiary)",
        "disabledOn": []
    },
    {
        "property": "theme.customstatusbar.text_color",
        "label": "Set the text color. '#a403ad' or 'var(--lwt-text-color)'",
        "type": "string",
        "defaultValue": "var(--lwt-text-color)",
        "placeholder": "var(--lwt-text-color)",
        "disabledOn": []
    }
]
```
