### ISSUE TITLE
[create-theme]: Everblush

### ISSUE THREAD

**Issue by saxophone-dev** [zen-browser/theme-store#1128]
### Name

Everblush

### Description

The everblush colorscheme, for Zen.

### Homepage

https://github.com/Everblush

### Image

https://avatars.githubusercontent.com/u/101412540

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
:root {
    --zen-colors-primary: #dadada !important;
    --zen-colors-secondary: #232a2d !important;
    --zen-colors-tertiary: #141b1e !important;
    --zen-colors-border: #232a2d !important;
    --zen-dialog-background: #141b1e !important;
}
```

### Readme

```markdown
<div align="center">
<img align="center" src="https://raw.githubusercontent.com/Everblush/assets/main/logo.png" height="200px" width="200px" alt="logo"> 
</div> 

<h1 align="center">Everblush</h1> 
<h4 align="center"><i>A dark, vibrant and beautiful colorscheme for your desktop</i></h4> 


<div align="center">
<a href="https://discord.gg/KmARmpTegP">
<img alt="Discord" src="https://img.shields.io/discord/989429995925553182?color=%2367b0e8&label=DISCORD&logo=discord&logoColor=%236cb5ed&style=for-the-badge">
</a> 
</div>

# About 
Everblush is a color scheme like the others in the programmer / ricer's community, but with beautiful syntax highlighting and colors.

## Contribution
- saxophone-dev
- Ever blush creator
```

### Preferences

```json

```
