### ISSUE TITLE
[create-theme]: sidebar-drag-fix

### ISSUE THREAD

**Issue by rsiebertdev** [zen-browser/theme-store#1147]
### Name

Sidebar Drag Fix

### Description

This mod fixes the missing drag effect on collapsed sidebar tabs.

### Homepage

https://github.com/rsiebertdev/zen-themes

### Image

https://github.com/rsiebertdev/zen-themes/blob/themes/sidebar-drag-fix/image.png?raw=true

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
:root:not([zen-sidebar-expanded="true"]) #tabbrowser-tabs .tabbrowser-tab:active {
	scale: 0.93 !important;
}
```

### Readme

```markdown
# Sidebar Drag Fix
This mod fixes the missing drag effect on collapsed sidebar tabs.

> These mods may break or become depreciated as Zen Browser updates. However, I try to keep them up-to-date with the latest versions of Zen. If something isn't working or doesn't feel right, feel free to [submit an issue](https://github.com/rsiebertdev/zen-themes/issues/new). Made with 💖 by Roman.

## Change log

### 1.0.0
- 💥 Initial submission.
```

### Preferences

```json

```
