### ISSUE TITLE
[create-theme]: Opera GX Gradient

### ISSUE THREAD

**Issue by JLBlk** [zen-browser/theme-store#115]
### Name

Opera GX Gradient

### Description

Red-Blue'ish Gradient resembling Opera GX

### Homepage

https://github.com/JLBlk/Zen-Theme

### Image

https://github.com/JLBlk/Zen-Theme/blob/main/Screenshot%202024-08-22%20171550%20(Custom).png?raw=true

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
:root {
    --zen-main-browser-background: radial-gradient(circle, rgb(255, 0, 30) 0%, rgba(49,4,23,1) 90%, rgba(15,4,29,1) 100%) !important;
  }
  

@media (-moz-bool-pref: "zen.view.compact"){

  #titlebar {
    background: radial-gradient(circle at 100%, rgb(88, 0, 0) 0%, rgba(15,4,29,1) 100%) !important;
  }

}

@media (-moz-bool-pref: "zen.view.compact.hide-toolbar") and (-moz-bool-pref: "zen.view.compact"){

  #zen-appcontent-navbar-container {
    background: radial-gradient(circle at 100%, rgb(88, 0, 0) 0%, rgba(15,4,29,1) 100%) !important;
  }

}
```

### Readme

```markdown
This color theme creates a colorful gradient reminding of Opera GX while also supporting the compact mode of Zen, as well as retaining the ability to use and change the accent Color found in Zen's Look and Feel Settings.
```
