### ISSUE TITLE
[create-theme]: Empty your PiP

### ISSUE THREAD

**Issue by ImBada** [zen-browser/theme-store#1156]
### Name

Empty your PiP

### Description

Remove all the UI elements on the PiP window. Just pure video.

### Image

https://i.imgur.com/GMtNhp5.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
.control-item.control-button {
	display: none !important;
}

#close, #unpip {
	display: none !important;

	&:hover {
		&::after {
			display: none !important;
		}
	}
}

#close {
	display: none !important;
}

#unpip {
	display: none !important;
}

/* for dragging */
#controls {
	visibility: hidden !important;

	&:hover {
		visibility: hidden !important;
	}
}

#controls-bottom-gradient {
	display: none !important;
}

#controls-bottom {
	display: none !important;
}

/* progress bar */
.scrubber-no-drag {
	display: none !important;
}

#scrubber::-moz-range-thumb {
	display: none !important;
}

#scrubber {
	display: none !important;
	&:hover {
		display: none !important;
	}
}

#scrubber {
	&::-moz-range-track, &::-moz-range-progress {
		display: none !important;
	}
}
```

### Readme

```markdown
It's a pure PiP with no UI elements—just video.
I sometimes found the UI elements visible on mouseover annoying, and I always wanted a player that just shows videos.
```

### Preferences

```json

```
