### ISSUE TITLE
[create-theme]: Zen Letterbox

### ISSUE THREAD

**Issue by p-sw** [zen-browser/theme-store#1158]
### Name

Zen Letterbox

### Description

A simple way to change the width of the letterbox.

### Image

https://imgur.com/a/IX67dhO

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#browser {
  --zen-element-separation: calc(6px * var(--letterbox-multiply-factor, 3)) !important;
}
```

### Readme

```markdown
# Zen Letterbox
This mod provides a simple way to change the width of the letterbox.
```

### Preferences

```json
[
  {
    "property": "letterbox.multiply-factor",
    "label": "Multiply Factor (number)",
    "type": "string",
    "defaultValue": "3",
    "placeholder": "0.5, 1, 2, ..."
  }
]
```
