### ISSUE TITLE
[create-theme]: Mute Button Not Clickable

### ISSUE THREAD

**Issue by jamez243** [zen-browser/theme-store#1164]
### Name

Mute Button Not Clickable

### Description

This will show the speaker from the tab that is playing but will prevent you from accidently clicking it. Can use right click context menu to mute the tab.

### Image

https://i.postimg.cc/mZ77q38p/image.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
/* Show audio icon but make it non-interactive */
  .tab-icon-overlay[soundplaying] {
    display: block !important;
    pointer-events: none !important;
  }
  
  /* Hide the muted state icon */
  .tab-icon-overlay[muted] {
    display: none !important;
  }
  
  /* Hide the blocked media icon if needed */
  .tab-icon-overlay[activemedia-blocked] {
    display: block !important; 
    pointer-events: none !important;
  }
  
  .tab-icon-image {
    opacity: 1 !important;
  }
}
```

### Readme

```markdown
This just shows the speaker icon on the tab so you know where the audio is coming from but doesn't allow you to click it to mute it. 

I kept muting Teams calls while switching back to the tab by accident and thinking I had a audio hardware issue.

You can still mute the tab by right clicking the tab and selecting mute.
```

### Preferences

```json

```
