### ISSUE TITLE
[create-theme]: Relocate Mute Icon (Unclickable)

### ISSUE THREAD

**Issue by jamez243** [zen-browser/theme-store#1165]
### Name

Mute Icon (Unclickable)

### Description

Relocate mute icon and make it unclickable.

### Image

https://i.postimg.cc/vB1Z16Y6/image.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
/* Main approach: Target tabs with notifications */
  .tabbrowser-tab[label*="("] .tab-stack::before {
    content: "";
    position: absolute;
    top: 4px;
    left: 4px;
    width: 10px;
    height: 10px;
    background-color: #4CAF50; /* Green color */
    border-radius: 50%;
    z-index: 999;
  }
  
  /* Also target Gmail's "Inbox (X)" format */
  .tabbrowser-tab[label*="Inbox ("] .tab-stack::before {
    content: "";
    position: absolute;
    top: 4px;
    left: 4px;
    width: 10px;
    height: 10px;
    background-color: #4CAF50;
    border-radius: 50%;
    z-index: 999;
  }
}
```

### Readme

```markdown
This moves the speaker icon to the bottom left of the tab and makes it where you can't click it. This prevents accidental muting of tabs when trying to select them. You can still right click a tab and mute it from the context menu.
```

### Preferences

```json

```
