### ISSUE TITLE
[create-theme]: Top Left Notification Dot

### ISSUE THREAD

**Issue by jamez243** [zen-browser/theme-store#1166]
### Name

Top Left Notification Dot

### Description

This adds a green dot at the top left for tabs.

### Image

https://i.postimg.cc/3NFWX46r/image.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@-moz-document url-prefix("chrome://") {
  /* Main approach: Target tabs with notifications */
  .tabbrowser-tab[label*="("] .tab-stack::before {
    content: "";
    position: absolute;
    top: 4px;
    left: 4px;
    width: 10px;
    height: 10px;
    background-color: #4CAF50; /* Green color */
    border-radius: 50%;
    z-index: 999;
  }
  
  /* Also target Gmail's "Inbox (X)" format */
  .tabbrowser-tab[label*="Inbox ("] .tab-stack::before {
    content: "";
    position: absolute;
    top: 4px;
    left: 4px;
    width: 10px;
    height: 10px;
    background-color: #4CAF50;
    border-radius: 50%;
    z-index: 999;
  }
}
```

### Readme

```markdown
This places a bright green dot at the top left of tabs when there's notifications... works with Teams and Gmail by looking for tabs that start with:

"(x" 
"Inbox (x"

The first one is for Teams, the second one is for Gmail, but will also work for any tabs that list notifications in that manner.
```

### Preferences

```json

```
