### ISSUE TITLE
[create-theme]: Better Active Tab

### ISSUE THREAD

**Issue by kurtschambach** [zen-browser/theme-store#1172]
### Name

Better Active Tab

### Description

A Zen mod that highlights the active tab, and leaves the Essential Tabs highlighting intact

### Image

https://i.imgur.com/I7DtZZI.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
.tab-background {
  &:is([selected], [multiselected]) {
    border-style: solid;
    border-color: var(--zen-primary-color) !important;
    border-width: 2px;
  }
}

#zen-essentials-container > .tabbrowser-tab > stack >.tab-background {
  border-width: 0px !important;
}
```

### Readme

```markdown
A Zen Browser mod that highlights the active tab, and leaves the Essential Tabs highlighting intact
```

### Preferences

```json

```
