### ISSUE TITLE
[create-theme]: Floating Bookmarks

### ISSUE THREAD

**Issue by Frost-Phoenix** [zen-browser/theme-store#1175]
### Name

Floating Bookmarks

### Description

Makes the bookmarks tab floating.

### Homepage

https://github.com/Frost-Phoenix/zen-floating-bookmarks

### Image

https://github.com/user-attachments/assets/4184325b-0f3e-4405-8f2c-e4c0645923d5

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
/* Disable dragable splitter */
#sidebar-box[sidebarcommand="viewBookmarksSidebar"]+splitter {
    display: none !important;
}

/* Make sure content is not affect by bookmarks tab sliding in and out */
#tabbrowser-tabbox[flex="1"][tabcontainer="tabbrowser-tabs"] {
    will-change: unset !important;
}

/* Bookmarks Tab Styles */
#sidebar-box[sidebarcommand="viewBookmarksSidebar"] {
    order: none !important;
    height: 80% !important;
    width: 22em !important;

    body:has(#theme-Floating-Bookmarks[theme-floating_bookmarks-position="right"]) {
        right: 15px;
    }

    body:has(#theme-Floating-Bookmarks[theme-floating_bookmarks-position="left"]) {
        left: 15px;
    }


    position: fixed !important;
    transform: translateX(50%) !important;
    z-index: 10;

    transform: translateY(12%) !important;

    border-radius: var(--zen-border-radius) !important;

    box-shadow: var(--box-shadow-10) !important;
    background: var(--zen-colors-tertiary) !important;
    border: 1px solid var(--zen-colors-border) !important;

    transition: transform 0.35s !important;
    visibility: visible !important;
    opacity: 1 !important;


    &[hidden="true"] {
        display: flex !important;

        body:has(#theme-Floating-Bookmarks[theme-floating_bookmarks-position="right"]) {
            transform: translateX(110%) translateY(12%) !important;
        }

        body:has(#theme-Floating-Bookmarks[theme-floating_bookmarks-position="left"]) {
            transform: translateX(-110%) translateY(12%) !important;
        }
    }

    @starting-style {
        display: flex !important;

        body:has(#theme-Floating-Bookmarks[theme-floating_bookmarks-position="right"]) {
            transform: translateX(110%) translateY(12%) !important;
        }

        body:has(#theme-Floating-Bookmarks[theme-floating_bookmarks-position="left"]) {
            transform: translateX(-110%) translateY(12%) !important;
        }
    }

    &[checked="true"] {
        display: flex !important;
        transform: translateX(0%) translateY(12%) !important;
    }
}


/* Inner Styles of Bookmarks Tab */

#sidebar-box[sidebarcommand="viewBookmarksSidebar"] box#sidebar-header {
    border-bottom: none !important;
}

window#bookmarks-panel {
    box-shadow: var(--box-shadow-10) !important;
    background: var(--zen-colors-tertiary) !important;
}

/* Search Bar Styles */
window#bookmarks-panel search-textbox#search-box[data-l10n-id="places-bookmarks-search"] {
    appearance: none !important;
    background-color: var(--input-bgcolor, var(--zen-colors-tertiary)) !important;
    color: var(--input-color, var(--toolbar-field-color)) !important;
    border: 1px solid var(--zen-input-border-color, rgb(66, 65, 77));
    border-radius: 4px;
    outline: none;
    box-sizing: border-box;
    padding: 0.5rem !important;


    &[focused="true"] {
        background-color: var(--input-bgcolor, var(--toolbar-field-background-color)) !important;
        border: 1px solid var(--input-border-color, rgb(66, 65, 77));
    }
}


/* View Button Styles */
window#bookmarks-panel hbox#sidebar-search-container button#viewButton {
    appearance: none !important;
    margin-inline-end: 4px !important;
    border-radius: 6px !important;
    border: 1px solid transparent !important;
    padding: 2px 4px !important;
    background: transparent !important;
}

window#bookmarks-panel hbox#sidebar-search-container button#viewButton:hover {
    background-color: color-mix(in srgb, currentColor 10%, transparent) !important;
}

window#bookmarks-panel hbox#sidebar-search-container button#viewButton:active {
    background-color: color-mix(in srgb, currentColor 15%, transparent) !important;
}

window#bookmarks-panel hbox#sidebar-search-container {
    margin-bottom: 1rem !important;
}
```

### Readme

```markdown
# zen-floating-bookmarks

Improves the bookmarks tab by matching the browser theme, make it floating, more responsive, and allow placing it on either side.
```

### Preferences

```json
[
  {
    "property": "theme.floating_bookmarks.position",
    "label": "Position",
    "type": "dropdown",
    "disabledOn": [],
    "defaultValue": "right",
    "options": [
      {
        "label": "Left",
        "value": "left"
      },
      {
        "label": "Right",
        "value": "right"
      }
    ]
  }
]
```
