### ISSUE TITLE
[create-theme]: Fixed Pinned Tabs

### ISSUE THREAD

**Issue by Cybolic** [zen-browser/theme-store#1178]
### Name

Fixed Pinned Tabs

### Description

Keep pinned tabs visible when scrolling the vertical tabs

### Image

https://i.imgur.com/OBJzE11.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@media (-moz-bool-pref: "zen.tabs.vertical") {
  
  #zen-browser-tabs-container {
    position: absolute;
    width: 100%;
    height: 100%;
    display: flex;
    flex-direction: column;
    overflow-y: clip;
  }

  #vertical-pinned-tabs-container .zen-workspace-tabs-section {
    overflow: auto;
    position: sticky !important;
  }
  
  #tabbrowser-arrowscrollbox {
    min-height: 0 !important;
    max-height: 100% !important;
    position: relative;
  }
  #tabbrowser-arrowscrollbox .zen-workspace-tabs-section {
    position: relative !important;
    overflow-y: auto;
    margin-top: initial !important;
  }
  
  @media (-moz-bool-pref: "mod.fixed-pins.sticky_new_tab") {
    #tabbrowser-arrowscrollbox-periphery {
      position: sticky !important;
      bottom: 0;
      left: 0;
      right: 0;
      background: var(--toolbox-bgcolor) !important;
    }
  }
}
```

### Readme

```markdown
Keep pinned tabs at the top of the vertical tab section, like in previous versions of Zen.
```

### Preferences

```json
{
  "property": "mod.fixed-pins.sticky_new_tab",
  "label": "Keep New Tab button visible when scrolling",
  "type": "checkbox"
}
```
