### ISSUE TITLE
[create-theme]:

### ISSUE THREAD

**Issue by HeasHeartfire** [zen-browser/theme-store#1182]
### Name

Minimalistic Workspaces

### Description

This mod will replace your workspace's with cleaner, more minimalistic indicators

### Image

https://i.imgur.com/KGW731v.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
.zen-current-workspace-indicator-icon {
    display: none !important;
}

.zen-workspace-icon {
    position: relative;
    color: transparent;
}

.zen-workspace-icon::before {
    position: absolute;
    inset: 6px;
    content: '';
    background-color: white;
    border-radius: 50%;
}
```

### Readme

```markdown
This mod will hide the icon next to the workspace's name at the top, as well as replacing the icons at the bottom with more minimalistic ones
```

### Preferences

```json

```
