### ISSUE TITLE
[create-theme]: Minimalistic Workspaces

### ISSUE THREAD

**Issue by HeasHeartfire** [zen-browser/theme-store#1183]
### Name

Minimalistic Workspaces

### Description

Replace your workspace icons with more minimalistic ones

### Image

https://i.imgur.com/GChZdrE.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
.zen-current-workspace-indicator-icon {
    display: none !important;
}

.zen-workspace-icon {
    position: relative;
    color: transparent;
}

.zen-workspace-icon::before {
    position: absolute;
    inset: 6px;
    content: '';
    background-color: white;
    border-radius: 50%;
}
```

### Readme

```markdown
This mod will hide the icon next to the workspace name at the top, as well as replace the icon indicators at the bottom with cleaner, more minimalistic ones.
```

### Preferences

```json

```
