### ISSUE TITLE
[create-theme]: Zen Letterbox

### ISSUE THREAD

**Issue by p-sw** [zen-browser/theme-store#1186]
### Name

Zen Letterbox

### Description

A simple way to change the width of the letterbox.

### Image

https://github.com/zen-browser/theme-store/blob/2c34f99cc1b21e03bcc726c9070ceac05a82da66/themes/c0c32823-2b49-4693-8ce3-5a66212ea501/image.png?raw=true

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
:root {
  --letterbox-multiply-calculated: calc(6px * var(--letterbox-multiply-factor));
}

:root[zen-single-toolbar='true']:not([customizing]) {
  #zen-appcontent-navbar-container {
    @media (-moz-bool-pref: 'zen.view.hide-window-controls') {
      &:not([zen-has-hover='true']):not([has-popup-menu]):not(:focus-within):not(:has(*:is([panelopen='true'], [open='true']))) {
        height: 0px !important;
      }
    }
  }
}

:root:not([inDOMFullscreen='true']):not([chromehidden~='location']):not([chromehidden~='toolbar']) {
  & #zen-tabbox-wrapper {
    margin-bottom: var(--letterbox-multiply-calculated) !important;
  }
  
  &[zen-single-toolbar='true'] {
    & #zen-tabbox-wrapper {
      margin-top: var(--letterbox-multiply-calculated) !important;
      transition: margin-top 0.15s ease;
      transition-delay: 0.2s;
    }
    & #zen-appcontent-navbar-container[zen-has-hover="true"] + #zen-tabbox-wrapper {
      margin-top: 0 !important;
    }
  }
  
  &:not([zen-right-side="true"]) #zen-tabbox-wrapper {
    margin-right: var(--letterbox-multiply-calculated) !important;
  }
}
```

### Readme

```markdown
# Zen Letterbox
A simple way to change the width of the letterbox.
```

### Preferences

```json
[
    {
        "property": "letterbox.multiply-factor",
        "label": "Multiply Factor (number)",
        "type": "string",
        "defaultValue": "3",
        "placeholder": "0.5, 1, 2, ..."
    }
]
```
