### ISSUE TITLE
[create-theme]: Remove back and forward button

### ISSUE THREAD

**Issue by ogYwx** [zen-browser/theme-store#1197]
### Name

Hide nav buttons

### Description

This removes the annoying Forward and back button in the sidebar

### Image

https://i.imgur.com/w5iCdX1.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@-moz-document url-prefix("chrome:") {
    #back-button, /* Hides the back button */
    #forward-button /* Hides the forward button */ 
    {
      display: none !important;
    }
  }
```

### Readme

```markdown
# HideBack&Forward Arrows in sidebar

This **Zen theme** hides the Forward & Back button.

Credits to: HidePlugin Dev https://github.com/adammpkins

I toke his code and changed 2 lines xD.
```

### Preferences

```json

```
