### ISSUE TITLE
[create-theme]: Right side Macos style buttons

### ISSUE THREAD

**Issue by arg387** [zen-browser/theme-store#1201]
### Name

min max close button

### Description

lt changes your zen browser min-max-close control buttons to macos styles in non-macos systems.

### Homepage

https://github.com/arg387/zenedit

### Image

https://imgur.com/a/7PGB7PC

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#PanelUI-menu-button {
    padding-inline-end: 20px !important;
 }

.titlebar-buttonbox{
  border: 1px solid black !important;
  border-radius: 5px !important;
  position: relative !important;
}
.titlebar-buttonbox .titlebar-button {
  background: hsl(228, 13%, 40%) !important;
}
.titlebar-button{
  padding: 8px 4px 10px 10px !important;
}
.titlebar-button > .toolbarbutton-icon {
  display: relative !important;
  width: 14px !important;
  height: 14px !important;
  border-radius: 50% !important;
  margin: 0 !important;
  padding: 0 !important;
  list-style-image: none !important;
  transition: all 0.3s ease !important;
  cursor: pointer !important;
  justify-content: center !important;
  align-items: center !important;
  stroke: none !important;
  min-width: 14px !important;
  min-height: 14px !important;
}
.titlebar-button > .toolbarbutton-icon::before,
.titlebar-button > .toolbarbutton-icon::after {
  content: '' !important;
  border-radius: 50% !important;
}
/* Macos min button */
.titlebar-min > .toolbarbutton-icon {
  background: #ebb51f !important;
  border: 1px solid #ffbb00 !important;
  transition:  background-color 200ms ease !important;
  overflow: hidden !important;

}
.titlebar-buttonbox-container .titlebar-min::before{
	content: '';
	position: absolute;
	top: 100%;
	left: 20%;
	transform: translate(-50%, -50%);
	width: 8px;
	height: 2px;
	opacity: 0;
	background:  rgba(0, 0, 0, 0.6);
  	border-radius: 2px;
	transition: 200ms;
}
.titlebar-buttonbox-container .titlebar-min:hover::before{
	opacity: 1;
	top: 50%;
}
/* Macos restore button  and Macos max button */
.titlebar-max > .toolbarbutton-icon,
.titlebar-restore > .toolbarbutton-icon {
  background: #16dc16dd !important;
  border: 1px solid #00ff00 !important;
  overflow: hidden !important;
  transition:  background-color 200ms ease !important;
}
.titlebar-buttonbox-container .titlebar-restore::before{
	content: '';
	position: absolute;
	top: 100%;
	left: 54%;
	transform: translate(-50%, -50%);
	width: 9px;
	height: 9px;
	opacity: 0;
	background:  rgba(0, 0, 0, 0.6);
 	border-radius: 3px;
	transition: 200ms;

}
.titlebar-buttonbox-container .titlebar-restore::after{
  	content: '';
	position: absolute;
	top: 100%;
	left: 54%;
	transform: translate(-50%, -50%);
	width: 4px;
	height: 4px;
	opacity: 0;
	background: #39ea49;
	transition: 200ms;
}
.titlebar-buttonbox-container .titlebar-restore:hover::before, 
.titlebar-buttonbox-container .titlebar-restore:hover::after{
	opacity: 1;
	top: 50%;
}
.titlebar-buttonbox-container .titlebar-max::before{
	content: '';
	position: absolute;
	top: 100%;
	left: 54%;
	transform: translate(-50%, -50%);
	width: 9px;
	height: 9px;
	opacity: 0;
	background:  rgba(0, 0, 0, 0.6);
  	border-radius: 2px;
	transition: 200ms;

}
.titlebar-buttonbox-container .titlebar-max::after{
	content: '';
	position: absolute;
	top: 100%;
	left: 54%;
	transform: translate(-50%, -50%) rotate(-45deg);
	width: 4px;
	height: 8px;
	opacity: 0;
	background: #39ea49;
	transition: 200ms;
}
.titlebar-buttonbox-container .titlebar-max:hover::before, 
.titlebar-buttonbox-container .titlebar-max:hover::after{
	opacity: 1;
	top: 50%;
}
/* Macos close button */
.titlebar-close > .toolbarbutton-icon {
  background: #e71d27dd !important;
  border: 1px solid #ff000d !important;
  overflow: hidden !important;
  transition:  background-color 200ms ease !important;
}

.titlebar-buttonbox-container .titlebar-close::before{
	content: '';
	position: absolute;
	top: 100%;
	left: 87%;
	transform: translate(-50%, -50%) rotate(-45deg);
	width: 2px;
	height: 9px;
	opacity: 0;
	background:  rgba(0, 0, 0, 0.65);
  	border-radius: 1px;
	transition: 200ms;
}
.titlebar-buttonbox-container .titlebar-close::after{
	content: '';
	position: absolute;
	top: 100%;
	left: 87%;
	transform: translate(-50%, -50%) rotate(45deg);
	width: 2px;
	height: 9px;
  	opacity: 0;
	background: rgba(0, 0, 0, 0.65);
   	border-radius: 1px;
	transition: 200ms;
 
}
 .titlebar-buttonbox-container .titlebar-close:hover::before,  
 .titlebar-buttonbox-container .titlebar-close:hover::after{
	opacity: 1;
	top: 50%;
}
```

### Readme

```markdown
### This is a theme that changes normal windows min-max-close buttons to macos style buttons.
```

### Preferences

```json

```
