### ISSUE TITLE
[create-theme]: True Compact Mode

### ISSUE THREAD

**Issue by E-VanDeWoestyne** [zen-browser/theme-store#1205]
### Name

True Compact Mode

### Description

Completely disables the sidebar while in compact mode

### Image

https://i.imgur.com/bLc0wxZ.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
:root[zen-compact-mode="true"] {
    #navigator-toolbox {
        display: none !important;
    }
}
```

### Readme

```markdown
A very simple mod that simply disables the zen sidebar completely while compact mode is enabled, as opposed to being able to open on hover.

When compact mode is enabled again, the normal sidebar pops back on screen.
```

### Preferences

```json

```
