### ISSUE TITLE
[create-theme]:

### ISSUE THREAD

**Issue by jean06560** [zen-browser/theme-store#1211]
### Name

Back Fwd Always Hidden

### Description

Back and forward buttons will always be hidden. Useful if your mouse has the relevant buttons

### Image

https://image.noelshack.com/fichiers/2025/10/4/1741261728-sans-titre-1.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
:root:not([customizing]) #back-button {
    display: none !important;
  }
  :root:not([customizing]) #forward-button {
    display: none !important;
  }
```

### Readme

```markdown
Back and forward buttons will always be hidden. Useful if your mouse has the relevant buttons.
Inspired by "Zen Back Forward" (@KiKaraage)

Consider the fact that with this mod, you won't be able to click-old previous to choose between previous pages.
```

### Preferences

```json

```
