### ISSUE TITLE
[create-theme]: Floating Bookmark

### ISSUE THREAD

**Issue by TISupe** [zen-browser/theme-store#1217]
### Name

Floating-Bookmark

### Description

Improves appearance of bookmark sidebar, placing on right, floating it and giving it a modern look.

### Homepage

https://github.com/TISupe/Zen-Floating-Bookmark

### Image

https://github.com/TISupe/Zen-Floating-Bookmark/blob/main/screenshots/screenshot.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@-moz-document url-prefix("chrome:") {
  window.sidebar-panel {
    background-color: var(--zen-themed-toolbar-bg) !important;
  }
  
  search-textbox#search-box {
    appearance: none !important;
    background-color: var(--zen-colors-tertiary) !important;
    border: 1px solid var(--zen-colors-border) !important;
    padding: 0.5rem !important;
    border-radius: 5px !important;
  }
  
  search-textbox#search-box:hover {
    border: 1px solid var(--zen-colors-secondary) !important;
  }
  
  search-textbox#search-box:hover:active {
    border: 1px solid var(--zen-colors-secondary) !important;
  }
  
  button#viewButton {
    appearance: none;
    color: inherit;
    background-color: transparent !important;
    border-radius: var(--toolbarbutton-border-radius);
    border: 1px solid transparent !important;
  }
  
  button#viewButton:hover {
    background-color: var(--zen-colors-border) !important;
  }
  
  button#viewButton:hover:active {
    background-color: var(--zen-colors-border) !important;
  }
  
  #sidebar-box[sidebarcommand="viewBookmarksSidebar"] #sidebar-header {
    border-bottom: 0px !important;
  }
  
  #sidebar-box[sidebarcommand="viewBookmarksSidebar"] {
    background-color: var(--zen-themed-toolbar-bg) !important;
    border-radius: var(--zen-border-radius);
    box-shadow: 0 0 2px 2px rgba(0,0,0,.1);
    border: 1px solid var(--zen-colors-border);
    padding: var(--zen-toolbox-padding) !important;
    position: fixed;
    z-index: 1;
    height: 80vh !important;
    width: 20em !important;
    top: 10vh !important;
    right: 0.6vw !important;
    transform: translateX(105%);
    transition: all 0.2s ease-in-out;
  }
  
  #sidebar-box[hidden=true][sidebarcommand="viewBookmarksSidebar"] {
    display: flex !important;
    opacity: 0 !important;
    transform: translateX(105%);
  }
  
  #sidebar-box[checked=true][sidebarcommand="viewBookmarksSidebar"] {
    transform: translateX(0);
  }
}
```

### Readme

```markdown
Zen-Floating-Bookmark

Improves appearance of bookmark sidebar, placing on right, floating it and giving it a modern look.

I Just modified this for bookmark sidebar https://github.com/ahmaadaziz/zen-floating-history
```

### Preferences

```json

```
