### ISSUE TITLE
[create-theme]: Cleaner Downloads

### ISSUE THREAD

**Issue by MihkelMK** [zen-browser/theme-store#1221]
### Name

Cleaner Downloads

### Description

Change spacing and remove borders in the recent downloads menu.

### Homepage

https://github.com/MihkelMK/zen-mods/tree/main/cleaner_downloads

### Image

https://raw.githubusercontent.com/MihkelMK/zen-mods/refs/heads/main/cleaner_downloads/image.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#emptyDownloads,
#downloadsListBox richlistitem,
#downloadsFooter button {
  padding-block: 0.7em !important;
  padding-inline: 10px !important;
  margin-block: 2px !important;
  margin-inline: var(--tab-block-margin) !important;
}

#downloadsFooter button {
  border: 0 !important;
}
#downloadsPanel-blockedSubview,
#downloadsPanel-mainView {
  padding: 0 !important;
}
#downloadsListBox richlistitem button.downloadButton {
  min-width: 1em !important;
}
```

### Readme

```markdown
# Cleaner Downloads

Clean up the recent downloads menu.

- Adjust spacing
- Make the separator take up the full width
- Remove the border from `Show all downloads` button
- Decrease the minimum with of the `Show in folder` button

Inspired by [Cleaner Extension Menu - Zen Mods](https://zen-browser.app/mods/1e86cf37-a127-4f24-b919-d265b5ce29a0/) by [KiKaraage](https://github.com/KiKaraage).

![Screenshot of customized downloads menu](https://raw.githubusercontent.com/MihkelMK/zen-mods/refs/heads/main/cleaner_downloads/image.png)
```

### Preferences

```json

```
