### ISSUE TITLE
[create-theme]: Workspace Tweaks

### ISSUE THREAD

**Issue by MihkelMK** [zen-browser/theme-store#1228]
### Name

Workspace Tweaks

### Description

Change spacing, placement and backgrounds of the top and bottom workspace indicators.

### Homepage

https://github.com/MihkelMK/zen-mods/tree/main/workspace_tweaks

### Image

https://raw.githubusercontent.com/MihkelMK/zen-mods/refs/heads/main/workspace_tweaks/thumbnail.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@media (-moz-bool-pref: "uc.workspace-tweaks.top-pad-rm") {
  #titlebar {
    margin-top: calc(var(--zen-element-separation) * 1) !important;
  }

  #zen-sidebar-top-buttons {
    display: none !important;
  }
}

@media (-moz-bool-pref: "uc.workspace-tweaks.top-center") {
  #zen-current-workspace-indicator-container .zen-current-workspace-indicator {
    justify-content: center;
  }
}

@media (-moz-bool-pref: "uc.workspace-tweaks.bottom-pad") {
  #zen-sidebar-bottom-buttons {
    padding-inline: var(--zen-element-separation) !important;
    padding-block: calc(var(--zen-element-separation) / 2) !important;
    margin-top: calc(var(--zen-element-separation)) !important;

    & .zen-workspaces-button {
      --arrowpanel-menuitem-padding-inline: var(
        --arrowpanel-menuitem-padding-block
      ) !important;
    }
  }
}

@media (-moz-bool-pref: "uc.workspace-tweaks.bottom-bg") {
  #zen-sidebar-bottom-buttons {
    border-radius: var(--zen-border-radius);
    background-color: var(--zen-toolbar-element-bg) !important;
  }
}

@media (-moz-bool-pref: "uc.workspace-tweaks.top-bg") {
  #zen-current-workspace-indicator-container .zen-current-workspace-indicator {
    border-radius: var(--zen-border-radius);
    background-color: var(--zen-toolbar-element-bg) !important;
  }
}
```

### Readme

```markdown
# Workspace Tweaks

Change spacing, placement and backgrounds of the top and bottom workspace indicators.

![Screenshot of customized workspace indicators](https://raw.githubusercontent.com/MihkelMK/zen-mods/refs/heads/main/workspace_tweaks/image.png)

## Options

- Show the workspace-indicator above Pins.
- Remove padding from sidebar start (Looks best with Bottom Essentials).
- Center top workspace-indicator label.
- Add padding to the bottom workspace icons
- Add a background to the top workspace-indicator label.
- Add a background to the bottom workspace-indicator label.
```

### Preferences

```json
[
  {
    "property": "zen.workspaces.show-workspace-indicator",
    "label": "Shows the workspace-indicator above Pins.",
    "type": "checkbox",
    "disabledOn": []
  },
  {
    "property": "uc.workspace-tweaks.top-pad-rm",
    "label": "Remove padding from sidebar start. Looks best with Bottom Essentials.",
    "type": "checkbox",
    "disabledOn": []
  },
  {
    "property": "uc.workspace-tweaks.top-center",
    "label": "Center top workspace-indicator label.",
    "type": "checkbox",
    "disabledOn": []
  },
  {
    "property": "uc.workspace-tweaks.bottom-pad",
    "label": "Add padding to the bottom workspace icons",
    "type": "checkbox",
    "disabledOn": []
  },
  {
    "property": "uc.workspace-tweaks.top-bg",
    "label": "Add a background to the top workspace-indicator label.",
    "type": "checkbox",
    "disabledOn": []
  },
  {
    "property": "uc.workspace-tweaks.bottom-bg",
    "label": "Add a background to the bottom workspace-indicator label.",
    "type": "checkbox",
    "disabledOn": []
  }
]
```
