### ISSUE TITLE
[create-theme]: trackpad backwards and forwards gesture

### ISSUE THREAD

**Issue by Fury7425** [zen-browser/theme-store#1236]
### Name

trackpad animation

### Description

adds backward and forward animation for trackpad gesture

### Homepage

https://github.com/Fury7425/zen-trackpad-gesture-animation

### Image

https://github.com/Fury7425/zen-trackpad-gesture-animation/blob/main/example.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
.browserStack browser {
  transition: transform 0.22s cubic-bezier(0.3, 1.2, 0.5, 1) !important;
}

.browserStack:has(#historySwipeAnimationPreviousArrow:not([style="translate: none;"]))
  browser {
  scale: 0.95 !important;
  transform: translateX(4%) !important;
}

.browserStack:has(#historySwipeAnimationNextArrow:not([style="translate: none;"]))
  browser {
  scale: 0.95 !important;
  transform: translateX(-4%) !important;
}

.browserStack browser:not(:has(#historySwipeAnimationPreviousArrow, #historySwipeAnimationNextArrow)) {
  transition: transform 0.25s cubic-bezier(0.2, 1.4, 0.3, 1) !important;
  transform: translateX(0) !important;
}
```

### Readme

```markdown
made it for an extra animation when using a trackpad.
```

### Preferences

```json

```
