### ISSUE TITLE
[create-theme]: Square Tabs

### ISSUE THREAD

**Issue by M-Borer** [zen-browser/theme-store#1244]
### Name

Square Tabs

### Description

Removes rounded corners from tabs in the tab bar

### Homepage

https://github.com/M-Borer/zen-mods/tree/master/square-tabs

### Image

https://i.imgur.com/hYDgI0b.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
.tab-background {
  border-radius: 0px !important;
  margin-block: 1px 0 !important;
}
```

### Readme

```markdown
Removes rounded corners from tabs in the tab bar.

This should generally be compatible with other mods that affect the tab bar.
```

### Preferences

```json

```
