### ISSUE TITLE
[create-theme]: hide pinned close button

### ISSUE THREAD

**Issue by Bliwi** [zen-browser/theme-store#1253]
### Name

Hide pinned close button

### Description

hide the close button on pinned tabs, to prevent accidental closure.

### Homepage

https://github.com/Bliwi/zenhideclosepinned

### Image

https://raw.githubusercontent.com/Bliwi/zenhideclosepinned/5366ba7d343586b2edf0cf240396d880d8d1c63c/thumb.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@-moz-document url-prefix("chrome:") {
/* Hides the close button on pinned tabs */
:root #vertical-pinned-tabs-container .tab-close-button,
#main-window #vertical-pinned-tabs-container .tab-close-button {
   display: none !important;
}
}
```

### Readme

```markdown
This zen mod removes the close button from pinned tabs to prevent accidental closure.
Pinned tabs can still be closed through the context menu.
```

### Preferences

```json

```
