### ISSUE TITLE
[create-theme]: Vertical Tab Groups

### ISSUE THREAD

**Issue by ToBinio** [zen-browser/theme-store#1258]
### Name

Vertical Tab Groups

### Description

Display tab groups vertically so you can still read the page names

### Homepage

https://github.com/ToBinio/zen-mods/tree/main/vertical-tab-groups

### Image

https://raw.githubusercontent.com/ToBinio/zen-mods/refs/heads/main/vertical-tab-groups/thumbnail.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
tab-group[split-view-group] {
    flex-direction: column;
    padding: 2px 2px !important;
    position: relative;

    &::after {
        content: '';
        width: 1px;
        height: calc(100% - 8px);
        background-color: light-dark(rgba(0, 0, 0, 0.1), rgba(255, 255, 255, 0.2));
        position: absolute;
        right: 0;
        top: 50%;
        transform: translateY(-50%);
    }

    &:hover, &:has(> tab:is([visuallyselected], [multiselected])){
        &::after{
            width: 0;
        }
    }
}

tab-group[split-view-group] {
    & > .tabbrowser-tab {
        &:not(:last-child)::after {
            width: 0 !important;
            height: 0 !important;
        }
    }
}
```

### Readme

```markdown
# Vertical Tab Groups

Display tab groups vertically so you can still read the page names.
```

### Preferences

```json

```
