### ISSUE TITLE
[create-theme]: Big Essentials

### ISSUE THREAD

**Issue by leaferiksen** [zen-browser/theme-store#1260]
### Name

Big Essentials

### Description

Make the essential tab icons big enough (32px w/ 16px padding) to be recognisable without their names.

### Homepage

https://github.com/leaferiksen/zen-browser-big-essentials

### Image

https://raw.githubusercontent.com/leaferiksen/zen-browser-big-essentials/8a4faa6d38598b4b3dd9daa9cc49aac3fa10f05f/Big%20Essentials.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#zen-essentials-container > tab > stack:nth-child(1) > hbox:nth-child(2) > stack:nth-child(2) > img:nth-child(3) {
  height: 32px !important;
  width: 32px !important;
}

#zen-essentials-container > tab > stack:nth-child(1) > hbox:nth-child(2) > stack:nth-child(2) {
    padding: 16px !important;
}

#zen-essentials-container {
    gap: 8px 8px !important;
    grid-template-columns: repeat(auto-fit, minmax(80px, auto)) !important;
}
```

### Readme

```markdown
# Big Essentials
Make the essential tab icons big enough (32px w/ 16px padding) to be recognisable without their names.
```

### Preferences

```json

```
