### ISSUE TITLE
[create-theme]: Big Essentials

### ISSUE THREAD

**Issue by leaferiksen** [zen-browser/theme-store#1261]
### Name

Big Essentials

### Description

Make the Essential tab icons big enough (32px w/ 16px padding) to be recognisable without their names.

### Homepage

https://github.com/leaferiksen/zen-browser-big-essentials

### Image

https://github.com/leaferiksen/zen-browser-big-essentials/blob/main/Big%20Essentials.png?raw=true

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#zen-essentials-container > tab > stack:nth-child(1) > hbox:nth-child(2) > stack:nth-child(2) > img:nth-child(3) {
  height: 32px !important;
  width: 32px !important;
}

#zen-essentials-container > tab > stack:nth-child(1) > hbox:nth-child(2) > stack:nth-child(2) {
    padding: 16px !important;
}

#zen-essentials-container {
    gap: 8px 8px !important;
    grid-template-columns: repeat(auto-fit, minmax(80px, auto)) !important;
}
```

### Readme

```markdown
# Big Essentials
Make the Essential tab icons big enough (32px w/ 16px padding) to be recognisable without their names.
```

### Preferences

```json

```
