### ISSUE TITLE
[create-theme]: Fullscreen Bookmarks Toolbar

### ISSUE THREAD

**Issue by LikeAMantis** [zen-browser/theme-store#1265]
### Name

Fullscreen Bookmarks Toolbar

### Description

 Make the Bookmarks Toolbar also visible in fullscreen mode, instead of only showing an empty bar

### Image

https://imgur.com/a/ixCBO3i

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
toolbar#PersonalToolbar {
  visibility: visible !important;
}
```

### Readme

```markdown
# Fullscreen Bookmarks Toolbar

Make the Bookmarks Toolbar also visible in fullscreen mode, instead of only showing an empty bar
```

### Preferences

```json

```
