### ISSUE TITLE
[create-theme]: Fullscreen Bookmarks Bar

### ISSUE THREAD

**Issue by LikeAMantis** [zen-browser/theme-store#1267]
### Name

Fullscreen Bookmarks Bar

### Description

Make the Bookmarks Toolbar also visible in fullscreen mode, instead of only showing an empty bar

### Image

https://i.imgur.com/eqKDmyb.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
toolbar#PersonalToolbar {
  visibility: visible !important;
}
```

### Readme

```markdown
# Fullscreen Bookmarks Toolbar

Make the Bookmarks Toolbar also visible in fullscreen mode, instead of only showing an empty bar
```

### Preferences

```json

```
