### ISSUE TITLE
[create-theme]: Hide Tab Close Icon

### ISSUE THREAD

**Issue by natefabian18** [zen-browser/theme-store#1269]
### Name

Hide Tab Close Icon

### Description

Hide the close tab button added by firefox version 136

### Image

https://i.ibb.co/DfRmxcCg/HideTabX.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
.tabbrowser-tab .tab-close-button {
    visibility: collapse !important;
}
```

### Readme

```markdown
CSS Credit goes to [Inzaniity](https://github.com/Inzaniity) for the actual css

https://github.com/zen-browser/desktop/issues/6325#issuecomment-2715117375
```

### Preferences

```json

```
