### ISSUE TITLE
[create-theme]: centered-url-bar

### ISSUE THREAD

**Issue by SleepInfinity** [zen-browser/theme-store#1271]
### Name

Centered URL Bar

### Description

Give your Zen Browser a sleek, balanced look by centering the URL bar text.

### Homepage

https://github.com/SleepInfinity/centered-url-bar

### Image

https://imgur.com/a/9oL4AHK

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
.urlbar-input {
  text-align: center !important;
}

.urlbar-input[aria-expanded="false"] {
  text-align: center !important;
}

.urlbar-input[aria-expanded="true"] {
  text-align: match-parent !important;
}
```

### Readme

```markdown
# Centered URL Bar

Give your Zen Browser a sleek, balanced look by centering the URL bar text. This simple tweak enhances aesthetics and symmetry, creating a more refined browsing experience.
```

### Preferences

```json

```
