### ISSUE TITLE
[create-theme]: Dark Docs

### ISSUE THREAD

**Issue by SleepInfinity** [zen-browser/theme-store#1275]
### Name

Dark Docs

### Description

Say goodbye to blinding white documents! Dark Docs applies a dark mode to PDF documents.

### Homepage

https://github.com/SleepInfinity/dark-docs

### Image

https://i.imgur.com/fKzZHiz.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@-moz-document regexp(".*\\.pdf(\\?.*)?$") {
  .page {
      filter: invert(1) grayscale(1) contrast(75%) !important;
  }
}
```

### Readme

```markdown
# Dark Docs

Say goodbye to blinding white documents! Dark Docs applies a dark mode to PDF documents in Zen Browser, reducing eye strain and making long reading sessions easier on your eyes.
```

### Preferences

```json

```
