### ISSUE TITLE
[create-theme]: Container Tab show Zen Logo

### ISSUE THREAD

**Issue by irasnalida** [zen-browser/theme-store#1277]
### Name

Container Tab Zen Logo

### Description

Replaces the container indicator with the Zen logo.

### Homepage

https://github.com/irasnalida/Zen-Mods/tree/main/container-tab-zen-logo

### Image

https://i.postimg.cc/44w8ZLrL/image.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
tab {
  --irs-ctxl-logo-opacity: 0.65;
  --irs-ctxl-logo-selected-opacity: 0.35;
  --logo-circle-style: url('data:image/svg+xml,<svg width="32" height="32" viewBox="0 0 64 64" fill="context-fill" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" clip-rule="evenodd" d="M32 44.3077C38.7974 44.3077 44.3077 38.7974 44.3077 32C44.3077 25.2027 38.7974 19.6923 32 19.6923C25.2027 19.6923 19.6923 25.2027 19.6923 32C19.6923 38.7974 25.2027 44.3077 32 44.3077ZM41.8462 32C41.8462 37.4379 37.4379 41.8462 32 41.8462C26.5621 41.8462 22.1538 37.4379 22.1538 32C22.1538 26.5621 26.5621 22.1538 32 22.1538C37.4379 22.1538 41.8462 26.5621 41.8462 32Z"></path><path fill-rule="evenodd" clip-rule="evenodd" d="M53.3333 32C53.3333 43.7821 43.7821 53.3333 32 53.3333C20.2179 53.3333 10.6667 43.7821 10.6667 32C10.6667 20.2179 20.2179 10.6667 32 10.6667C43.7821 10.6667 53.3333 20.2179 53.3333 32ZM32 49.2308C41.5163 49.2308 49.2308 41.5163 49.2308 32C49.2308 22.4837 41.5163 14.7692 32 14.7692C22.4837 14.7692 14.7692 22.4837 14.7692 32C14.7692 41.5163 22.4837 49.2308 32 49.2308Z"></path><path fill-rule="evenodd" clip-rule="evenodd" d="M64 32C64 49.6731 49.6731 64 32 64C14.3269 64 0 49.6731 0 32C0 14.3269 14.3269 0 32 0C49.6731 0 64 14.3269 64 32ZM32 58.2564C46.501 58.2564 58.2564 46.501 58.2564 32C58.2564 17.499 46.501 5.74359 32 5.74359C17.499 5.74359 5.74359 17.499 5.74359 32C5.74359 46.501 17.499 58.2564 32 58.2564Z"></path></svg>');

  .tab-context-line {
    width: 100% !important;
    -webkit-mask-image: var(--logo-circle-style) !important;
    mask-image: var(--logo-circle-style) !important;
    background-color: var(--identity-icon-color) !important;
    mask-repeat: no-repeat !important;
    mask-position: right center;
    mask-position-x: calc(100% + 20px);
    mask-size: contain;
    opacity: var(--irs-ctxl-logo-opacity);
    transition: mask-position-x 0.2s 0.15s ease-in;
  }

  &[zen-essential="true"] {
    .tab-context-line {
      background-position-x: calc(100% + 25px);
      mask-position-x: calc(100% + 25px) !important;
    }
  }

  &[selected] {
    .tab-context-line {
      mask-position-x: calc(100% + 15px);
      opacity: var(--irs-ctxl-logo-selected-opacity);
    }

    &[zen-essential="true"] {
      .tab-context-line {
        mask-position-x: calc(100% + 19px);
      }
    }
  }
}
```

### Readme

```markdown
This css mod will show the zen logo as colored container indicator. Just install and it should work.
```

### Preferences

```json

```
