### ISSUE TITLE
[create-theme]: Right side Macos style buttons

### ISSUE THREAD

**Issue by arg387** [zen-browser/theme-store#1281]
### Name

min max close button

### Description

lt changes your zen browser min-max-close control buttons to macos styles in non-macos systems.

### Homepage

https://github.com/arg387/zenedit

### Image

https://imgur.com/a/X7eCnqZ

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#PanelUI-menu-button {
    padding-inline-end: 20px !important;
  }

.titlebar-buttonbox{
  border: 1px solid black !important;
}

.titlebar-button{
  padding: 8px 4px 10px 10px !important;
}

.titlebar-buttonbox-container .titlebar-buttonbox .titlebar-button{
  position: relative !important;
  cursor: pointer;
}
.titlebar-buttonbox > .titlebar-button {
  background: hsl(228, 13%, 40%) !important;
}

.titlebar-button > .toolbarbutton-icon {
  display: flex !important;
  width: 14px !important;
  height: 14px !important;
  border-radius: 50% !important;
  margin: 0 !important;
  padding: 0 !important;
  list-style-image: none !important;
  justify-content: center !important;
  align-items: center !important;
  stroke: none !important;
}

.titlebar-button > .toolbarbutton-icon::before,
.titlebar-button > .toolbarbutton-icon::after {
  border-radius: 50% !important;
}


.titlebar-min > .toolbarbutton-icon {
  background: hsla(44, 100%, 52%, 0.954) !important;
  border: 1px solid #ffbb00 !important;
  overflow: hidden !important;
  transition:  all 400ms ease !important;
}

.titlebar-min::before{
	content: '';
	position: absolute;
	top: 100%;
	left: 60%;
	transform: translate(-50%, -50%);
	width: 8px;
	height: 2px;
	opacity: 0;
	background:  rgba(0, 0, 0, 0.6);
  	border-radius: 2px;
}

.titlebar-min:hover::before{
	opacity: 1;
	top: 50%;
}


.titlebar-max > .toolbarbutton-icon,
.titlebar-restore > .toolbarbutton-icon {
  background: hsla(120, 94%, 49%, 0.867) !important;
  border: 1px solid #00ff00 !important;
  overflow: hidden !important;
  transition:  all 400ms ease !important;
}

.titlebar-restore::before{
	content: '';
	position: absolute;
	top: 100%;
	left: 60%;
	transform: translate(-50%, -50%);
	width: 9px;
	height: 9px;
	opacity: 0;
	background:  rgba(0, 0, 0, 0.6);
  	border-radius: 2px;
}

.titlebar-restore::after{
  	content: '';
	position: absolute;
	top: 100%;
	left: 60%;
	transform: translate(-50%, -50%);
	width: 4px;
	height: 6px;
	opacity: 0;
	background: #39ea49;
}

.titlebar-restore:hover::before, 
.titlebar-restore:hover::after{
	opacity: 1;
	top: 50%;
}

.titlebar-max::before{
	content: '';
	position: absolute;
	top: 100%;
	left: 60%;
	transform: translate(-50%, -50%);
	width: 9px;
	height: 9px;
	opacity: 0;
	background:  rgba(0, 0, 0, 0.6);
  	border-radius: 2px;
}

.titlebar-max::after{
	content: '';
	position: absolute;
	top: 100%;
	left: 60%;
	transform: translate(-50%, -50%) rotate(-45deg);
	width: 4px;
	height: 30%;
	opacity: 0;
	background: #39ea49;
}

.titlebar-max:hover::before, 
.titlebar-max:hover::after{
	opacity: 1;
	top: 50%;
}


.titlebar-close > .toolbarbutton-icon{
  background: hsla(357, 97%, 52%, 0.867) !important;
  border: 1px solid #ff000d !important;
  overflow: hidden !important;
  transition:  all 400ms ease !important;
}

.titlebar-close::before{
	content: '';
	position: absolute;
	top: 100%;
	left: 60%;
	transform: translate(-50%, -50%) rotate(-45deg);
	width: 2px;
	height: 9px;
	opacity: 0;
	background:  rgba(0, 0, 0, 0.65);
  	border-radius: 1px;
}

.titlebar-close::after{
	content: '';
	position: absolute;
	top: 100%;
	left: 60%;
	transform: translate(-50%, -50%) rotate(45deg);
	width: 2px;
	height: 9px;
 	opacity: 0;
	background: rgba(0, 0, 0, 0.65);
  	border-radius: 1px;
}

.titlebar-close:hover::before,  
.titlebar-close:hover::after{
	opacity: 1;
	top: 50%;
}
```

### Readme

```markdown
## Macos style button right side
- [x] **Small window style**
<div align="center">
  <figure>
    <img src="https://github.com/arg387/zenedit/blob/main/macos-left-button-small.gif">
  </figure>
  <p>$${\color{lightgreen}**Preview**}$$<p>
</div>

- [x] **Full window style**
<div align="center">
  <figure>
    <img src="https://github.com/arg387/zenedit/blob/main/macos-left-button-full.gif">
  </figure>
  <p>$${\color{lightgreen}**Preview**}$$<p>
</div>
```

### Preferences

```json

```
