### ISSUE TITLE
[create-theme]: centered placeholder

### ISSUE THREAD

**Issue by arg387** [zen-browser/theme-store#1282]
### Name

centered placeholder

### Description

Make Placeholder text centered

### Homepage

https://github.com/arg387/zenedit

### Image

https://imgur.com/a/Zpom9Pc

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#urlbar-input { 
  text-align: center !important; 
}
```

### Readme

```markdown
This will center the placeholder text of search box.
```

### Preferences

```json

```
