### ISSUE TITLE
[create-theme]: scrollbar to screen edge

### ISSUE THREAD

**Issue by tahawael** [zen-browser/theme-store#1292]
### Name

scrollbar to screen edge

### Description

Puts the scrollbar to the very right edge of the screen

### Image

https://imgur.com/a/Crv3TsM

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@-moz-document url-prefix("chrome:") {
    & #zen-tabbox-wrapper {
        margin: 0 !important;
    }
}
```

### Readme

```markdown
# scrollbar to screen edge

Puts the scrollbar to the very right edge of the screen
```

### Preferences

```json

```
