### ISSUE TITLE
[create-theme]: Floating Media Bar

### ISSUE THREAD

**Issue by sebascontre** [zen-browser/theme-store#1306]
### Name

Floating Media Bar

### Description

Made the new Media Bar floats over the corner when the sidebar is in thin or compact mode

### Image

https://i.imgur.com/tnBGLPh.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#navigator-toolbox:not([zen-sidebar-expanded="true"]) {
  opacity: 1 !important;
  z-index: calc(var(--browser-area-z-index-toolbox) + 1) !important;
  
  #zen-media-controls-toolbar {
    display: block !important;
    bottom: calc(var(--zen-element-separation) + var(--zen-toolbox-padding));
    left: calc(var(--actual-zen-sidebar-width) + var(--zen-toolbox-padding));
    position: absolute !important;
    width: 200px;
    z-index: 3 !important;
  }
}

#navigator-toolbox[zen-right-side="true"]:not([zen-sidebar-expanded="true"]) {
  #zen-media-controls-toolbar[style="height: 34px; opacity: 1; transform: none;"]
  {
    left: auto;
    right: calc(var(--actual-zen-sidebar-width) + var(--zen-toolbox-padding));
  }
}

#zen-main-app-wrapper[zen-compact-mode="true"] {
  #navigator-toolbox:not([zen-sidebar-expanded="true"]) {
    #zen-media-controls-toolbar {
      bottom: calc(var(--zen-element-separation));
    }
  }
}
```

### Readme

```markdown
# Floating Media Bar

## Description
Made the new Media Bar floats over the corner when the sidebar is in thin or compact mode
```

### Preferences

```json

```
