### ISSUE TITLE
[create-theme]: Better Spacing

### ISSUE THREAD

**Issue by nalejandroveron** [zen-browser/theme-store#1310]
### Name

Better Spacing

### Description

Let Zen breathe with more margin on the URL bar & icons aligned with the browser window

### Homepage

https://github.com/nalejandroveron/zen-better-spacing

### Image

https://raw.githubusercontent.com/nalejandroveron/zen-better-spacing/refs/heads/main/Mod-thumbnail.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
:root:not([zen-single-toolbar="true"]) #nav-bar {
  margin: 0.4rem 0;
  margin-bottom: 0.4rem !important;
}

:root:not([zen-single-toolbar="true"]):not([zen-compact-mode="true"]) #TabsToolbar-customization-target {
  margin-top: 0.8rem;
}

:root:not([zen-single-toolbar="true"]) #PersonalToolbar:not([collapsed="true"]) {
  margin-bottom: 0.2rem;
}

:root[zen-single-toolbar="true"] #PersonalToolbar:not([collapsed="true"]) {
  margin: 0.2rem 0;
}

:root:not([zen-compact-mode="true"])[zen-sidebar-expanded="true"] #zen-sidebar-bottom-buttons {
  margin-bottom: 0.3rem;
}

:root:not([zen-compact-mode="true"]):not([zen-sidebar-expanded="true"]) #zen-sidebar-bottom-buttons {
  margin-bottom: 1rem;
}
```

### Readme

```markdown
# Zen Better Spacing

Let Zen breathe with this mod that adds the following changes:

- More margin on the URL bar for two toolbars setting.
- Sidebar icons aligned with the browser window.
```

### Preferences

```json

```
