### ISSUE TITLE
Center URL Mod

### ISSUE THREAD

**Issue by GentleWizard** [zen-browser/theme-store#1314]
### Name

Center URL

### Description

A mod for Zen Browser that centers the URL bar in compact mode, creating a cleaner browsing experience with fewer distractions.

### Homepage

https://github.com/GentleWizard/Zen-Mods/tree/main/Center%20URL

### Image

https://raw.githubusercontent.com/GentleWizard/Zen-Mods/refs/heads/main/Center%20URL/image.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
:root[zen-compact-mode="true"] #urlbar[open] {
	visibility: visible !important;
	position: fixed !important;
	padding: 15px !important;
	top: 35% !important;
	left: 50% !important;
	transform: translateX(-50%);
	transform-origin: top center;
	min-width: 45% !important;
	z-index: 9999 !important;
}

@media (-moz-bool-pref: "mod.centerurl.hide_toolbar") {
	#zen-appcontent-navbar-container {
		transition: initial !important;
	}

	:root[zen-compact-mode="true"]
		#zen-appcontent-navbar-container:has(#urlbar[open]) {
		visibility: hidden !important;
	}
}
```

### Readme

```markdown
# Center URL Mod for Zen Browser

## Overview

This mod centers the URL bar in the middle of the screen when activated and compact mode is enabled, creating a cleaner and more focused browsing experience.

## Features

- Centers the URL bar
- Option to hide the top toolbar when the URL bar is active
-

## Configuration

The mod can be configured through the Zen browser's settings panel:

| Option | Description | Default |
|--------|-------------|---------|
| Hide the toolbar | Hides the navigation toolbar when the URL bar is opened | Enabled |

## How It Works

When you click on the URL bar or use the keybind in compact mode, it will:

1. Detach from its normal position
2. Optionally hide the toolbar for a cleaner look
3. Return to normal position when you finish your interaction

## Compatibility

This mod is designed to work with Zen browser's compact mode. Ensure you have compact mode enabled to see the effects.
Other mods that modify the URL's position may conflict with this mod. Otherwise, it should work with most other mods.

## Troubleshooting

If the URL bar isn't centering properly:

- Verify that compact mode is enabled in Zen
- Check that the mod is properly installed in your chrome folder
- Restart the browser after making changes
```

### Preferences

```json
{
	"property": "mod.centerurl.hide_toolbar",
	"label": "Hide the toolbar",
	"type": "checkbox",
	"defaultValue": true
}
```
