### ISSUE TITLE
[create-theme]: Floating Media Bar

### ISSUE THREAD

**Issue by sebascontre** [zen-browser/theme-store#1315]
### Name

Floating Media Bar

### Description

Add the new media bar floating in a corner when using the sidebar is in thin mode

### Image

https://i.imgur.com/4yxQHHh.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#navigator-toolbox:not([zen-sidebar-expanded="true"]) {
  opacity: 1 !important;
  z-index: calc(var(--browser-area-z-index-toolbox) + 1) !important;
  
  #zen-media-controls-toolbar:has(#zen-media-focus-button[style]) {
    display: block !important;
    bottom: calc(var(--zen-element-separation) + var(--zen-toolbox-padding));
    left: calc(var(--actual-zen-sidebar-width) + var(--zen-toolbox-padding));
    position: absolute !important;
    width: 200px;
    transition: 0.2s !important;
    z-index: 3 !important;
  }  
  
  @media (-moz-bool-pref: "mod.floating-media-bar.favicon-only") {
    #zen-media-controls-toolbar:has(#zen-media-focus-button[style]) {
      width: calc(26px + 12px);
    }
    
    #zen-media-controls-toolbar:hover {
      width: 200px !important;
    }
    
    #zen-media-controls-toolbar:hover #zen-media-previoustrack-button,
    #zen-media-controls-toolbar:hover #zen-media-nexttrack-button,
    #zen-media-controls-toolbar:hover #zen-media-playpause-button,
    #zen-media-controls-toolbar:hover #zen-media-mute-button {
      display: initial;
    }

    #zen-media-previoustrack-button,
    #zen-media-nexttrack-button,
    #zen-media-playpause-button,
    #zen-media-mute-button {
      display: none;
    }
  }
}

#navigator-toolbox[zen-right-side="true"]:not([zen-sidebar-expanded="true"]) {
  #zen-media-controls-toolbar {
    left: auto !important;
    right: calc(var(--actual-zen-sidebar-width) + var(--zen-toolbox-padding));
  }
}

#zen-main-app-wrapper[zen-compact-mode="true"] {
  #navigator-toolbox:has(#zen-media-controls-toolbar:hover):not([zen-sidebar-expanded="true"]) {
    left: calc(-1 * var(--actual-zen-sidebar-width) + 1px) !important;
  }
  
  #navigator-toolbox[zen-right-side="true"]:has(#zen-media-controls-toolbar:hover):not([zen-sidebar-expanded="true"]) {
    left: auto !important;
    right: calc(-1 * var(--actual-zen-sidebar-width) + 1px) !important;
  }

  
  #navigator-toolbox:not([zen-sidebar-expanded="true"]) {
    #zen-media-controls-toolbar {
      bottom: var(--zen-element-separation);
    }
  }
}

#zen-main-app-wrapper[zen-compact-mode="true"]:has(#zen-appcontent-wrapper:hover) {
  #navigator-toolbox:not([zen-sidebar-expanded="true"]) {
    left: calc(-1 * var(--actual-zen-sidebar-width) + 1px) !important;
  }
  
  #navigator-toolbox[zen-right-side="true"]:not([zen-sidebar-expanded="true"]) {
    left: auto !important;
    right: calc(-1 * var(--actual-zen-sidebar-width) + 1px) !important;
  }
}
```

### Readme

```markdown
# Floating Media Bar

Add the new media bar floating in a corner when using the sidebar is in thin mode.

## Settings

- Has a toggle to show the full bar always, or only the favicon and the rest on hover.

## Thanks to

- [AcademicShape6829](https://www.reddit.com/user/AcademicShape6829/) for the favicon only idea and css code.
```

### Preferences

```json
[
{
  "property": "mod.floating-media-bar.favicon-only",
  "label": "Shows only the favicon in the media bar, hover it for the complete bar.",
  "type": "checkbox",
  "defaultValue": false,
  "disabledOn": []
}
]
```
