### ISSUE TITLE
[create-theme]: No Bottom Workspaces

### ISSUE THREAD

**Issue by phlppk** [zen-browser/theme-store#1319]
### Name

No Bottom Workspaces

### Description

Removes the bottom workspace switcher and icons from Zen’s sidebar.

### Image

https://i.imgur.com/t9w5Iyl.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#zen-workspaces-button {
    display: none !important;
  }
```

### Readme

```markdown
Removes the bottom workspace switcher and icons from Zen’s sidebar.
```

### Preferences

```json

```
