### ISSUE TITLE
[create-theme]: No Bottom Workspaces

### ISSUE THREAD

**Issue by phlppk** [zen-browser/theme-store#1320]
### Name

No Bottom Workspaces

### Description

Removes the bottom workspace switcher and icons from Zen’s sidebar.

### Image

blob:https://imgur.com/a769e2cc-da85-4339-a7f6-b1664035f431

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#zen-workspaces-button {
    display: none !important;
  }
```

### Readme

```markdown
Removes the bottom workspace switcher and icons from Zen’s sidebar.
```

### Preferences

```json

```
