### ISSUE TITLE
[create-theme]: Zen UI: Compact URL + Sidebar

### ISSUE THREAD

**Issue by Pjhochman** [zen-browser/theme-store#1329]
### Name

Zen UI: Compact URL + Sidebar

### Description

A compact UI mod with a smaller, centered URL bar, a vertically centered sidebar, and Zen palette.

### Homepage

https://github.com/pjhochman

### Image

https://imgur.com/a/UH2ieKC

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
/* Custom Zen UI Tweaks */

/* Common values to simplify repeated values */
:root {
  --zen-dark-bg: rgba(31, 31, 31, 0.9);
  --zen-light-text: rgba(242, 239, 228, 1);
  --zen-highlight: rgba(31, 31, 31, 1);
  --zen-accent: rgba(247, 111, 83, 1);
  --border-radius: 8px;
}

* {
  --urlbarView-highlight-background: var(--zen-light-text) !important;
  --toolbar-field-focus-color: var(--zen-light-text) !important;
  --urlbarView-highlight-color: var(--zen-highlight) !important;
  --toolbar-field-color: var(--zen-light-text) !important;
  --zen-branding-bg-reverse: transparent !important;
}

/* Hide the URL path from the URL bar view */
span.urlbarView-url {
  display: none !important;
}

/* Apply text and background color when hovering over url rows */
.urlbarView-row:hover {
  background-color: var(--zen-light-text) !important;
  color: var(--zen-dark-bg) !important;
}

/* Hide hyphen and 'search on Google' from the URL bar view  */
span.urlbarView-action, 
span.urlbarView-title-separator {
  display: none !important;
}

/* Remove close buttons on sidebar tab icons for a cleaner look */
.tab-close-button {
  display: none !important;
}

/* Hide the "Extension tabliss" label in the URL bar to remove clutter */
box#identity-icon-box {
  display: none !important;
}

/* Hide navbar container and reduce its width to prevent triggering navbar visibility on side hover */
#zen-appcontent-navbar-container {
  box-shadow: unset !important;
  background: transparent !important;
  border: unset !important;
  position: absolute !important;
  width: 45% !important;
  left: 50% !important;
  transform: translateX(-50%) !important;
  z-index: 10 !important;
}

/* Increase negative variable value to fully hide navbar */
@-moz-document url("chrome://browser/content/browser.xhtml") {
  :root[zen-compact-mode="true"]:not([customizing]):not([inDOMFullscreen="true"]):not([zen-single-toolbar="true"]) #zen-appcontent-navbar-container {
   --zen-element-separation: -10px !important; 
  }
}

/* Customize the toolbar appearance */
toolbar#nav-bar {
  width: 100%;
  top: 1.8vh !important;
  background: var(--zen-dark-bg) !important;
  box-shadow: var(--zen-big-shadow) !important;
  border: 0 solid var(--zen-dark-bg) !important;
  border-radius: var(--border-radius) !important;
}

/* Center the URL bar */
#urlbar {
  left: 50% !important;
  transform: translateX(-50%) !important;
}

/* Placeholder text color for search bar input */
.urlbar-input::placeholder,
.searchbar-textbox::placeholder {
   color: var(--zen-light-text) !important;
}

/* Improve responsiveness for the URL bar */
#urlbar-container {
  #nav-bar:is([downloadsbuttonshown], [unifiedextensionsbuttonshown]) & {
    width: 0 !important;
  }
}

/* URL bar background before typing */
#urlbar:not([breakout-extend="true"]) #urlbar-background {
  transition: unset !important;
  background: transparent !important;
}

/* URL bar background after typing */
#urlbar[breakout][breakout-extend] #urlbar-background {
  background: rgba(31, 31, 31, 0.95) !important;
}

/* URL Bar text styling */
#urlbar-container {
  text-align: center;
  font-weight: 400 !important;
}

/* URL bar text color BEFORE entering breakout state */
#urlbar {
  color: var(--zen-light-text) !important;
}

/* URL bar text color DURING breakout state (when expanded or focused) */
#urlbar[breakout][breakout-extend] {
  color: var(--zen-light-text) !important;
}

/* Position side bar in the middle */
toolbox#navigator-toolbox {
  justify-content: center !important;
}

/* Styling of the sidebar */
hbox#titlebar {
  height: 75% !important;
  background: var(--zen-dark-bg) !important;
  border: unset !important;
}

/* Styling of the sidebar */
:root[zen-compact-mode="true"]:not([customizing]):not([inDOMFullscreen="true"])
#navigator-toolbox:not([animate="true"]) #titlebar {
  border-radius: var(--border-radius) !important;
}

/* Sidebar tab icons styling */
vbox.tab-background {
  background: transparent !important;
  border-radius: var(--border-radius) !important;
}

/* Apply Zen brand color to the selected sidebar tab icon */
.tab-content {
  &:is([selected], [multiselected]) {
    border-left: 2px solid var(--zen-accent);
  }
}

/* Adjust menu button position for centered navbar alignment */
#PanelUI-menu-button {
  padding-inline-end: 0px !important;
  margin-left: -5px !important;
}

/* Apply Zen brand color to the three-dot menu button */
.toolbarbutton-icon[label="Zen"] {
  fill: var(--zen-accent) !important;
}

/* If kept, make starred bookmarks blend in with other icons */
#star-button[starred] {
  fill-opacity: 0.4 !important;
  fill: var(--toolbarbutton-icon-fill) !important;
}

/* Hide buttons for a cleaner interface */
#reader-mode-button,
#translations-button,
#identity-permission-box,
#star-button-box,
#PersonalToolbar {
  display: none !important;
}

/* Reduce width to prevent customization palette container from collapsing */
#customization-panel-container {
width: 20% !important;
}
```

### Readme

```markdown
# Zen UI: Compact URL + Sidebar

A minimalist UI mod for Zen Browser that applies the official Zen color palette, compacts the URL bar, vertically centers the sidebar, and removes unnecessary UI elements for a cleaner, more focused browsing experience.

---

## 🌟 Features

- 🔳 **Floating, compact URL bar**
- 🧱 **Vertically centered, compact sidebar**
- 🎨 **Applies the official Zen color palette**
- ✂️ **Removes unnecessary labels and buttons for a cleaner interface**
- 🖱️ **Sidebar and toolbar appear on hover for quick access**
- 🚀 **Fully compatible with Zen Browser's Compact Mode**

---

## 🛠 Preferences Setup

This mod **automatically applies** the recommended settings via JSON preferences, so you **don’t need to manually configure anything**.


{
  "zen.urlbar.behavior": "float",
  "zen.view.compact": true,
  "zen.view.compact.show-sidebar-and-toolbar-on-hover": true,
  "zen.view.compact.hide-toolbar": true,
  "zen.view.compact.hide-tabbar": true,
  "zen.view.compact.animate-sidebar": true,
  "zen.view.compact.toolbar-flash-popup": true
}


If certain features don’t work as expected, check your Zen Browser settings under **"Compact Mode" and "Zen URL Bar"** to ensure they align with your preferences.

---

## 💻 Toolbar Customization (macOS & Windows)

### 🪟 Windows:
1. Right-click the sidebar → **Customize Toolbar**
2. Drag **three Flexible Space** items to both the **left and right** of the URL input field.
   - This visually centers the URL bar and makes the browser window easier to grab.

### 🍎 macOS:
1. Right-click the sidebar → **Customize Toolbar**
2. Drag **two Flexible Space** items to both the **left and right** of the URL input field.
3. _(Optional)_ For a perfectly symmetrical layout:
   - Move the **Back Arrow** to the **left** of the URL input.
   - Move the **Forward Arrow** to the **right** of the URL input.

**Suggested toolbar layout (left → right):**

[Close] [Minimize] [Maximize] [Reload] [Back] 
[URL Input] 
[Forward] [Any two toolbar items of your choice] [Three-dot Menu]

> For example, common toolbar items include: **Bookmarks, History, Extensions, or Translate**.

---

## 📷 Screenshot

https://imgur.com/a/UH2ieKC

---

## ⚙️ Preferences JSON

_Already included in the mod (see above), no manual changes needed._

---

### ✅ **Final Notes**
- This mod is designed for **Compact Mode users** who prefer a cleaner, distraction-free layout.
- If you experience issues with visibility, try toggling **"Compact Mode" settings in Zen Browser’s preferences**.

---
```

### Preferences

```json
{
  "zen.urlbar.behavior": "float",
  "zen.view.compact": true,
  "zen.view.compact.show-sidebar-and-toolbar-on-hover": true,
  "zen.view.compact.hide-toolbar": true,
  "zen.view.compact.hide-tabbar": true,
  "zen.view.compact.animate-sidebar": true,
  "zen.view.compact.toolbar-flash-popup": true
}
```
