### ISSUE TITLE
[create-theme]: Bookmark Hide Compact

### ISSUE THREAD

**Issue by Markusice** [zen-browser/theme-store#1343]
### Name

Bookmark Hide Compact

### Description

Hides bookmarks in Compact mode when using Single toolbar layout.

### Homepage

https://github.com/Markusice/bookmark_hide_compact

### Image

https://imgur.com/a/coT8LUj

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
:root[zen-single-toolbar="true"][zen-compact-mode="true"] {
    & #zen-appcontent-navbar-container {
        max-height: 0 !important;
        overflow: hidden;
        opacity: 0 !important;
        pointer-events: none !important;

        & #PersonalToolbar {
            max-height: 0px;
            min-height: 0px;
            visibility: collapse;
        }
    }
}
```

### Readme

```markdown
# Bookmark Hide Compact

Hides bookmarks in Compact mode when using Single toolbar layout with zen.view.hide-window-controls set to false.

## Enable bookmarks in Single toolbar layout

- Go to `about:config`
- Search for `zen.view.hide-window-controls` and double click on it to set it to false.

![bookmark_hide_compact](https://github.com/user-attachments/assets/82022ac0-3881-49c5-8815-0be9e3f47c96)
```

### Preferences

```json

```
