### ISSUE TITLE
[create-theme]: Remove Dim PiP

### ISSUE THREAD

**Issue by seanstackn** [zen-browser/theme-store#1350]
### Name

Remove Dim PiP

### Description

Removes the dimming effect while hovering a Picture in Picture video

### Homepage

https://github.com/seanstackn/Remove-Dim-PiP

### Image

https://private-user-images.githubusercontent.com/29420276/426635578-651dbcaa-b2d9-4b9e-80dd-ce9186b43137.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDI5MjE2NjUsIm5iZiI6MTc0MjkyMTM2NSwicGF0aCI6Ii8yOTQyMDI3Ni80MjY2MzU1NzgtNjUxZGJjYWEtYjJkOS00YjllLTgwZGQtY2U5MTg2YjQzMTM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzI1VDE2NDkyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmODY4MWFmMTg0MTA4OWI1YzdlNDk1MDYyMzMzM2ZiNDIxYzM3MjE3YzQ3ZmRiZmZmNTlhZDc1ZmJiZjc3MGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3dyPmzR697ql11WLr0r6wjccllyNkMUG8rrSBRctDgw

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
/* Removes dimming effect while hovering PiP (Picture in Picture) video */
#controls:hover {
	background-color: transparent !important;
}

#pip-window:hover {
  opacity: 1 !important;
}
```

### Readme

```markdown
# Remove-Dim-PiP
Removes the dim effect when hovering on a video in Picture in Picture mode
![image](https://github.com/user-attachments/assets/651dbcaa-b2d9-4b9e-80dd-ce9186b43137)
```

### Preferences

```json

```
