### ISSUE TITLE
[create-theme]: Remove Dim PiP

### ISSUE THREAD

**Issue by seanstackn** [zen-browser/theme-store#1353]
### Name

Remove Dim PiP

### Description

Removes the dimming effect while hovering a Picture in Picture video

### Homepage

https://github.com/seanstackn/Remove-Dim-PiP

### Image

https://imgur.com/qv0FOEQ

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
/* Removes dimming effect while hovering PiP (Picture in Picture) video */
#controls:hover {
	background-color: transparent !important;
}

#pip-window:hover {
  opacity: 1 !important;
}
```

### Readme

```markdown
# Remove-Dim-PiP
Removes the dim effect when hovering on a video in Picture in Picture mode
![qv0FOEQ](https://github.com/user-attachments/assets/78930c1a-a05b-4587-b95b-593cdc0f54ca)
```

### Preferences

```json

```
