### ISSUE TITLE
[create-theme]: black and gray theme

### ISSUE THREAD

**Issue by Pen-Man** [zen-browser/theme-store#136]
### Name

black and gray

### Description

its just a zen theme with black and gray

### Image

https://imgur.com/a/NrZHaCd

### Type

- [X] JSON Color Theme

### Theme Styles

```css
@-moz-document url-prefix("chrome:") {
        /* This is an auto generated color theme. */
:root {
    --zen-colors-primary: #4d4d4d !important;
    --zen-colors-secondary: #3c3c3c !important;
    --zen-colors-tertiary: #111111 !important;
    --zen-colors-border: #212121 !important;
    --zen-primary-color: #9e9e9e !important;
    color-scheme: dark !important;
}

      }
```

### Readme

```markdown
umm, its simple.
```
