### ISSUE TITLE
[create-theme]: Zen Mod - MacOs buttons

### ISSUE THREAD

**Issue by YofarDev** [zen-browser/theme-store#1361]
### Name

MacOs buttons

### Description

Changes the Exit-Maximize-Reduce buttons close to MacOS version for Linux/Windows

### Homepage

https://github.com/YofarDev/zen-minimal-exit-menu-main

### Image

https://github.com/YofarDev/zen-minimal-exit-menu-main/blob/main/screen.png?raw=true

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
.titlebar-buttonbox {
    margin-right: 20px;
}

.titlebar-button {
    padding: 0px !important;
    min-height: 13px !important;
    min-width: 13px !important;
    height: 13px !important;
    align-self: center;
    margin-left: 10px !important;
    border-radius: 50px;
    transition: all 100ms;
}

.titlebar-min {
    background-color: hsl(93, 30%, 65%, 0.7) !important;
}

.titlebar-max, .titlebar-restore {
    background-color: hsl(40, 71%, 73%, 0.7) !important;
}

.titlebar-close {
    background-color: hsl(354, 42%, 56%, 0.7) !important;
}

.titlebar-button > image {
    visibility: collapse !important;
}

.titlebar-min:hover {
    background-color: hsl(93, 30%, 65%) !important;
}

.titlebar-max:hover, .titlebar-restore:hover {
    background-color: hsl(40, 71%, 73%) !important;
}

.titlebar-close:hover {
    background-color: hsl(354, 42%, 56%) !important;
}
```

### Readme

```markdown
# Zen MacOs buttons

A Zen browser mod that changes the Exit-Maximize-Reduce buttons close to MacOS version for Linux/Windows.
```

### Preferences

```json
[
    {
        "property": "theme.zen-macos-buttons.enable-macos-buttons",
        "label": "Enable MacOS theme for Exit-Maximize-Reduce buttons",
        "defaultValue": "false",
        "disabledOn": [
            "macos"
        ],
        "type": "checkbox"
    }
]
```
