### ISSUE TITLE
[create-theme]: Application Frame

### ISSUE THREAD

**Issue by psu** [zen-browser/theme-store#1364]
### Name

Application Frame

### Description

A small mod to add _application frame width_ as a preference in Zen.

### Homepage

https://github.com/psu/zen-mods

### Image

https://raw.githubusercontent.com/psu/zen-mods/refs/heads/main/application-frame/application-frame.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
/**
* Zen Mod: Application Frame
* Add application frame width as a preference to the Zen Browser.
* Pontus Sundén <hi@pontus.cc>
*/
  :root {
    /**
    --psu-app_frame-width: 5px;
    /**/
    --zen-element-separation: var(--psu-app_frame-width) !important;
  }
```

### Readme

```markdown
# Zen Mod: Application Frame

A small mod to add _application frame width_ as a preference in Zen.

![screenshot](./application-frame.png)

[Source code at GitHub](https://github.com/psu/zen-mods)
```

### Preferences

```json
[
  {
    "label": "Width",
    "defaultValue": "5px",
    "placeholder": "8px",
    "property": "psu.app_frame.width",
    "type": "string"
  }
]
```
