### ISSUE TITLE
[create-theme]: Tab rename fix

### ISSUE THREAD

**Issue by psu** [zen-browser/theme-store#1373]
### Name

Tab rename fix

### Description

Better visibility of tab renaming by inverting the selected text colors.

### Homepage

https://github.com/psu/zen-mods

### Image

https://raw.githubusercontent.com/psu/zen-mods/refs/heads/main/tab-rename-fix/tab-rename-fix.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
/**
* Zen Mod: Tab rename fix
* Better visibility of tab renaming by inverting the selected text colors.
* Pontus Sundén <hi@pontus.cc>
*/
  #tab-label-input::selection {
    background: var(--input-color) !important;
    color: var(--input-bgcolor) !important;
  }
```

### Readme

```markdown
# Zen Mod: Tab rename fix

Better visibility of tab renaming by inverting the selected text colors.

![screenshot](./tab-rename-fix.png)

[Source code at GitHub](https://github.com/psu/zen-mods)
```

### Preferences

```json

```
