### ISSUE TITLE
[create-theme]: Tab title fixes

### ISSUE THREAD

**Issue by psu** [zen-browser/theme-store#1375]
### Name

Tab title fixes

### Description

Increase size of tab titles and add make pending tabs standing out more.

### Homepage

https://github.com/psu/zen-mods

### Image

https://raw.githubusercontent.com/psu/zen-mods/refs/heads/main/tab-title-fix/tab-title-fix.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
/**
* Zen Mod: Tab title fixes
* Increase size of tab titles and add make pending tabs standing out more.
* Pontus Sundén <hi@pontus.cc>
*/
  :root {
    /**
    --psu-tab_title_fixes-font_size: 13px;
    --psu-tab_title_fixes-pending_opacity: 0.55;
    /**/
  }
  #tabbrowser-tabs {
    .tabbrowser-tab {
      #tab-label-input,
      .tab-label {
        font-size: var(--psu-tab_title_fixes-font_size) !important;
      }
      .tab-icon-image,
      .tab-label-container {
        &:not([selected], [multiselected]) {
          opacity: calc(var(--psu-tab_title_fixes-pending_opacity) + 0.3) !important;
        }
      }
      @media (-moz-bool-pref: 'zen.tabs.dim-pending') {
        &[pending='true'] {
          .tab-icon-image,
          .tab-label-container:not([selected], [multiselected]) {
            opacity: var(--psu-tab_title_fixes-pending_opacity) !important;
          }
        }
      }
    }
  }
```

### Readme

```markdown
# Zen Mod: Tab title fixes

Increase size of tab titles and add make pending tabs standing out more.

![screenshot](./tab-title-fix.png)

[Source code at GitHub](https://github.com/psu/zen-mods)
```

### Preferences

```json
[
  {
    "label": "Tab Name Font Size",
    "defaultValue": "13px",
    "placeholder": "11px",
    "property": "psu.tab_title_fixes.font_size",
    "type": "string"
  },
  {
    "label": "Icon and Name Opacity for Tabs not Loaded",
    "defaultValue": "0.55",
    "placeholder": "1",
    "property": "psu.tab_title_fixes.pending_opacity",
    "type": "string"
  }
]
```
