### ISSUE TITLE
[create-theme]: Right Side Glance Buttons

### ISSUE THREAD

**Issue by psu** [zen-browser/theme-store#1379]
### Name

Right Side Glance Buttons

### Description

Move the at a glance buttons to the right side of the window.

### Homepage

https://github.com/psu/zen-mods

### Image

https://raw.githubusercontent.com/psu/zen-mods/refs/heads/main/glance-buttons-right/glance-buttons-right.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
/**
* Zen Mod: Right Side Glance Buttons
* Move the at a glance buttons to the right side of the window.
* Pontus Sundén <hi@pontus.cc>
*/
  #zen-glance-sidebar-container {
    left: unset !important;
    right: 6% !important;
    top: 60px !important;
    toolbarbutton {
      box-shadow: 0px 0px 8px 4px rgba(0, 0, 0, 0.07) !important;
      border: rgba(180, 180, 180, 0.2) 0.2px solid;
    }
  }
```

### Readme

```markdown
# Zen Mod: Right Side Glance Buttons

Move the at a glance buttons to the right side of the window.

![screenshot](./glance-buttons-right.png)

[Source code at GitHub](https://github.com/psu/zen-mods)
```

### Preferences

```json

```
