### ISSUE TITLE
[create-theme]:

### ISSUE THREAD

**Issue by dillontkh** [zen-browser/theme-store#1387]
### Name

Hide Sidebar Toggle

### Description

Make the Toggle Sidebar's Width keyboard shortcut completely hide the sidebar.

### Image

https://i.imgur.com/MuFhm4S.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#navigator-toolbox:not([zen-sidebar-expanded='true']) {
    visibility: collapse;
}

:root:not([zen-sidebar-expanded='true']) #zen-sidebar-splitter {
    display: initial !important;
    pointer-events: none !important;
}
```

### Readme

```markdown
Make the Toggle Sidebar's Width keyboard shortcut completely hide the sidebar.
```

### Preferences

```json

```
