### ISSUE TITLE
[create-theme]: hidden-workspace-tab-top-margin

### ISSUE THREAD

**Issue by davidambler** [zen-browser/theme-store#1398]
### Name

Hide Workspace Tab Margin

### Description

Add margin between tabs and essentials when `workspaces.show-workspace-indicator` config is `false`.

### Homepage

https://github.com/davidambler/zen-hidden-workspace-tab-top-margin

### Image

https://raw.githubusercontent.com/davidambler/zen-hidden-workspace-tab-top-margin/refs/heads/main/screenshots/zen-hidden-workspace-tab-top-margin.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
/* Fix to tab margins when `zen.workspaces.show-workspace-indicator`
is set to false */
#zen-tabs-wrapper {
    margin-top: var(--zen-toolbox-padding);
}
```

### Readme

```markdown
# zen-hidden-workspace-tab-top-margin
Fix margin between tabs and essentials when `workspaces.show-workspace-indicator` config is `false`.
```

### Preferences

```json

```
