### ISSUE TITLE
[create-theme]: <Frostfocus>

### ISSUE THREAD

**Issue by akahyperion** [zen-browser/theme-store#1403]
### Name

Frostfocus

### Description

Adds a smooth blur effect to your web content whenever the URL bar is focused.

### Image

https://bashify.io/i/XVT0O9

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
/* Default state: no blur */
#zen-tabbox-wrapper {
  transition: filter 0.25s ease;
  filter: none;
}

/* Blur when urlbar is focused */
:has(#urlbar:focus-within) #zen-tabbox-wrapper {
  filter: blur(8px) brightness(0.7);
}
```

### Readme

```markdown
Adds a smooth blur effect to your web content whenever the URL bar is focused.
```

### Preferences

```json

```
