### ISSUE TITLE
[create-theme]: <Frostfocus>

### ISSUE THREAD

**Issue by akahyperion** [zen-browser/theme-store#1404]
### Name

Frostfocus

### Description

Adds a smooth blur effect to your web content whenever the URL bar is focused.

### Image

https://bashify.io/img/5f22fadf6d4bcd2524cbfd9e493ff5c1

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
/* Default state: no blur */
#zen-tabbox-wrapper {
  transition: filter 0.25s ease;
  filter: none;
}

/* Blur and dim when #urlbar is focused */
:has(#urlbar:focus-within) #zen-tabbox-wrapper {
  filter: blur(8px) brightness(0.7);
}
```

### Readme

```markdown
Adds a smooth blur effect to your web content whenever the URL bar is focused.
```

### Preferences

```json

```
