### ISSUE TITLE
[create-theme]: Zen frontback gesture

### ISSUE THREAD

**Issue by Fury7425** [zen-browser/theme-store#1409]
### Name

trackpad animation

### Description

adds backward and forward animation for trackpad gesture

### Homepage

https://github.com/Fury7425/zen-trackpad-gesture-animation

### Image

https://github.com/Fury7425/zen-trackpad-gesture-animation/blob/main/example.png?raw=true

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@media (-moz-bool-pref: "mod.browser.scale_enabled") {
  :root {
    --mod-browser-scale: var(--user-browser-scale, 0.98);
    --mod-browser-ease-swipe: var(--user-browser-ease-swipe, 0.3, 1.2, 0.5, 1);
    --mod-browser-ease-reset: var(--user-browser-ease-reset, 0.2, 1.4, 0.3, 1);
  }

  .browserStack browser {
    transition: transform 0.22s cubic-bezier(var(--mod-browser-ease-swipe)) !important;
  }

  .browserStack:has(#historySwipeAnimationPreviousArrow:not([style="translate: none;"])) browser {
    scale: var(--mod-browser-scale) !important;
    transform: translateX(4%) !important;
  }

  .browserStack:has(#historySwipeAnimationNextArrow:not([style="translate: none;"])) browser {
    scale: var(--mod-browser-scale) !important;
    transform: translateX(-4%) !important;
  }

  .browserStack browser:not(:has(#historySwipeAnimationPreviousArrow, #historySwipeAnimationNextArrow)) {
    transition: transform 0.25s cubic-bezier(var(--mod-browser-ease-reset)) !important;
    transform: translateX(0) !important;
  }
}
```

### Readme

```markdown
made it for an extra animation when using a trackpad.
```

### Preferences

```json
[
    {
        "property": "mod.browser.scale_enabled",
        "label": "Enable swipe scale animation",
        "type": "checkbox",
        "defaultValue": true
    },
    {
        "property": "user-browser-scale",
        "label": "Swipe scale (e.g. 0.98 for 2%)",
        "type": "string",
        "defaultValue": "0.98",
        "placeholder": "0.97\u20131.00"
    },
    {
        "property": "user-browser-ease-swipe",
        "label": "Swipe easing curve (4 numbers)",
        "type": "string",
        "defaultValue": "0.3, 1.2, 0.5, 1",
        "placeholder": "e.g. 0.25, 0.1, 0.25, 1"
      },
      {
        "property": "user-browser-ease-reset",
        "label": "Reset easing curve (4 numbers)",
        "type": "string",
        "defaultValue": "0.2, 1.4, 0.3, 1",
        "placeholder": "e.g. 0.2, 0.8, 0.2, 1"
      }
      
]
```
