### ISSUE TITLE
[create-theme]: Outlined Tab Groups

### ISSUE THREAD

**Issue by Lu9-ST** [zen-browser/theme-store#1420]
### Name

Outlined Tab Groups

### Description

Fixes text centering on tab groups (experimental feature) and gives them an outline-only look

### Homepage

https://github.com/Lu9-ST/zen-stuff/tree/main

### Image

https://raw.githubusercontent.com/Lu9-ST/zen-stuff/refs/heads/main/outlined-tab-groups.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
/* Outlined Tab Groups */
/* Fixes text centering on tab groups (experimental Firefox 137+ feature, can be activated now in Zen with about:config) and gives them an outline-only look, changes to solid fill color when opened */
.tab-group-label-container {
  padding-left: 5px;
}

.tab-group-label {
  outline: unset;
  background-color: var(--tab-group-color) !important;
  color: white !important;
  padding-right: 4px !important;
  padding-top: 2px !important;
}

.tab-group-label {
  tab-group[collapsed] > .tab-group-label-container > & {
  outline-width: 1px !important;
  outline-color: var(--tab-group-color) !important;
  color: var(--tab-group-color) !important;
  background-color: unset !important;
}
}

.tab-group-label {
  tab-group[collapsed] > .tab-group-label-container > &:hover {
  outline-color:  color-mix(in hsl, var(--tab-group-color),white 20%) !important;
  color: color-mix(in hsl, var(--tab-group-color),white 20%) !important;
}
}
```

### Readme

```markdown
# Outlined Tab Groups
Fixes text centering on tab groups (experimental Firefox 137+ feature, can be activated now in Zen with about:config) and gives them an outline-only look, changes to solid fill color when opened
```

### Preferences

```json

```
