### ISSUE TITLE
[create-theme]: Sticky Pinned Tabs

### ISSUE THREAD

**Issue by Lu9-ST** [zen-browser/theme-store#1424]
### Name

Sticky Pinned Tabs

### Description

Make pinned tabs pin again! (Compatible with SuperPins)

### Homepage

https://github.com/Lu9-ST/zen-stuff

### Image

https://github.com/Lu9-ST/zen-stuff/blob/main/pin-pinned-tabs.png?raw=true

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
/* Revert Pinned Tab Behavior */
/* CO-AUTHORED by sporocyst and Lu9 */
/* Make pinned tabs pinned again! (Warning: contains issues with transparency/blur in non-compact mode when Mica/Acrylic is enabled) */
#zen-tabs-wrapper {position: static !important;}
#zen-browser-tabs-container {
  position: static !important;
}
#vertical-pinned-tabs-container {position: static !important;}

#vertical-pinned-tabs-container > .zen-workspace-tabs-section {
z-index: 5;
width: 100%;
.tabbrowser-tab .tab-background {
    background: var(--zen-toolbar-element-bg) !important;
  }
.tabbrowser-tab:hover .tab-background {
    background: var(--tab-selected-bgcolor) !important;
  }
}

#tabbrowser-arrowscrollbox {position: relative !important;}

#vertical-pinned-tabs-container > .zen-workspace-tabs-section {
backdrop-filter: blur(10px);
}
```

### Readme

```markdown
# Revert Pinned Tab Behavior
**([Co-authored with sporocyst](https://github.com/zen-browser/desktop/discussions/4810) - do not post without also crediting them)**
Make pinned tabs pin again! (Warning: contains issues with transparency/blur in non-compact mode when Mica/Acrylic is enabled) (Compatible with SuperPins)
```

### Preferences

```json

```
