### ISSUE TITLE
[create-theme]: urlbar animation

### ISSUE THREAD

**Issue by Fury7425** [zen-browser/theme-store#1433]
### Name

urlbar animation

### Description

this adds a customizable blur and tab expanding animation to the urlbar animation

### Homepage

https://github.com/Fury7425/my-zen-mods

### Image

https://github.com/Fury7425/my-zen-mods/blob/main/urlbar-animation/example.png?raw=true

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
:root {
  --zen-tabbox-scale: var(--zen-tabbox-user-scale, 1.07);
  --zen-tabbox-blur: var(--zen-tabbox-user-blur, 10px);
  --zen-tabbox-brightness: var(--zen-tabbox-user-brightness, 0.7);
  --zen-tabbox-ease: cubic-bezier(var(--zen-tabbox-user-ease, 0.46, -0.45, 0.34, 1.69));
}

#zen-tabbox-wrapper {
  transition: filter 0.25s ease, transform 0.25s var(--zen-tabbox-ease) !important;
  filter: none !important;
  transform: scale(1) !important;
}

:has(#urlbar:focus-within) #zen-tabbox-wrapper {
  filter: blur(var(--zen-tabbox-blur)) brightness(var(--zen-tabbox-brightness)) !important;
  transform: scale(var(--zen-tabbox-scale)) !important;
}
```

### Readme

```markdown
this adds a customizable blur and tab expanding animation to the urlbar animation
```

### Preferences

```json
[
  {
    "property": "zen-tabbox-user-scale",
    "label": "Tabbox scale (e.g. 1.07)",
    "type": "string",
    "defaultValue": "1.07",
    "placeholder": "e.g. 1.05"
  },
  {
    "property": "zen-tabbox-user-blur",
    "label": "Tabbox blur amount",
    "type": "string",
    "defaultValue": "10px",
    "placeholder": "e.g. 8px"
  },
  {
    "property": "zen-tabbox-user-brightness",
    "label": "Tabbox brightness",
    "type": "string",
    "defaultValue": "0.7",
    "placeholder": "e.g. 0.9"
  },
  {
    "property": "zen-tabbox-user-ease",
    "label": "Easing curve (4 values)",
    "type": "string",
    "defaultValue": "0.46, -0.45, 0.34, 1.69",
    "placeholder": "e.g. 0.25, 0.1, 0.25, 1"
  }
]
```
