### ISSUE TITLE
[create-theme]: Quick Compact CTRL + Tab

### ISSUE THREAD

**Issue by schizokid88** [zen-browser/theme-store#1437]
### Name

Quick Compact CTRL + Tab

### Description

Removes floating tabs sidebar when switching tabs with Ctrl + Tab in Compact mode. 

### Image

https://i.imgur.com/28eyUNH.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#navigator-toolbox[flash-popup]{
  &:not([zen-has-hover]){
    transition: none !important;
    &:not([supress-primary-adjustment='true']) {
      opacity: 0 !important;
    }
  } 
}
```

### Readme

```markdown
# Quick Compact Tab Switch ::
Removes floating tabs sidebar when switching tabs with Ctrl + Tab in Compact mode. 
N. B: also removes sidebar's animation when **quickly** switching tabs with mouse.
```

### Preferences

```json

```
