### ISSUE TITLE
[create-theme]: Custom uiFont

### ISSUE THREAD

**Issue by lindongbin** [zen-browser/theme-store#1462]
### Name

Custom uiFont

### Description

Customize the interface font, the default is consistent with the serif font in the settings.

### Image

https://006750.xyz/customuifont.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
:root:has(#theme-Custom-uiFont[theme-custom_uifont-default="Serif"]) {
    * {font-family: serif !important;}
}
:root:has(#theme-Custom-uiFont[theme-custom_uifont-default="Custom"]) {
    * {font-family: var(--theme-custom_uifont-custom) !important; text-shadow: var(--theme-custom_uifont-shadow) !important;}
}
```

### Readme

```markdown
Customize the interface font, the default is consistent with the serif font in the settings.
```

### Preferences

```json
[
    {
        "property": "theme.custom_uifont.default",
        "label": "Select Font:",
        "type": "dropdown",
        "defaultValue": "Serif",
        "options": [
            {
                "label": "Serif",
                "value": "Serif"
            },
            {
                "label": "Custom",
                "value": "Custom"
            }
        ]
    },
    {
        "property": "theme.custom_uifont.custom",
        "label": "font-family:",
        "type": "string",
        "placeholder": "sans-serif",
        "defaultValue": "sans-serif"
    },
    {
        "property": "theme.custom_uifont.shadow",
        "label": "text-shadow:",
        "type": "string",
        "placeholder": "0.01em 0.01em 0.05em #7C7C7C70",
        "defaultValue": "none"
    }
]
```
