### ISSUE TITLE
[create-theme]: Uniform Workspaces Button

### ISSUE THREAD

**Issue by andrewbellucci** [zen-browser/theme-store#147]
### Name

Uniform Workspaces Button

### Description

Make the workspaces button consistent with the other sidebar buttons, while remaining unique.

### Homepage

https://github.com/andrewbellucci/zen-uniform-workspaces-button

### Image

https://github.com/andrewbellucci/zen-uniform-workspaces-button/raw/main/image.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#zen-workspaces-button {
  border-radius: 8px !important;
  box-sizing: border-box;
  height: 34px !important;
  width: 34px !important;
  border-width: 1px;
  aspect-ratio: 1 / 1;
  transition: min-width 100ms ease-out, max-width 100ms ease-out;
  font-weight: 500;
}

#zen-workspaces-button:hover {
  background: var(--toolbarbutton-hover-background) !important;
}

#zen-workspaces-button:active {
  transform: scale(0.9);
  font-weight: initial;
}


@media (-moz-bool-pref: "zen.view.sidebar-expanded") {
  #zen-workspaces-button {
    width: calc(100% - 4px) !important;
  }
}
```

### Readme

```markdown
# Zen Browser Theme - Consistent Workspaces Button

This is a really simple theme put together to make the workspaces button a little more consistent with the other sidebar buttons.

## Preview
![Preview of Theme](/image.png)

## Original
![Original Theme](/original.png)
```
