### ISSUE TITLE
[create-theme]: Hides navigation buttons

### ISSUE THREAD

**Issue by BinaryQuantumSoul** [zen-browser/theme-store#1476]
### Name

Hides navigation buttons

### Description

Hides navigation buttons

### Homepage

https://github.com/BinaryQuantumSoul/Zen-themes/tree/main/themes/hide-navigation-buttons

### Image

https://github.com/BinaryQuantumSoul/Zen-themes/blob/main/themes/hide-navigation-buttons/image.png?raw=true

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
toolbarbutton#back-button, toolbarbutton#forward-button {
    visibility: hidden;
}
```

### Readme

```markdown
Hides navigation buttons
```

### Preferences

```json

```
