### ISSUE TITLE
[create-theme]: Custom accent color

### ISSUE THREAD

**Issue by BinaryQuantumSoul** [zen-browser/theme-store#1478]
### Name

Custom accent color

### Description

Allows to set a custom theme accent color for the zen window.

### Homepage

https://github.com/BinaryQuantumSoul/Zen-themes/tree/main/themes/custom-accent-color

### Image

https://github.com/BinaryQuantumSoul/Zen-themes/blob/main/themes/custom-accent-color/image.png?raw=true

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
:root {
    --zen-primary-color: var(--bqs-color-accent_color) !important;
}
```

### Readme

```markdown
Allows to set a custom theme accent color for the zen window.
```

### Preferences

```json
[
    {
        "property": "bqs.color.accent_color",
        "label": "Accent color",
        "type": "string",
        "defaultValue": "purple"
    }
]
```
