### ISSUE TITLE
[create-theme]: Remove workspace switcher

### ISSUE THREAD

**Issue by treffendharm** [zen-browser/theme-store#1479]
### Name

Remove workspace switcher

### Description

Remove the top workspace switcher from the UI when using vertical tabs. This will provide a clean look.

### Homepage

https://github.com/treffendharm/remove-workspace-switcher

### Image

https://github.com/treffendharm/remove-workspace-switcher/blob/main/image.png?raw=true

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@media (-moz-bool-pref: "zen.tabs.vertical") {
    #zen-current-workspace-indicator-container {
        display: none;
    }
}
```

### Readme

```markdown
# Remove Workspace Switcher

This **Zen Mod** removes the workspace switcher from the UI.

## Features
  - Hides the workspace switcher element.

## Installation
1. Download the latest release.
2. Follow the standard Zen Mod installation instructions.

## Source code
- https://github.com/treffendharm/remove-workspace-switcher
```

### Preferences

```json

```
