### ISSUE TITLE
[create-theme]: Better Workspace switcher

### ISSUE THREAD

**Issue by JustAdumbPrsn** [zen-browser/theme-store#1481]
### Name

Better Workspace switcher

### Description

Adds new macOS inspired animations  to workspace switcher!

### Homepage

https://github.com/JustAdumbPrsn/better-workspace-switcher

### Image

https://i.ibb.co/qMcNRMZs/image.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
/* ------------------------------ Workspace buttons ------------------------------ */
#zen-workspaces-button {
  height: 30px !important;
  padding: 3px !important;
  container-type: initial !important;
  width: auto !important;
  position: relative; /* Ensure it's a stacking context */
  overflow: visible !important; /* Allow child scaling outside bounds */
  z-index: 1;
}

#zen-workspaces-button .subviewbutton {
  width: 40px;
  height: 40px;
  border-radius: 12px !important;
  transition: transform 0.25s ease, filter 0.3s ease, opacity 0.3s ease-out !important;
  filter: grayscale(100%) !important;
  opacity: 0.75 !important;
  display: flex;
  align-items: center;
  justify-content: center;
  background: none !important;
  transform: scale(1);
  transform-origin: bottom center;
  
  &[active] {
      filter: grayscale(0%) !important; /* No grayscale for selected button */
      opacity: 1 !important; /* Full opacity for selected button */
  }
}
/* Main hovered item */
#zen-workspaces-button .subviewbutton:hover {
  transform: scale(1.4) !important;
  filter: grayscale(0%) !important;
  opacity: 1 !important;
  z-index: 3;
   font-size: 1.25em; /* Adjust this to your preference */
  justify-content: center; /* Center the emoji if it's alone */
  align-items: center;
}

/* Adjacent - scale slightly less */
#zen-workspaces-button .subviewbutton:hover + .subviewbutton,
#zen-workspaces-button .subviewbutton:has(+ .subviewbutton:hover) {
  transform: scale(1.1) !important;
  z-index: 2;
  opacity: 0.9 !important;
  justify-content: center; /* Center the emoji if it's alone */
  align-items: center;
}

/* One more over - slight scale */
#zen-workspaces-button .subviewbutton:hover + .subviewbutton + .subviewbutton,
#zen-workspaces-button .subviewbutton:has(+ .subviewbutton + .subviewbutton:hover) {
  transform: scale(1) !important;
  z-index: 1;
  opacity: 0.85 !important;
}
```

### Readme

```markdown
A simple mod which tweaks the workspace buttons!
```

### Preferences

```json

```
