### ISSUE TITLE
[create-theme]: Hides workspace button

### ISSUE THREAD

**Issue by BinaryQuantumSoul** [zen-browser/theme-store#1486]
### Name

Hides workspace button

### Description

Hides annoying workspace button

### Homepage

https://github.com/BinaryQuantumSoul/Zen-themes/tree/main/themes/hide-workspace-button

### Image

https://github.com/BinaryQuantumSoul/Zen-themes/blob/main/themes/hide-workspace-button/image.png?raw=true

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#zen-current-workspace-indicator-container {
    display: none;
}
```

### Readme

```markdown
Hides annoying workspace button
```

### Preferences

```json

```
