### ISSUE TITLE
[create-theme]: Mod for removing pinned tab close button

### ISSUE THREAD

**Issue by adnval** [zen-browser/theme-store#1488]
### Name

Remove Pinned Tab X

### Description

Removes a pinned tab's close button to prevent pinned tabs from being accidentally closed.

### Homepage

https://github.com/adnval/remove-pinned-tab-x

### Image

https://github.com/adnval/remove-pinned-tab-x/blob/main/image.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#tabbrowser-tabs .tabbrowser-tab[pinned] .tab-close-button {
	display: none !important;
}
```

### Readme

```markdown
# remove-pinned-tab-x

Zen browser mod to remove the close button from pinned tabs. Should help prevent pinned tabs from being accidentally closed.
```

### Preferences

```json

```
