### ISSUE TITLE
[create-theme]: smaller zen toast popup mod

### ISSUE THREAD

**Issue by lenzfliker** [zen-browser/theme-store#1492]
### Name

smaller zen toast popup

### Description

Makes the 'New background tab opened!' toast popup notification less distracting and adds hover

### Homepage

https://github.com/lenzfliker/zen-mods/tree/main/%5BMOD%5D%20smaller%20zen%20toast%20popup

### Image

https://raw.githubusercontent.com/lenzfliker/zen-mods/refs/heads/main/%5BIMAGES%5D/smaller%20zen%20toast%20popup.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#zen-toast-container {
  top: calc(var(--zen-element-separation) * 6) !important;
  
  :root:not([zen-right-side='true']) & {
    right: calc(var(--zen-element-separation) * 2) !important;
  }

  :root[zen-right-side='true'] & {
    left: calc(var(--zen-element-separation) * 2) !important;
  }

    & .zen-toast {

    padding: 6px !important;
    border-radius: 12px !important;
    font-weight: 600 !important;
    font-size: 12px !important;
    box-shadow: 0px !important ;
    border: 1px solid rgba(0, 0, 0, 0.2) !important;
    background: rgba(255, 255, 255, 0.2)  !important;
    color: color-mix(in srgb, var(--button-primary-color) 20%, transparent) !important;
    
    & .description {
        font-size: 10px !important;
    }
  }

    & .zen-toast:hover {
    background: var(--zen-primary-color) !important;
    color: var(--button-primary-color) !important;
    border: 1px solid rgba(0, 0, 0, 0.0) !important;
    transition: 0.3s !important;
  }

}
```

### Readme

```markdown
Makes the 'New background tab opened!' toast popup notification less distracting and adds hover
```

### Preferences

```json

```
