### ISSUE TITLE
[create-theme]: zen-floating-toast

### ISSUE THREAD

**Issue by bobbymannino** [zen-browser/theme-store#1498]
### Name

Zen Floating Toast

### Description

A simple Zen mod to make the toast more elegant and zen-like.

### Homepage

https://github.com/bobbymannino/zen-floating-toast

### Image

https://github.com/bobbymannino/zen-floating-toast/blob/b691df8e5317c062c6d9488ad3bfac0194886e0c/screenshot.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#zen-toast-container {
    top: 8px !important;
    display: block;

    :root:not([zen-right-side="true"]) & {
        right: 8px !important;
    }

    :root[zen-right-side="true"] & {
        left: 8px !important;
    }

    & .zen-toast {
        :root[zen-right-side="true"] & {
            translate: 0 !important;
        }

        background: var(--zen-colors-tertiary) !important;
        border: 1px solid var(--zen-colors-secondary) !important;
        color: var(--zen-colors-secondary) !important;
        padding: 2px !important;
        font-size: 12px !important;
        margin: 0px !important;
        position: static !important;

        :root[zen-right-side="true"] & {
            transform-origin: top left !important;
        }

        :root:not([zen-right-side="true"]) & {
            transform-origin: top right !important;
        }
    }
}
```

### Readme

```markdown
# Zen Floating Toast

A simple Zen mod to make the toast more elegant and zen-like.

![Screenshot](https://github.com/bobbymannino/zen-floating-toast/blob/b691df8e5317c062c6d9488ad3bfac0194886e0c/screenshot.png)
```

### Preferences

```json

```
