### ISSUE TITLE
[create-theme]: Top PiP

### ISSUE THREAD

**Issue by tolgaizdas** [zen-browser/theme-store#1506]
### Name

Top PiP

### Description

Move the PiP button to the top right or left corner of your videos.

### Homepage

https://github.com/tolgaizdas/top-pip

### Image

https://raw.githubusercontent.com/tolgaizdas/top-pip/refs/heads/main/thumbnail.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
.pip-wrapper[position="top-right"] {
    top: var(--pip-toggle-distanceFromVideoEdge) !important;
    right: calc(var(--pip-icon-width-with-margins) + var(--pip-toggle-distanceFromVideoEdge));
}

.pip-wrapper[position="top-left"] {
    top: var(--pip-toggle-distanceFromVideoEdge) !important;
    left: var(--pip-toggle-distanceFromVideoEdge) !important;
}
```

### Readme

```markdown
This Zen Browser mod makes watching videos easier by moving the Picture-in-Picture button to the top right or top left corner of the video. This simple tweak helps you keep the button out of the way and lets you choose where it feels most comfortable.
```

### Preferences

```json
[
	{
		"property": "media.videocontrols.picture-in-picture.video-toggle.position",
		"label": "Position",
		"type": "dropdown",
		"disabledOn": [],
		"placeholder": "Select PiP position",
		"defaultValue": "top-right",
		"options": [
			{
				"label": "Default",
				"value": "right"
			},
			{
				"label": "Top Left",
				"value": "top-left"
			},
			{
				"label": "Top Right",
				"value": "top-right"
			}
		]
	}
]
```
