### ISSUE TITLE
[create-theme]: add window border

### ISSUE THREAD

**Issue by leaeasy** [zen-browser/theme-store#1509]
### Name

window border enabled

### Description

Enable window border for easy window identification

### Image

https://imgur.com/AXLl3LK

### Type

- [x] JSON Color Theme

### Theme Styles

```css
#zen-main-app-wrapper {
	border-width: 1px !important;
	border-style: solid;
	border-color: #e5e7eb;
	border-radius: 6px !important;
}
```

### Readme

```markdown
Add window border for easy window identification
```

### Preferences

```json

```
