### ISSUE TITLE
Update Allow Toolbar Theming theme

### ISSUE THREAD

**Issue by ch4og** [zen-browser/theme-store#151]
Add support for toolbar theming in compact mode

Here is new chrome.css:
```css
@-moz-document url-prefix("chrome:") {
  @media not (-moz-bool-pref: "zen.view.compact") {
    #navigator-toolbox {
      --zen-navigator-toolbox-background: var(--lwt-header-image, var(--lwt-additional-images)) no-repeat var(--lwt-background-tiling) var(--lwt-background-alignment) var(--lwt-accent-color);
    }
  }
  @media (-moz-bool-pref: "zen.view.compact") {
    #TabsToolbar {
      background: var(--lwt-header-image, var(--lwt-additional-images)) no-repeat var(--lwt-background-tiling) var(--lwt-background-alignment) var(--lwt-accent-color);
    }
  }
}
```
