### ISSUE TITLE
[create-theme]: No Borders in Fullscreen

### ISSUE THREAD

**Issue by Risengan** [zen-browser/theme-store#1515]
### Name

No Borders in Fullscreen

### Description

Borders are hidden when Zen Browser goes to fullscreen, just like Arc.

### Image

https://i.imgur.com/d7Zzh4T.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
html[inFullscreen="true"] {
  #zen-main-app-wrapper {
    --zen-element-separation: 0px;
  }
  .browserSidebarContainer {
    border-radius: 0px !important;
  }
}
```

### Readme

```markdown
Borders are hidden when Zen Browser goes to fullscreen, just like Arc.
```

### Preferences

```json

```
