### ISSUE TITLE
[create-theme]: 

### ISSUE THREAD

**Issue by Mojas84** [zen-browser/theme-store#152]
### Name

Catppuccin Frappe

### Description

Unofficial Catppuccin Frappe Theme for Zen Browser

### Homepage

https://github.com/catppuccin/catppuccin

### Image

https://raw.githubusercontent.com/catppuccin/catppuccin/main/assets/logos/exports/1544x1544_circle.png

### Type

- [X] JSON Color Theme

### Theme Styles

```css
/* This is an auto generated color theme. */
:root {
    --zen-colors-primary: #303446 !important;
    --zen-colors-secondary: #504945 !important;
    --zen-colors-tertiary: #292c3c !important;
    --zen-colors-border: #f4b8e4 !important;
}
```

### Readme

```markdown
Unofficial Catppuccin Frappe Theme for Zen Browser!!! {Mojas84}
```
