### ISSUE TITLE
[create-theme]: PywalZen

### ISSUE THREAD

**Issue by Axenide** [zen-browser/theme-store#1521]
### Name

PywalZen

### Description

Enable correct support for Pywalfox!

### Homepage

https://github.com/Axenide/PywalZen

### Image

https://i.imgur.com/mRfWImA.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
:root {
  --zen-primary-color: #d9d9d9 !important;
  --zen-colors-primary: var(--tab-loading-fill) !important;
  --zen-colors-secondary: var(--tab-loading-fill) !important;
  --toolbarbutton-icon-fill: var(--tab-loading-fill) !important;
}

:root:has(#theme-PywalZen[uc-pywalzen-darkness="default"]) {
  --zen-colors-tertiary: var(--lwt-accent-color) !important;
  --zen-main-browser-background: var(--lwt-accent-color) !important;
  --zen-themed-toolbar-bg: var(--lwt-accent-color) !important;
  --arrowpanel-background: var(--lwt-accent-color) !important;
  #urlbar[breakout-extend="true"] > #urlbar-background {
    background: var(--lwt-accent-color) !important;
  }
}

:root:has(#theme-PywalZen[uc-pywalzen-darkness="dark"]) {
  --zen-colors-tertiary: color-mix(
    in srgb,
    var(--lwt-accent-color),
    black 25%
  ) !important;
  --zen-main-browser-background: color-mix(
    in srgb,
    var(--lwt-accent-color),
    black 25%
  ) !important;
  --zen-themed-toolbar-bg: color-mix(
    in srgb,
    var(--lwt-accent-color),
    black 25%
  ) !important;
  --arrowpanel-background: color-mix(
    in srgb,
    var(--lwt-accent-color),
    black 25%
  ) !important;
  #urlbar[breakout-extend="true"] > #urlbar-background {
    background: color-mix(
      in srgb,
      var(--lwt-accent-color),
      black 25%
    ) !important;
  }
}

:root:has(#theme-PywalZen[uc-pywalzen-darkness="darker"]) {
  --zen-colors-tertiary: color-mix(
    in srgb,
    var(--lwt-accent-color),
    black 50%
  ) !important;
  --zen-main-browser-background: color-mix(
    in srgb,
    var(--lwt-accent-color),
    black 50%
  ) !important;
  --zen-themed-toolbar-bg: color-mix(
    in srgb,
    var(--lwt-accent-color),
    black 50%
  ) !important;
  --arrowpanel-background: color-mix(
    in srgb,
    var(--lwt-accent-color),
    black 50%
  ) !important;
  #urlbar[breakout-extend="true"] > #urlbar-background {
    background: color-mix(
      in srgb,
      var(--lwt-accent-color),
      black 50%
    ) !important;
  }
}

:root:has(#theme-PywalZen[uc-pywalzen-darkness="yet-darker"]) {
  --zen-colors-tertiary: color-mix(
    in srgb,
    var(--lwt-accent-color),
    black 75%
  ) !important;
  --zen-main-browser-background: color-mix(
    in srgb,
    var(--lwt-accent-color),
    black 75%
  ) !important;
  --zen-themed-toolbar-bg: color-mix(
    in srgb,
    var(--lwt-accent-color),
    black 75%
  ) !important;
  --arrowpanel-background: color-mix(
    in srgb,
    var(--lwt-accent-color),
    black 75%
  ) !important;
  #urlbar[breakout-extend="true"] > #urlbar-background {
    background: color-mix(
      in srgb,
      var(--lwt-accent-color),
      black 75%
    ) !important;
  }
}

:root:has(#theme-PywalZen[uc-pywalzen-darkness="pitch-black"]) {
  --zen-colors-tertiary: black !important;
  --zen-main-browser-background: black !important;
  --zen-themed-toolbar-bg: black !important;
  --arrowpanel-background: black !important;
  #urlbar[breakout-extend="true"] > #urlbar-background {
    background: black !important;
  }
}

#urlbar:not([focused="true"]):not([breakout-extend="true"])
  > #urlbar-background {
  background: color-mix(
    in srgb,
    light-dark(#fff, var(--zen-colors-secondary)) 35%,
    transparent 65%
  ) !important;
}

#commonDialogWindow {
  background-color: black !important;
}
```

### Readme

```markdown
# 🎨 PywalZen

*By using some native color variables, this theme makes [Pywalfox](https://github.com/Frewacom/pywalfox) work with [Zen Browser](https://zen-browser.app/) correctly.*

![Screenshot 1](https://raw.githubusercontent.com/Axenide/PywalZen/main/screenshots/1.png)  
![Screenshot 2](https://raw.githubusercontent.com/Axenide/PywalZen/main/screenshots/2.png)  
![Screenshot 3](https://raw.githubusercontent.com/Axenide/PywalZen/main/screenshots/3.png)  

> ⚠️ **CAUTION**  
> Use this exclusively with Pywalfox, if not the theme will look wrong causing unreadable text and other issues.
```

### Preferences

```json
[
    {
        "property": "uc.pywalzen.darkness",
        "label": "Darkness level",
        "type": "dropdown",
        "defaultValue": "default",
        "options": [
            {"value": "default", "label": "Default"},
            {"value": "dark", "label": "Dark"},
            {"value": "darker", "label": "Darker"},
            {"value": "yet-darker", "label": "Yet darker"},
            {"value": "pitch-black", "label": "Pitch black"}
        ],
        "disabledOn": []
    }
]
```
