### ISSUE TITLE
[create-theme]:  Hide workspace icon

### ISSUE THREAD

**Issue by Rafi993** [zen-browser/theme-store#1524]
### Name

Hide workspace icon

### Description

Zen mod to hide workspace icon

### Homepage

https://github.com/Rafi993/zen-hide-workspace-mod

### Image

https://ik.imagekit.io/cosmobot/screenshot.png?updatedAt=1747623956827

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@media not -moz-pref("zen.workspaces.show-workspace-indicator") {
  #zen-current-workspace-indicator-container {
    display: none !important;
  }
}
```

### Readme

```markdown
Simple zen mod to hide workspace logo at the top
```

### Preferences

```json

```
