### ISSUE TITLE
[create-theme]: Borderless Compact Mode

### ISSUE THREAD

**Issue by declider** [zen-browser/theme-store#1527]
### Name

Borderless Compact Mode

### Description

Remove border and rounded corners only when compact mode enabled

### Image

https://i.ibb.co/vxn1YHG1/Borderless-Compact-Mode.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
html[zen-compact-mode="true"] {
	--zen-element-separation: 0px !important;
	--zen-webview-border-radius: 0;
}
```

### Readme

```markdown
Remove border and rounded corners only when compact mode enabled. It doesn't affect normal mode.
```

### Preferences

```json

```
