### ISSUE TITLE
[create-theme]: Hide Workspace Indicator

### ISSUE THREAD

**Issue by seagram** [zen-browser/theme-store#1531]
### Name

Hide Workspace Indicator

### Description

This mod removes the workspace indicator in the Zen toolbar.

### Homepage

https://github.com/seagram/hide-workspace-indicator

### Image

https://i.imgur.com/4TSibvi.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
.zen-current-workspace-indicator {
  display: none !important;
}
```

### Readme

```markdown
# Hide Workspace Indicator
This mod removes the workspace indicator in the Zen toolbar.
```

### Preferences

```json

```
