### ISSUE TITLE
[create-theme]: Adaptive Zen

### ISSUE THREAD

**Issue by easonwong-de** [zen-browser/theme-store#1537]
### Name

Adaptive Zen

### Description

This mod adds support for “Adaptive Tab Bar Colour” to the Zen browser, allowing the tab bar to dynamically match the active website’s theme for a more integrated browsing experience.

### Homepage

https://github.com/easonwong-de/Easons-Zen-Mod-Collection/tree/main/adaptive-zen

### Image

https://github.com/easonwong-de/Easons-Zen-Mod-Collection/blob/main/adaptive-zen/preview.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
:root {
    /* Only applies adaptive colour if tab is not empty */
	&:has(#tabbrowser-tabpanels > .browserSidebarContainer[id] browser:not([transparent])) {
		–zen-main-browser-background: var(--lwt-accent-color) !important;
	}
	/* Reverts toolbar button’s active colour */
	–toolbarbutton-active-background: var(--zen-toolbar-element-bg) !important;
}

/* Removes shadow around the tab panel & side bar */
.browserSidebarContainer,
#zen-tabbox-wrapper #sidebar-box {
	box-shadow: none !important;
}

/* Removes tab outline */
.tab-background {
	outline: none !important;
}

/* Makes tab panel transparent */
browser[transparent="true"] {
	background-color: transparent !important;
}
```

### Readme

```markdown
# Adaptive Zen

This mod adds support for “Adaptive Tab Bar Colour” to the Zen browser, allowing the tab bar to dynamically match the active website’s theme for a more integrated browsing experience.
```

### Preferences

```json

```
