### ISSUE TITLE
[create-theme]: Hide Sidebar

### ISSUE THREAD

**Issue by jqtmviyu** [zen-browser/theme-store#1549]
### Name

Hide Sidebar

### Description

Hide default sidebar for using Sidebery

### Homepage

https://git.081024.xyz/hxx/zen-mods

### Image

https://git.081024.xyz/hxx/zen-mods/raw/branch/main/zen-hide-sidebar/image.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@media (-moz-bool-pref: "mod.hidesidebar.hide_sidebar_header") {
  #sidebar-header {
    display: none !important;
  }
}

@media (-moz-bool-pref: "mod.hidesidebar.hide_navigator_toolbox") {
  #navigator-toolbox {
    display: none !important;
  }
}
```

### Readme

```markdown
# Hide Sidebar

> Conceal the sidebar and Sidebery title bar.

1.  Install the `Sidebery` add-on.
2.  Right-click on the sidebar and select `Compact mode -> Hide sidebar -> Enable compact mode`.
3.  Activate the mode configuration.

Tips:

1.  Add `user.js` to your `Profiles` directory to enable `Browser Toolbox Mode`.

    
    // user.js

    user_pref("devtools.chrome.enabled", true);
    user_pref("devtools.debugger.remote-enabled", true);

    user_pref("xpinstall.signatures.required", false);
    user_pref("config.trim_on_minimize", true);
    

2.  `Browser Toolbox Mode` is located under `Tools -> Browser Tools`.
3.  For quick style previews, utilize the `Style Editor`.
4.  Customize navigation and sidebar colors via `about:config -> zen.theme.gradient.show-custom-colors -> true`.
5.  Disable transparent backgrounds: `about:config -> transparent -> false`.
```

### Preferences

```json
[
  {
    "property": "mod.hidesidebar.hide_sidebar_header",
    "label": "hide Sidebery header",
    "type": "checkbox",
    "defaultValue": true
  },
  {
    "property": "mod.hidesidebar.hide_navigator_toolbox",
    "label": "hide default sidebar",
    "type": "checkbox",
    "defaultValue": true
  }
]
```
