### ISSUE TITLE
[create-theme]: Fixed Compact Sidebar

### ISSUE THREAD

**Issue by eastse** [zen-browser/theme-store#157]
### Name

Fixed Compact Sidebar

### Description

Fixed the tab sidebar in compact mode to always appear on the side instead of floating on the page

### Image

https://imgur.com/a/gAbD4Vt

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@media (-moz-bool-pref: "zen.view.compact") and (-moz-bool-pref: "zen.tabs.vertical") {

    /* Tag sidebar configuration */
    #navigator-toolbox {
        /* Cancel the sidebar floating effect */
        position: relative !important;
        padding: 0 !important;
        border-radius: 0 !important;
        background-color: none !important;

        /* remove borders */
        #titlebar {
            border: none !important;
            padding: 0 !important;
            border-radius: 0 !important;
        }

        /* Tab bar width */
        #TabsToolbar {
            padding: 5px 3px !important;
        }

        #zen-sidebar-icons-wrapper {
            margin: 0 !important;
        }
    }

    /* Border background color */
    #tabbrowser-tabbox #tabbrowser-tabpanels .browserSidebarContainer {
        box-shadow: none !important;
    }

    /* Reduce borders */
    #tabbrowser-tabpanels {
        background-color: var(--zen-colors-tertiary) !important;

        & .browserSidebarContainer:not([zen-split="true"]) {
            --zen-browser-border-radius: var(--zen-border-radius) 0 0 0;
            --zen-element-separation: 3px;
        }

    }

    /* Remove borders from full screen */
    :root:is([inFullscreen="true"]) {
        #tabbrowser-tabpanels {
            & .browserSidebarContainer:not([zen-split="true"]) {
                --zen-element-separation: 0px;
                border-radius: 0 !important;
            }
        }
    }

    /* Hide tab bar remove width */
    #navigator-toolbox:not([zen-user-show]) {
        width: 0 !important;
    }

    /* Show tab bar shows left border */
    #zen-tabbox-wrapper:has(#navigator-toolbox[zen-user-show]) {
        #tabbrowser-tabbox #tabbrowser-tabpanels .browserSidebarContainer {
            margin-left: 0 !important;
        }
    }
}
```

### Readme

```markdown
Fixed the tab sidebar in compact mode to always appear on the side instead of floating on the page
```
