### ISSUE TITLE
[create-theme]: Hide-Unified-Extensions

### ISSUE THREAD

**Issue by tangowithfoxtrot** [zen-browser/theme-store#158]
### Name

Hide Unified Extensions

### Description

You can finally hide the unifiedExtensions button.

### Homepage

https://github.com/tangowithfoxtrot/zen-hide-unified-extensions

### Image

https://raw.githubusercontent.com/tangowithfoxtrot/zen-hide-unified-extensions/main/image.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@-moz-document url-prefix("chrome:") {
    @media (-moz-bool-pref: "uc.unifiedExtensions-hide.hide-unifiedExtensions.enabled") {
        #unified-extensions-button {
            display: none !important;
        }
    }
}
```

### Readme

```markdown
# Hide-Unified-Extensions

You can finally hide the unifiedExtensions button.
```

### Preferences

```json
{
    "uc.unifiedExtensions-hide.hide-unifiedExtensions.enabled": "Hide the unifiedExtensions button"
}
```
