### ISSUE TITLE
[create-theme]: Smaller Compact Mode

### ISSUE THREAD

**Issue by n7itro** [zen-browser/theme-store#160]
### Name

Smaller Compact Mode

### Description

Reduce the height of the compact sidebar!

### Homepage

https://github.com/n7itro/Zen-Themes

### Image

https://i.imgur.com/ixAHACk.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
/* Reduce width */
@media (-moz-bool-pref: "zen.view.sidebar-expanded") {  
    #navigator-toolbox {
      --zen-navigation-toolbar-min-width: 100px !important;
   }
 }
 
/* Reduced height */
@media (-moz-bool-pref: "zen.view.compact") {
     #navigator-toolbox {
         padding-top: 12.5vh !important;
         height: 85vh !important;
     }
}
```

### Readme

```markdown
With this theme you can make the compact mode even more compact!

This theme makes two changes:
- It reduces the height of the tab sidebar while in compact mode
- It reduces the minimum width of the tab sidebar

This theme works well with the **Minimal Sidebar** theme
```
