### ISSUE TITLE
[create-theme]: centered toolbar buttons

### ISSUE THREAD

**Issue by 11x1** [zen-browser/theme-store#162]
### Name

Centered toolbar buttons

### Description

Centers toolbar buttons instead of having them aligned on the left

### Image

https://i.imgur.com/4aL2wYB.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@-moz-document url-prefix("chrome:") {
	/* Element | chrome://browser/content/browser.xhtml */
	toolbar#zen-sidebar-icons-wrapper {
		display: flex !important;
		flex-direction: row !important;
		flex-wrap: wrap !important;
		justify-content: center !important;
	}
	
	toolbar#zen-sidebar-icons-wrapper > toolbarbutton {
    flex: 1;
	}
}
```

### Readme

```markdown
# Centered toolbar buttons

Centers icons on the bottom of the sidebar.
```
