### ISSUE TITLE
[create-theme]: 

### ISSUE THREAD

**Issue by danm36** [zen-browser/theme-store#168]
### Name

Private Browsing Toolbar Highlighting

### Description

This theme adds a purple gradient and icon to the main toolbar of any private browsing window.

### Homepage

https://github.com/danm36/zen-browser-private-browsing-toolbar-highlighting

### Image

https://raw.githubusercontent.com/danm36/zen-browser-private-browsing-toolbar-highlighting/main/image.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@media not (-moz-bool-pref: "uc.private-browsing-top-bar.no-bg") {
  [privatebrowsingmode] #nav-bar {
    background-image: linear-gradient(to bottom, #25003EFF, #25003E44) !important;
  }

  @media (-moz-bool-pref: "uc.private-browsing-top-bar.solid-bg") {
    [privatebrowsingmode] #nav-bar {
      background-image: none !important;
      background-color: #25003E !important;
    }
  }
}

@media not (-moz-bool-pref: "uc.private-browsing-top-bar.hide-icon") {
  [privatebrowsingmode] #stop-reload-button {
    position: relative;
  }

  [privatebrowsingmode] #stop-reload-button::after {
    content: "";
    position: absolute;
    left: 100%;
    top: 0;
    width: 100%;
    height: 100%;
    background-image: url("chrome://global/skin/icons/indicator-private-browsing.svg");
    background-repeat: no-repeat;
    background-position: center center;
  }
}
```

### Readme

```markdown
# Private Browsing Toolbar Highlighting

Any Zen window in private browsing mode isn't obviously indicated by default. This theme fixes that.

## What this theme does.

By default, this theme:

* Highlights the toolbar of a private browsing window with a purple gradient.
* Adds a private browsing icon to the right of the refresh button.

It also comes with three settings:

* Replace the gradient with a solid purple color.
* Remove the background color entirely.
* Hide the private browsing icon.

These settings can be found in Zen's browser settings, in the 'Look and Feel' tab.

Encountered an issue? Raise them [here](https://github.com/danm36/zen-browser-private-browsing-toolbar-highlighting/issues).
```

### Preferences

```json
{
    "uc.private-browsing-top-bar.solid-bg": "Replaces the purple gradient on the toolbar with a solid purple color", 
    "uc.private-browsing-top-bar.no-bg": "Removes the background color on the toolbar entirely", 
    "uc.private-browsing-top-bar.hide-icon": "Hides the private browsing icon"
}
```
