### ISSUE TITLE
[create-theme]: Hide Extension Name

### ISSUE THREAD

**Issue by ch4og** [zen-browser/theme-store#172]
### Name

Hide Extension Name

### Description

Hides the name of the extension on tabs loaded from the extension

### Homepage

https://github.com/ch4og/zenbrowser-themes/tree/main/Hide%20Extension%20Name

### Image

https://raw.githubusercontent.com/ch4og/zenbrowser-themes/main/Hide%20Extension%20Name/fcfw12rh.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#urlbar #identity-box.extensionPage #identity-icon-label {
  display: none !important;
}
```

### Readme

```markdown
Hides the name of the extension on tabs loaded from the extension
```
