### ISSUE TITLE
[create-theme]: Ctrl+Tab panel theme

### ISSUE THREAD

**Issue by marwanehab98** [zen-browser/theme-store#175]
### Name

CTRL+Tab panel theme

### Description

Changes the look of the CTRL+Tab panel

### Homepage

https://github.com/marwanehab98/zen-ctrltab-panel-theme

### Image

https://github.com/marwanehab98/zen-ctrltab-panel-theme/blob/master/image.png?raw=true

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@-moz-document url-prefix("chrome:") {

    .ctrlTab-canvas {
        border-radius: 0.5rem !important;
    }

    .ctrlTab-preview-inner {
        border-radius: 0.5rem !important;

        canvas {
            border-radius: 0.5rem !important;
        }

        img {
            border-radius: 0.5rem !important;
        }
    }

    .ctrlTab-favicon-container {
        display: none !important;
    }

    #ctrlTab-panel {
        --panel-background: #212120 !important;
        border-color: #2121207D !important;
    }

}
```

### Readme

```markdown
# Change the look of the control+tab preview panel

This theme changes the following in the preview panel:
- Makes the panel's background color darker.
- Removes the panel's transparency.
- Gives the preview images rounded corners
- Removes the favicons
```
