### ISSUE TITLE
[create-theme]: elementary OS Titlebar

### ISSUE THREAD

**Issue by SudoVanilla** [zen-browser/theme-store#182]
### Name

elementary OS Titlebar

### Description

Respect elementary OS's default titlebar layout

### Homepage

https://ark.sudovanilla.org/Korbs/zen-eos-fix

### Image

https://md.sudovanilla.org/images/zen-eos-fix.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
/* Move Maximize Button to Right-Side */
.titlebar-button.titlebar-max {
  position: fixed;
  right: 11px;
  top: 12px;
}
#PanelUI-button {
  margin-right: 36px;
}

/* Move Close Button a little to the right too */
.titlebar-button.titlebar-close {
  margin-left: 10px;
}

/* Fix Corners */
#zen-main-app-wrapper {
    border-radius: 6px 6px 0px 0px;
}
```

### Readme

```markdown
Respect elementary OS's default titlebar layout.
```
