### ISSUE TITLE
[create-theme]: Dracula

### ISSUE THREAD

**Issue by DemonKingSwarn** [zen-browser/theme-store#190]
### Name

Dracula

### Description

Dive into Dracula color theme for Zen!

### Homepage

https://draculatheme.com/

### Image

https://i.imgur.com/rLSEEkN.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
:root {
  --zen-colors-primary: #282a36 !important; /* Deep purple background */
  --zen-colors-secondary: #44475a !important; /* Current line */
  --zen-colors-tertiary: #6272a4 !important; /* Comment/Inactive */
  --zen-colors-border: #8b94b2 !important; /* Accent/Borders */

  --zen-colors-accent: #ff79c6 !important; /* Pink accent */
  --zen-colors-teal: #66d9ef !important; /* Teal accent */
}
```

### Readme

```markdown
# Dracula

Dracula color pallete ported into Zen!

- *Not affiliated with `Dracula`*
```
