### ISSUE TITLE
[create-theme]: Now playing indicator

### ISSUE THREAD

**Issue by benstone326** [zen-browser/theme-store#193]
### Name

Now playing indicator

### Description

Show indicator for for "Now playing" tab if the sidebar is collapsed.

### Image

https://imgur.com/a/7l2gbTQ.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@-moz-document url-prefix("chrome:") {
	
	@media not (-moz-bool-pref: "zen.view.sidebar-expanded") {
		.tabbrowser-tab:is([soundplaying], [muted], [activemedia-blocked])::after {
			content:'';
			position: absolute;
			width: 3px;
			border-radius: 3px;
			height: calc(100% - 0px);
			top: 50%;
			left: calc(100% - 2px);
			transform: translateY(-50%);
			background-color: var(--zen-primary-color);
		}
		
		.tabbrowser-tab:not([selected=true]){
			border-radius: 0px;
		}
		
		.tabbrowser-tab:not([selected=true]):hover{
			border-radius: 8px;
		}
	}
	
}
```

### Readme

```markdown
Show indicator for for "Now playing" tab if the sidebar is collapsed.
This is useful if you installed "Hide tab mute" Zen browser theme, but you want to know, which tab is playing sound.
```
