### ISSUE TITLE
[create-theme]: Audio TabIcon Plus

### ISSUE THREAD

**Issue by DaitiDay** [zen-browser/theme-store#195]
### Name

Audio TabIcon Plus

### Description

Enhance the appearency and utility of the audio/mute tab-icon

### Image

https://ibb.co/kB5d6hw

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
.tab-icon-overlay {
  -moz-box-ordinal-group: 0 !important;
  border-radius: 50% !important;
  margin: initial !important;
  visibility: visible !important;
  margin-right: -16px !important;
  opacity: 1 !important;
  transform: translate(60%, -35%) scale(0.7) !important;
  color: light-dark(white, black) !important;
  background-color: light-dark(black, white) !important;
}

.tab-icon-overlay:hover {
  color: light-dark(white, black) !important;
  background-color: light-dark(black, white) !important;
}

.tab-icon-overlay:is([soundplaying], [muted]):not([selected]) {
  display: block !important;
}
```

### Readme

```markdown
# Audio/Mute TabIcon Plus

Enhance the appearency and utility of the audio/mute tab-icon.
The icon is more visible and does not get hidden when the tab loses focus and/or the tab gets suspended.
```
