### ISSUE TITLE
[create-theme]: Audio TabIcon Plus

### ISSUE THREAD

**Issue by DaitiDay** [zen-browser/theme-store#196]
### Name

Audio TabIcon Plus

### Description

Enhance audio/mute tab-icon

### Image

https://imgur.com/a/4Yb0OmZ

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
.tab-icon-overlay {
  -moz-box-ordinal-group: 0 !important;
  border-radius: 50% !important;
  margin: initial !important;
  visibility: visible !important;
  margin-right: -16px !important;
  opacity: 1 !important;
  transform: translate(60%, -35%) scale(0.7) !important;
  color: light-dark(white, black) !important;
  background-color: light-dark(black, white) !important;
}

.tab-icon-overlay:hover {
  color: light-dark(white, black) !important;
  background-color: light-dark(black, white) !important;
}

.tab-icon-overlay:is([soundplaying], [muted]):not([selected]) {
  display: block !important;
}
```

### Readme

```markdown
# Audio Tab Icon Plus

Enhance the visibility of the audio/mute tab icon. Furthermore, it allows the icon to be displayed even if the tab is not focused and/or suspended.
```
