### ISSUE TITLE
[create-theme]: Compact tabs title

### ISSUE THREAD

**Issue by Tc-001** [zen-browser/theme-store#198]
### Name

Compact tabs title

### Description

Show the first few title characters even in compact mode

### Image

https://github.com/user-attachments/assets/bbd6fe8a-c7d0-44b1-98f9-4c3b024118d4

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@media not (-moz-bool-pref: "zen.view.sidebar-expanded") {
  .tabbrowser-tab {
    .tab-label-container {
      --comptitle-width: 2ch;
      overflow: hidden;
      position: absolute;
      text-overflow: ellipsis;
      width: var(--comptitle-width);
      right: 0;
      white-space: nowrap;
      background: color-mix(in srgb, var(--background-color-box) 75%, transparent);
      height: 1rem !important;
      opacity: 1;
      top: 0;
      border-radius: 5px;
      font-family: monospace;
      display: flex !important;
      mask-image: none !important;
      color: var(--text-color-deemphasized);
    }
    &[selected] {
      .tab-label-container {
        color: initial!important;
      }
    }
  
    @media (-moz-bool-pref: "uc.theme.comptitle-one-char-title.enabled") {
      .tab-label-container {
        --comptitle-width: 1ch;
      }
    }

    @media (-moz-bool-pref: "uc.theme.comptitle-three-char-title.enabled") {
      .tab-label-container {
        --comptitle-width: 3ch;
      }
    }

    @media (-moz-bool-pref: "uc.theme.comptitle-enable-pinned.enabled") {
      .tab-label-container {
        width: var(--comptitle-width)!important;
      }
    }

    @media (-moz-bool-pref: "uc.theme.comptitle-default-text.enabled") {
      .tab-label-container {
        color: initial!important;
      }
    }
    
  }
}
```

### Readme

```markdown
Shows the first few characters of the tab even if compact mode is on. 
This can help you differentiate between multiple tabs even if they all have the same favicon. 
You can customize between 1, 2, or 3 letters shown.
```

### Preferences

```json
{
  "uc.theme.comptitle-one-char-title.enabled": "Shorter title (1 character)",
  "uc.theme.comptitle-three-char-title.enabled": "Longer title (3 characters)",
  "uc.theme.comptitle-enable-pinned.enabled": "Enable in pinned tabs",
  "uc.theme.comptitle-default-text.enabled": "More contrast-y text, may be harder to look at"
}
```
