### ISSUE TITLE
[create-theme]: Better Letterboxing

### ISSUE THREAD

**Issue by qtchaos** [zen-browser/theme-store#202]
### Name

Better Letterboxing

### Description

More pleasant, theme-friendly, and most importantly, rounded letterboxing.

### Image

https://files.catbox.moe/vws7s1.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
.browserContainer {
  background: linear-gradient(90deg, var(--zen-colors-secondary) 0%, var(--zen-colors-primary) 100%);
}

stack > browser {
  border-radius: 10px !important;
}
```

### Readme

```markdown
## Better Letterboxing

Makes letterboxing look better by rounding the browser corners and adding a slight gradient to the background to make it feel more Tor-like.
```
