### ISSUE TITLE
[create-theme]: SuperPins

### ISSUE THREAD

**Issue by JLBlk** [zen-browser/theme-store#211]
### Name

SuperPins

### Description

This Zen theme enhances pinned tabs and the tab bar in general, inspired by the favorites in Arc.

### Homepage

https://github.com/JLBlk/Zen-Themes/tree/main/SuperPins

### Image

https://github.com/JLBlk/Zen-Themes/blob/main/SuperPins/Screenshot%202024-08-27%20184122%20(Custom).png?raw=true

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
/* Increase size of pinned tabs */
@media (-moz-bool-pref: "zen.tabs.vertical") {
  @media (-moz-bool-pref: "zen.view.sidebar-expanded") {
    .scrollbox-clip > scrollbox {
      grid-template-columns: repeat(auto-fill, minmax(calc(var(--tab-min-height) * 1.9), 1fr)) !important;
      column-gap: 10px;
    }
    .tabbrowser-tab[pinned] {
      margin-top: 5px !important;
      margin-bottom: 5px !important;
    }
  }
}


/* COLORS of pinned tabs*/

/* background color of pinned tabs in a normal state (not hovered/selected) */
.tabbrowser-tab[pinned] {
  background-color: color-mix(in srgb, var(--toolbarbutton-hover-background), #000000 30%) !important;
  border-radius: 8px !important;
}

/* background color when hovering */
.tabbrowser-tab[pinned]:hover {
  background-color: color-mix(in srgb, var(--toolbarbutton-hover-background), #000000 20%) !important;
}

/* background color when selected */
.tabbrowser-tab[pinned][selected="true"] {
  background-color: color-mix(in srgb, var(--toolbarbutton-hover-background), #000000 0%) !important;
}

/* background color when hovering and selected */
.tabbrowser-tab[pinned][selected="true"]:hover {
  background-color: color-mix(in srgb, var(--toolbarbutton-hover-background), #ffffff 5%) !important;
}


/* Align tab bar with nav bar when not in compact mode when toggled on */
@media not (-moz-bool-pref: "zen.view.compact"){
  @media (-moz-bool-pref: "uc.tab-bar.align-with-navbar") {
    #TabsToolbar {
      padding-top: 0 !important;
    }
  }
} 

/* Remove the border of the workspace button if enabled when toggled on */
@media (-moz-bool-pref: "uc.workspace-button.remove-border"){
  #zen-workspaces-button {
    border: hidden !important;
  }
}

/* Move workspace button to the bottom if enabled when toggled on */
@media (-moz-bool-pref: "uc.workspace-button.move-to-bottom"){
  #zen-workspaces-button {
    order: 1;
    margin-bottom: auto !important;
  }
  @media (-moz-bool-pref: "zen.tabs.vertical") {
    @media (-moz-bool-pref: "zen.view.sidebar-expanded") {
      .tabbrowser-tab[pinned] {
        margin-top: 0px !important;
        margin-bottom: 10px !important;
      }
    }
  }
}

/* Hide seperator line above first normal tab when toggled on */
@media (-moz-bool-pref: "uc.hide-seperator-line") {
  #tabbrowser-tabs:has(.tabbrowser-tab[pinned]) .tabbrowser-tab:nth-child(1 of [fadein]:not([pinned]):not([hidden])) {
	  margin-top: 10px !important;
	  overflow: hidden !important;
  }
}

/* Adjust border radius of workspace button to the same as tabs when toggled on */
@media (-moz-bool-pref: "uc.workspace-button.border-radius") {
  #zen-workspaces-button {
    border-radius: 10px !important;
  }
}
```

### Readme

```markdown
# SuperPins

This **Zen theme** elevates your experience with pinned tabs and the tab bar in general by making some UI changes, inspired by the favorites in Arc.

## What it does by default:
  - Increase the size of pinned tabs
  - Adds a background color (according to your accent color set in *Settings -> Look and Feel -> Theme Color*)
  - Adds some space between the pinned tabs



## Optional Features (toggle in Zen's theme settings:
  - Stop Zen from loading all pinned tabs on startup
  - Stop Zen from dimming unloaded pinned tabs
  - Align tab bar with nav bar
  - Remove the border of the workspace button
  - Move workspace button to the bottom of the tab bar
  - Hide seperator line between pinned tabs and normal tabs
  - Adjust border radius of workspace button to the same as tabs
```

### Preferences

```json
{
    "browser.sessionstore.restore_pinned_tabs_on_demand": "Stop Zen from loading all pinned tabs on startup, instead load pinned tabs on demand",
    "zen.tabs.dim-pending": "Stop Zen from dimming unloaded pinned tabs",
    "uc.hide-seperator-line": "Hide the seperator line between pinned tabs and the first normal tab",
    "uc.tab-bar.align-with-navbar": "Aligns the tab bar with the navbar",
    "uc.workspace-button.border-radius": "This applies the same border radius from the tabs to the workspace button",
    "uc.workspace-button.remove-border": "Removes the border of the workspace button",
    "uc.workspace-button.move-to-bottom": "Move the workspace button to the bottom of the tab bar"
}
```
