### ISSUE TITLE
[create-theme]: Only top bar in compact

### ISSUE THREAD

**Issue by vytorrennan** [zen-browser/theme-store#214]
### Name

Only top bar in compact mode

### Description

This theme will allow you can use the only hide the top bar of your browser, so that you can still see all of your tabs

### Homepage

https://github.com/vytorrennan/Zen-theme-only-top-bar-compact

### Image

https://github.com/vytorrennan/Zen-theme-only-top-bar-compact/blob/main/image.png?raw=true

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@-moz-document url-prefix("chrome:") {

#zen-appcontent-navbar-container {
      --urlbar-height: unset;
      transition: .2s ease-in-out;
      transform: translateY(calc(-100% + 5px));
      opacity: 0;
      position: absolute;
      width: 100%;
      border-bottom-left-radius: 8px;
      border-bottom-right-radius: 8px;
      border-bottom: 1px solid var(--zen-colors-border);
      top: 0;
      background: var(--zen-colors-tertiary);
      z-index: 2;
      transition: .2s ease-in-out;
    }

    #zen-appcontent-navbar-container:hover,
    #zen-appcontent-navbar-container:focus-within,
    #zen-appcontent-navbar-container[zen-user-show],
    #mainPopupSet:has(> #appMenu-popup:hover) ~ #zen-appcontent-navbar-container,
    #zen-appcontent-navbar-container:has(*[open="true"]) {
      transform: translateY(0);
      opacity: 1;
    }

    :root:not([inDOMFullscreen="true"]) #tabbrowser-tabbox #tabbrowser-tabpanels .browserSidebarContainer {
      margin-top: var(--zen-element-separation) !important;
    }

    #titlebar {
      padding-top: 5px !important;
    }

    #zen-sidebar-web-panel-wrapper {
      margin-top: 10px !important;
    }
  }

      }
```

### Readme

```markdown
# Zen-theme-only-top-bar-compact
This theme will allow you can use the only hide the top bar of your browser, so that you can still see all of your tabs
```
