### ISSUE TITLE
[create-theme]: Floating Web Panel

### ISSUE THREAD

**Issue by tunalad** [zen-browser/theme-store#227]
### Name

Floating Web Panel

### Description

Opening the sidebar's web panel will be over the page's content, instead of splitting the space.

### Homepage

https://github.com/tunalad/zen-floating-webpanel/

### Image

https://raw.githubusercontent.com/tunalad/zen-floating-webpanel/master/image.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#zen-sidebar-web-panel-wrapper {
    margin: 10px !important;
    position: absolute !important;
    z-index: 999999 !important;
    bottom: 0 !important;
    top: 0 !important;
}

@media (-moz-bool-pref: "uc.floating-webpanel.midmargin.enabled") {
    #zen-sidebar-web-panel-wrapper {
        margin: 5px !important;
        position: absolute !important;
        z-index: 999999 !important;
        bottom: 0 !important;
        top: 0 !important;
    }
}

@media (-moz-bool-pref: "uc.floating-webpanel.nomargin.enabled") {
    #zen-sidebar-web-panel-wrapper {
        margin: 0 !important;
        position: absolute !important;
        z-index: 999999 !important;
        bottom: 0 !important;
        top: 0 !important;
    }
}
```

### Readme

```markdown
# Floating Web Panel

Opening the sidebar's web panel will be over the page's content, instead of splitting the space.

By default, the margins around the panel is 10px, but via options you can set it to 5px margins, or disable them completely.
```

### Preferences

```json
{
    "uc.floating-webpanel.midmargin.enabled": "Margin around the panel is 5px",
    "uc.floating-webpanel.nomargin.enabled": "Disables margin around the panel completely"
}
```
