### ISSUE TITLE
[create-theme]: HidePlugins

### ISSUE THREAD

**Issue by adammpkins** [zen-browser/theme-store#230]
### Name

HidePlugins

### Description

Theme to hide the plugin button from the toolbar.

### Homepage

https://github.com/adammpkins/HidePlugins/tree/main

### Image

https://github.com/adammpkins/HidePlugins/raw/main/image.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@media (-moz-bool-pref: "uc.hidePlugins.disabled") {
  #unified-extensions-button{
    display: inherit;
 }
}

#unified-extensions-button{
    display:none;
}
```

### Readme

```markdown
# HidePlugins

This **Zen theme** hides the plugins button in the Zen toolbar.

## What it does by default:
  - Hides the plugins button in the Zen toolbar


![image](https://github.com/adammpkins/HidePlugins/blob/main/image.png)

## Optional Features (toggle in Zen's theme settings):
  - Restores the plugin button in the toolbar
```

### Preferences

```json
{
    "uc.hidePlugins.disabled" : "Restores the plugin button in the toolbar"
}
```
