### ISSUE TITLE
[create-theme]: Better UniExtBtn

### ISSUE THREAD

**Issue by lindongbin** [zen-browser/theme-store#233]
### Name

Better UniExtBtn

### Description

change unified extensions button to zen browser icon

### Image

https://006750.xyz/icon.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#unified-extensions-button {
  list-style-image: url("chrome://branding/content/icon32.png") !important;
}
```

### Readme

```markdown
The unified extension button does not match the color of other extension buttons. It looks more comfortable to change it to the browser icon.
```
