### ISSUE TITLE
[create-theme]: Restore Legacy Top Bar

### ISSUE THREAD

**Issue by bw8686** [zen-browser/theme-store#246]
### Name

Restore Legacy Top Bar

### Description

Restores the pre 1.0.0-a32 top bar.

### Homepage

https://github.com/bw8686/zentheme-restorelegacytopbar

### Image

https://i.imgur.com/lc9HNIG.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#navigator-toolbox {
  margin-top: 50px !important;
}

#zen-appcontent-navbar-container {
  margin-left: -50px !important;
}
#appcontent {
  overflow: visible !important;
}
```

### Readme

```markdown
Restores the pre 1.0.0-a32 top bar.
```
