### ISSUE TITLE
[create-theme]: Rosé Pine

### ISSUE THREAD

**Issue by zomby43** [zen-browser/theme-store#251]
### Name

Rosé Pine

### Description

Something beautiful

### Homepage

https://rosepinetheme.com/

### Image

https://i.imgur.com/UJ5Ltzh.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@-moz-document url-prefix("chrome:") {
  :root {
    --zen-colors-primary: #191724 !important;
    --zen-colors-secondary: #191724 !important;
    --zen-colors-tertiary: #191724 !important;
    --zen-colors-border: #26233a !important;
    --primary-color: #c4a7e7 !important;
    --dark-color: #21202e !important;
    color-scheme: dark !important;
  }

  toolbarbutton, titlebar-button, label{
    color: var(--primary-color) !important;;
    fill: var(--primary-color) !important;;
  }

  #tracking-protection-icon, #star-button.urlbar-icon {
    fill: #e0def4 !important;
  }

  #identity-icon-box.identity-box-button {
    background-color: var(--primary-color) !important;
  }

  #identity-icon, #identity-icon-label {
    color: var(--dark-color) !important;
  }

  #urlbar-background {
    background-color: var(--zen-colors-primary) !important;
  }
}
```

### Readme

```markdown
# Rosé Pine

All natural pine, faux fur and a bit of soho vibes for the classy minimalist.
```
