### ISSUE TITLE
[create-theme]: Uniform Url Bar

### ISSUE THREAD

**Issue by JLBlk** [zen-browser/theme-store#256]
### Name

Uniform Url Bar

### Description

Get simple rounded corners consistent with other buttons or centered text for your url bar.

### Homepage

https://github.com/JLBlk/Zen-Themes/tree/main/UniformUrlBar

### Image

https://github.com/JLBlk/Zen-Themes/blob/main/UniformUrlBar/image.png?raw=true

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@media (-moz-bool-pref: "uc.urlbar.border-radius") {
  #urlbar {
    border-radius: 10px !important;
  }
          
  #notification-popup-box {
    border-radius: 6px !important;
  }
        
  /* Border radius on hover */
  #urlbar .urlbar-page-action, #urlbar #tracking-protection-icon-container, #urlbar:not([breakout-extend="true"]) #identity-box:is(:not(.chromeUI), [pageproxystate="invalid"]) #identity-icon-box {
    border-radius: 6px !important;;
  }
        
  /* Border radius of boxes on the left */
  #identity-box:has(#identity-permission-box:is([hasPermissions], [hasSharingIcon])):not([pageproxystate="invalid"]) #identity-icon-box {
    border-top-left-radius: 6px !important;
    border-bottom-left-radius: 6px !important;
    border-top-right-radius: 0 !important;
    border-bottom-right-radius: 0 !important;
  }

  /* Extensions or similar */
  #urlbar:not([breakout-extend="true"]) #identity-box.chromeUI:not([pageproxystate="invalid"]) #identity-icon-box {
    border-radius: 6px 6px 6px 6px !important;
  }
}


@media (-moz-bool-pref: "uc.urltext.center") {
  #urlbar:not([focused]) .urlbar-input{ text-align: center !important; }
}
```

### Readme

```markdown
# Uniform Url Bar

## This **Zen theme** gives you 2 optional toggles (in Zen's theme settings):
  - Adjust border radius of url bar
  - Center url text
```

### Preferences

```json
{
    "uc.urlbar.border-radius": "Adjusts the border radius of the url bar and its items",
    "uc.urltext.center": "Centers the text inside the url bar"
}
```
