### ISSUE TITLE
[create-theme]: Collapsed Tab X-Button

### ISSUE THREAD

**Issue by burnt0rice** [zen-browser/theme-store#260]
### Name

Collapsed Tab X-Button

### Description

This theme adds a close button to the collapsed tabs in Zen Browser.

### Homepage

https://github.com/burnt0rice/zen-themes/tree/main/collapsed-tab-close-button

### Image

https://github.com/burnt0rice/zen-themes/blob/main/collapsed-tab-close-button/image.png?raw=true

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@media not (-moz-bool-pref: "zen.view.sidebar-expanded") {
  & .tabbrowser-tab {
    &:not([pinned]) {
      &:hover .tab-icon-stack {
        margin-left: 7px;
      }

      &:hover .tab-close-button {
        position: absolute !important;
        display: block !important;
        padding: 5px !important;
        height: 18px !important;
        width: 18px !important;
        border-radius: 50% !important;
        margin-inline-end: 0 !important;
        margin-left: -9px;
        margin-top: -18px;
        background-color: var(--zen-main-browser-background) !important;
        cursor: pointer;
      }
    }
  }
}
```

### Readme

```markdown
# Collapsed Tab Close Button

This theme adds a close button to the collapsed tabs in Zen Browser.

## What the extension does

This theme does:

- Display a close button on the collapsed tabs
- On hover, the close button will be shown

Have any suggestions or feedback? Feel free to open an issue in the [GitHub repository](https://github.com/burnt0rice/zen-themes/issues).
```
