### ISSUE TITLE
[create-theme]: zen-remove-workspaces-button

### ISSUE THREAD

**Issue by BrunoPoiano** [zen-browser/theme-store#266]
### Name

Remove Workspace Button

### Description

This theme is for those that do not use workspaces and want a little more space for the sidebar buttons.

### Homepage

https://github.com/BrunoPoiano/zen-remove-workspaces-button

### Image

https://imgur.com/a/gZxN3p1

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@-moz-document url-prefix("chrome:") {
  #zen-workspaces-button {
    display: none !important;
  }

  @media (-moz-bool-pref: "zen.view.sidebar-expanded") {
    #zen-workspaces-button {
      display: none !important;
    }
  }
}
```

### Readme

```markdown
# Zen Browser Theme - Removing the Workspace button

This theme is for those that do not use workspaces and want a little more space for the sidebar buttons.
```
