### ISSUE TITLE
[create-theme]: 

### ISSUE THREAD

**Issue by k2662** [zen-browser/theme-store#267]
### Name

rose-pine-moon

### Description

Soho Vibes for zen browser alpha

### Image

https://www.colorhexa.com/232136.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
:root {
    --zen-colors-primary: #2A273F !important;
    --zen-colors-secondary: #2A273F !important;
    --zen-colors-tertiary: #2A273F !important;
    --zen-colors-border: #C4A7E7 !important;
}
```

### Readme

```markdown
Soho Vibes for zen browser alpha
```
