### ISSUE TITLE
[create-theme]: 

### ISSUE THREAD

**Issue by k2662** [zen-browser/theme-store#268]
### Name

Rosé Pine Moon

### Description

Soho Vibes for zen browser alpha

### Homepage

https://rosepinetheme.com

### Image

https://raw.githubusercontent.com/k2662/png232136/main/232136.png

### Type

- [X] JSON Color Theme

### Theme Styles

```css
@-moz-document url-prefix("chrome:") {
  :root {
    --zen-colors-primary: #232136 !important;
    --zen-colors-secondary: #232136 !important;
    --zen-colors-tertiary: #232136 !important;
    --zen-colors-border: #393552 !important;
    --primary-color: #c4a7e7 !important;
    --dark-color: #2a283e !important;
    color-scheme: dark !important;
  }

  toolbarbutton, titlebar-button, label{
    color: var(--primary-color) !important;;
    fill: var(--primary-color) !important;;
  }

  #tracking-protection-icon, #star-button.urlbar-icon {
    fill: #e0def4 !important;
  }

  #identity-icon-box.identity-box-button {
    background-color: var(--primary-color) !important;
  }

  #identity-icon, #identity-icon-label {
    color: var(--dark-color) !important;
  }

  #urlbar-background {
    background-color: var(--zen-colors-primary) !important;
  }
}
```

### Readme

```markdown
###Rose Pine Moon
All natural pine, faux fur and a bit of soho vibes for the classy minimalist.
```
