### ISSUE TITLE
[create-theme]: 

### ISSUE THREAD

**Issue by Stilic** [zen-browser/theme-store#274]
### Name

Hide Tab Manager

### Description

Hides the sidebar's tab manager.

### Homepage

https://github.com/Stilic/zen-hide-tab-manager

### Image

https://raw.githubusercontent.com/Stilic/zen-hide-tab-manager/main/preview.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#alltabs-button {
  display: none !important;
}
```

### Readme

```markdown
# Zen Browser - Hide Tab Manager
Zen theme that hides the sidebar's tab manager.
```
