### ISSUE TITLE
[create-theme]: awd

### ISSUE THREAD

**Issue by mauro-balades** [zen-browser/theme-store#28]
### Name

....

### Description

awdddddddddddddddddddddddddddddddddddddddddddddddd

### Homepage

test

### Theme Styles

```css
test {
  blah: blagh;
}
```

### Readme

```markdown
# test

hello!!!!
```
