### ISSUE TITLE
[create-theme]: Zen Sidebar At Right Side

### ISSUE THREAD

**Issue by AntonioSTM** [zen-browser/theme-store#285]
### Name

Zen Sidebar At Right Side

### Description

Pin or float the Zen Sidebar at the right side.

### Image

https://raw.githubusercontent.com/AntonioSTM/theme-store/f1504325914cf5c2ce05b0b5d3b060eda9378bc4/themes/6a51c7de-3796-4aa8-a2e4-46274f0b59a8/image.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
/*#region  ZEN SIDEBAR AT RIGHT SIDE  */
	/*#region  RIGHT SIDE PINNED ZEN SIDEBAR  */
		@media (-moz-bool-pref: "uc.zen-sidebar.pin-at-right-side") {
			#zen-sidebar-web-panel-wrapper:not(:has(#zen-sidebar-web-panel[pinned="true"])) {
				order: 2 !important;
				margin-left: 10px !important;
			}
		}
	/*#endregion*/
	/*#region  RIGHT SIDE FLOATING ZEN SIDEBAR  */
		@media (-moz-bool-pref: "uc.zen-sidebar.float-at-right-side") {
			#zen-sidebar-web-panel-wrapper:has(#zen-sidebar-web-panel[pinned="true"]) {
				flex-direction: row-reverse;
			}
		}
	/*#endregion*/
/*#endregion*/
```

### Readme

```markdown
# Zen Sidebar At Right Side

Pin or float the **Zen Sidebar** at the right side.

## Features Available (through Zen Browser theme settings)

  = Pin the **Zen Sidebar** at the right side when pinned.

  = Float the **Zen Sidebar** at the right side when floating.
```

### Preferences

```json
{
    "uc.zen-sidebar.pin-at-right-side": "Pin the Zen Sidebar at the right side when pinned.",
    "uc.zen-sidebar.float-at-right-side": "Float the Zen Sidebar at the right side when floating."
}
```
