### ISSUE TITLE
[create-theme]: 

### ISSUE THREAD

**Issue by KiKaraage** [zen-browser/theme-store#294]
### Name

Neat Back and Forward Button

### Description

Hide Back and Forward button when you don't need them!

### Image

https://i.imgur.com/UF87jz9.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
:root:not([customizing]) #back-button[disabled] {
    display: none !important;
}

:root:not([customizing]) #forward-button[disabled] {
    display: none !important;
}
```

### Readme

```markdown
Achieve the Zen state further! Hide Back and/or Forward button on their disabled state - will appear only when you need them or when you want to arrange their positions (Right click on top bar > Customize Toolbar...)
```
