### ISSUE TITLE
[create-theme]: Zen Back Forward

### ISSUE THREAD

**Issue by KiKaraage** [zen-browser/theme-store#295]
### Name

Zen Back Forward

### Description

Hide Back and Forward button when you don't need them

### Image

https://i.imgur.com/UF87jz9.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
:root:not([customizing]) #back-button[disabled] {
    display: none !important;
}

:root:not([customizing]) #forward-button[disabled] {
    display: none !important;
}
```

### Readme

```markdown
Achieve the Zen state further! Hide Back and/or Forward button when you don't need them. 

Both buttons will still shows when you arrange their positions from the Customize Toolbar menu.
```
