### ISSUE TITLE
[create-theme]: test

### ISSUE THREAD

**Issue by mauro-balades** [zen-browser/theme-store#30]
### Name

test

### Description

awdawd

### Homepage

test

### Theme Styles

```css
test {
  blah: blagh;
}
```

### Readme

```markdown
# test

hello!!!!
```
