### ISSUE TITLE
[create-theme]: Cleaner Extension Menu

### ISSUE THREAD

**Issue by KiKaraage** [zen-browser/theme-store#300]
### Name

Cleaner Extension Menu 

### Description

Remove header and reduce width of the Unified Extension Menu in Zen

### Image

https://i.imgur.com/5AFz5LD.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#unified-extensions-view box.panel-header,
#unified-extensions-description,
#unified-extensions-messages-container {
  display: none !important;
}

#unified-extensions-view {
  width: var(--menu-panel-width) !important;
}

panelview .unified-extensions-item-action-button {
  padding-inline: 10px !important;
  padding-block: 0px !important;
}

#unified-extensions-manage-extensions {
  padding-inline: 10px !important;
}

#unified-extensions-panel .unified-extensions-item {
  margin-block: 1px !important;
}
```

### Readme

```markdown
Default Unified Extension Menu in Zen has lengthy description which added extra width on it. This theme will remove the Extension header and description, results on efficient panel size.

[Go here if you want to submit issue related to this theme](https://github.com/KiKaraage/ArcWTF/issues/new?assignees=KiKaraage&labels=Zen+Themes&projects=&template=zen-browser-theme-issue.md&title=%5BZBT%5D+)
```
