### ISSUE TITLE
[create-theme]: Rosé Pine Dawn

### ISSUE THREAD

**Issue by zomby43** [zen-browser/theme-store#305]
### Name

Rosé Pine Dawn

### Description

Something Beautiful

### Homepage

https://rosepinetheme.com/

### Image

https://i.imgur.com/f6BjFVl.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@-moz-document url-prefix("chrome:") {
  :root {
    --zen-colors-primary: #faf4ed !important;
    --zen-colors-secondary: #faf4ed !important;
    --zen-colors-tertiary: #faf4ed !important;
    --zen-colors-border: #f2e9e1 !important;
    --primary-color: #797593!important;
    --light-color: #cecacd !important;
    --alt-color: #9893a5 !important;
    color-scheme: light !important;
  }

  toolbarbutton, titlebar-button, label{
    color: var(--primary-color) !important;;
    fill: var(--primary-color) !important;;
  }

  #tracking-protection-icon, #star-button.urlbar-icon {
    fill: var(--alt-color) !important;
  }

  #identity-icon-box.identity-box-button {
    background-color: var(--primary-color) !important;
  }

  #identity-icon, #identity-icon-label {
    color: var(--light-color) !important;
  }

  #urlbar-background {
    background-color: var(--zen-colors-primary) !important;
  }
}
```

### Readme

```markdown
# Rosé Pine Dawn

All natural pine, faux fur and a bit of soho vibes for the classy minimalist. 

Light theme - Enable Light Theme in :addons if nessesary.
```
