### ISSUE TITLE
[create-theme]: remove statusbar

### ISSUE THREAD

**Issue by F-U-B-AR** [zen-browser/theme-store#308]
### Name

Disable Status Bar

### Description

This removes the bottom-left status bar when hovering over a URL.

### Image

https://i.postimg.cc/QMqtsb7W/remove-statusbar.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#statuspanel {
 display: none !important;

 }
```

### Readme

```markdown
Removes the bottom-left statusbar when hovering over a URL.
```
