### ISSUE TITLE
[create-theme]: drop-shadow panel

### ISSUE THREAD

**Issue by mohvn** [zen-browser/theme-store#310]
### Name

Drop Shadow

### Description

Adds a drop shadow to the website's browser panel.

### Homepage

https://github.com/mohvn/dropshadow-zenbrowser

### Image

https://github.com/mohvn/dropshadow-zenbrowser/raw/main/preview.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#navigator-toolbox toolbar#TabsToolbar {
  padding: 5px 5px !important;
}

& #tabbrowser-tabbox #tabbrowser-tabpanels .browserSidebarContainer {
  box-shadow: 1px 1px 3px 1px rgba(0, 0, 0, 0.5) !important;
}
```

### Readme

```markdown
Adds a drop shadow to the website's browser panel.
```
