### ISSUE TITLE
[create-theme]: New tab button position

### ISSUE THREAD

**Issue by benstone326** [zen-browser/theme-store#319]
### Name

New tab button position

### Description

New tab button position is always the last in order

### Homepage

https://github.com/benstone326/zen-browser-new-tab-position/tree/main

### Image

https://files.catbox.moe/ntfm0k.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#newtab-button-container{
  order: 9999 !important;
}
```

### Readme

```markdown
New tab button position is always the last in order
```
