### ISSUE TITLE
[create-theme]: Compact Floating TopBar

### ISSUE THREAD

**Issue by HiroDane** [zen-browser/theme-store#323]
### Name

Compact Floating Topbar

### Description

Compact your topbar to be in center of screen.

### Homepage

https://github.com/HiroDane/zen-themes

### Image

https://imgur.com/a/cr6KuO7

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@media (-moz-bool-pref: "zen.view.compact") {
 #zen-appcontent-navbar-container {
   align-self: center !important;
   width: 75% !important;
   border-radius: 0px 0px 10px 10px !important;
 }
 @media (-moz-bool-pref: "uc.topbar.float") {
  #zen-appcontent-navbar-container {
   margin-top: 1vh;
   border-radius: 10px 10px 10px 10px !important;
  }
 }
}
```

### Readme

```markdown
# Compact Floating TopBar
This theme changes the top bar to be more compact and centered.
- Can be configured to be floating from Theme Store Settings by setting "uc.topbar.float" to true.
- Works in compact mode.
- Matches well with Smaller Compact Mode theme.

### credits
modifyed code from : https://github.com/n7itro/Zen-Themes/blob/main/Centered%20Top%20Bar/chrome.css
```

### Preferences

```json
{
 "uc.topbar.float":"Makes the top bar float out from screen edge in compact mode"
}
```
