### ISSUE TITLE
[create-theme]: Better Active Tab Indicator

### ISSUE THREAD

**Issue by HliasOuzounis** [zen-browser/theme-store#327]
### Name

Better Active Tab Indicator

### Description

Adds a bright line to the active tab to better highlight it

### Homepage

https://github.com/HliasOuzounis/zen-browser-better-active-tab-indicator

### Image

https://github.com/HliasOuzounis/zen-browser-better-active-tab-indicator/blob/master/images/active-indicator.png?raw=true

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@media not (-moz-bool-pref: "zen.view.sidebar-expanded") {
    .tabbrowser-tab::after {
      content:'';
      position: absolute;
      width: 3px !important;
      height: 100% !important;
      background-color: var(--zen-primary-color) !important;
    }
  
    .tabbrowser-tab:not([selected=true])::after{
      height: 0% !important;
    }
  }
```

### Readme

```markdown
# Better Active Tab Indicator

Adds a bright line next to the active tab to better highlight it.

![Active tab](images/active-indicator.png)
```
