### ISSUE TITLE
[create-theme]: Workspace Seperator

### ISSUE THREAD

**Issue by HliasOuzounis** [zen-browser/theme-store#332]
### Name

Workspace Seperator

### Description

Adds a line below the workspace button to seperate it from other tabs

### Homepage

https://github.com/HliasOuzounis/zen-browser-workspace-seperator

### Image

https://github.com/HliasOuzounis/zen-browser-workspace-seperator/blob/master/images/after.png?raw=true

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#zen-workspaces-button::after {
  content:'';
  position: absolute;
  border-radius: 3px !important;
  height: 2px !important;
  transform: translateY(+24px);
  background-color: var(--zen-input-border-color) !important;
}

@media not (-moz-bool-pref: "zen.view.sidebar-expanded") {
  #zen-workspaces-button::after {
    width: 40px;
  }
}

@media (-moz-bool-pref: "zen.view.sidebar-expanded") {
  #zen-workspaces-button::after {
    width: 160px;
  }
}

#zen-workspaces-button {
  margin-bottom: 15px !important;
}
```

### Readme

```markdown
# Workspace-Seperator

A theme that add a small white line under the workspace button
to differentiate it from the other buttons.

Works best alongside the [Uniform Workspace Button](https://zen-browser.app/themes/5ac61d13-a0dc-400e-aaa0-0f10fd3a7d0c) theme.

## Preview

![after](images/after.png)

## Original

![before](images/before.png)
```
