### ISSUE TITLE
[create-theme]: Better Bookmark

### ISSUE THREAD

**Issue by Gnkalk** [zen-browser/theme-store#334]
### Name

Better Bookmark

### Description

Make BookmarkBar better than before and match with Zen

### Image

https://private-user-images.githubusercontent.com/74614163/364412006-b0c495a5-046e-436e-9b93-a7aab2e60ff5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU1MzE2MTUsIm5iZiI6MTcyNTUzMTMxNSwicGF0aCI6Ii83NDYxNDE2My8zNjQ0MTIwMDYtYjBjNDk1YTUtMDQ2ZS00MzZlLTliOTMtYTdhYWIyZTYwZmY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA1VDEwMTUxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1YTY0YjhhM2U4MTA1MDNmNGEwNDM3N2M3NTIwNTc4YzIxMDRjNDQzMDQ4NTBmYTc5MDk3MTVjZjJlOTRlNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1M689rK-yt0vGzVTNYQvgC610r7Ip9xB9e0lbqIQmX8

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#PersonalToolbar {
  padding-block-end: .5rem !important;
  padding-inline: 6px 12px !important;
  .bookmark-item {
    padding-inline: .5rem !important;
  }
  #PlacesChevron{
    margin-inline: .5rem !important;
    height: fit-content;
    margin-block: auto !important;
    image {
      transform: rotateZ(90deg)
    }
    
    &[open] {
      #PlacesChevronPopup{
        opacity: 1;
        left: -50rem;
      }
    }
    #PlacesChevronPopup{
      margin-top: 1rem !important;
      padding-bottom: 1rem;
      margin-block-end: 1rem !important;
      padding-inline: .5rem 1rem !important;
      opacity: .2;
      transition: opacity 300ms ease-out;
    }
  }
  #OtherBookmarks {
    &[open] {
      #OtherBookmarksPopup{
        opacity: 1;
        left: -50rem;
      }
    }
    #OtherBookmarksPopup{
      margin-top: .75rem !important;
      padding-bottom: .75rem;
      margin-block-end: 1rem !important;
      padding-inline: .5rem 1rem !important;
      opacity: .2;
      transition: opacity 300ms ease-out;
    }
    
  }
  
  #OtherBookmarks::before {
    left: -.75rem;
    position: relative;
    content: "";
    width: 1px;
    background-color: color-mix(in srgb, var(--zen-primary-color) 35%, transparent 50%);
    height: 100%;
  }
}
@media (prefers-reduced-motion) {
  #PlacesChevronPopup{
      transition: none;
   }
  #OtherBookmarksPopup{
    transition: none;
  }
}
```

### Readme

```markdown
If you toggle the bookmark bar, you see some issues like no margin between main window and bar and etc.

this theme fix this issues :)
```
