### ISSUE TITLE
[create-theme]: Uniform generic sidebar

### ISSUE THREAD

**Issue by Gnkalk** [zen-browser/theme-store#336]
### Name

Uniform Sidebar

### Description

Uniform Firefox Sidebar

### Image

https://imgur.com/a/SXhYXDX

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#sidebar-box {
  background: var(--zen-colors-tertiary) !important;
  border: var(--zen-appcontent-border) !important;
  
  display: flex !important;
  transition: 400ms cubic-bezier(0,0,.15,1.28) !important;
  
  &[hidden] {
    width: 0 !important;
    min-width: 0 !important;
  }
}
```

### Readme

```markdown
Uniform firefox generic sidebar with smooth animation
```
