### ISSUE TITLE
[create-theme]: Compact Floating TopBar

### ISSUE THREAD

**Issue by HiroDane** [zen-browser/theme-store#342]
### Name

Compact Floating TopBar

### Description

This theme changes the top bar to be more compact and centered in compact mode.

### Homepage

https://github.com/HiroDane/zen-themes/tree/main/compact-floating-topbar

### Image

https://github.com/HiroDane/zen-themes/blob/main/compact-floating-topbar/image.png?raw=true

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@media (-moz-bool-pref: "zen.view.compact") {
 #zen-appcontent-navbar-container {
   align-self: center !important;
   width: 75% !important;
   border-radius: 0px 0px 10px 10px !important;
 }
 @media (-moz-bool-pref: "uc.compacttopbar.float") {
  #zen-appcontent-navbar-container {
   margin: 1vh !important;
   border-radius: 10px 10px 10px 10px !important;
  }
 }
 @media (-moz-bool-pref: "uc.compacttopbar.glow") {
  #nav-bar {
   box-shadow: rgb(38, 57, 77) 0px 0px 20px 10px;
   border-radius: 0px 0px 10px 10px !important;
  }
  @media (-moz-bool-pref: "uc.topbar.float") {
   #nav-bar {
    border-radius: 10px 10px 10px 10px !important;
   }
  }
 }
 @media (-moz-bool-pref: "uc.compacttopbar.outline") {
  #nav-bar {
   border: 1px solid rgba(255, 255, 255, 0.4) !important;
   border-top: 0px solid !important;
   border-radius: 0px 0px 10px 10px !important;
  }
  @media (-moz-bool-pref: "uc.compacttopbar.float") {
   #nav-bar {
    border: 1px solid rgba(255, 255, 255, 0.4) !important;
    border-radius: 10px 10px 10px 10px !important;
   }
  }
 }
 @media (-moz-bool-pref: "uc.compacttopbar.applyToTabBar") {
  @media (-moz-bool-pref: "uc.topbar.glow") {
   #titlebar {
    box-shadow: rgb(38, 57, 77) 0px 0px 20px 10px;
    border-radius: 10px 10px 10px 10px !important;
   }
  }
  @media (-moz-bool-pref: "uc.compacttopbar.outline") {
   #titlebar {
    border: 1px solid rgba(255, 255, 255, 0.4) !important;
    border-radius: 10px 10px 10px 10px !important;
   }
  }
 }
}
```

### Readme

```markdown
# Compact Floating TopBar
This theme changes the top bar to be more compact and centered.
- Works in compact mode ONLY (recommended: hide top bar).
- Customizable (float out, glow, outline) from theme settings.
- Matches well with Smaller Compact Mode theme.
```

### Preferences

```json
{
 "uc.compacttopbar.float":"Makes the top bar float out from screen edge in compact mode",
 "uc.compacttopbar.glow":"Makes the top bar have a glow around it for better visual seperation",
 "uc.compacttopbar.outline":"Makes the top bar have a thin white outline around it for better visual seperation",
 "uc.compacttopbar.applyToTabBar":"Apply glow and outline to Tab navigation side bar as well"
}
```
