### ISSUE TITLE
[create-theme]: Persistent Compact Mode

### ISSUE THREAD

**Issue by HiroDane** [zen-browser/theme-store#347]
### Name

Persistent Compact Mode

### Description

Makes the compact mode panels always visible.

### Homepage

https://github.com/HiroDane/zen-themes/tree/main/persistent-compact-mode

### Image

https://github.com/HiroDane/zen-themes/blob/main/persistent-compact-mode/image.png?raw=true

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@media (-moz-bool-pref: "uc.persistentcompactmode.active"){
 @media (-moz-bool-pref: "zen.view.compact") {
  #navigator-toolbox {
   opacity: 1 !important;
   transform: none !important;
  }

  #zen-appcontent-navbar-container {
   opacity: 1 !important;
   transform: none !important;
  }
 @media (-moz-bool-pref: "uc.persistentcompactmode.transparent") {
  #navigator-toolbox {
   opacity: 0.7 !important;
  }

  #zen-appcontent-navbar-container {
   opacity: 0.7 !important;
  }
 }
 }
}
```

### Readme

```markdown
# Persistent Compact Mode
Makes the compact mode panels always visible.
- CAUTION: It can make certain sites unusable if the panels cover up necessary things.
- Have to manually activate from settings.
- Option for transparency.
```

### Preferences

```json
{
 "uc.persistentcompactmode.active" : "Activate the theme. Make sure to have compact mode and hide top bar options active.",
 "uc.persistentcompactmode.transparent" : "Make the panels slightly transparent"
}
```
