### ISSUE TITLE
[create-theme]: Compact Topsites

### ISSUE THREAD

**Issue by naiyerasif** [zen-browser/theme-store#351]
### Name

Compact Topsites

### Description

Theme for compact Top site icons on new tab 

### Homepage

https://github.com/naiyerasif/zen-compact-topsites

### Image

https://raw.githubusercontent.com/naiyerasif/zen-compact-topsites/main/image.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
.top-site-outer {
	--tile-radius: 12px;
	--tile-icon-size: 32px;
	--tile-size: 56px;
	border-radius: 16px !important;
}
.top-site-outer .tile {
	border-radius: var(--tile-radius) !important;
	height: var(--tile-size) !important;
	width: var(--tile-size) !important;
}
.top-site-outer .tile .icon-wrapper {
	width: var(--tile-icon-size) !important;
	height: var(--tile-icon-size) !important;
}
.top-site-outer .tile .icon-wrapper.letter-fallback::before {
	font-size: 32px !important;
	top: 0 !important;
}
.top-site-outer .context-menu-button {
	--tile-btn-size: 24px;
	--tile-btn-radius: 8px;
	border-radius: 0 !important;
}
.top-site-outer .context-menu-button {
	background-color: var(--newtab-element-hover-color) !important;
	padding: 1.5ch !important;
	height: var(--tile-btn-size) !important;
	width: var(--tile-btn-size) !important;
	border-radius: var(--tile-btn-radius) !important;
	right: 0 !important;
	top: -12px !important;
}
```

### Readme

```markdown
# Compact Topsites

**Zen Browser theme** for compact Top site icons on new tab

## What it does by default:

- Makes top site icons on new tab smaller and rounder
```
