### ISSUE TITLE
[create-theme]: 

### ISSUE THREAD

**Issue by dhanushl0l** [zen-browser/theme-store#359]
### Name

Remove border 

### Description

it remove border padding in zen browser

### Homepage

https://github.com/dhanushl0l/remove-border-padding-zen-browser/tree/main

### Image

https://i.imgur.com/8m0apAm.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
/* Remove border padding */
:root:not([inDOMFullscreen="true"]):not([chromehidden~="location"]):not([chromehidden~="toolbar"]) {
  & #tabbrowser-tabbox #tabbrowser-tabpanels .browserSidebarContainer  {
    margin: 0 !important;
    border-radius: 0 !important;
  }
}

/* Remove border padding from Zen sidebar */
:root:not([inDOMFullscreen="true"]):not([chromehidden~="location"]):not([chromehidden~="toolbar"]) {
  & #zen-sidebar-web-panel-wrapper {
    margin: 0 !important;
  }
}

:root:not([inDOMFullscreen="true"]):not([chromehidden~="location"]):not([chromehidden~="toolbar"]) {
  & #zen-sidebar-web-header {
    border-radius: 0 !important;
  }
}

:root:not([inDOMFullscreen="true"]):not([chromehidden~="location"]):not([chromehidden~="toolbar"]) {
  & #zen-sidebar-web-panel {
    border-radius: 0 !important;
  }
}
```

### Readme

```markdown
# Remove border padding zen browser
I hate borders because they waste valuable screen space. This custom CSS is designed to remove borders and padding, allowing you to visit all pages in fullscreen mode without any distractions or wasted space.

![preview image1](https://i.imgur.com/Oc0NL8L.png)
![preview image2](https://i.imgur.com/k01hbgi.png)
```
