### ISSUE TITLE
[create-theme]: zen-browser-bookmarks-folder-icon

### ISSUE THREAD

**Issue by Hfanes** [zen-browser/theme-store#366]
### Name

Bookmarks Folders Icon

### Description

Change the default bookmark folder icons in the Zen browser to custom fodler icon. 

### Homepage

https://github.com/Hfanes/zen-browser-bookmarks-folder-icon

### Image

https://raw.githubusercontent.com/Hfanes/zen-browser-bookmarks-folder-icon/main/preview.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
/*foldes*/
#PlacesToolbarItems .bookmark-item[container] > .toolbarbutton-icon {
  list-style-image: url("folder.ico") !important;
}

/* subfolders */
#PlacesToolbarItems .bookmark-item[container] .bookmark-item[container] {
  list-style-image: url("folder.ico") !important;
}

#PlacesChevron .bookmark-item[container] .menu-iconic-icon {
  list-style-image: url("folder.ico") !important;
}
```

### Readme

```markdown
# zen-browser-bookmarks-folder-icon

Change the default bookmark folder icons in the Zen browser to custom fodler icon.

## Original

![Original](/original.png)

## Preview

![Preview](/before.png)

## Example

![Preview](/preview.png)
```
