### ISSUE TITLE
[create-theme]: Hide New Tab Button

### ISSUE THREAD

**Issue by mvahaste** [zen-browser/theme-store#371]
### Name

Hide New Tab Button

### Description

Hide the new tab button in the sidebar.

### Image

https://i.ibb.co/vctz4CK/thumb.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#vertical-tabs-newtab-button {
  display: none !important;
}
```

### Readme

```markdown
This theme hides the vertical tabs new tab button in the sidebar by applying `display: none` to the corresponding `toolbarbutton` element. Nice if you always use keyboard shortcuts instead of the button anyway.
```
