### ISSUE TITLE
[create-theme]: 

### ISSUE THREAD

**Issue by DaitiDay** [zen-browser/theme-store#373]
### Name

TitleBarButton UI Tweaks

### Description

Small UI tweaks to the titlebar buttons to make them more coherent with the Zen Browser design philosophy.

### Image

https://i.imgur.com/qN2kA0D.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
.titlebar-buttonbox {
  padding: 9px !important;
}

.titlebar-button:hover {
  background-color: var(--button-hover-bgcolor) !important;
}

.titlebar-min {
  padding-left: 10px !important;
  padding-right: 10px !important;
  border-radius: var(--uc-contextmenu-menuitem-border-radius) !important;
}

.titlebar-max {
  padding-left: 10px !important;
  padding-right: 10px !important;
  margin-left: 5px !important;
  margin-right: 5px !important;
  border-radius: var(--uc-contextmenu-menuitem-border-radius) !important;
}

.titlebar-close {
  padding-left: 10px !important;
  padding-right: 10px !important;
  border-radius: var(--uc-contextmenu-menuitem-border-radius) !important;
}

.titlebar-close:hover {
  background-color: var(--buttons-destructive-hover-bgcolor) !important;
}
```

### Readme

```markdown
# TitleBarButton UI Tweaks

Thank to this theme, the titlebar buttons (minimize, maximize and close) are more coherent with the Zen Browser design philosophy, with smaller buttons, rounded borders and accent colors that fit the browser's appearance.
```
