### ISSUE TITLE
[create-theme]: Floating toolbar

### ISSUE THREAD

**Issue by anaarkei** [zen-browser/theme-store#376]
### Name

Floating toolbar

### Description

Detaches toolbar from edge of browser window so that it appears to float

### Image

https://beta.jarick.works/zen-floating-toolbar.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#zen-appcontent-navbar-container {
  padding: 20px;
  border: none !important;
  background: none !important;
  box-sizing: border-box;
}

#nav-bar {
  background: var(--zen-colors-tertiary) !important;
  border-radius: 8px;
  border: 1px solid var(--zen-colors-border) !important;
}
```

### Readme

```markdown
Detaches toolbar from edge of browser window so that it appears to float.

Requires compact mode to be enabled and top toolbar to be hidden.
```
