### ISSUE TITLE
[create-theme]: Hide Sidebar Seperators

### ISSUE THREAD

**Issue by LarveyOfficial** [zen-browser/theme-store#380]
### Name

Hide Sidebar Seperators

### Description

Hide the sidebar's seperators in the Zen Browser

### Homepage

https://github.com/LarveyOfficial/zen-browser-hide-sidebar-seperators/tree/main

### Image

![screenshot](https://github.com/user-attachments/assets/d668d30b-8ff9-431d-b717-820a59e208ec)

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#zen-sidebar-icons-wrapper::before{
  width: 0% !important;
}

#newtab-button-container::before {
  width: 0% !important;
}
```

### Readme

```markdown
# Hide Sidebar Seperators
Hide the sidebar's seperators in the Zen Browser

![Zen-Remove-Sidebar-Seperators](https://github.com/user-attachments/assets/9702b439-6293-4b7a-a8f8-fca3d7d3d134)
```
