### ISSUE TITLE
[create-theme]: zen-sidebery

### ISSUE THREAD

**Issue by Alexcoder5** [zen-browser/theme-store#384]
### Name

Zen Sidebery

### Description

Hide native Zen tab panel to use Sidebery

### Homepage

https://github.com/Alexcoder5/zen-sidebery/tree/main

### Image

https://github.com/Alexcoder5/zen-sidebery/blob/main/img/preview.png?raw=true

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#zen-sidebar-splitter {
    display: none !important;
}

#navigator-toolbox {
    position: absolute !important;
    top: -9999px;
    left: -9999px;
}

html:has(#sidebar-box[hidden="true"]) #tabbrowser-tabpanels {
    padding-left: var(--zen-element-separation) !important;
    margin-left: -2px
}

#sidebar-box {
    min-width: 34px !important;
}

#sidebar-splitter {
    right: -8px;
    z-index: 999 !important;
    border: 2px solid transparent !important;
}

#history-panel,
#bookmarksPanel {
    background: transparent !important;
}

html {
    --lwt-sidebar-background-color: transparent !important;
}

@media (-moz-bool-pref: "uc.theme.compact-tab-bar.enabled") {
    #tabbrowser-tabpanels {
        padding-left: 0px !important;
    }
}


@media (-moz-bool-pref: "uc.theme.hide-sidebar-header.enabled") {
    #sidebar-header {
        display: none !important;
    }
}
```

### Readme

```markdown
# Zen-Sidebery

## Hide native Zen tab panel to use Sidebery

### What you can enable

* Hide Sidebar Header

### Instructions:

1. Install the theme
2. Install [Sidebery addon](https://addons.mozilla.org/en-US/firefox/addon/sidebery/)
3. Enjoy

### You can upload custom Sidebery settings:

1. Download sidebery.json from this repo (press on ***Visit Homepage***)
2. Go to Sidebery Settings -> Help -> Import Addon Data
3. Select downloaded file

### or customize it the way you want
```

### Preferences

```json
{
    "uc.theme.hide-sidebar-header.enabled": "Hide Sidebar Header"
}
```
