### ISSUE TITLE
[create-theme]: 

### ISSUE THREAD

**Issue by Osmagtor** [zen-browser/theme-store#386]
### Name

New tab button at the bottom

### Description

Move the new tab button to the end of the list of open tabs

### Homepage

https://github.com/Osmagtor/zen-themes/tree/main/New%20tab%20button%20at%20the%20bottom

### Image

https://raw.githubusercontent.com/Osmagtor/zen-themes/main/New%20tab%20button%20at%20the%20bottom/screenshot.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#newtab-button-container {
	order: 1;
	margin-bottom: var(--space-small);
	margin-top: -10px;
}

#tabbrowser-arrowscrollbox {
	margin-bottom: 0px !important;
}
```

### Readme

```markdown
# New tab button at the bottom

Move the new tab button to the end of the list of open tabs.
```
