### ISSUE TITLE
[create-theme]: MinMaxCloseButtonStyledLikeMac

### ISSUE THREAD

**Issue by amatya-aditya** [zen-browser/theme-store#390]
### Name

MinMaxCloseButtonStyledLikeMac

### Description

It styles the min, max and close button of the title bar.

### Homepage

https://github.com/amatya-aditya/Zen-Mods/tree/main/MinMaxCloseButtonStyled

### Image

https://github.com/amatya-aditya/Zen-Mods/blob/main/MinMaxCloseButtonStyled/Screenshot%202024-09-16%20144307.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
/* Make window-control - aka caption buttons round following theme text color. */
/* Uncomment the following line to use colorful icons ala MacOS */

.titlebar-button{ --uc-caption-background: var(--uc-caption-color) }

.titlebar-button { opacity: 0.6; --uc-caption-color: rgb(0, 153, 0); }
.titlebar-min    { opacity: 0.5; --uc-caption-color: rgb(255, 255, 0); }
.titlebar-close  { opacity: 0.7; --uc-caption-color: rgb(246, 41, 41);}

.titlebar-button:hover { opacity: 1 }

.titlebar-button {
  background: transparent !important;
  padding-inline: 2px !important;
  transition: opacity 0.2s ease;
}

.titlebar-button > .toolbarbutton-icon {
	list-style-image: none;
	border-radius: 10px;
  background: var(--uc-caption-background,currentColor) !important;
}

.tabbrowser-tab .tab-close-button{
  display:none;
}
.tabbrowser-tab:not([pinned]):hover .tab-close-button{
  display: flex !important;
  align-items: center;
  color:#80808000;
}

.titlebar-buttonbox .titlebar-button {
  padding: 14px 8px !important;
}

.toolbarbutton.titlebar-button{
  padding: 14px 8px !important;

}
```

### Readme

```markdown
It styles the min, max and close button of the title bar and make it looks minimal.
```
