### ISSUE TITLE
[create-theme]: MacOS traffic lights

### ISSUE THREAD

**Issue by Osmagtor** [zen-browser/theme-store#401]
### Name

MacOS traffic lights

### Description

Move the close, minimize and maximize icons on macOS all the way to the left.

### Homepage

https://github.com/Osmagtor/zen-themes/tree/main/MacOS%20traffic%20lights

### Image

https://raw.githubusercontent.com/Osmagtor/zen-themes/main/MacOS%20traffic%20lights/screenshot.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@media (-moz-platform: macos) {
	#navigator-toolbox {
		margin-top: 40px !important;
	}

	#appcontent {
		overflow: visible !important;
	}

	#zen-appcontent-navbar-container {
		margin-left: -50px;
	}

	#nav-bar-customization-target {
		margin-left: 20px;
	}

	@media (-moz-bool-pref: "zen.view.sidebar-expanded") {
		#zen-appcontent-navbar-container {
			margin-left: -164px;
		}
	}
}
```

### Readme

```markdown
# MacOS traffic lights on the left
Move the close, minimize and maximize icons on macOS all the way to the left.
```
