### ISSUE TITLE
[create-theme]: Old navigation buttons

### ISSUE THREAD

**Issue by Osmagtor** [zen-browser/theme-store#404]
### Name

Old navigation buttons

### Description

Restore the original Firefox navigation buttons.

### Homepage

https://github.com/Osmagtor/zen-themes/tree/main/Restore%20navigation%20buttons

### Image

https://raw.githubusercontent.com/Osmagtor/zen-themes/main/Restore%20navigation%20buttons/screenshot.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#back-button {
	list-style-image: url("chrome://browser/skin/back.svg") !important;
}

#forward-button {
	list-style-image: url("chrome://browser/skin/forward.svg") !important;
}

#reload-button {
	list-style-image: url("chrome://global/skin/icons/reload.svg") !important;
}
```

### Readme

```markdown
# Restore navigation buttons
Restore the original Firefox navigation buttons.
```
