### ISSUE TITLE
[create-theme]: Hide Restore/Maximize Button

### ISSUE THREAD

**Issue by StyingDev** [zen-browser/theme-store#415]
### Name

Hide Restore/Maximize

### Description

Hide the Restore/Maximize button on Zen.

### Homepage

https://github.com/StyingDev/Styings-Zen-Browser-Mods/tree/main/Hide%20Restore%20and%20Maximize%20button

### Image

https://i.imgur.com/wgimZ2c.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
/* Hides the toolbarbutton element for restore and minimize */
toolbarbutton.titlebar-button.titlebar-restore {
  display: none;
}

toolbarbutton.titlebar-button.titlebar-max {
  display: none;
}
```

### Readme

```markdown
# Zen Browser Toolbar Button Hider

This project provides a simple CSS modification to hide the "Restore Down" and "Maximize" buttons in the Zen Browser.

This style ensure that the specified buttons are no longer visible in the browser interface, offering a more minimalist UI.
```
