### ISSUE TITLE
[create-theme]: 

### ISSUE THREAD

**Issue by Dinno-DEV** [zen-browser/theme-store#418]
### Name

Zen Minimal Exit Menu

### Description

A zen browser mod that changes the exit menu to 3 circles similar (but a bit different) to one in MacOS.

### Homepage

https://github.com/Dinno-DEV/zen-minimal-exit-menu

### Image

https://private-user-images.githubusercontent.com/109049468/369019467-9d85eef2-775d-44a8-89e7-d2b44a401e47.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NTM3OTAsIm5iZiI6MTcyNjc1MzQ5MCwicGF0aCI6Ii8xMDkwNDk0NjgvMzY5MDE5NDY3LTlkODVlZWYyLTc3NWQtNDRhOC04OWU3LWQyYjQ0YTQwMWU0Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOVQxMzQ0NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYTE5N2RiZWU1ZGJiM2ViMzcxYzQ1YzJjZDM2YjkxMmY4ZDE4OTk2YjEwMzQ4NDE1MDYxZGU2ZmI0ZGE2MDA3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1CASHlzvpEykV6QLe-aZs774-tvyJ5vHn-LvPw8htN8

### Type

- [x] JSON Color Theme

### Theme Styles

```css
.titlebar-buttonbox {
    margin-right: 20px;
}

.titlebar-button {
    padding: 0px !important;
    min-height: 13px !important;
    min-width: 13px !important;
    align-self: center;
    background-color: hsl(0, 0%, 20%) !important;
    margin-left: 5px !important;
    border-radius: 50px;
    transition: all 100ms;
}

.titlebar-button:hover {
    min-height: 20px !important;
}

.titlebar-min:hover {
    background-color: hsl(130, 50%, 40%) !important;
}

.titlebar-max:hover, .titlebar-restore:hover {
    background-color: hsl(60, 50%, 50%) !important;
}

.titlebar-close:hover {
    background-color: hsl(0, 50%, 50%) !important;
}

.titlebar-button > image {
    visibility: collapse !important;
}
```

### Readme

```markdown
# Zen Minimal Exit Menu
A zen browser mod that changes the exit menu to 3 circles similar (but a bit different) to one in MacOS.
```
