### ISSUE TITLE
[create-theme]: Hide Window Control Buttons

### ISSUE THREAD

**Issue by n7itro** [zen-browser/theme-store#42]
### Name

Hide Window Control Buttons

### Description

Hide the minimize, maximize, and close window buttons

### Image

https://i.imgur.com/mms4VdY.png

### Theme Styles

```css
/* Remove minimize window button */
@media (-moz-bool-pref: "uc.my-preference.hide-minimize") {
  .titlebar-min {
    display: none;
  }
}

/* Remove maximize window button */
@media (-moz-bool-pref: "uc.my-preference.hide-maximize") {
  .titlebar-max {
    display: none;
  }
  .titlebar-restore {
    display: none;
  }
}

/* Remove close window button */
@media (-moz-bool-pref: "uc.my-preference.hide-close") {
  .titlebar-close {
    display: none;
  }
}
```

### Readme

```markdown
With this theme you can remove the buttons for minimizing, maximizing or closing a window individually.
You can still perform these actions by pressing Alt + Space.
```

### Preferences

```json
{
  "uc.my-preference.hide-minimize": "Hide the minimize window button",
  "uc.my-preference.hide-maximize": "Hide the maximize window button",
  "uc.my-preference.hide-close": "Hide the close window button"
}
```
