### ISSUE TITLE
[create-theme]: Floating findbar

### ISSUE THREAD

**Issue by anaarkei** [zen-browser/theme-store#425]
### Name

Floating findbar

### Description

Mod for Zen Browser that detaches findbar from edge of browser window so that it appears to float. 

### Homepage

https://github.com/anaarkei/zen-floating-findbar

### Image

https://beta.jarick.works/zen-floating-findbar.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
.browserContainer > findbar {
  position: fixed;
  bottom: 0px;
  margin-bottom: var(--zen-element-separation);
  margin-left: var(--zen-element-separation);
  margin-right: var(--zen-element-separation);
  background: var(--zen-colors-tertiary) !important;
  border-radius: var(--zen-border-radius);
  width: calc( 100% - var(--zen-element-separation) * 2);
}

.browserContainer > findbar,
.findbar-textbox {
  border: 1px solid var(--zen-colors-border) !important;
}

/* Enable compact findbar, similar to Smaller Compact Mode by n7itro */
@media (-moz-bool-pref: "uc.floatingfindbar.compact.enabled") {
  .browserContainer > findbar {
    width: 75vw !important;
    margin-left: calc( 12.5vw - var(--zen-element-separation) ) !important;
  }
}
```

### Readme

```markdown
# zen-floating-findbar
Mod for Zen Browser that detaches findbar from edge of browser window so that it appears to float. 

## Options
- Enable compact toolbar, similar to Smaller Compact Mode by n7itro.
```

### Preferences

```json
{
    "uc.floatingfindbar.compact.enabled": "Enable compact findbar, similar to Smaller Compact Mode by n7itro"
}
```
