### ISSUE TITLE
[create-theme]: New Tab button at bottom

### ISSUE THREAD

**Issue by anikthink** [zen-browser/theme-store#427]
### Name

New Tab button at bottom

### Description

Moves the new tab button to the bottom of the vertical tabs list.

### Image

https://imgur.com/a/gGrTXN0

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
/* Move new tab button to the bottom */
#newtab-button-container {
  position: absolute;
  bottom: 0;
  width: 100%;
  margin: 4px 0 !important;
}
```

### Readme

```markdown
Moves the new tab button to the bottom of the vertical tabs list.

This is more intuitive than the default position because new tabs are added at the bottom.
```
