### ISSUE TITLE
[create-theme]: New Tab button stickied at bottom

### ISSUE THREAD

**Issue by anikthink** [zen-browser/theme-store#428]
### Name

New Tab button stickied at bottom

### Description

Fixes the new tab button to the bottom of the vertical tabs list container.

### Homepage

https://i.imgur.com/hoG04O2.png

### Image

https://i.imgur.com/hoG04O2.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
/* Fix new tab button to the bottom */
#newtab-button-container {
  position: absolute;
  bottom: 0;
  width: 100%;
  margin: 4px 0 !important;
}
```

### Readme

```markdown
Moves the new tab button to the bottom of the vertical tabs list.

This is more intuitive than the default position because new tabs are added at the bottom.
```
