### ISSUE TITLE
[create-theme]: Matcha

### ISSUE THREAD

**Issue by KiKaraage** [zen-browser/theme-store#432]
### Name

Matcha

### Description

Sweet and peaceful vibrant theme, supported light and dark mode

### Homepage

https://github.com/KiKaraage/ZenMods

### Image

https://i.imgur.com/n5RdTGA.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@media (prefers-color-scheme: dark) {
  :root {
    --zen-colors-primary: #437030 !important;
    --zen-colors-secondary: #407A27 !important;
    --zen-colors-tertiary: #14210E !important;
    --zen-colors-border: #2B471F !important;
    --zen-primary-color: #407A27 !important;
    --zen-dialog-background: #0D160A !important;
    --toolbarbutton-icon-fill: color-mix(in srgb, var(--zen-primary-color) 70%, white 30%) !important;
    --toolbar-field-color: color-mix(in srgb, var(--zen-primary-color) 40%, white 60%) !important;
    .tabbrowser-tab { color: #ADC694 !important; }
    .tabbrowser-tab:is([visuallyselected], [multiselected]) { color: #EDFFE5 !important; }
  }
}

@media (prefers-color-scheme: light) {
  :root {
    --zen-colors-primary: #437030 !important;
    --zen-colors-secondary: #73C351 !important;
    --zen-colors-tertiary: #D8FAB5 !important;
    --zen-colors-border: #68B647 !important;
    --zen-primary-color: #73C351 !important;
    --zen-dialog-background: #F1FAE7 !important;
    --toolbarbutton-icon-fill: color-mix(in srgb, var(--zen-primary-color) 70%, black 30%) !important;
    --toolbar-field-color: color-mix(in srgb, var(--zen-primary-color) 40%, black 60%) !important;
    .tabbrowser-tab { color: #2B5718 !important; }
    .tabbrowser-tab:is([visuallyselected], [multiselected]) { color: #0A1F00 !important; }
  }
}
```

### Readme

```markdown
Sweet peaceful theme based on green tea aesthetics, supported all Zen theming mode (Light, Dark, Zen Dream and Zen Galaxy).

[Star the repo](https://github.com/KiKaraage/ZenMods) if you appreciate this theme!
```
