### ISSUE TITLE
Zen Minimal Exit Menu theme compatibility update

### ISSUE THREAD

**Issue by Dinno-DEV** [zen-browser/theme-store#436]
Makes the exit menu color follows the browser's border color.

previous:
```css
.titlebar-button {
    padding: 0px !important;
    min-height: 13px !important;
    min-width: 13px !important;
    align-self: center;
    background-color: hsl(0, 0%, 20%) !important;
    margin-left: 5px !important;
    border-radius: 50px;
    transition: all 100ms;
}
```

new:
```css
.titlebar-button {
    padding: 0px !important;
    min-height: 13px !important;
    min-width: 13px !important;
    align-self: center;
    background-color: var(--zen-colors-border) !important;
    margin-left: 5px !important;
    border-radius: 50px;
    transition: all 100ms;
}
```
