### ISSUE TITLE
[create-theme]: Floating Compact Sidebar

### ISSUE THREAD

**Issue by Hypatech** [zen-browser/theme-store#450]
### Name

Floating Compact Sidebar

### Description

Modifies the sidebar in compact mode to not overlap with the edges of the window.

### Image

https://imgur.com/a/JIcrMBL

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@media (-moz-bool-pref: "zen.view.compact") {
    :root:not([customizing]) {
        --separation: calc(var(--zen-element-separation) + 1px);
        
        --margin: 7px;
        
        --horiz-padding: 10px;
        --vert-padding: 5px;
        @media (-moz-bool-pref: "zen.view.compact.hide-tabbar") {
            & #navigator-toolbox{
                position: absolute !important;
                left: 0 !important;
                padding-right: var(--horiz-padding) !important;
                padding-left: calc(var(--margin) + calc(var(--separation) + var(--horiz-padding))) !important;
                padding-top: calc(var(--vert-padding) + var(--margin)) !important;
                padding-bottom: calc(var(--vert-padding) + var(--margin)) !important;
                top: 1px !important;
                bottom: var(--separation) !important;
                height: auto !important;
                border: none !important;
                box-shadow: none !important;

                
                background: none !important;
                min-width: calc(calc(calc(var(--horiz-padding) * 2) + var(--zen-toolbox-max-width)) + var(--margin)) !important;
                
                transform: translate3d(-90%, 0, 0) !important;
            }
            
            & #navigator-toolbox[zen-expanded]{
                min-width: 250px !important;                
            }
            
            & #navigator-toolbox::before{
                content: "" !important;
                position: absolute !important;
                top: var(--margin) !important;
                bottom: var(--margin) !important;
                left: calc(var(--separation) + var(--margin)) !important;
                right: 0 !important;
                
                background: var(--zen-themed-toolbar-bg) !important;
                border-radius: var(--zen-border-radius) !important;
                box-shadow: 15px -10px 20px -20px black !important;
                border: none;
               
                
            }
            
               & #navigator-toolbox:hover, & #navigator-toolbox[zen-has-hover], & #navigator-toolbox:focus-within, & #navigator-toolbox[zen-user-show], & #navigator-toolbox[flash-popup], & #navigator-toolbox[has-popup-menu], & #navigator-toolbox[movingtab], & #mainPopupSet:has(> #appMenu-popup:hover) ~ toolbox, & #navigator-toolbox:has(.tabbrowser-tab:active), & #navigator-toolbox:has([open="true"]:not(tab):not(#zen-sidepanel-button)){
                transform: translate3d(0, 0, 0) !important;
            }
        }
    }
}
```

### Readme

```markdown
Modifies the sidebar in compact mode to not overlap with the edges of the window.

No preferences as of yet, but will add some to adjust margins in the future.
```
