### ISSUE TITLE
[create-theme]: Minimarks

### ISSUE THREAD

**Issue by ben4ali** [zen-browser/theme-store#458]
### Name

Minimarks

### Description

A compact bookmark extension that only displays the icon of the bookmark. 

### Homepage

https://github.com/ben4ali/Zen-Minimarks

### Image

https://github.com/ben4ali/Zen-Minimarks/blob/main/Sample.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#PersonalToolbar {
    margin-left: 4rem;
}
#PersonalToolbar .bookmark-item {
    display: flex !important; 
    justify-content: start !important;
    align-items: center !important;
    width: 2rem !important;
    transition: 0.25s !important;
    padding-right: 1rem !important;
}
#PersonalToolbar .bookmark-item:hover{
    width: 10rem !important;
}
```

### Readme

```markdown
# Minimarks Extension

## Overview
The Minimark Extension provides a minimalist experience by displaying only the icons of your bookmarks. The bookmark titles are shown on hover, keeping your browser interface clean and uncluttered.

Enjoy a cleaner browsing experience with Minimarks!

## What does it do
This theme does:
  - Displays only the icons of the bookmarks
  - Displays the bookmark title on hover

Preview: 

  ![alt text](https://github.com/ben4ali/Zen-Compact-Bookmarks/blob/main/Sample.png)

## License
This project is licensed under the MIT License.
```
