### ISSUE TITLE
[create-theme]: Remove browser padding

### ISSUE THREAD

**Issue by mauro-balades** [zen-browser/theme-store#46]
### Name

Remove Browser Padding

### Description

Remove the right and bottom paddings of the browser views on zen!

### Homepage

https://github.com/zen-browser/theme-components

### Image

https://i.imgur.com/kifJNaA.png

### Theme Styles

```css
#tabbrowser-tabpanels {
    & .browserSidebarContainer:not([zen-split="true"]) {
        --zen-browser-border-radius: var(--zen-border-radius) 0 0 0;
        --zen-element-separation: 0;
    }
}
```

### Readme

```markdown
# No browser padding

Another official theme done by Zen's team. Many people requested this feature inside Zen, and now they have it, thanks to this theme!

## What does it do?

It removes the right and bottom margins and border radius of the browser's view, creating a more compact experience for those who want it.

* This theme is intentionally done so that it doesn't apply for split views as it would look a bit weird!

Please submit any issues related to this theme [here](https://github.com/zen-browser/theme-components/issues) instead of Zen's desktop repository.

Hope you like it!
```
