### ISSUE TITLE
[create-theme]: Container Tab Theme

### ISSUE THREAD

**Issue by ocean-mars** [zen-browser/theme-store#466]
### Name

Container Tab Theme

### Description

Changes the default container tab theme

### Homepage

https://github.com/ocean-mars/things

### Image

https://github.com/ocean-mars/things/blob/main/Zen%20Themes/Container%20Tab%20Theme/preview.png?raw=true

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
.tab-context-line{display: none !important;}
#tabbrowser-tabs { & .tabbrowser-tab { &[selected] .tab-background { border: 2px solid var(--identity-icon-color) !important; opacity: 0.8 !important;}}}
```

### Readme

```markdown
Changes the default left sided container color from tabs.
```
