### ISSUE TITLE
[create-theme]: Floating Status Bar

### ISSUE THREAD

**Issue by AmirhBeigi** [zen-browser/theme-store#469]
### Name

Floating Status Bar

### Description

Mod for Zen Browser that detaches the status bar from the bottom left corner of the browser window.

### Homepage

https://github.com/AmirhBeigi/zen-floating-statusbar/

### Image

https://raw.githubusercontent.com/AmirhBeigi/zen-floating-statusbar/refs/heads/main/screenShot.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#statuspanel {
  margin: 10px !important;
}

#statuspanel-label {
  border-radius: 10000px !important;
  padding: 2px 10px !important;
  border: 1px solid var(--zen-colors-border) !important;
  background: var(--zen-colors-tertiary) !important;
}
```

### Readme

```markdown
# Zen Floating Statusbar
Mod for Zen Browser that detaches the status bar from the bottom left corner of the browser window so that it appears to float.
```
