### ISSUE TITLE
[create-theme]: Floating tab bar

### ISSUE THREAD

**Issue by anaarkei** [zen-browser/theme-store#471]
### Name

Floating tab bar

### Description

Mod for Zen Browser that detaches tab bar from edge of browser window so that it appears to float. 

### Homepage

https://github.com/anaarkei/zen-floating-tabbar

### Image

https://beta.jarick.works/zen-floating-tabbar.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#navigator-toolbox {
  --zen-toolbox-max-width: 74px !important;
  background: none !important;
  border: none !important;
  box-shadow: none !important;
  height: 100vh !important;
  padding: 0 !important;
  min-width: calc(var(--zen-toolbox-max-width) + var(--zen-toolbox-padding) + var(--zen-element-separation)) !important;
}

#titlebar {
  border-radius: var(--zen-border-radius) !important;
  border: 1px solid var(--zen-colors-border) !important;
  background: var(--zen-colors-tertiary) !important;
  margin: calc( var(--zen-element-separation) * 2 );
  padding: var(--zen-element-separation);
}

/* Increase space around edge of browser window and tab bar */
@media (-moz-bool-pref: "uc.floatingtabbar.increase.spacing") {
  #main-window {
    --zen-element-separation: 10px !important;
  }
  #titlebar {
    padding: calc( var(--zen-element-separation) / 2 );
  }
}

/* Enable compact tab bar, similar to Smaller Compact Mode by n7itro */
@media (-moz-bool-pref: "uc.floatingtabbar.compact.enabled") {
  #titlebar {
    height: 75vh !important;
    margin-top: 12.5vh !important;
  }
}
```

### Readme

```markdown
# zen-floating-tabbar
Detaches tab bar from edge of browser window so that it appears to float. 

## Options
- Increase space around edge of browser window and tab bar; and
- Enable compact tab bar, similar to Smaller Compact Mode by n7itro.

## Requires
- Compact mode to be enabled; and
- Side tab bar to be hidden.
```

### Preferences

```json
{
  "uc.floatingtabbar.increase.spacing": "Increase space around edge of browser window and tab bar",
  "uc.floatingtabbar.compact.enabled": "Enable compact tab bar, similar to Smaller Compact Mode by n7itro"
}
```
