### ISSUE TITLE
[create-theme]: Monochrome

### ISSUE THREAD

**Issue by antonsizikov** [zen-browser/theme-store#481]
### Name

Monochrome

### Description

There is no monochrome option in theme settings, so i created this theme.

### Homepage

https://github.com/antonsizikov/zen-browser-monochrome-theme

### Image

https://raw.githubusercontent.com/antonsizikov/zen-browser-monochrome-theme/refs/heads/main/image.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
:root {
    --zen-primary-color: #808080 !important;
}

@media not (prefers-color-scheme: dark) {
    :root {
        --zen-colors-primary: #D2D2D2 !important;
        --zen-colors-secondary: #D2D2D2 !important;
        --zen-colors-tertiary: #FFFFFF !important;
        --zen-colors-border: #DDDDDD !important;
    }
}

@media (prefers-color-scheme: dark) {
    :root {
        --zen-colors-primary: #373737 !important;
        --zen-colors-secondary: #373737 !important;
        --zen-colors-tertiary: #171717 !important;
        --zen-colors-border: #202020 !important;
    }
}
```

### Readme

```markdown
# Monochrome theme for [Zen Browser](https://github.com/zen-browser/desktop)

There is no monochrome option in theme settings, so i created this theme.

- No distracting colours, only grayscale.
- No outline border on tabs.
- Window outline border slightly dimmed.
- Supports Light and Dark mode.
```
