### ISSUE TITLE
[create-theme]: Wider Zen Sidebar

### ISSUE THREAD

**Issue by Axenide** [zen-browser/theme-store#483]
### Name

Wider Zen Sidebar

### Description

This theme let's you expand the Zen Sidebar even more!

### Image

https://i.imgur.com/gBbXG7i.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#zen-sidebar-web-panel {
  max-width: 1000px !important;
}
```

### Readme

```markdown
# Wider Zen Sidebar
This theme let's you expand the Zen Sidebar even more!
![](https://i.imgur.com/gBbXG7i.png)
```
