### ISSUE TITLE
[create-theme]: Use Firefox Theme

### ISSUE THREAD

**Issue by Spatulox** [zen-browser/theme-store#487]
### Name

Use Firefox Theme

### Description

This Zen Browser addon let you use the Firefox themes from the Firefox store.

### Homepage

https://github.com/Spatulox/Use-FireFox-Theme

### Image

https://raw.githubusercontent.com/Spatulox/Use-FireFox-Theme/refs/heads/main/image.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@media {
  #zen-appcontent-navbar-container {
    background: var(--lwt-header-image, var(--lwt-additional-images))
                no-repeat var(--lwt-background-tiling) var(--lwt-background-alignment)
                var(--lwt-accent-color) !important;
    background-size: var(--lwt-background-tiling) !important;
    background-position-y: var(--theme-firefoxtheme-heightmove, 50%) !important;
  }
}
```

### Readme

```markdown
# Use Firefox Theme
This Zen Browser addon let you use the Firefox themes from the Firefox store.
Check the mod settings to adjust the height (% or px) of the background 😉.

Works with most of the available background on the Firefox addons store
```

### Preferences

```json
[
    {
        "property": "theme.firefoxtheme.heightmove",
        "label": "Move up the theme if needed (pixel or %)",
        "type": "string",
        "defaultValue": "50%",
        "placeholder": "e.g: 50px / 50%",
        "disabledOn": []
    }
]
```
