### ISSUE TITLE
[create-theme]: zen-11

### ISSUE THREAD

**Issue by Alexcoder5** [zen-browser/theme-store#49]
### Name

zen11

### Description

Costomize  your Zen experience. 

### Theme Styles

```css
/* Hide Window Control Buttons on Mac */
@media (-moz-bool-pref: "uc.theme.hide-window-control-mac.enabled") {
    .titlebar-buttonbox-container {
        display: none
    }
}

/* Hide Folder Icons in Bookmarks */
@media (-moz-bool-pref: "uc.theme.hide-bookmarks-folder-icons.enabled") {
    .bookmark-item>image:not([src]) {
        display: none;
    }
}

/* Remove forward button */
@media (-moz-bool-pref: "uc.remove-forward-btn.enabled") {
    #forward-button {
        display: none !important;
    }
}

/* Make Web Sidebar Compact */
@media (-moz-bool-pref: "uc.theme.compact-web-sidebar.enabled") {
    #zen-sidebar-web-header {
        min-height: 38px !important;
    }

    #zen-sidebar-web-header toolbarbutton image {
        height: 24px !important;
        width: 24px !important;
    }

    #zen-sidebar-panels-wrapper {
        min-height: 42px !important;
        border: none !important;
    }
}

/* Compact Tab Tar */
@media (-moz-bool-pref: "uc.theme.compact-tab-bar.enabled") {
    .tabbrowser-tab {
        margin-bottom: 2px !important;
        min-height: unset !important;
        border: none !important;
    }

    #tabs-newtab-button {
        height: unset !important;
    }
}

/* Hide New Tab Button */
@media (-moz-bool-pref: "uc.theme.hide-new-tab-btn.enabled") {
    #tabs-newtab-button {
        display: none !important;
    }
}


/* Fix expand sidebar */
#zen-expand-sidebar-button {
    display: flex !important;
    justify-content: center !important;
    align-items: center !important;
}

/* Remove Double bg on hover */
#zen-sidebar-icons-wrapper>toolbarbutton>image {
    background: none !important;
}
```

### Readme

```markdown
# Customize Your Zen

## Go to Settings -> Look and Feel -> Theme Settings to customize Zen browser

### What you can enable

1. Hide Window Control Buttons on Mac
2. Hide Folder Icons in Bookmarks
3. Remove forward button
4. Make Web Sidebar Compact
5. Compact Tab Tar
6. Hide New Tab Button
7. Enable dark background
```

### Preferences

```json
{
    "uc.theme.hide-window-control-mac.enabled": "Hide Window Control Buttons on Mac",
    "uc.theme.hide-bookmarks-folder-icons": "Hide Folder Icons in Bookmarks",
    "uc.remove-forward-btn.enabled": "Remove forward button",
    "uc.theme.compact-web-sidebar.enabled": "Make Web Sidebar Compact",
    "uc.theme.compact-tab-bar.enabled": "Compact Tab Tar",
    "uc.theme.hide-new-tab-btn.enabled": "Hide New Tab Button",
    "uc.theme.dark-background.enabled": "Enable dark background",
}
```
