### ISSUE TITLE
[create-theme]: 

### ISSUE THREAD

**Issue by BrunoPoiano** [zen-browser/theme-store#490]
### Name

Better Tab Highlight

### Description

Adds a soft border to the collapsed tabs

### Homepage

https://github.com/BrunoPoiano/zen-browser-dark-theme-tab-highlight

### Image

https://imgur.com/a/e3CEeGl

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@media (-moz-bool-pref: "zen.tabs.vertical") {
  #navigator-toolbox:not(
      #navigator-toolbox:is(
          #navigator-toolbox[zen-user-hover="true"][zen-has-hover],
          #navigator-toolbox[zen-user-hover="true"]:focus-within,
          #navigator-toolbox[zen-user-hover="true"][movingtab],
          #navigator-toolbox[zen-user-hover="true"][flash-popup],
          #navigator-toolbox[zen-user-hover="true"][has-popup-menu],
          #navigator-toolbox[zen-user-hover="true"]:has(
              [open="true"]:not(tab):not(#zen-sidepanel-button)
            ),
          #navigator-toolbox[zen-expanded="true"]:not([zen-user-hover="true"])
        )
    ) {
    & #tabbrowser-tabs {
      & .tabbrowser-tab {
        --new-border-color: color-mix(
          in oklab,
          var(--zen-colors-border) 80%,
          white
        );
        border: 1px solid var(--new-border-color) !important;
        margin-bottom: 5px !important;
      }
    }
  }
}
```

### Readme

```markdown
# Better Tab Highlight For Dark Themes

Adds a soft border to the collapsed tabs.
```
