### ISSUE TITLE
[create-theme]: Bigger Mute Button

### ISSUE THREAD

**Issue by jvabn** [zen-browser/theme-store#493]
### Name

Bigger Mute Button

### Description

Increases size of mute button and hides the tab's sound labels. The tab icon is replaced by the mute button if the tabs are not expanded.

### Homepage

https://github.com/jvabn/zenbrowser-themes

### Image

https://i.imgur.com/jsbpSqJ.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
.tab-icon-overlay {
  opacity: 1 !important;
  margin: initial !important;
  margin-right: 32px !important;
  transform: translate(160%, 0%) scale(1.6) !important;
  color: light-dark(black, white) !important;
  background-color: transparent !important;
  transition: 0.3s !important;
}

.tab-icon-overlay:hover {
  color: var(--zen-primary-color) !important;
  transition: 0.3s !important;
}

.tab-icon-overlay:is([soundplaying], [muted]):not([selected]) {
  display: block !important;
}

/* Hide sound labels */
.tab-icon-sound-label, 
.tab-icon-sound-playing-label {
  display: none !important;
}

/* Mute button takes place of tab icon when tabs are not expanded */
@media not (-moz-bool-pref: "zen.view.sidebar-expanded") {
  .tab-icon-overlay {
    margin: auto 30px !important;
    transform: scale(1.6) !important;
  }
}
```

### Readme

```markdown
# Bigger Mute Button
**Description:** 
- Increases size of mute button and hides the tab's sound labels. 
- The tab icon is replaced by the mute button if the tabs are not expanded.
```
