### ISSUE TITLE
[create-theme]: NoHighlightSplit

### ISSUE THREAD

**Issue by JtdeGraaf** [zen-browser/theme-store#506]
### Name

https://raw.githubusercontent.com/JtdeGraaf/zen-remove-split-view-tab-highlight/363d18ad227f06f345e28b04d15613b72eaa9ab6/300x400.png

### Description

Removes the border highlight around the active tab while using split view.

### Homepage

https://github.com/JtdeGraaf/zen-remove-split-view-tab-highlight

### Image

https://raw.githubusercontent.com/JtdeGraaf/zen-remove-split-view-tab-highlight/363d18ad227f06f345e28b04d15613b72eaa9ab6/300x400.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#tabbrowser-tabpanels[zen-split-view='true'] .browserSidebarContainer[zen-split-active='true'] {
    --uc-tweak-rounded-corners-shadow-color: var(--zen-colors-border) !important;
}
```

### Readme

```markdown
# zen-remove-split-view-tab-highlight

Mod for Zen Browser that removes the border highlight on the active tab in split view.

**Before:**

![With border highlight](https://raw.githubusercontent.com/JtdeGraaf/zen-remove-split-view-tab-highlight/20cc46e4acee3f95da0cab568331e953ec22a09f/withborderhighlight.png)

**After:**

![Without border highlight](https://raw.githubusercontent.com/JtdeGraaf/zen-remove-split-view-tab-highlight/20cc46e4acee3f95da0cab568331e953ec22a09f/withoutborderhighlight.png)
```
