### ISSUE TITLE
[create-theme]: Right On Hover Sidebar

### ISSUE THREAD

**Issue by p2d0** [zen-browser/theme-store#509]
### Name

Right On Hover Sidebar

### Description

Web Panels sidebar that popups on hover on the right (like compact mode)

### Image

https://puu.sh/Kg3ie/1f0719765e.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#zen-sidebar-web-panel:not([pinned="true"]) {
    width: var(--uc-right_on_hover_sidebar-width)!important;
}

#zen-sidebar-web-panel-wrapper:not(:has(#zen-sidebar-web-panel[pinned="true"])) {
    transition: all 0.2s ease-in-out!important;
    height: 100%;
    z-index: 1;
    opacity: 0;
    width: var(--uc-right_on_hover_sidebar-width);
    position:absolute!important;
    right: calc(0px - var(--uc-right_on_hover_sidebar-width) + var(--uc-right_on_hover_sidebar-hover_width));
    top: 0;
    &:hover {
        opacity: 1;
        transform: translateX(var(--zen-element-separation));
        right:0;
    }
    @media (-moz-bool-pref: "uc.right_on_hover_sidebar.stay_on_focus") {
        &:focus-within {
            opacity: 1;
            transform: translateX(var(--zen-element-separation));
            right:0;
        }
    }
}
```

### Readme

```markdown
# Right On Hover Sidebar

Web Panels sidebar that popups on hover on the right (like compact mode)

## Options

- Stay on focus
- Set sidebar width
- Set sidebar hover trigger width
```

### Preferences

```json
[
    {
        "property": "uc.right_on_hover_sidebar.stay_on_focus",
        "label": "Stay on focus",
        "type": "checkbox",
        "disabledOn": []
    },
    {
        "property": "uc.right_on_hover_sidebar.width",
        "label": "Set sidebar width",
        "type": "string",
        "defaultValue": "300px"
    },
    {
        "property": "uc.right_on_hover_sidebar.hover_width",
        "label": "Set sidebar hover trigger width",
        "type": "string",
        "defaultValue": "2px"
    }
]
```
