### ISSUE TITLE
[create-theme]: Disable Rounded Corners

### ISSUE THREAD

**Issue by gunir** [zen-browser/theme-store#53]
### Name

Disable Rounded Corners

### Description

Disable Rounded Corners from Web View.

### Homepage

https://github.com/gunir/desktop/tree/themes/themes

### Image

https://raw.githubusercontent.com/gunir/desktop/themes/themes/disable_rounded_corners.png

### Theme Styles

```css
:root .browserSidebarContainer {
    margin: unset!important;
    box-shadow: unset!important;
    clip-path: unset!important;
    border-radius: unset!important;
    overflow: unset!important;
}
```

### Readme

```markdown
Disable Zen's Rounded Corners, just install and enjoy!
```
