### ISSUE TITLE
[create-theme]: Beach

### ISSUE THREAD

**Issue by feco** [zen-browser/theme-store#532]
### Name

Beach warmth

### Description

Get some summer vibes with this beach theme

### Homepage

https://github.com/feco/zen-beach

### Image

https://github.com/feco/zen-beach/blob/main/thumbnail.png?raw=true

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#zen-main-app-wrapper {
    background-image: linear-gradient(to bottom, #eed296, #96B2EE) !important;
}

#appMenu-mainView {
    background-image: linear-gradient(#eed296, #96B2EE) !important;
}

#appmenu-moreTools {
    background-image: linear-gradient(#eed296, #96B2EE) !important;
}

#PanelUI-button {
    --button-active-bgcolor: black !important;
}

html#main-window {
    --lwt-text-color: #4a4948 !important;
}
```

### Readme

```markdown
# zen-beach
A theme around beach vibes for Zen-browser
Click install and you are ready to go!
```
