### ISSUE TITLE
[create-theme]: Rosé Pine Dawn theme

### ISSUE THREAD

**Issue by feco** [zen-browser/theme-store#534]
### Name

Rosé Pine Dawn

### Description

Minimalist, pine, freshness for your browser!

### Homepage

https://github.com/feco/zen-rose-pine-dawn

### Image

https://github.com/feco/zen-rose-pine-dawn/blob/main/thumbnail.png?raw=true

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#zen-main-app-wrapper {
    background-color: #faf4ed !important;
}

#appMenu-mainView {
    background-color: #f2e9e1 !important;
}

#appmenu-moreTools {
    background-color: #f2e9e1 !important;
}

#PanelUI-button {
    --button-active-bgcolor: black !important;
}

html#main-window {
    --lwt-text-color: #575279 !important;
    --toolbarbutton-icon-fill: #b4637a !important;
    --toolbar-field-color: #286983 !important;
}
```

### Readme

```markdown
# Zen Rosé Pine Dawn
A theme around the Rosé Pine Dawn colors for the Zen-browser.
Click install and enjoy!
```
