### ISSUE TITLE
[create-theme]: Zen Context Menu

### ISSUE THREAD

**Issue by KiKaraage** [zen-browser/theme-store#537]
### Name

Zen Context Menu

### Description

Declutter your right click menu, hide options you don't need

### Homepage

https://github.com/KiKaraage/ZenMods/

### Image

https://i.imgur.com/H5LwTMJ.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
/* Only use “Copy Link Without Site Tracking” */
@media (-moz-bool-pref: "uc.hidecontext.copylink") {
  #context-copylink {
    display: none !important;
  }
}
/* Hide "Menu Bar" toggle */
@media (-moz-bool-pref: "uc.hidecontext.menubar") {
  #toggle_toolbar-menubar {
    display: none !important;
  }
}
/* Hide "Bookmark Tab/Link” */
@media (-moz-bool-pref: "uc.hidecontext.bookmark") {
  #toolbar-context-bookmarkSelectedTab, 
  #toolbar-context-bookmarkSelectedTabs,
  #context_bookmarkTab,
  #context-bookmarklink {
    display: none !important;
  }
}
/* Hide “Open Tab/Link in New Container Tab” */
@media (-moz-bool-pref: "uc.hidecontext.newcontainer") {
  #context_reopenInContainer,
  #context-openlinkinusercontext-menu {
    display: none !important;
  }
}
/* Hide “Send Tab/Link to Device” */
@media (-moz-bool-pref: "uc.hidecontext.sendtodevice") {
  #context_sendTabToDevice,
  #context-sendpagetodevice,
  #context-sendlinktodevice,
  #context-sep-sendlinktodevice {
    display: none !important;
  }
}
/* Hide “Search Keywords" with your preferred search engine */
@media (-moz-bool-pref: "uc.hidecontext.search") {
  #context-searchselect {
    display: none !important;
  }
}
/* Hide “Search Keywords in a Private Window” */
@media (-moz-bool-pref: "uc.hidecontext.searchinpriv") {
  #context-searchselect-private {
    display: none !important;
  }
}
/* Hide Firefox's "Translate Selection/Link" options */
@media (-moz-bool-pref: "uc.hidecontext.translate") {
  #context-translate-selection,
  #frame-sep {
    display: none !important;
  }
}
/* Hide “Email Image”, “Set Image as Desktop Background”, and “View Image Info” options */
@media (-moz-bool-pref: "uc.hidecontext.image") {
  #context-saveimage,
  #context-sep-setbackground,
  #context-setDesktopBackground,
  #context-sep-sharing,
  #context-viewimageinfo {
    display: none !important;
  }
}
/* Hide “Select All Text” option */
@media (-moz-bool-pref: "uc.hidecontext.selectalltext") {
  #context-selectall {
    display: none !important;
  }
}
/* Hide “Select All Tabs" option */
@media (-moz-bool-pref: "uc.hidecontext.selectalltabs") {
  #context_selectAllTabs,
  #toolbar-context-selectAllTabs {
    display: none !important;
  }
}
/* Hide “Reload Tab” option */
@media (-moz-bool-pref: "uc.hidecontext.reloadtab") {
  #context_reloadTab,
  #toolbar-context-reloadSelectedTab,
  #toolbar-context-reloadSelectedTabs {
    display: none !important;
  }
}
/* Hide “Tab Unloader Actions” */
@media (-moz-bool-pref: "uc.hidecontext.unloadactions") {
  #context_zenTabActions {
    display: none !important;
  }
}
/* Hide “View Page Source” and “Inspect” options */
@media (-moz-bool-pref: "uc.hidecontext.inspect") {
  #context-viewsource,
  #context-inspect-a11y,
  #context-inspect,
  #context-media-eme-separator {
    display: none !important;
  }
}
/* Hide “Save Link As” */
@media (-moz-bool-pref: "uc.hidecontext.savelink") {
  #context-savelink {
    display: none !important;
  }
}
/* Hide "Take Screenshot" option */
@media (-moz-bool-pref: "uc.hidecontext.screenshot") {
  #context-take-screenshot,
  #context-sep-screenshots,
  #frame-sep {
    display: none !important;
  }
}
```

### Readme

```markdown
What can you do with this Mod:
- Only use “Copy Link Without Site Tracking”
- Hide "Menu Bar" toggle
- Hide "Bookmark Tab/Link”
- Hide “Open Tab/Link in New Container Tab”
- Hide “Send Tab/Link to Device”
- Hide “Search Keywords" with your preferred search engine
- Hide “Search Keywords in a Private Window”
- Hide Firefox's "Translate Selection/Link" options
- Hide “Email Image”, “Set Image as Desktop Background”, and “View Image Info” options
- Hide “Select All Text” option
- Hide “Select All Tabs” option
- Hide “Reload Tab” option
- Hide “Tab Unloader Actions”
- Hide “View Page Source” and “Inspect” options
- Hide “Save Link As”
- Hide “Take Screenshot” option

Go to Settings, Zen Mods, look up "Zen Context Menu", click the gear ⚙️ button, and check your desired preferences.

[Star the repo](https://github.com/KiKaraage/ZenMods/) if you appreciate this Mod!
```

### Preferences

```json
[
  {
    "property": "uc.hidecontext.copylink",
    "label": "Only use 'Copy Link Without Site Tracking'",
    "type": "checkbox"
  },
  {
    "property": "uc.hidecontext.menubar",
    "label": "Hide 'Menu Bar' toggle",
    "type": "checkbox"
  },
  {
    "property": "uc.hidecontext.bookmark",
    "label": "Hide 'Bookmark Tab/Link'",
    "type": "checkbox"
  },
  {
    "property": "uc.hidecontext.newcontainer",
    "label": "Hide 'Open Tab/Link in New Container Tab'",
    "type": "checkbox"
  },
  {
    "property": "uc.hidecontext.sendtodevice",
    "label": "Hide 'Send Tab/Link to Device'",
    "type": "checkbox"
  },
  {
    "property": "uc.hidecontext.search",
    "label": "Hide 'Search Keywords' with your preferred search engine",
    "type": "checkbox"
  },
  {
    "property": "uc.hidecontext.searchinpriv",
    "label": "Hide 'Search Keywords in a Private Window'",
    "type": "checkbox"
  },
  {
    "property": "uc.hidecontext.translate",
    "label": "Hide Firefox's 'Translate Selection/Link' options",
    "type": "checkbox"
  },
  {
    "property": "uc.hidecontext.image",
    "label": "Hide 'Email Image', 'Set Image as Desktop Background', and 'View Image Info' options",
    "type": "checkbox"
  },
  {
    "property": "uc.hidecontext.selectalltext",
    "label": "Hide 'Select All Text' option",
    "type": "checkbox"
  },
  {
    "property": "uc.hidecontext.selectalltabs",
    "label": "Hide 'Select All Tabs' option",
    "type": "checkbox"
  },
  {
    "property": "uc.hidecontext.reloadtab",
    "label": "Hide 'Reload Tab' option",
    "type": "checkbox"
  },
  {
    "property": "uc.hidecontext.unloadactions",
    "label": "Hide 'Tab Unloader Actions'",
    "type": "checkbox"
  },
  {
    "property": "uc.hidecontext.inspect",
    "label": "Hide 'View Page Source' and 'Inspect' options",
    "type": "checkbox"
    },
  {
    "property": "uc.hidecontext.savelink",
    "label": "Hide 'Save Link As'",
    "type": "checkbox"
  },
  {
    "property": "uc.hidecontext.screenshot",
    "label": "Hide 'Take Screenshot' option",
    "type": "checkbox"
  }
]
```
