### ISSUE TITLE
[create-theme]: Only Close On Hover

### ISSUE THREAD

**Issue by p-sw** [zen-browser/theme-store#541]
### Name

Only Close On Hover

### Description

Show tab's close button only on hover, even on the active tab.

### Image

https://i.ibb.co/8K0rY8p/asdf.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#tabbrowser-tabs .tabbrowser-tab:not([pinned]):is([visuallyselected]):not(:hover) .tab-close-button {
    display: none !important;
}
```

### Readme

```markdown
Show tab's close button only on hover, even on the active tab.
Zen browser always show the close button on the active tab by default, and this theme will disable that behavior and make close button on the active tab only visible on hover.
```
