### ISSUE TITLE
[create-theme]: Better Unloaded Tabs

### ISSUE THREAD

**Issue by Felkazz** [zen-browser/theme-store#551]
### Name

Better Unloaded Tabs

### Description

Makes unloaded tabs easier to notice by making them greyscale and transparent.

### Homepage

https://github.com/Felkazz/zen-browser-better-unloaded-tabs

### Image

https://i.imgur.com/LxBTTmQ.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
.tabbrowser-tab[pending="true"] {
    filter: grayscale(1);
    opacity: 0.5;
}
```

### Readme

```markdown
# zen-browser-better-unloaded-tabs
Makes unloaded tabs easier to notice by making them grayscale and transparent.
```
