### ISSUE TITLE
[create-theme]: Better Better Active Tab

### ISSUE THREAD

**Issue by bridgebucket** [zen-browser/theme-store#556]
### Name

Better Better Active Tab

### Description

A fork of HliasOuzounis' Better Active Tab which makes the indicator more consistent with existing Zen UI design :-)

### Homepage

https://github.com/bridgebucket/zen-browser-better-better-active-tab-indicator

### Image

https://raw.githubusercontent.com/bridgebucket/zen-browser-better-better-active-tab-indicator/refs/heads/master/images/zen-theme-store-preview.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@-moz-document url-prefix("chrome:") {
    .tab-background[selected='']::before {
        content: '';
        position: absolute;
        display: block;
        height: 70%;
        width: 4px;
        border-radius: 5px;
        margin-top: 10%;
        background-color: var(--zen-primary-color);
    }
     @media (-moz-bool-pref: "zen.view.sidebar-expanded") {
         .tab-background[selected='']::before {
             margin-top: 3%;
         }
     }
    @media (-moz-bool-pref: "theme.bat-indicator.on-right"){
        .tab-background[selected='']::before {
            right: 0px;
        }
    }
}
```

### Readme

```markdown
# Better Better Active Tab Indicator

A fork of HliasOuzounis' project which makes the better active tab indicator more consistent with existing Zen UI design :-)

![Active tab](images/active-indicator.png)
```

### Preferences

```json
{
    "property": "theme.bat-indicator.on-right",
    "label": "Moves the active tab indicator to the right side of the tab. Has a neat little compatibility with Now Playing Indicator by benstone326 :-)",
    "type": "checkbox"
}
```
