### ISSUE TITLE
[create-theme]: Linux Tokyonight GTK Button style

### ISSUE THREAD

**Issue by parlandin** [zen-browser/theme-store#576]
### Name

Linux Tokyonight GTK Btn

### Description

This theme adds linux tokyonight GTK buttons in zen-browser (like macOS).

### Homepage

https://github.com/parlandin/Linux-Tokyonight-GTK-Btn-Zen-Theme

### Image

https://github.com/parlandin/Linux-Tokyonight-GTK-Btn-Zen-Theme/blob/5df6e3bcc44cad815f654441da445fc554a769b7/linux-btn-tokyonight.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
.titlebar-buttonbox {
    margin-right: 20px;
}

.titlebar-button {
    padding: 0px !important;
    min-height: 15px !important;
    min-width: 15px !important;
    align-self: center;
    margin-left: 5px !important;
    border-radius: 50%;
    transition: all 100ms;
    cursor: pointer;
}

.titlebar-button > image {
    visibility: collapse !important;
}


.titlebar-button:hover {
    opacity: 0.5 !important;
}

.titlebar-min {
    background-color: #ff9e64 !important;
}

.titlebar-max, .titlebar-restore {
    background-color: #9ece6a !important;
}

.titlebar-close {
    background-color: #f7768e !important;
}
```

### Readme

```markdown
This theme adds the buttons from the Tokyonight-GTK theme (from Linux) to the Zen-Browser. The colors are similar to macOS, but if you want the same as macOS, try the "Zen Minimal Exit Menu" theme.
```
