### ISSUE TITLE
Update Theme: sleek border 

### ISSUE THREAD

**Issue by Lumio4u** [zen-browser/theme-store#581]
The previous styles were not applied correctly because `!important` was missing. 
Changes:
   1. Added `!important`
   2. Reduced unnecessary code by removing unmodified or redundant CSS rules.

```css
:root {
     --sno-colors-border: #e8e8e80f;
     --sno-colors-border-hover: #3e3e3eb2;
     #urlbar {
         transform-origin: right !important;
         transition: all 0.2s linear !important;
         border: 1px solid var(--sno-colors-border) !important;
    }
     #urlbar:hover {
         border: 1px solid var(--sno-colors-border-hover) !important;
    }
     #urlbar[breakout][breakout-extend] {
         top: 10% !important;
    }
     #urlbar:is([focused], [open]) > #urlbar-background, #searchbar:focus-within {
         background: #000000e5 !important;
    }
}

:root:not([inDOMFullscreen='true']):not([chromehidden~='location']):not([chromehidden~='toolbar']) {
     & #tabbrowser-tabbox #tabbrowser-tabpanels .browserSidebarContainer {
         --uc-tweak-rounded-corners-shadow-color: var(--sno-colors-border) !important;
         box-shadow: var(--uc-tweak-rounded-corners-shadow) !important;
    }
}
```

<sub>i hope this time it will work</sub>
