### ISSUE TITLE
[create-theme]: Compact Bookmarks

### ISSUE THREAD

**Issue by Crackvignoule** [zen-browser/theme-store#593]
### Name

Compact Bookmarks

### Description

Reduces padding and margins in bookmarks folders

### Homepage

https://github.com/Crackvignoule/zen-browser-compact-bookmarks

### Image

https://raw.githubusercontent.com/Crackvignoule/zen-browser-compact-bookmarks/refs/heads/main/images/comparison.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
.toolbar-menupopup .bookmark-item {
    margin-block: 0 !important;
    padding: 0 !important;
}
```

### Readme

```markdown
# Compact Bookmarks
Reduces padding and margins in bookmarks folders.

![comparison](./images/comparison.png)
```
