### ISSUE TITLE
[create-theme]: Nord Theme

### ISSUE THREAD

**Issue by Mircobrb** [zen-browser/theme-store#602]
### Name

Nord Theme

### Description

A Nord Theme for Zen Browser

### Homepage

https://github.com/Mircobrb/Nord-Theme---zenbrowser

### Image

https://imgur.com/a/Rm4qFO7

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
:root {
    --zen-colors-primary: #88c0d0 !important;
    --zen-colors-secondary: #88c0d0 !important;
    --zen-colors-tertiary: #3b4252 !important;
    --zen-colors-border: #4c566a !important;
    --zen-dialog-background: #2e3440 !important;
    --tab-selected-textcolor: #2e3440 !important;
    --toolbar-field-background-color: #2e3440 !important;
    --toolbar-field-focus-background-color: #2e3440 !important;
      }
   
.urlbar-input {
  text-align: center;
}
```

### Readme

```markdown
A Nord Theme for Zen Browser
```
