### ISSUE TITLE
[create-theme]: Simple Golden Black

### ISSUE THREAD

**Issue by Mithun-750** [zen-browser/theme-store#606]
### Name

Simple GoldenBlack

### Description

A simple golden-black color theme for Zen .

### Image

https://imgur.com/a/DHHiS9g

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@-moz-document url-prefix("chrome:") {
    :root {
        --zen-colors-primary: black !important;
        --zen-colors-secondary: rgba(255, 217, 0, 0.8) !important;
        --zen-colors-tertiary: black !important;
        --zen-colors-border: rgba(255, 217, 0, 0.4) !important;
        --zen-dialog-background: black !important;
    }

}
```

### Readme

```markdown
A simple golden-black color theme for Zen Browser.
```
