### ISSUE TITLE
[create-theme]: clickable Scrollbar in Sidebar [fix]

### ISSUE THREAD

**Issue by tahawael** [zen-browser/theme-store#610]
### Name

clickable Scrollbar in Sidebar [fix]

### Description

# clickable Scrollbar in Sidebar  Makes Sidebar Scrollbar clickable

### Image

https://i.imgur.com/6tR61jB.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
scrollbox:nth-child(5) {
      scrollbar-width: thin !important;
}


@media (-moz-bool-pref: "zen.view.sidebar-expanded") {
      scrollbox:nth-child(5) {
            scrollbar-width: auto !important;
      }
}



#navigator-toolbox {
      -moz-window-dragging: no-drag; /* Disables window dragging */
}
```

### Readme

```markdown
# clickable Scrollbar in Sidebar

Makes Sidebar Scrollbar clickable
```
