### ISSUE TITLE
[create-theme]: Better Windows Buttons

### ISSUE THREAD

**Issue by tsukanov-alexey** [zen-browser/theme-store#613]
### Name

Better Windows Buttons

### Description

Do you rage when looking at the standard Windows buttons? This theme is the Solution.

### Homepage

https://github.com/tsukanov-alexey/zen-related-stuff

### Image

https://raw.githubusercontent.com/tsukanov-alexey/zen-related-stuff/refs/heads/main/%5BUI%5D%20Better%20%E2%80%93%20%E2%A7%89%20%E2%9C%96%20Windows%20buttons/image.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
.titlebar-buttonbox {
    padding-inline-end: calc(var(--zen-toolbox-padding) - var(--toolbarbutton-outer-padding)) !important;
    align-items: center;
}

.titlebar-button {
    padding: 0 var(--toolbarbutton-outer-padding) !important;
    height: calc(2 * var(--toolbarbutton-inner-padding) + 16px);
}

.titlebar-button > image {
    padding: var(--toolbarbutton-inner-padding) !important;
    border-radius: var(--toolbarbutton-border-radius) !important;
    outline: var(--toolbarbutton-outline) !important;
    outline-offset: var(--toolbarbutton-outline-offset) !important;

    width: calc(2 * var(--toolbarbutton-inner-padding) + 12px) !important;
    height: calc(2 * var(--toolbarbutton-inner-padding) + 12px) !important;
}

.titlebar-button:hover > image {
    background-color: var(--toolbarbutton-hover-background) !important;

    outline-color: var(--toolbarbutton-hover-outline-color) !important;
}

.titlebar-min:hover {
    background: none !important;
}

.titlebar-max:hover {
    background: none !important;
}

.titlebar-restore:hover {
    background: none !important;
}

.titlebar-close:hover {
    stroke: currentColor !important;
    background: none !important;
}


@media (-moz-bool-pref: "theme.betterWindowsButtons.use_custom_icon_color_for_close") {
    .titlebar-close:hover {
        stroke: var(--theme-betterWindowsButtons-icon_color_for_close) !important;
    }
}

@media (-moz-bool-pref: "theme.betterWindowsButtons.use_custom_button_color_for_close") {
    .titlebar-close:hover > image {
        background-color: var(--theme-betterWindowsButtons-button_color_for_close) !important;
    }
}


@media (-moz-bool-pref: "theme.betterWindowsButtons.use_custom_icon_color_for_restore") {
    .titlebar-restore:hover,
    .titlebar-max:hover {
        stroke: var(--theme-betterWindowsButtons-icon_color_for_restore) !important;
    }
}

@media (-moz-bool-pref: "theme.betterWindowsButtons.use_custom_button_color_for_restore") {
    .titlebar-restore:hover > image,
    .titlebar-max:hover > image {
        background-color: var(--theme-betterWindowsButtons-button_color_for_restore) !important;
    }
}


@media (-moz-bool-pref: "theme.betterWindowsButtons.use_custom_icon_color_for_min") {
    .titlebar-min:hover {
        stroke: var(--theme-betterWindowsButtons-icon_color_for_min) !important;
    }
}

@media (-moz-bool-pref: "theme.betterWindowsButtons.use_custom_button_color_for_min") {
    .titlebar-min:hover > image {
        background-color: var(--theme-betterWindowsButtons-button_color_for_min) !important;
    }
}
```

### Readme

```markdown
# Better – ⧉ ✖ Windows Buttons

Do you rage when looking at the standard Windows buttons? This theme is the Solution.

## Features

- Looks stunning
- Moreover, it’s perfectly consistent
- Plus, you can customize the colors in the settings
```

### Preferences

```json
[
    {
        "property": "theme.betterWindowsButtons.use_custom_icon_color_for_min",
        "label": "Use custom icon color for ━ button",
        "type": "checkbox",
        "defaultValue": false
    },
    {
        "property": "theme.betterWindowsButtons.icon_color_for_min",
        "label": "Icon color for ━ button (tick checkbox above)",
        "type": "string",
        "placeholder": "white, #fff, rgb(255, 255, 255), etc..."
    },
    {
        "property": "theme.betterWindowsButtons.use_custom_button_color_for_min",
        "label": "Use custom button color for ━ button",
        "type": "checkbox",
        "defaultValue": false
    },
    {
        "property": "theme.betterWindowsButtons.button_color_for_min",
        "label": "Button color for ━ button (tick checkbox above)",
        "type": "string",
        "placeholder": "limegreen, #f53, rgb(255, 85, 51), etc..."
    },

    {
        "property": "theme.betterWindowsButtons.use_custom_icon_color_for_restore",
        "label": "Use custom icon color for ⧉ button",
        "type": "checkbox",
        "defaultValue": false
    },
    {
        "property": "theme.betterWindowsButtons.icon_color_for_restore",
        "label": "Icon color for ⧉ button (tick checkbox above)",
        "type": "string",
        "placeholder": "white, #fff, rgb(255, 255, 255), etc..."
    },
    {
        "property": "theme.betterWindowsButtons.use_custom_button_color_for_restore",
        "label": "Use custom button color for ⧉ button",
        "type": "checkbox",
        "defaultValue": false
    },
    {
        "property": "theme.betterWindowsButtons.button_color_for_restore",
        "label": "Button color for ⧉ button (tick checkbox above)",
        "type": "string",
        "placeholder": "orange, #ffa500, rgb(255, 87, 51), etc..."
    },

    {
        "property": "theme.betterWindowsButtons.use_custom_icon_color_for_close",
        "label": "Use custom icon color for ✖ button",
        "type": "checkbox",
        "defaultValue": false
    },
    {
        "property": "theme.betterWindowsButtons.icon_color_for_close",
        "label": "Icon color for ✖ button (tick checkbox above)",
        "type": "string",
        "placeholder": "white, #fff, rgb(255, 255, 255), etc..."
    },
    {
        "property": "theme.betterWindowsButtons.use_custom_button_color_for_close",
        "label": "Use custom button color for ✖ button",
        "type": "checkbox",
        "defaultValue": false
    },
    {
        "property": "theme.betterWindowsButtons.button_color_for_close",
        "label": "Button color for ✖ button (tick checkbox above)",
        "type": "string",
        "placeholder": "red, #f00, rgb(255, 0, 0), etc..."
    }
]
```
