### ISSUE TITLE
[create-theme]: Bookmark Toolbar Tweaks

### ISSUE THREAD

**Issue by n7itro** [zen-browser/theme-store#62]
### Name

Bookmark Toolbar Tweaks

### Description

Center bookmarks, hide the icons!

### Homepage

https://github.com/n7itro/Zen-Themes/

### Image

https://i.imgur.com/mKlKe7d.png

### Theme Styles

```css
/* Center the bookmarks toolbar */
@media (-moz-bool-pref: "uc.bookmarks.center-toolbar") {
  #PlacesToolbarItems {
    justify-content: center;
  }
}

/* Hide folder icons in the bookmarks toolbar */
@media (-moz-bool-pref: "uc.bookmarks.hide-folder-icons") {
  .bookmark-item[container="true"] .toolbarbutton-icon {
    display: none;
  }
}

/* Hide favicons in the bookmarks toolbar */
@media (-moz-bool-pref: "uc.bookmarks.hide-favicons") {
  .bookmark-item:not([container]) .toolbarbutton-icon {
    display: none;
  }
}
```

### Readme

```markdown
This theme contains a few small tweaks to the bookmarks toolbar:
- Center the toolbar
- Hide bookmark or bookmark folder icons

Each of these settings can be enabled individually by changing the configuration in the settings page.

To enable the bookmarks toolbar, press Ctrl + Shift + B

Feel free to suggest additional tweaks.
```

### Preferences

```json
{
  "uc.bookmarks.center-toolbar": "Center the bookmarks toolbar", 
  "uc.bookmarks.hide-folder-icons": "Hide folder icons", 
  "uc.bookmarks.hide-favicons": "Hide website icons"
}
```
