### ISSUE TITLE
[create-theme]: No Gaps

### ISSUE THREAD

**Issue by Peleret** [zen-browser/theme-store#627]
### Name

No Gaps

### Description

Removes the gaps when the view isn't split.

### Image

https://i.imgur.com/5ZcNJIb.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@media (-moz-bool-pref: "theme.no_gaps.split.enabled") {

  #tabbrowser-tabbox{
    --zen-split-row-gap: 0 !important;
    --zen-split-column-gap: 0 !important;
    padding: 0 !important;
  }

  #tabbrowser-tabbox:has(> #tabbrowser-tabpanels[zen-split-view="true"]) {
    padding: 0 1px 0 0 !important;
  }

  #tabbrowser-tabpanels{
    padding: 0 !important;
  }
  .zen-split-view-splitter {
    display: none;
  }

  @media (-moz-bool-pref: "theme.no_gaps.split.border") {
    .browserSidebarContainer[zen-split="true"]{
      padding: 1px !important;
    }
  }

}

@media not (-moz-bool-pref: "theme.no_gaps.split.enabled") {

  #tabbrowser-tabpanels:not([zen-split-view="true"]){
    padding: 0 !important;
  }
  #tabbrowser-tabbox:has(> #tabbrowser-tabpanels:not([zen-split-view="true"])) {
    padding: 0 !important;
  }

}

@media not (-moz-bool-pref: "theme.no_gaps.border") {

  @media not (-moz-bool-pref: "theme.no_gaps.split.border") {

    .browserSidebarContainer{
      --uc-tweak-rounded-corners-shadow-color: transparent !important;
    }

    @media (-moz-bool-pref: "theme.no_gaps.split.rounded_corners") {
      .browserSidebarContainer[zen-split="true"]{
        overflow: visible !important;
      }
    }

  }

  @media (-moz-bool-pref: "theme.no_gaps.split.border") {
    .browserSidebarContainer:not([zen-split="true"]){
      --uc-tweak-rounded-corners-shadow-color: transparent !important;
    }
  }

}

@media (-moz-bool-pref: "theme.no_gaps.border") {

  @media not (-moz-bool-pref: "theme.no_gaps.split.border") {
    .browserSidebarContainer[zen-split="true"]{
      --uc-tweak-rounded-corners-shadow-color: transparent !important;
    }

    @media (-moz-bool-pref: "theme.no_gaps.split.rounded_corners") {
      .browserSidebarContainer[zen-split="true"]{
        overflow: visible !important;
      }
    }

  }

}

@media not (-moz-bool-pref: "theme.no_gaps.rounded_corners") {

  @media not (-moz-bool-pref: "theme.no_gaps.split.rounded_corners") {
    #tabbrowser-tabpanels{
      --zen-webview-border-radius: 0;
    }
  }

  @media (-moz-bool-pref: "theme.no_gaps.split.rounded_corners") {
    #tabbrowser-tabpanels:not([zen-split-view="true"]){
      --zen-webview-border-radius: 0;
    }
  }

}

@media (-moz-bool-pref: "theme.no_gaps.rounded_corners") {
  @media not (-moz-bool-pref: "theme.no_gaps.split.rounded_corners") {
    #tabbrowser-tabpanels[zen-split-view="true"]{
      --zen-webview-border-radius: 0;
    }
  }
}
```

### Readme

```markdown
# No Gaps
Removes the gaps when the view isn't split.

## Options
- Remove gaps in split view
Default: Off

- Keep border
Removes the border in default view when unchecked
Default: On

- Keep rounded corners
Removes rounded corners in default view when unchecked
Default: On

- Keep border in split view
Removes the border in split view when unchecked
Default: On

- Keep rounded corners in split view
Removes rounded corners in split view when unchecked
Default: On
```

### Preferences

```json
[
	{
		"property": "theme.no_gaps.split.enabled",
		"label": "Remove gaps in split view",
		"type": "checkbox",
		"defaultValue": false
	},
	{
		"property": "theme.no_gaps.border",
		"label": "Keep border",
		"type": "checkbox",
		"defaultValue": true
	},
	{
		"property": "theme.no_gaps.rounded_corners",
		"label": "Keep rounded corners",
		"type": "checkbox",
		"defaultValue": false
	},
	{
		"property": "theme.no_gaps.split.border",
		"label": "Keep border in split view",
		"type": "checkbox",
		"defaultValue": true
	},
	{
		"property": "theme.no_gaps.split.rounded_corners",
		"label": "Keep rounded corners in split view",
		"type": "checkbox",
		"defaultValue": true
	}
]
```
