### ISSUE TITLE
[create-theme]: Custom Sidebar Panel

### ISSUE THREAD

**Issue by KorvusDev** [zen-browser/theme-store#630]
### Name

Custom Sidebar Panel

### Description

A Zen Browser mod that allows you to customize the Zen Sidebar Panel.

### Image

https://i.ibb.co/ZLNsB0g/imagen.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#tabbrowser-tabbox {
    #zen-sidebar-web-panel-wrapper {
        margin: 10px !important;

        @media (-moz-bool-pref: "zen.view.compact.hide-tabbar") {
            margin-left: 16px !important;
        }

        #zen-sidebar-web-panel {
            box-shadow: none !important;
            min-width: 300px !important; 
            max-width: 100% !important; 
            position: relative;
            overflow: auto;
            resize: both;
            background: var(--uc-custom-zen-sidebar-panel-color-background, #21212180) !important;
            backdrop-filter: blur(var(--uc-custom-zen-sidebar-panel-blur, 3px)) !important;
            border-radius: var(--uc-custom-zen-sidebar-panel-border-radius, 15px) !important;
            box-shadow: 0 var(--uc-custom-zen-sidebar-panel-shadow-position, 0px) var(--uc-custom-zen-sidebar-panel-shadow-strength, 5px) var(--uc-custom-zen-sidebar-panel-color-shadow, #3d3d3d1a)  !important;
            browser {opacity: var(--uc-custom-zen-sidebar-panel-color-opacity, 0.8);}


            @media (-moz-bool-pref: "uc.custom-zen-sidebar-panel.show-borders") {
                border: 1 !important;
            }
            @media not (-moz-bool-pref: "uc.custom-zen-sidebar-panel.show-borders") {
                border: 0 !important;
            }

            resizer {
                @media not (-moz-bool-pref: "uc.custom-zen-sidebar-panel.transparent-resizer") {
                    background: transparent;
                }
            }
        }
    }
}
```

### Readme

```markdown
# Custom Sidebar Panel

A Zen Browser mod that allows you to customize the Zen Sidebar Panel.
```

### Preferences

```json
[
    {
        "property": "uc.custom-zen-sidebar-panel.color.background",
        "label": "Background (Hex: #RRGGBBAA / def: #21212180)",
        "type": "string"
    },
    {
        "property": "uc.custom-zen-sidebar-panel.color.opacity",
        "label": "Opacity (Between 0, 1 / def: 0.8)",
        "type": "string"
    },
    {
        "property": "uc.custom-zen-sidebar-panel.show-borders",
        "label": "Show Borders",
        "type": "checkbox"
    },
    {
        "property": "uc.custom-zen-sidebar-panel.color.shadow",
        "label": "Shadow (Hex: #RRGGBBAA / def: #3d3d3d1a)",
        "type": "string"
    },
    {
        "property": "uc.custom-zen-sidebar-panel.shadow-position",
        "label": "Shadow Position (n+px / def: 0px)",
        "type": "string"
    },
    {
        "property": "uc.custom-zen-sidebar-panel.shadow-strength",
        "label": "Shadow Strength (n+px / def: 5px)",
        "type": "string"
    },
    {
        "property": "uc.custom-zen-sidebar-panel.blur",
        "label": "Blur (n+px / def: 3px)",
        "type": "string"
    },
    {
        "property": "uc.custom-zen-sidebar-panel.border-radius",
        "label": "Border Radius (n+px or n+% / def: 15px)",
        "type": "string"
    },
    {
        "property": "uc.custom-zen-sidebar-panel.transparent-resizer",
        "label": "Show Resizer",
        "type": "checkbox"
    }
]
```
