### ISSUE TITLE
[create-theme]: Compact Sidebar

### ISSUE THREAD

**Issue by n7itro** [zen-browser/theme-store#64]
### Name

Compact Sidebar

### Description

Allow the tab sidebar to take up less space!

### Homepage

https://github.com/n7itro/Zen-Themes/

### Image

https://i.imgur.com/adYfkN0.png

### Theme Styles

```css
/* Decrease the minimum width of the tab sidebar */
@media (-moz-bool-pref: "uc.sidebar.compact-min-width") and (-moz-bool-pref: "zen.view.sidebar-expanded") {  
   #navigator-toolbox {
     --zen-navigation-toolbar-min-width: 115px !important;
  }
}

/* Decrease the minimum height of tabs */
@media (-moz-bool-pref: "uc.sidebar.compact-tabs") {
  .tabbrowser-tab {
    --tab-min-width: 20px !important;
  }
}
```

### Readme

```markdown
This theme contains a few small tweaks for making the tab sidebar more compact:
- Reduce the minimum width of the sidebar while expanded
- Reduce the height of tabs

Each of these settings can be enabled individually by changing the configuration in the settings page.

Feel free to suggest more features for this theme.
```

### Preferences

```json
{
  "uc.sidebar.compact-min-width": "Decrease the minimum width of the tab sidebar", 
  "uc.sidebar.compact-tabs": "Decrease the height of tabs", 
}
```
