### ISSUE TITLE
[create-theme]: Perfection

### ISSUE THREAD

**Issue by saschaeggi** [zen-browser/theme-store#653]
### Name

Perfection

### Description

Adds spacing to the toolbar/sidebar, increases tab font size, and makes minor tweaks to the URL bar.

### Homepage

https://github.com/saschaeggi/zenbrowser-themes/tree/main/Perfection

### Image

https://raw.githubusercontent.com/saschaeggi/zenbrowser-themes/refs/heads/main/Perfection/image.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
body {
  --zen-toolbar-height: 54px;
}

.urlbar-background {
  background: rgba(255, 255, 255, 0.1);
  margin-inline-end: 0.25em;
}

#identity-box {
  margin-inline-end: 0;
}

#urlbar #identity-box #identity-icon-box {
  background: transparent !important;
  border-inline-end: 1px solid rgba(255, 255, 255, 0.3) !important;
  border-radius: 0 !important;
  padding-inline: 1rem !important;
  margin-block: 0.5rem !important;
  margin-inline-end: 1rem !important;
}

.toolbar-items {
  padding-inline-start: 0.5em;
}

.tab-label {
  font-size: 1.25em;
}

#zen-sidebar-top-buttons-customization-target {
  padding-block: 0.5em;
}

.titlebar-buttonbox-container {
  margin-inline-end: 0.75rem;
}
```

### Readme

```markdown
# Perfection

Adjusts the toolbar and sidebar to add some extra spacing and increases the font size for tabs. Also includes minor visual improvements to the URL bar.
```
