### ISSUE TITLE
[create-theme]: Inactive tab opacity

### ISSUE THREAD

**Issue by benstone326** [zen-browser/theme-store#655]
### Name

Inactive tab opacity

### Description

This config lowers the opacity of the inactive tabs.

### Homepage

https://github.com/benstone326/zen-mods/tree/main

### Image

https://github.com/benstone326/zen-mods/blob/main/%5BConfig%5D%20Inactive%20tab%20opacity/image.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
.tabbrowser-tab:is([pending="true"]){
  & .tab-icon-stack, & .tab-label-container{
    opacity: 0.5 !important;
  }
}
```

### Readme

```markdown
# Inactive tab opacity

This config lowers the opacity of the inactive tabs. 

**In version 1.0.0:**
- Opacity set to 50%, if the tab is in inactive state.

---

Please note that other themes may conflict with this one. If you experience any issues, please disable this theme and report the issue to the theme maintainer.
```
