### ISSUE TITLE
[create-theme]: Nyan Catto Mod

### ISSUE THREAD

**Issue by RayZ3R0** [zen-browser/theme-store#658]
### Name

Nyan Catto

### Description

Playful sidebar mod featuring Bongo Cat above and marching Nyan Cats below 🐱

### Homepage

https://github.com/RayZ3R0/nyan-catto

### Image

https://i.imgur.com/DJTdWLB.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
/*Nyan Cat and Friends*/

@media (-moz-bool-pref: "z0.catto.nyancats") {
  #TabsToolbar {
    overflow: hidden !important;
  }

  #zen-sidebar-icons-wrapper:before {
    content: "";
    position: absolute;
    bottom: 100%;
    right: -205%;
    animation: autoRun 5s linear infinite;
    width: 200%;
    height: 60%;
    background-image: url("https://media.tenor.com/AO6SLyoIk3sAAAAi/%D0%BD%D1%8F%D0%BD%D0%BA%D0%B5%D1%82%D0%BB%D0%B2.gif"),
      url("https://media.tenor.com/VrZKjGxIIiAAAAAi/123.gif"),
      url("https://media.tenor.com/tpEn9Nhx-OEAAAAi/cat-wow.gif"),
      url("https://media.tenor.com/kb2qWxydQigAAAAi/chenille-catarpillar.gif");
    background-size: contain, contain, contain, contain;
    background-repeat: no-repeat;
    background-position-x: 0, 60px, 120px, 160px;
    background-position-y: 0, 0, 0;
  }

  @keyframes autoRun {
    from {
      right: 0%;
    }
    to {
      right: -205%;
    }
  }
}

/*Nyan Cat and Friends*/


/*Bongo Cat Start*/
@media (-moz-bool-pref: "z0.catto.bongocat") {
#navigator-toolbox:before {
  position: absolute;
  top: 100px;
  right: 50%;
  transform: translateX(50%);
  width: 200px;
  height: 40px;
  z-index: 1;
  content: "";
  font-size: 20px;
  text-align: center;
  background-image: url("https://media.tenor.com/ZZu2QC-efdUAAAAi/cute-cat-white.gif");
  background-size: contain;
  background-repeat: no-repeat;
  background-position-x: center;
  overflow: visible;
  pointer-events: none;
}
}

/*Bongo Cat End*/


/*Reduce the Size*/
@media (-moz-bool-pref: "z0.catto.reduce_size") {
  
    #navigator-toolbox {
      --zen-navigation-toolbar-min-width: 100px !important;
         padding-top: 12.5vh !important;
         height: 85vh !important;
     }
}
```

### Readme

```markdown
# 🐱 Catto Zen Mod
A delightful collection of feline-themed modifications for your browser's sidebar! Bring some cat energy to your browsing experience.

## ✨ Features

### 🌈 Nyan Cat March
- Colourful Nyan Cat and friends parade across the bottom of your sidebar
- Adds a playful touch to your browsing experience

### 🙀 Bongo Cat
- Adorable Bongo Cat animation at the top of the sidebar
- **Important**: Requires Compact Mode to be working properly!

### 📐 Compact Size Reducer
- Reduces sidebar dimensions in compact mode
- Customizes height to 85vh
- Sets minimum width to 100px
- Creates a more streamlined look

## ⚙️ Configuration

All features are independently toggleable, allowing you to customize your experience

## ⚠️ Requirements

- Compact Mode must be enabled for Bongo Cat to display properly.

## 🎨 Customization

Each feature can be enabled or disabled independently to create your perfect browsing environment. Mix and match to suit your style!
```

### Preferences

```json
[
  {
  "property": "z0.catto.nyancats",
  "label": "Enable Nyan Cat and friends.",
  "type": "checkbox",
  "defaultValue": true
  },
  {
  "property": "z0.catto.bongocat",
  "label": "Enable Bongocat at the top.",
  "type": "checkbox",
  "defaultValue": false
  },
  {
  "property": "z0.catto.reduce_size",
  "label": "Reduce the size of compact mode sidebar to fit in the bongocat properly.",
  "type": "checkbox",
  "defaultValue": false
  },
]
```
