### ISSUE TITLE
[create-theme]: Nyan Catto Mod

### ISSUE THREAD

**Issue by RayZ3R0** [zen-browser/theme-store#659]
### Name

Nyan Catto Mod

### Description

Playful sidebar mod featuring Bongo Cat above and marching Nyan Cats below 🐱

### Homepage

https://github.com/RayZ3R0/nyan-catto

### Image

https://i.imgur.com/DJTdWLB.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
/*Nyan Cat and Friends*/

@media (-moz-bool-pref: "z0.catto.nyancats") {
  #TabsToolbar {
    overflow: hidden !important;
  }

  #zen-sidebar-icons-wrapper:before {
    content: "";
    position: absolute;
    bottom: 100%;
    right: -205%;
    animation: autoRun 5s linear infinite;
    width: 200%;
    height: 60%;
    background-image: url("https://media.tenor.com/AO6SLyoIk3sAAAAi/%D0%BD%D1%8F%D0%BD%D0%BA%D0%B5%D1%82%D0%BB%D0%B2.gif"),
      url("https://media.tenor.com/VrZKjGxIIiAAAAAi/123.gif"),
      url("https://media.tenor.com/tpEn9Nhx-OEAAAAi/cat-wow.gif"),
      url("https://media.tenor.com/kb2qWxydQigAAAAi/chenille-catarpillar.gif");
    background-size: contain, contain, contain, contain;
    background-repeat: no-repeat;
    background-position-x: 0, 60px, 120px, 160px;
    background-position-y: 0, 0, 0;
  }

  @keyframes autoRun {
    from {
      right: 0%;
    }
    to {
      right: -205%;
    }
  }
}

/*Nyan Cat and Friends*/


/*Bongo Cat Start*/
@media (-moz-bool-pref: "z0.catto.bongocat") {
#navigator-toolbox:before {
  position: absolute;
  top: 100px;
  right: 50%;
  transform: translateX(50%);
  width: 200px;
  height: 40px;
  z-index: 1;
  content: "";
  font-size: 20px;
  text-align: center;
  background-image: url("https://media.tenor.com/ZZu2QC-efdUAAAAi/cute-cat-white.gif");
  background-size: contain;
  background-repeat: no-repeat;
  background-position-x: center;
  overflow: visible;
  pointer-events: none;
}
}

/*Bongo Cat End*/


/*Reduce the Size*/
@media (-moz-bool-pref: "z0.catto.reduce_size") {
  
    #navigator-toolbox {
      --zen-navigation-toolbar-min-width: 100px !important;
         padding-top: 12.5vh !important;
         height: 85vh !important;
     }
}
```

### Readme

```markdown
## ✨ Features

🌈 **Nyan Cat March**
- Colorful Nyan Cats parade across sidebar bottom

🙀 **Bongo Cat**
- Cute Bongo Cat animation at sidebar top
- *Requires Compact Mode*

📐 **Size Reducer**
- Reduces sidebar in compact mode (85vh height, 100px min width)

All features independently toggleable - mix and match to suit your style! 🐱✨
```

### Preferences

```json
[
  {
  "property": "z0.catto.nyancats",
  "label": "Enable Nyan Cat and friends.",
  "type": "checkbox",
  "defaultValue": true
  },
  {
  "property": "z0.catto.bongocat",
  "label": "Enable Bongocat at the top.",
  "type": "checkbox",
  "defaultValue": false
  },
  {
  "property": "z0.catto.reduce_size",
  "label": "Reduce the size of compact mode sidebar to fit in the bongocat properly.",
  "type": "checkbox",
  "defaultValue": false
  }
]
```
