### ISSUE TITLE
[create-theme]: Bottom Icons Reverse Order

### ISSUE THREAD

**Issue by stetide** [zen-browser/theme-store#662]
### Name

Bottom Icons Reverse Order

### Description

Reverses the order of the bottom icons when collapsed

### Homepage

https://github.com/stetide/zen-bottom-icons-reversed-order

### Image

https://github.com/stetide/zen-bottom-icons-reversed-order/blob/main/preview.png?raw=true

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
/* reverse order of sidebar elements when collapsed */
@media (-moz-bool-pref: "zen.tabs.vertical") {
  #navigator-toolbox:not(#navigator-toolbox:is(#navigator-toolbox[zen-user-hover="true"][zen-has-hover], #navigator-toolbox[zen-user-hover="true"]:focus-within, #navigator-toolbox[zen-user-hover="true"][movingtab], #navigator-toolbox[zen-user-hover="true"][flash-popup], #navigator-toolbox[zen-user-hover="true"][has-popup-menu], #navigator-toolbox[zen-user-hover="true"]:has([open="true"]:not(tab):not(#zen-sidepanel-button)), #navigator-toolbox[zen-expanded="true"]:not([zen-user-hover="true"]))) {
    & #zen-sidebar-icons-wrapper {
      flex-direction: column-reverse !important;
    }
  }
}
```

### Readme

```markdown
# zen-bottom-icons-reversed-order
A Zen Mod which reverses the order of the bottom icons when collapsed

![preview](https://github.com/user-attachments/assets/d00b64af-09f9-44fb-8300-090762119f4a)
```
