### ISSUE TITLE
[create-theme]: Dark-Mode-Favicon-Outlines

### ISSUE THREAD

**Issue by tedbergstrand** [zen-browser/theme-store#665]
### Name

Dark-Mode-Favicon-Outlines

### Description

Adds White Outlines to Tab and Web Panel Icons in Dark Mode

### Homepage

https://github.com/tedbergstrand/zen-browser-themes/tree/main/Dark-Mode-Favicon-Outlines

### Image

https://github.com/tedbergstrand/zen-browser-themes/blob/main/Dark-Mode-Favicon-Outlines/Screenshot%202024-10-30%20103934.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@media (prefers-color-scheme: dark) {
  /* Styles for tab favicons */
  .tab-icon-image,
  /* Styles for Zen sidebar favicons */
  .zen-sidebar-panel-button image {
    filter: drop-shadow(0 0 1px rgba(255, 255, 255, 0.7)) 
            drop-shadow(0 0 1px rgba(255, 255, 255, 0.7)) !important;
  }

  /* Remove filter for elements without favicons */
  .tab-icon-image:not([src]),
  .zen-sidebar-panel-button image:not([src]) {
    filter: none !important;
  }
}
```

### Readme

```markdown
# Dark Mode Favicon Outlines

## Description

The Zen Favicon Outline Mod enhances the visibility of favicons in Zen Browser's dark mode. It adds a white outline to favicons in tabs and the Zen sidebar, making dark icons more visible against dark backgrounds.

## Features

- Adds a white outline to favicons in dark mode
- Applies to both tab favicons and Zen sidebar favicons
- Slightly increases webpanel favicon size for better visibility and interaction
- Only activates in dark mode, preserving the default look in light mode

## Customization

If you want to adjust the outline thickness, you can modify the `chrome.css` file:

- To change the outline thickness, adjust the `drop-shadow` values.

## Compatibility

This mod is compatible with the latest version of Zen Browser. It may need updates for future Zen Browser versions if the CSS selectors change.

## Support

If you encounter any issues or have suggestions for improvements, please open an issue on the GitHub repository or contact the mod author.

## License

This mod is released under the MIT License. See the LICENSE file for details.

## Author

Ted Bergstrand

## Acknowledgments

Thanks to the Zen Browser team and community for inspiration.
```
