### ISSUE TITLE
[create-theme]: Top New Tab Button

### ISSUE THREAD

**Issue by GunGunGun** [zen-browser/theme-store#670]
### Name

Top New Tab Button

### Description

Move New Tab button to the top of tab toolbar.

### Homepage

https://github.com/GunGunGun

### Image

https://raw.githubusercontent.com/GunGunGun/zenCustomCursorMod/main/topnewtabbutton/image.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#tabbrowser-arrowscrollbox-periphery {order: -1;}
```

### Readme

```markdown
Move New Tab button to the top of tab toolbar.
```
