### ISSUE TITLE
[create-theme]: Better Floating Sidebar

### ISSUE THREAD

**Issue by rockwillck** [zen-browser/theme-store#672]
### Name

Better Floating Sidebar

### Description

A floating sidebar that obeys Zen gradient themes and is evenly margined and padded.

### Image

https://i.imgur.com/EjsBGTr.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@media (-moz-bool-pref: "zen.view.compact") {
        :root:not([customizing]) {
            @media (-moz-bool-pref: "zen.view.compact.hide-tabbar") {
                & #navigator-toolbox{
                  left: 0 !important;
                  box-shadow: none !important;
                  transform: translate3d(-98%, 0, 0) !important;
                  padding:0;
                }

                & #titlebar {
                  border: none !important;
                  box-shadow: none !important;
                  padding: 10px !important;
                  margin:10px 0 10px 10px !important;
                  box-sizing: border-box !important;
                  width: fit-content !important;
                }

                & #navigator-toolbox:hover, & #navigator-toolbox[zen-has-hover], & #navigator-toolbox:focus-within, & #navigator-toolbox[zen-user-show], & #navigator-toolbox[flash-popup], & #navigator-toolbox[has-popup-menu], & #navigator-toolbox[movingtab], & #mainPopupSet:has(> #appMenu-popup:hover) ~ toolbox, & #navigator-toolbox:has(.tabbrowser-tab:active), & #navigator-toolbox:has([open="true"]:not(tab):not(#zen-sidepanel-button)) {
                    transform: translate3d(0, 0, 0) !important;
                }
            }
        }
    }
```

### Readme

```markdown
# Better Floating Sidebar
A reimplementation of the floating sidebar seen in the [Floating Compact Sidebar](https://zen-browser.app/mods/46690a54-5eff-4141-8af8-9cd772ab6e2c) extension. Works with gradients and doesn't have the same trigger zone/padding/margin issues as the aforementioned extension.
```
