### ISSUE TITLE
[create-theme]: zen-firefox-theme-support

### ISSUE THREAD

**Issue by Eugenenoble2005** [zen-browser/theme-store#674]
### Name

Firefox Theme Support

### Description

Adds support for firefox themes, including images and accent colors to the toolbar and urlbar

### Homepage

https://github.com/Eugenenoble2005/zenbrowser-mods/tree/main/zen-firefox-themes-support

### Image

https://private-user-images.githubusercontent.com/71329328/381914774-08ff5882-475d-4bcc-8d24-f0fab575b9ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzNzA4NTksIm5iZiI6MTczMDM3MDU1OSwicGF0aCI6Ii83MTMyOTMyOC8zODE5MTQ3NzQtMDhmZjU4ODItNDc1ZC00YmNjLThkMjQtZjBmYWI1NzViOWVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDEwMjkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4NDAwMTg5MzM0ZTZkMTFiYTllM2UxYmI3M2NkZDczM2VkYWRiYTAzNTZiYzRjYWQ0MTMwMmNhY2E0ZmE5N2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kvqr1_3MOdxNMeboAA_1UML2az7jhAt2BUId8dfB14Q

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#nav-bar, #navigator-toolbox{
 background: var(
        --lwt-header-image,
        var(--lwt-additional-images), var(--lwt-accent-color)) !important;
  background-position: var(--lwt-background-alignment) !important;
  background-repeat: var(--lwt-background-tiling) !important;
  background-attachment: fixed;
}
```

### Readme

```markdown
Zen Browser theme that attempts to create greater support for firefox themes. Including images and accent colors in the toolbar and urlbar.
```
