### ISSUE TITLE
[create-theme]: Hide Inactive Workspaces

### ISSUE THREAD

**Issue by GunGunGun** [zen-browser/theme-store#689]
### Name

Hide Inactive Workspaces

### Description

Reducing space by hiding inactive workspace icons, extremely useful if you have a lot of workspaces.

### Homepage

https://github.com/GunGunGun/zenCustomCursorMod/tree/main/autohide_inactive_workspaces

### Image

https://raw.githubusercontent.com/GunGunGun/zenCustomCursorMod/main/autohide_inactive_workspaces/image.png?raw=true

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#zen-workspaces-button .subviewbutton:not([active="true"]) {
  display: none!important;
}
#zen-workspaces-button:hover .subviewbutton:not([active="true"]) {
  display: flex!important;
}
```

### Readme

```markdown
Reducing space by hiding inactive workspace icons, extremely useful if you have a lot of workspaces.
```
