### ISSUE TITLE
[create-theme]: Tabs Borders

### ISSUE THREAD

**Issue by sebascontre** [zen-browser/theme-store#693]
### Name

Tabs Borders

### Description

Add a border to tabs in case thats whats you like

### Image

https://i.imgur.com/XLB9orR.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#tabbrowser-tabs .tabbrowser-tab .tab-background {
    border: 1px solid rgba(0,0,0,0.25) !important;
}
```

### Readme

```markdown
# Zen Mod: Add Border To Tabs

A very simple mod that add a border to tabs in case that's what you like.
```
