### ISSUE TITLE
[create-theme]: No Borders

### ISSUE THREAD

**Issue by wysh3** [zen-browser/theme-store#697]
### Name

No Borders

### Description

This mod for Zen Browser removes borders around tabs, giving you extra space for content and a cleaner browsing experience

### Homepage

https://github.com/wysh3/Zen-Mods/tree/main/No%20Borders

### Image

https://private-user-images.githubusercontent.com/179528356/382551092-1d6fa3cf-a84e-46cc-bc68-27588514a284.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA2MTM5MDgsIm5iZiI6MTczMDYxMzYwOCwicGF0aCI6Ii8xNzk1MjgzNTYvMzgyNTUxMDkyLTFkNmZhM2NmLWE4NGUtNDZjYy1iYzY4LTI3NTg4NTE0YTI4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwM1QwNjAwMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NTc4Zjc3ZTU5NTU3YzkzNTRhNzA0NGM1YTgxOTcwOGIyMDE3OTQxYTQ0ZGYzNTIzMmQyZTM5YTk0ZGNjNWM0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.37bFLBArTVjwwFK4W9tDdGGfkHg7cInx6Ff1a01XoyY

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
/* Reset padding and margin for the tab browser's tabbox and tab panels */
#tabbrowser-tabbox,
#tabbrowser-tabpanels {
    padding: 0px !important; /* Remove all padding */
    margin: 0px !important; /* Remove all margin */
    --zen-border-radius: 0px !important; /* Remove border radius for a square appearance */
}
```

### Readme

```markdown
# ✨ No Borders

**Get more screen, less clutter.** This mod for Zen Browser removes borders around tabs, giving you extra space for content and a cleaner browsing experience. Perfect for anyone who loves a minimalist, streamlined look. 

## 📌 Overview

Zen Browser’s default design includes borders around tabs for aesthetics, but some of us like it even simpler. This mod removes those borders, leaving you with a sleek, spacious interface that lets you focus on what’s important. 

![mod preview](https://github.com/user-attachments/assets/bba2eb2b-bb12-46d2-8666-d8d18ec82a1d)

[⭐ Star the repo](https://github.com/wysh3/Zen-Mods) if you appreciate this theme!
```
