### ISSUE TITLE
[create-theme]: No Borders

### ISSUE THREAD

**Issue by wysh3** [zen-browser/theme-store#699]
### Name

No Borders

### Description

Remove tab borders in Zen Browser for more content space and a better browsing experience

### Homepage

https://github.com/wysh3/Zen-Mods/tree/main/No%20Borders

### Image

https://imgur.com/a/qFKDmrU

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
/* Reset padding and margin for the tab browser's tabbox and tab panels */
#tabbrowser-tabbox,
#tabbrowser-tabpanels {
    padding: 0px !important; /* Remove all padding */
    margin: 0px !important; /* Remove all margin */
    --zen-border-radius: 0px !important; /* Remove border radius for a square appearance */
}
```

### Readme

```markdown
# ✨ No Borders

**Get more screen, less clutter.** This mod for Zen Browser removes borders around tabs, giving you extra space for content and a cleaner browsing experience. Perfect for anyone who loves a minimalist, streamlined look. 

## 📌 Overview

Zen Browser’s default design includes borders around tabs for aesthetics, but some of us like it even simpler. This mod removes those borders, leaving you with a sleek, spacious interface that lets you focus on what’s important. 

![mod preview](https://github.com/user-attachments/assets/44bfece6-7e00-4c00-86b8-de7ba0c84564)

[⭐ Star the repo](https://github.com/wysh3/Zen-Mods) if you appreciate this theme!
```
