### ISSUE TITLE
[create-theme]: PiP Rounded Corners

### ISSUE THREAD

**Issue by ghostsshadow** [zen-browser/theme-store#713]
### Name

PiP Rounded Corners

### Description

Adds rounded corners to the PiP window

### Homepage

https://github.com/ghostsshadow/zen-pip-rounded-corners.git

### Image

https://imgur.com/dF5rooz

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
html {
    border: 0px solid rgba(255, 0, 0, 255) !important;
    border-radius: 1rem !important; 
  }
```

### Readme

```markdown
Adds rounded corners to the PiP player
```
