### ISSUE TITLE
[create-theme]: Minimalist Container Indicator

### ISSUE THREAD

**Issue by anjerodev** [zen-browser/theme-store#717]
### Name

Min Container Indicator

### Description

This theme add a minimalist dot indicator for the current container in Zen Browser.

### Homepage

https://github.com/anjerodev/zen-themes/tree/main/minimalist-container-indicator

### Image

https://github.com/anjerodev/zen-themes/blob/main/minimalist-container-indicator/preview.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@-moz-document url-prefix('chrome://') {
    #urlbar-container #page-action-buttons #userContext-icons {
        position: relative;
        order: 2;
        height: 8px;
        width: 8px;
        background-color: var(--identity-icon-color);
        border-radius: 32px;
        margin-left: 12px !important;

        & image,
        label {
            display: none;
        }
    }
}
```

### Readme

```markdown
#  Minimalist Container Indicator

This theme add a minimalist dot indicator for the current container in Zen Browser.

## What the extension does

- Hide the label and icon of the current container in the search bar and instead show a minimalist dot with the color set to the container.

- Rearrange the order of the icons in the search bar to make the container indicator the last one.

![Preview](preview.png)
```
