### ISSUE TITLE
[create-theme]: Finetuning

### ISSUE THREAD

**Issue by wxxxcxx** [zen-browser/theme-store#722]
### Name

Finetuning

### Description

Finetuning is a mod that allows you to fine-tune the appearance of the browser.

### Image

https://i.imgur.com/cB6cIlE.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@-moz-document url-prefix("chrome:") {
  :root {
    --zen-toolbar-height: var(--finetuning-titlebar-titlebar_height) !important;
  }
  #nav-bar #zen-sidebar-top-buttons {
    min-height: auto !important;
    height: auto !important;
    max-height: auto !important;
    padding-right: 15px !important;
  }

  .titlebar-buttonbox-container {
    padding-left: 15px !important;
  }

  /* Hide the new tab button at the end of the tabs */
  @media (-moz-bool-pref: "finetuning.tabs.hide_tabs_newtab_button") {
    #tabbrowser-arrowscrollbox-periphery {
      display: none !important;
    }
  }
}
```

### Readme

```markdown
# Finetuning

Finetuning is a theme that allows you to fine-tune the appearance of the browser.

## Features

- Set the height of the titlebar
- Hide the new tab button at the end of the tabs
```

### Preferences

```json
[
    {
        "property": "finetuning.titlebar.titlebar_height",
        "label": "Set the height of the titlebar",
        "type": "string",
        "defaultValue": "40px",
        "disabledOn": []
    },
    {
        "property": "finetuning.tabs.hide_tabs_newtab_button",
        "label": "Hide the new tab button at the end of the tabs",
        "type": "checkbox",
        "defaultValue": false,
        "disabledOn": []
    }
]
```
