### ISSUE TITLE
[create-theme]: <hide-back-forward-button>

### ISSUE THREAD

**Issue by tandukuda** [zen-browser/theme-store#724]
### Name

Hide Back Forward Button

### Description

With this theme, you can hide your back & forward button. 

### Homepage

https://github.com/tandukuda/Zen-Browser-Theme/tree/cbbec167c12356fea0eb2a3c4f73338716cf04b5/Hide%20Back%20Forward%20Button

### Image

https://imgur.com/a/28mkGlC

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@-moz-document url-prefix("chrome:") {    :root:not([customizing]) #back-button{ display: none !important; }    :root:not([customizing]) #forward-button{ display: none !important; } }
```

### Readme

```markdown
# Hide Back & Forward Button
With this theme, you can hide your back & forward button.
<br/><br/>
![image](https://github.com/user-attachments/assets/348eae5a-e97b-401f-9108-578a9679be74)
```
