### ISSUE TITLE
[create-theme]: Transparent New Tab mod

### ISSUE THREAD

**Issue by TheBigWazz** [zen-browser/theme-store#726]
### Name

Transparent New Tab

### Description

Set the blank page in new tabs to transparent for a clean new tab view.

### Homepage

https://github.com/TheBigWazz/TransparentNewTabZen

### Image

https://github.com/user-attachments/assets/1c956166-576b-4a21-83fe-dede2653bd4f

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@media (-moz-bool-pref: "browser.tabs.allow_transparent_browser") {
    :root {
      --tabpanel-background-color: #00000000 !important;
    }
  }
```

### Readme

```markdown
<p align="center">
  <img src="https://github.com/user-attachments/assets/1c956166-576b-4a21-83fe-dede2653bd4f" alt="Wazz's custom image"/>
</p>


# Transparent New Tab for Zen Browser
Set the blank page in new tabs to transparent for a clean new tab view. Mod for Zen Browser.


## Enable Transparency
- Go to :config
- Set ```browser.tabs.allow_transparent_browser``` to ```true```
- In Zen settings, set New Tabs to ```Blank Page```
```
