### ISSUE TITLE
[create-theme]: 

### ISSUE THREAD

**Issue by Realrubr2** [zen-browser/theme-store#731]
### Name

SleepyRed

### Description

a theme with dark red accents. also the search bar is more elegant

### Homepage

https://github.com/Realrubr2/Zen-Theme

### Image

https://imgur.com/a/Bsky5pw

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
/* colours */
@media (prefers-color-scheme: dark) {
    :root {
        --zen-colors-primary: #bacbff !important;
        --zen-colors-secondary: #8a505a !important;
        --zen-colors-tertiary: #6d3b47 !important;
        --zen-colors-border: #6d3b47 !important;
        --zen-primary-color: #3c4574 !important;
        --zen-dialog-background: #F1FAE7 !important;
        --toolbarbutton-icon-fill: color-mix(in srgb, var(--zen-primary-color) 70%, white 30%) !important;
        --toolbar-field-color: color-mix(in srgb, var(--zen-primary-color) 40%, white 60%) !important;
        .tabbrowser-tab { color: #404c6e !important; }
        .tabbrowser-tab:is([visuallyselected], [multiselected]) { color: white !important; }
    }}

    @media (prefers-color-scheme: light) {
        :root {
          --zen-colors-primary: #854549 !important;
          --zen-colors-secondary: #8a505a !important;
          --zen-colors-tertiary: #6d3b47 !important;
          --zen-colors-border: #6d3b47 !important;
          --zen-primary-color: #c96168 !important;
          --zen-dialog-background: #F1FAE7 !important;
          --toolbarbutton-icon-fill: color-mix(in srgb, var(--zen-primary-color) 70%, black 30%) !important;
          --toolbar-field-color: color-mix(in srgb, var(--zen-primary-color) 40%, black 60%) !important;
          .tabbrowser-tab { color: #c96168 !important; }
          .tabbrowser-tab:is([visuallyselected], [multiselected]) { color: #0A1F00 !important; }
        }
      }
/*     zen-cleaned-url-bar
this is not my code under MIT liscene i am using it so dont hate :) */
#tracking-protection-icon-container {
    align-self: center !important;
    margin-bottom: -1px !important;
  }
  
  #page-action-buttons {
    margin-right: -2px !important;
    margin-bottom: -1px !important;
  }
  
  #urlbar-search-mode-indicator {
    background: transparent !important;
  }
  
  #urlbar-background {
    background: color-mix(in srgb, light-dark(#fff, var(--zen-colors-tertiary)) 60%, transparent 60%) !important;
    backdrop-filter: blur(50px) !important;
  }
  
  #identity-icon-box, #identity-permission-box {
    background: transparent !important;
    margin: 0 8px 0 0 !important;
  }
  
  .urlbarView-body-inner {
    #urlbar[open] > .urlbarView > .urlbarView-body-outer > & {
      border-top: none !important;
    }
  }
  
  .urlbarView:not([noresults]) > .search-one-offs:not([hidden]) {
    border-top: none !important;
  }
  
  .search-one-offs {
    padding: 4px !important;
    margin-bottom: 8px !important;
    opacity: 0.5 !important;
    background: var(--urlbarView-highlight-background) !important;
    border-radius: 8px !important;
  }
  
  .urlbarView-row {
    border-radius: 8px !important;
  }
  
  .search-panel-one-offs-container > *, .search-panel-one-offs-container > * > * {
    border-radius: 4px !important;
  }
  
  .urlbar-input-container {
    padding: 0px 3.5px !important;
  }
  
  #urlbar[open] {
    margin-top: 3px !important;
    padding-top: 6px !important;
  }
  
  .urlbar-go-button {
    align-self: center !important;
    opacity: 0.5 !important;
    background: transparent !important;
    margin-right: 6px !important;
  }
  
  .urlbar-go-button:hover {
    opacity: 1 !important;
  }
```

### Readme

```markdown
This theme is composed of a piece of code that is made by:https://github.com/Dinno-DEV
```
