### ISSUE TITLE
[create-theme]: Lychee's Zen Tweaks

### ISSUE THREAD

**Issue by zenlychee** [zen-browser/theme-store#732]
### Name

Lychee's Zen Tweaks

### Description

Some personal Zen Browser tweaks.

### Homepage

https://github.com/zenlychee/lychees-zen-tweaks

### Image

https://i.imgur.com/DTaQ9V2.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
.tab-text, #tabs-newtab-button {
    font-size: 1.125rem !important;
  }
  
.tab-icon-image {
    width: 1.75rem !important;
    height: 1.75rem !important;
}
  
.tab-background {
    border-radius: 1rem !important;
}
  
#vertical-pinned-tabs-container {
    grid-template-columns: repeat(3,minmax(var(--tab-pinned-min-width-expanded), auto)) !important;
}
  
#vertical-pinned-tabs-container .tab-background {
    height: inherit !important;
    border-radius: 1.124rem !important;
}
  
#vertical-pinned-tabs-container tab {
    height: 4.5rem !important;
}

.tabbrowser-tab[pending="true"] .tab-icon-image {
    opacity: 1 !important;
}
```

### Readme

```markdown
# Lychee's Zen Tweaks

<img src="assets/lychees-zen-tweaks-1200x800.png" alt="drawing" width="800"/>

A Zen Browser mod that comes with the following functionality:

- Increasing tab sizes

## Scripts

The repo comes with scripts to push and clear the userChrome file. In order to use them, ensure that within your `.env` file you have a `PROFILE_DIR` variable specified, pointing to the your Zen Browser profile directory.
```
