### ISSUE TITLE
[create-theme]: Tab Numbers

### ISSUE THREAD

**Issue by philmard** [zen-browser/theme-store#735]
### Name

Tab Numbers

### Description

Shows the Number corresponding to each Tab.

### Homepage

https://github.com/philmard/tab-numbers

### Image

https://raw.githubusercontent.com/philmard/tab-numbers/refs/heads/main/tab_numbers.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
tabs {
  counter-reset: tab-counter;
}

/* Automatically increment tab numbers for each .tab-content inside a tab */
tab .tab-content::before {
  counter-increment: tab-counter;
  content: counter(tab-counter) "";

  position: absolute;
  top: 5px;
  right: 1px;
  padding: 0px 4px;
  border-radius: 7px;

  opacity: 0.7;
  font-weight: bold;
  font-size: 80%;
}
```

### Readme

```markdown
# Tab Numbers

Shows the Number corresponding to each Tab. This can help you navigate between Tabs faster by pressing Cmd + Number of the Tab.
```
