### ISSUE TITLE
[create-theme]: Window Buttons Left Padding

### ISSUE THREAD

**Issue by pc-v2** [zen-browser/theme-store#750]
### Name

Window Buttons Left Padding

### Description

Just some tweaks for window buttons

### Homepage

https://github.com/pc-v2/zen-mods/tree/main/WindowButtonsLeftPadding

### Image

https://raw.githubusercontent.com/pc-v2/zen-mods/refs/heads/main/WindowButtonsLeftPadding/image.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
.titlebar-buttonbox-container {
        padding-left: var(--zen-element-separation);
}
```

### Readme

```markdown
Adds a padding on the left to window buttons. For those who have window buttons on the left
```
