### ISSUE TITLE
[create-theme]:Left Exit Padding

### ISSUE THREAD

**Issue by pc-v2** [zen-browser/theme-store#751]
### Name

Left Exit Padding

### Description

Adds left padding for window button on the left side

### Homepage

https://github.com/pc-v2/zen-mods/tree/main/WindowButtonsLeftPadding

### Image

https://raw.githubusercontent.com/pc-v2/zen-mods/refs/heads/main/WindowButtonsLeftPadding/mods.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
.titlebar-buttonbox-container {
        padding-left: var(--zen-element-separation);
}
```

### Readme

```markdown
Adds left padding for window button on the left side
```
