### ISSUE TITLE
[create-theme]: Unset pinned tabs container height

### ISSUE THREAD

**Issue by skipness** [zen-browser/theme-store#755]
### Name

pinned tabs height

### Description

Unset pinned tabs container height so you don't have to scroll

### Homepage

https://github.com/skipness/zen-browser-pinned-tabs-height

### Image

https://i.imgur.com/2JDmXVa.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#vertical-pinned-tabs-container {
  max-height: unset !important;
}
```

### Readme

```markdown
Unset pinned tabs container height so you don't have to scroll
```
