### ISSUE TITLE
[create-theme]: Thin Toolbar

### ISSUE THREAD

**Issue by MigueloAtla** [zen-browser/theme-store#757]
### Name

Thin Toolbar

### Description

Reduces the toolbar height.

### Homepage

https://github.com/MigueloAtla/zen-thin-toolbar-mod

### Image

https://imgur.com/a/jTIHebR

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#nav-bar {
  max-height: 30px !important;
  height: 30px !important;
  min-height: unset !important;
}
#urlbar:not([breakout][breakout-extend], [breakout][usertyping][focused]) {
  min-height: 26px !important;
  height: 26px !important;
}
.urlbar-input-container {
  align-items: center;
}
```

### Readme

```markdown
Decreases the toolbar height for a more compact appearance.
```
