### ISSUE TITLE
[create-theme]: No Workspace Whitespace

### ISSUE THREAD

**Issue by CallumOB** [zen-browser/theme-store#763]
### Name

No Workspace Whitespace

### Description

Removes the whitespace present at the top of the tab bar when the workspaces feature is disabled.

### Image

https://imgur.com/a/vrSahKW

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#zen-current-workspace-indicator {
  display: none !important;
}
```

### Readme

```markdown
Removes the whitespace present at the top of the tab bar when not using the workspaces feature.
```
