### ISSUE TITLE
[create-theme]: Bottom-Essentials

### ISSUE THREAD

**Issue by TheBigWazz** [zen-browser/theme-store#765]
### Name

Bottom Essentials

### Description

Move your Essential Tabs to the bottom of the Sidebar for some Visual seperation from Pinned tabs.

### Homepage

https://github.com/TheBigWazz/ZenThemes/tree/main/Bottom-Essentials

### Image

https://github.com/user-attachments/assets/0b66b793-f3d9-43c5-80f6-49488aefac2d

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
/* Move #zen-essentials-container to the bottom of the sidebar */
#zen-essentials-container {
   margin-top: auto; /* Pushes #zen-essentials-container to the bottom */
   order: 999; /* In case flexbox is used, ensure it's last */
}
```

### Readme

```markdown
<p align="center">
  <img src="https://github.com/user-attachments/assets/0b66b793-f3d9-43c5-80f6-49488aefac2d" alt="Wazz's custom image"/>
</p>


# Move Essentials to Bottom
Moves your essentials to the bottom on the Sidebar.
```
