### ISSUE TITLE
[create-theme]: Unfocsed Fade

### ISSUE THREAD

**Issue by TheBigWazz** [zen-browser/theme-store#767]
### Name

Unfocused Fade

### Description

Fade your text and window slightly when Zen loses focus. 

### Homepage

https://github.com/TheBigWazz/ZenThemes/tree/main/Unfocused-Fade

### Image

https://github.com/user-attachments/assets/413dcbe1-d3cc-42b0-afd2-847310b7705c

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
/* Consistent opacity when window is inactive */
.tab-stack:-moz-window-inactive, #urlbar:-moz-window-inactive {
    opacity: 0.5 !important;
  }
  
  /* Make browser slightly lighter when inactive */
  #browser:-moz-window-inactive {
    background-color: rgba(255, 255, 255, 0.1) !important;
  }
```

### Readme

```markdown
<p align="center">
  <img src="https://github.com/user-attachments/assets/413dcbe1-d3cc-42b0-afd2-847310b7705c" alt="Wazz's custom image"/>
</p>


# Unfocused Fade
Fade your browser slightly when Zen loses focus.
```
