### ISSUE TITLE
[create-theme]: Rosé Pine

### ISSUE THREAD

**Issue by saxophone-guy** [zen-browser/theme-store#770]
### Name

Rosé Pine

### Description

 All natural pine, faux fur and a bit of soho vibes for the classy minimalist. Now for zen browser!

### Homepage

https://github.com/rose-pine/zen-browser

### Image

https://private-user-images.githubusercontent.com/37913333/380530930-87a6d811-a91d-47f0-bd4d-f1ff1f4ee583.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0OTYzNzUsIm5iZiI6MTczMTQ5NjA3NSwicGF0aCI6Ii8zNzkxMzMzMy8zODA1MzA5MzAtODdhNmQ4MTEtYTkxZC00N2YwLWJkNGQtZjFmZjFmNGVlNTgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDExMDc1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjZTE5YjI0YTc5YjliMjI5NTAwYmNhZmJmNjAwNzM4NmI4M2NkMjMyNWJhZWUxYzBmODNhNTc0ODdhNjA1ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.nLWHb7Sjnj4DstpXBAIv6pX_c_MNi5h1Gs7W42RkjjE

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
* {
  --base:           #191724;
  --surface:        #1f1d2e;
  --overlay:        #26233a;
  --muted:          #6e6a86;
  --subtle:         #908caa;
  --text:           #e0def4;
  --love:           #eb6f92;
  --gold:           #f6c177;
  --rose:           #ebbcba;
  --pine:           #31748f;
  --foam:           #9ccfd8;
  --iris:           #c4a7e7;
  --highlightLow:   #21202e;
  --highlightMed:   #403d52;
  --highlightHigh:  #524f67;
}

#zen-main-app-wrapper {
  background-color: var(--base) !important;
}

#appMenu-mainView {
  background-color: var(--overlay) !important;
}

#appmenu-moreTools {
  background-color: var(--overlay) !important;
}

#PanelUI-button {
  --button-active-bgcolor: black !important;
}

toolbox#navigator-toolbox {
  background-color: var(--base) !important;
}

#zen-appcontent-navbar-container {
  background-color: var(--base) !important;
}

.menu-text {
  color: var(--text) !important;
}

.menuitem-iconic {
  color: var(--love) !important;
}

:not(:not(menubar) > menu, #ContentSelectDropdown)
  > menupopup
  > menuitem:not(
    .menuitem-iconic,
    [type="checkbox"],
    [type="radio"],
    .in-menulist,
    .in-menulist menuitem,
    .unified-nav-current
  ),
:not(:not(menubar) > menu, #ContentSelectDropdown)
  > menupopup
  > menu:not(
    .menu-iconic,
    [type="checkbox"],
    [type="radio"],
    .in-menulist,
    .in-menulist menu,
    .unified-nav-current
  ),
#toggle_toolbar-menubar,
#PanelUI-history toolbarbutton,
#unified-extensions-context-menu menuitem {
  fill: var(--text) !important;
}

html#main-window {
  --lwt-text-color: var(--text) !important;
  --toolbarbutton-icon-fill: var(--love) !important;
  --toolbar-field-color: var(--pine) !important;
  --toolbar-field-focus-color: var(--pine) !important;
  --toolbar-field-background-color: var(--surface) !important;
  --toolbar-field-focus-background-color: var(--surface) !important;

  --zen-colors-primary: var(--rose) !important;
  --zen-colors-secondary: var(--overlay) !important;
  --zen-colors-tertiary: var(--base) !important;
  --zen-colors-border: var(--base) !important;
  --zen-dialog-background: var(--overlay) !important;

  --arrowpanel-color: var(--text) !important;
}

#tabbrowser-tabbox {
  border-top-left-radius: 10px !important;
  border-left-width: 1px !important;
  border-top-width: 1px !important;
  border-color: var(--overlay) !important;
  border-style: solid !important;
}

#urlbar-background {
  border: 1px solid var(--overlay) !important;
}
```

### Readme

```markdown
<p align="center">
    <img src="https://github.com/rose-pine/rose-pine-theme/raw/main/assets/icon.png" width="80" />
    <h2 align="center">Rosé Pine for Zen Browser</h2>
</p>

<p align="center">All natural pine, faux fur and a bit of soho vibes for the classy minimalist</p>

<p align="center">
    <a href="https://github.com/rose-pine/rose-pine-theme">
        <img src="https://img.shields.io/badge/community-rosé%20pine-26233a?labelColor=191724&logo=data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjUwIiBoZWlnaHQ9IjIzNyIgdmlld0JveD0iMCAwIDI1MCAyMzciIGZpbGw9Im5vbmUiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CjxwYXRoIGQ9Ik0xNjEuMjI3IDE2MS4yNTFDMTMyLjE1NCAxNjkuMDQxIDExNC45MDEgMTk4LjkyNCAxMjIuNjkxIDIyNy45OTdDMTIzLjkyNSAyMzIuNjAzIDEyOC42NTkgMjM1LjMzNiAxMzMuMjY0IDIzNC4xMDJMMTg1LjkwNyAyMTkuOTk2QzIxOS41ODUgMjEwLjk3MiAyMzkuNTcgMTc2LjM1NCAyMzAuNTQ2IDE0Mi42NzdMMTYxLjIyNyAxNjEuMjUxWiIgZmlsbD0iIzI0NjI3QiIvPgo8cGF0aCBkPSJNODguMTgzNiAxNTkuOTg4QzExNy4yNTcgMTY3Ljc3OCAxMzQuNTEgMTk3LjY2MiAxMjYuNzIgMjI2LjczNUMxMjUuNDg2IDIzMS4zNCAxMjAuNzUyIDIzNC4wNzMgMTE2LjE0NyAyMzIuODM5TDYzLjUwNDEgMjE4LjczM0MyOS44MjY0IDIwOS43MSA5Ljg0MDk0IDE3NS4wOTIgMTguODY0OSAxNDEuNDE0TDg4LjE4MzYgMTU5Ljk4OFoiIGZpbGw9IiMyNDYyN0IiLz4KPHBhdGggZD0iTTE4Ni44NjcgMTcyLjk4QzE1Mi4wMDIgMTcyLjk4IDEyMy43MzcgMjAxLjI0NSAxMjMuNzM3IDIzNi4xMTFIMTg2Ljg3QzIyMS43MzYgMjM2LjExMSAyNTAgMjA3Ljg0NiAyNTAgMTcyLjk4TDE4Ni44NjcgMTcyLjk4WiIgZmlsbD0iIzMxNzQ4RiIvPgo8cGF0aCBkPSJNNjMuMTMyNyAxNzIuOThDOTcuOTk4NCAxNzIuOTggMTI2LjI2MyAyMDEuMjQ1IDEyNi4yNjMgMjM2LjExMUg2My4xM0MyOC4yNjQyIDIzNi4xMTEgLTEuNTI0MDNlLTA2IDIwNy44NDYgMCAxNzIuOThMNjMuMTMyNyAxNzIuOThaIiBmaWxsPSIjMzE3NDhGIi8+CjxwYXRoIGQ9Ik0xNzEuNzE3IDc1LjEyNjNDMTcxLjcxNyAxMDEuMjc2IDE1MC41MTggMTIyLjQ3NSAxMjQuMzY5IDEyMi40NzVDOTguMjE4OCAxMjIuNDc1IDc3LjAyMDIgMTAxLjI3NiA3Ny4wMjAyIDc1LjEyNjNDNzcuMDIwMiA0OC45NzY0IDk4LjIxODggMjcuNzc3OCAxMjQuMzY5IDI3Ljc3NzhDMTUwLjUxOCAyNy43Nzc4IDE3MS43MTcgNDguOTc2NCAxNzEuNzE3IDc1LjEyNjNaIiBmaWxsPSIjRUJCQ0JBIi8+CjxwYXRoIGQ9Ik0xNDQuMjE3IDg2LjIzNzlDMTYxLjY0OSA1Ni4wNDMyIDE1MS4zMDMgMTcuNDMyOSAxMjEuMTA4IDBMMTA2LjA2IDI2LjA2NDRDODguNjI3IDU2LjI1OSA5OC45NzM2IDk0Ljg2OTQgMTI5LjE2OCAxMTIuMzAyTDE0NC4yMTcgODYuMjM3OVoiIGZpbGw9IiNFQkJDQkEiLz4KPHBhdGggZD0iTTEyNS4yOTkgNjAuOTc4OUMxMTYuMjc1IDI3LjMwMTIgODEuNjU3NSA3LjMxNTY3IDQ3Ljk3OTcgMTYuMzM5Nkw2NC4zMTk3IDc3LjMyMTFDNzMuMzQzNiAxMTAuOTk5IDEwNy45NjEgMTMwLjk4NCAxNDEuNjM5IDEyMS45NkwxMjUuMjk5IDYwLjk3ODlaIiBmaWxsPSIjRUJCQ0JBIi8+CjxwYXRoIGQ9Ik0xMjQuOTI2IDYwLjk3ODlDMTMzLjk1IDI3LjMwMTIgMTY4LjU2NyA3LjMxNTY3IDIwMi4yNDUgMTYuMzM5NkwxODUuOTA1IDc3LjMyMTFDMTc2Ljg4MSAxMTAuOTk5IDE0Mi4yNjMgMTMwLjk4NCAxMDguNTg2IDEyMS45NkwxMjQuOTI2IDYwLjk3ODlaIiBmaWxsPSIjRUJCQ0JBIi8+Cjwvc3ZnPgo=&style=for-the-badge" />
    </a>
</p>
## Gallery

![Rosé Pine with Zen Browser](https://github.com/user-attachments/assets/fa9b285c-2805-4df9-bdf7-c5679f175afd)
![Rosé Pine Moon with Zen Browser](https://github.com/user-attachments/assets/87a6d811-a91d-47f0-bd4d-f1ff1f4ee583)
![Rosé Pine Dawn with Zen Browser](https://github.com/user-attachments/assets/f77bb6cc-9e97-4e72-976c-cafcaab8c78c)

## Thanks to

- [Wiktor Zykubek](https://github.com/wzykubek)
- [GoulvenV](https://github.com/feco)
```
