### ISSUE TITLE
[create-theme]: Fade off extension button 

### ISSUE THREAD

**Issue by RodiAda** [zen-browser/theme-store#771]
### Name

Fade off extension button 

### Description

Extension button hidden but visible on hover

### Homepage

https://github.com/RodiAda/fade-of-extanion-button

### Image

https://github.com/RodiAda/fade-of-extanion-button/blob/main/Pic.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@-moz-document url-prefix("chrome:") {
    @media (-moz-bool-pref: "uc.unifiedExtensions-hide.hide-unifiedExtensions.enabled") {
        #unified-extensions-button {
            display: none !important;
        }
    #unified-extensions-button {
        opacity: 0 !important;
        transition: opacity 0.3s ease;
    }
    #unified-extensions-button:hover {
        opacity: 1 !important;
    }
}
```

### Readme

```markdown
# fade-of-extanion-button
 Extention button hidden but visible on hover.
```
