### ISSUE TITLE
[create-theme]: Fade off extension button

### ISSUE THREAD

**Issue by RodiAda** [zen-browser/theme-store#772]
### Name

Fade off extension button

### Description

Extension button hidden but visible on hover

### Homepage

https://github.com/RodiAda/fade-of-extanion-button

### Image

https://i.imgur.com/4vboZrx.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@-moz-document url-prefix("chrome:") {
    @media (-moz-bool-pref: "uc.unifiedExtensions-hide.hide-unifiedExtensions.enabled") {
        #unified-extensions-button {
            display: none !important;
        }
    }
}
```

### Readme

```markdown
# fade-of-extanion-button
 Extention button hidden but visible on hover.
```
