### ISSUE TITLE
update: Thin Toolbar

### ISSUE THREAD

**Issue by MigueloAtla** [zen-browser/theme-store#775]
I revised the code to enhance reliability, resolved alignment issues, and added a preference option to support additional sizes.

This is the updated code:
css:
```css
:root {
  /* thin */
  --urlbar-height: 28px !important;
  --urlbar-container-height: 28px !important;
  --zen-toolbar-height: 35px !important;
  --urlbar-min-height: 28px !important;
  /* thinner */
  @media (-moz-bool-pref: "theme.thin_toolbar.thinner") {
    --urlbar-height: 26px !important;
    --urlbar-container-height: 26px !important;
    --zen-toolbar-height: 32px !important;
    --urlbar-min-height: 26px !important;
  }
}
#urlbar {
  /* thin */
  --urlbar-height: 28px !important;
  /* thinner */
  @media (-moz-bool-pref: "theme.thin_toolbar.thinner") {
    --urlbar-height: 26px !important;
  }
}
#urlbar-container {
  /* thin */
  --urlbar-container-height: 28px !important;
  /* thinner */
  @media (-moz-bool-pref: "theme.thin_toolbar.thinner") {
    --urlbar-container-height: 26px !important;
  }
}
.urlbar-input-container {
  align-items: center;
}
#identity-icon-label {
  padding-inline-start: 2px !important;
  font-size: 0.95em;
}
#identity-box > * {
  padding: 2px 8px;
}

```

preferences.json
```json
[
  {
    "property": "theme.thin_toolbar.thinner",
    "label": "Make toolbar thinner",
    "type": "checkbox",
    "defaultValue": false
  }
]
```
