### ISSUE TITLE
[create-theme]: Simple Centred Address

### ISSUE THREAD

**Issue by Lisiowen** [zen-browser/theme-store#778]
### Name

Simple Centred Address

### Description

Centres the URL bar text and hides buttons when unfocused.

### Image

https://imgur.com/a/BRvNxWD

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
/* ----- Search Bar Idle ----- */

@media (-moz-bool-pref: "uc.sca.enablecenteredtext") {
/* Centre text */
#urlbar-input {
  text-align: center !important;
}
}

/* Hide icons */
#page-action-buttons:has(#uc-sca[uc-sca-iconvisibility="quick"]),
#tracking-protection-icon-container:has(#uc-sca[uc-sca-iconvisibility="quick"]),
#identity-box:has(#uc-sca[uc-sca-iconvisibility="quick"]) {
  opacity: 0;
}

#page-action-buttons:has(#uc-sca[uc-sca-iconvisibility="smooth"]),
#tracking-protection-icon-container:has(#uc-sca[uc-sca-iconvisibility="smooth"]),
#identity-box:has(#uc-sca[uc-sca-iconvisibility="smooth"]) {
  opacity: 0;
  transition: opacity 0.3s ease;
}



/* ----- Search Bar Hover ----- */

/* Reveal icons*/
#urlbar:hover #page-action-buttons,
#urlbar:hover #tracking-protection-icon-container,
#urlbar:hover #identity-box {
  opacity: 1;
}


/* ----- Search Bar Focus ----- */

/* Revert text */
#urlbar[focused=""] #urlbar-input {
  text-align: left !important;
}



/* ----- Button Menu Opened ----- */

/* Keep buttons/menu visible */
#page-action-buttons:has(#star-button-box[open="true"])
#tracking-protection-icon-container[open="true"],
#identity-box:has(#identity-icon-box[open="true"]) {
  opacity: 1;
}
```

### Readme

```markdown
chrome.css notates what each block does. The text-align: center is only applied when the urlbar is unfocused to keep the modification simple.
```

### Preferences

```json
[
{
    "property": "uc.sca.enablecentredtext",
    "label": "Centred Text",
    "type": "checkbox",
    "defaultValue": true
}

{
    "property": "uc.sca.iconvisibility",
    "label": "Icon Visibility",
    "type": "dropdown",
    "placeholder": "Fade In On Hover",
    "defaultValue": "smooth",
    "options": [
      {
        "label": "Always Visible",
        "value": "always"
      },
      {
        "label": "Visible On Hover",
        "value": "quick"
      },
      {
        "label": "Fade In On Hover",
        "value": "smooth"
      }
    ]
}
]
```
