### ISSUE TITLE
[create-theme]: Hide tab mute

### ISSUE THREAD

**Issue by Tc-001** [zen-browser/theme-store#78]
### Name

Hide tab mute

### Description

Hides the mute/unmute button when the sidebar is collapsed to make clicking on tabs easier.

### Image

https://i.ibb.co/gjhNJh3/Board-2.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@media not (-moz-bool-pref: "zen.view.sidebar-expanded") {
    .tab-icon-overlay:is([soundplaying], [muted], [activemedia-blocked]) {
        display: none !important;
    }
}
```

### Readme

```markdown
Hides the "Mute"/"Unmute" button if the sidebar is collapsed.
This is useful if you want to click on or rearrange the tabs but instead keep accidentally muting your video/livestream/song.
```
