### ISSUE TITLE
[create-theme]: Container Indicator

### ISSUE THREAD

**Issue by Archer7x** [zen-browser/theme-store#784]
### Name

Container Indicator

### Description

This Mod removes the container indicator from Essentials, pinned and normal tabs.

### Homepage

https://github.com/Archer7x/Zen-Themes/tree/main/ContainerIndicator

### Image

https://raw.githubusercontent.com/Archer7x/Zen-Themes/refs/heads/main/ContainerIndicator/image.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@media (-moz-bool-pref: "theme.containerindicator.essentials") {
  #zen-essentials-container {
    .tabbrowser-tab[usercontextid]>.tab-stack>.tab-background>.tab-context-line {
      #tabbrowser-tabs[orient="vertical"] & {
        visibility: hidden;
      }
    }
  }
}

@media (-moz-bool-pref: "theme.containerindicator.pinedtabs") {
  #vertical-pinned-tabs-container {
    .tabbrowser-tab[usercontextid]>.tab-stack>.tab-background>.tab-context-line {
      visibility: hidden;
    }
  }
}

@media (-moz-bool-pref: "theme.containerindicator.normaltabs") {
  #tabbrowser-arrowscrollbox {
    .tabbrowser-tab[usercontextid]>.tab-stack>.tab-background>.tab-context-line {
      visibility: hidden;
    }
  }
}
```

### Readme

```markdown
# Container Indicator

This **Zen Mod** removes the container indicator from Essentials, pinned tabs and normal tabs.

![image](https://raw.githubusercontent.com/Archer7x/Zen-Themes/refs/heads/main/ContainerIndicator/image.png)

# Usage example
  - If you use the Firefox Add-on [**Facebook Container**](https://support.mozilla.org/en-US/kb/facebook-container-prevent-facebook-tracking) and have Instagram as an Essential,
    then the blue container indicator created by the Add-on might annoy you. (At least that's how it was for me.)
  - You can also remove the container indicator for pinned and normal tabs in the Zen-Mod preferences if you like.

## Settings (checkbox in Zens Mod settings):
  - Enable or disable container-indicator for Essentials (default on)
  - Enable or disable container-indicator for pinned tabs (default off)
  - Enable or disable container-indicator for normal tabs (default off)
```

### Preferences

```json
[
    {
        "property": "theme.containerindicator.essentials",
        "label": "Removes the container indicator from essetial tabs.",
        "type": "checkbox",
        "defaultValue": true,
        "disabledOn": []
    },
    {
        "property": "theme.containerindicator.pinedtabs",
        "label": "Removes the container indicator from pined tabs.",
        "type": "checkbox",
        "defaultValue": false,
        "disabledOn": []
    },
    {
        "property": "theme.containerindicator.normaltabs",
        "label": "Removes the container indicator from normal tabs.",
        "type": "checkbox",
        "defaultValue": false,
        "disabledOn": []
    }
]
```
