### ISSUE TITLE
[create-theme]: 

### ISSUE THREAD

**Issue by admayz** [zen-browser/theme-store#794]
### Name

Title Bar Buttons UI

### Description

Enhanced the Zen Browser title bar buttons with improved visuals, including hover effects, to provide a more modern and interactive user experience while maintaining design consistency.

### Image

https://imgur.com/EUToaw7

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
.titlebar-buttonbox{
    margin-top: 5px;
    margin-right: 5px;
  }

  .titlebar-button {
    height: 25px;
    width: 25px;
    margin: 2px;
    border-radius: var(--toolbarbutton-border-radius);
    cursor: pointer;
  }

  .titlebar-min:hover{
    background-color: #02751e;
  }

  .titlebar-restore:hover{
    background-color: #A27A05;
  }

  .titlebar-max:hover{
    background-color: #A27A05;
  }

  .titlebar-close:hover {
    background-color: #C64F46;
  }
```

### Readme

```markdown
Zen Browser Title Bar Buttons Enhancement
This project improves the visual and interactive aspects of the Zen Browser's title bar buttons, aligning them with the browser's minimalist and user-focused design principles.

Features
Hover Effects: Added smooth hover animations for better interactivity.
Modern Design: Updated button styles for a clean and coherent look.
Improved User Experience: Enhanced usability while maintaining simplicity.
Design Philosophy
The enhancements are inspired by the Zen Browser's design philosophy:

Minimalism: Keeping the interface uncluttered and intuitive.
Consistency: Ensuring the buttons blend seamlessly with the overall UI.
Interactivity: Providing feedback through subtle animations.
```
