### ISSUE TITLE
[create-theme]: 

### ISSUE THREAD

**Issue by admayz** [zen-browser/theme-store#798]
### Name

Status Bar UI

### Description

Enhanced Zen Browser status bar with a minimalist design, improving readability and seamless integration.

### Image

https://i.imgur.com/cMyxN3Y.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#statuspanel{
    padding: 10px;
  }

  #statuspanel-label{
    border: 1px solid var(--zen-colors-border) !important;
    background: var(--zen-colors-tertiary) !important;
    padding: 4px;
    border-radius: var(--toolbarbutton-border-radius);
  }
```

### Readme

```markdown
Zen Browser Status Bar Enhancements
This project introduces visual and functional improvements to the Zen Browser's status bar, focusing on simplicity and clarity.

Features
Minimalist Design: Updated the status bar to blend harmoniously with the browser's UI.
Enhanced Readability: Optimized font and spacing for better visibility.
Seamless Integration: Maintains the Zen Browser's design consistency.

Benefits
User-Centric Design: Focused on usability and aesthetics to enhance user experience.
Modern Look: Reflects a clean and professional appearance.
```
