### ISSUE TITLE
[create-theme]: Use default font for UI

### ISSUE THREAD

**Issue by redactedontop** [zen-browser/theme-store#808]
### Name

Use default font for UI

### Description

Basically just changes the UI's font to the default font selected in firefox settings.

### Image

https://i.imgur.com/eh0famX.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
* {
    font-family: serif !important;
}
```

### Readme

```markdown
Heya. I have nothing good to put here.
```
