### ISSUE TITLE
[create-theme]: Better Find Bar

### ISSUE THREAD

**Issue by RobotoSkunk** [zen-browser/theme-store#811]
### Name

Better Find Bar

### Description

Improves the find bar by matching the browser theme, making it floating, more responsive, and moving it to the top of the page.

### Homepage

https://github.com/RobotoSkunk/zen-better-findbar

### Image

https://raw.githubusercontent.com/RobotoSkunk/zen-better-findbar/refs/heads/main/image.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
:root {
	--rs-findbar-open-pos: 15px;
	--rs-findbar-closed-pos: -85px;
	--rs-findbar-transition-duration: 0.35s;
}

@keyframes rs-findbar-open {
	from {
		top: var(--rs-findbar-closed-pos);
	}

	to {
		top: var(--rs-findbar-open-pos);
	}
}

findbar {
	display: flex;

	border-radius: var(--zen-border-radius) !important;
	margin: 0px !important;

	width: 90% !important;
	max-width: 800px;

	/* height: 50px !important; */
	height: auto !important;

	position: absolute !important;
	top: var(--rs-findbar-open-pos);
	left: 50%;
	transform: translateX(-50%);

	overflow: unset !important;
	box-shadow: var(--box-shadow-10);

	background: var(--zen-colors-tertiary) !important;
	border: 1px solid var(--zen-colors-border) !important;

	animation-name: rs-findbar-open !important;
	animation-duration: var(--rs-findbar-transition-duration) !important;
	animation-timing-function: ease !important;

	transition: all var(--rs-findbar-transition-duration) ease !important;


	& .findbar-container {
		flex-wrap: wrap;
		overflow-x: auto !important;
		height: auto !important;

		row-gap: 10px;

		& > :first-child {
			width: 100% !important;
		}

		& .findbar-textbox {
			flex-grow: 1;
		}
	}

	&[hidden="true"] {
		top: var(--rs-findbar-closed-pos);
	}
}
```

### Readme

```markdown
# Better Find Bar

Improves the find bar by matching the browser theme, making it floating,
more responsive, and moving it to the top of the page.
```
