### ISSUE TITLE
[create-theme]: Move tab close button to the left

### ISSUE THREAD

**Issue by markatom** [zen-browser/theme-store#820]
### Name

Move tab close button to the left

### Description

This mod moves close button to the left. This is very useful when tabs are on the right side of the browser and tabs on hover

### Image

https://imgur.com/a/EANsjlT

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
.tab-content:hover {
	gap: 4.5px;
}

.tab-content:hover .tab-icon-stack {
	display: none;
}

.tab-content:hover .tab-close-button {
	order: -1;
}

.tab-content[selected] .tab-close-button {
  display: none !important;
}

.tab-content[selected]:hover .tab-close-button {
	display: inherit !important;
}
```

### Readme

```markdown
Move tab close button to the left.
```
