### ISSUE TITLE
[create-theme]: Move tab close button to the left

### ISSUE THREAD

**Issue by markatom** [zen-browser/theme-store#823]
### Name

Left close button

### Description

Move the tab close button to the left side

### Image

https://i.imgur.com/gGPu6OB.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
.tab-content:hover {
	gap: 4.5px;
}

.tab-content:hover .tab-icon-stack {
	display: none;
}

.tab-content:hover .tab-close-button {
	order: -1;
}

.tab-content[selected] .tab-close-button {
	display: none !important;
}

.tab-content[selected]:hover .tab-close-button {
	display: inherit !important;
}
```

### Readme

```markdown
This mod moves the tab close button to the left, which is very useful when tabs are on the right side of the browser window and expanded on hover. When the tabs expand, the mouse cursor lands directly on the close button, making it very likely to be clicked by accident.
```
