### ISSUE TITLE
[create-theme]: Customize Font Size

### ISSUE THREAD

**Issue by joadr** [zen-browser/theme-store#828]
### Name

Customize Font Size

### Description

Configure Zen Browser's UI font sizes.

### Homepage

https://github.com/joadr/zen-customize-fonts-size

### Image

https://raw.githubusercontent.com/joadr/zen-customize-fonts-size/refs/heads/main/image.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#tabbrowser-tabs {
  font-size: var(--cfs-font-size-tabbar-tabs) !important;
}

#zen-current-workspace-indicator-name {
  font-size: var(--cfs-font-size-workspace-title) !important;
}

.findbar-container {
  font-size: var(--cfs-font-size-searchbar) !important;
}

.zen-workspace-icon {
  font-size: var(--cfs-icon-size-footer) !important;
}
```

### Readme

```markdown
# zen-customize-fonts-size

# Customize Font Sizes

Configure Zen Browser's UI font sizes.

- Customize Workspace title font size
- Customize Tab's title font size.
- Customize Search Bar font size.
- Customize SideBar footer font size.
```

### Preferences

```json
[
    {
        "property": "cfs.font.size.workspace.title",
        "label": "Workspace font size \"1.5em\" or \"24px\"",
        "type": "string",
        "defaultValue": "1.5em"
    },
    {
        "property": "cfs.font.size.tabbar.tabs",
        "label": "Tabbar tabs font size \"1.3em\" or \"20px\"",
        "type": "string",
        "defaultValue": "1.3em"
    },
    {
        "property": "cfs.font.size.searchbar",
        "label": "Tabbar tabs font size \"1.4em\" or \"22px\"",
        "type": "string",
        "defaultValue": "1.4em"
    },
    {
        "property": "cfs.font.size.footer",
        "label": "Tabbar tabs font size \"1.5em\" or \"24px\"",
        "type": "string",
        "defaultValue": "1.5em"
    }
]
```
