### ISSUE TITLE
[create-theme]: Nav-Bar Padding

### ISSUE THREAD

**Issue by jusnim** [zen-browser/theme-store#835]
### Name

Nav-Bar Padding

### Description

Adds some top- and bottom-padding to the nav-bar so it doesn't look too tight.

### Image

https://i.imgur.com/p6pn1f4.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#nav-bar {
    padding-top: var(--zen-element-separation) !important;
    padding-bottom: var(--zen-element-separation) !important
}
```

### Readme

```markdown
# Nav-Bar Padding

Adds some top- and bottom-padding to the nav-bar so it doesn't look too tight.
```
