### ISSUE TITLE
[create-theme]: NavBar Margin

### ISSUE THREAD

**Issue by jusnim** [zen-browser/theme-store#836]
### Name

NavBar Margin

### Description

Adds some top- and bottom-margin to the navbar so it doesn't look too tight.

### Image

https://i.imgur.com/p6pn1f4.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#nav-bar {
   margin-top: var(--zen-element-separation) !important;
   margin-bottom: var(--zen-element-separation) !important
 }
```

### Readme

```markdown
# NavBar Margin

Adds some top- and bottom-margin to the navbar so it doesn't look too tight.
```
