### ISSUE TITLE
[create-theme]: Audio Indicator Enhanced

### ISSUE THREAD

**Issue by Kaedriz** [zen-browser/theme-store#844]
### Name

Audio Indicator Enhanced

### Description

Enhanced audio indicator, with more polished style

### Homepage

https://github.com/Kaedriz/ZenMods/tree/main/AudioIndicatorEnhanced

### Image

https://imgur.com/sApHgAz

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#tabbrowser-tabs[orient='vertical']
	.tabbrowser-tab
	.tab-icon-overlay:not([crashed]) {
	&:is([soundplaying], [muted], [activemedia-blocked]) {
		background-color: #161717 !important;
		border: 1px solid #ffffff29 !important;
		transition: transform 100ms ease-in-out, background-color 100ms ease-in-out;

		&:hover {
			transition: transform 100ms ease-in-out,
				background-color 100ms ease-in-out !important;
			transform: scale(1.3) translate(-8%, 14%);
			transform-origin: center !important;
		}
	}

    /* Different background color when muted */
	&[muted] {
		background-color: rgb(122, 31, 31) !important;
	}

    /* Revert new, zen's audio indicator */
	&[muted],
	&[soundplaying] {
		list-style-image: none !important;
	}
}
```

### Readme

```markdown
Enhanced audio indicator on tabs, visible when playing videos.

Currently, mod is tailored to dark theme.
For now, mostly just styles it differently, later some customization and matching to color theme is planned.

Works as of `1.0.1-a.22`
```
