### ISSUE TITLE
[create-theme]: bigger browser padding

### ISSUE THREAD

**Issue by froggy-jpg** [zen-browser/theme-store#849]
### Name

bigger browser padding

### Description

makes padding of the browser... well... bigger!

### Homepage

https://github.com/froggy-jpg/bigger-browser-padding

### Image

https://imgur.com/a/eXl5WlG

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
/* padding in normal mode */

@media (-moz-bool-pref: "uc.padding.big") {
    @media not (-moz-bool-pref: "zen.view.compact") {
        #tabbrowser-tabpanels {
            padding: 2px 12px 12px 2px !important;
        }
    }
}

@media (-moz-bool-pref: "uc.padding.bigger") {
    @media not (-moz-bool-pref: "zen.view.compact") {
        #tabbrowser-tabpanels {
            padding: 2px 16px 16px 2px !important;
        }
    }
}

@media (-moz-bool-pref: "uc.padding.biggest") {
    @media not (-moz-bool-pref: "zen.view.compact") {
        #tabbrowser-tabpanels {
            padding: 2px 20px 20px 2px !important;
        }
    }
}

/* padding in compact mode */

@media (-moz-bool-pref: "uc.padding.big") {
    @media (-moz-bool-pref: "zen.view.compact") {
        #tabbrowser-tabpanels {
            padding: 12px !important;
        }
    }
}

@media (-moz-bool-pref: "uc.padding.bigger") {
    @media (-moz-bool-pref: "zen.view.compact") {
        #tabbrowser-tabpanels {
            padding: 16px !important;
        }
    }
}

@media (-moz-bool-pref: "uc.padding.biggest") {
    @media (-moz-bool-pref: "zen.view.compact") {
        #tabbrowser-tabpanels {
            padding: 20px !important;
        }
    }
}
```

### Readme

```markdown
# bigger browser padding
makes padding of the zen browser bigger \
comes in 3 sizes:
- big (12px)
- bigger (16px)
- biggest (20px) 
  
also works in compact mode :3
```

### Preferences

```json
{
    "uc.padding.big": "big browser padding (12px)", 
    "uc.padding.bigger": "bigger browser padding (16px)", 
    "uc.padding.biggest": "biggest browser padding (20px)"
}
```
