### ISSUE TITLE
[create-theme]: 

### ISSUE THREAD

**Issue by eareater** [zen-browser/theme-store#853]
### Name

RainTabs

### Description

Hello! Rain-tabs is a rainy wallpaper with some more functionality to tabs, such as better active tab functionality (flashes color slowly) with a rainy theme, suspicious about code? Check the code here: https://pastebin.com/KEE04TGz

### Image

https://imgur.com/a/QaNVJWI

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#tabbrowser-tabs { background: url('https://i.redd.it/rh416j7r6fzb1.jpg') rgba(255, 255, 255, 0.15) !important; backdrop-filter: blur(25px) !important; border-radius: 10px !important; transition: background 0.3s ease !important; background-size: cover !important; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1) !important; border: 1px solid rgba(255, 255, 255, 0.3) !important; } #tabbrowser-tabs .tabbrowser-tab { background: none !important; } @keyframes cloudySky { 0% { background-color: #ffffff; } 25% { background-color: #e0f7fa; } 50% { background-color: #b3e5fc; } 75% { background-color: #e0f7fa; } 100% { background-color: #ffffff; } } @-moz-document url-prefix("chrome:") { .tab-background { position: relative; backdrop-filter: blur(10px); } .tab-background[selected='']::after { content: ''; position: absolute; width: 3px; height: 100%; background-color: var(--zen-primary-color); animation: cloudySky 3s infinite ease-in-out; } }
```

### Readme

```markdown
Hello! Rain-tabs is a rainy wallpaper with some more functionality to tabs, such as better active tab functionality (flashes color slowly) with a rainy theme, suspicious about code? Check the code here: https://pastebin.com/KEE04TGz
```
