### ISSUE TITLE
[create-theme]: raintabss

### ISSUE THREAD

**Issue by eareater** [zen-browser/theme-store#855]
### Name

RainTabs

### Description

Raintabs is a theme for your tabs. Code: https://pastebin.com/KEE04TGz

### Image

https://us-east.storage.cloudconvert.com/tasks/a2b01ef6-3084-4314-b1d6-d975aa052c70/Screenshot%202024-12-07%20142150.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Credential=cloudconvert-production%2F20241207%2Fva%2Fs3%2Faws4_request&X-Amz-Date=20241207T222808Z&X-Amz-Expires=86400&X-Amz-Signature=4c271557601479660ed87f84001f1c472e5b41a447fb5c4752a086c747708f62&X-Amz-SignedHeaders=host&response-content-disposition=inline%3B%20filename%3D%22Screenshot%202024-12-07%20142150.png%22&response-content-type=image%2Fpng&x-id=GetObject

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#tabbrowser-tabs { background: url('https://i.redd.it/rh416j7r6fzb1.jpg') rgba(255, 255, 255, 0.15) !important; backdrop-filter: blur(25px) !important; border-radius: 10px !important; transition: background 0.3s ease !important; background-size: cover !important; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1) !important; border: 1px solid rgba(255, 255, 255, 0.3) !important; } #tabbrowser-tabs .tabbrowser-tab { background: none !important; } @keyframes cloudySky { 0% { background-color: #ffffff; } 25% { background-color: #e0f7fa; } 50% { background-color: #b3e5fc; } 75% { background-color: #e0f7fa; } 100% { background-color: #ffffff; } } @-moz-document url-prefix("chrome:") { .tab-background { position: relative; backdrop-filter: blur(10px); } .tab-background[selected='']::after { content: ''; position: absolute; width: 3px; height: 100%; background-color: var(--zen-primary-color); animation: cloudySky 3s infinite ease-in-out; } }
```

### Readme

```markdown
Hello! Rain-tabs is a rainy wallpaper with some more functionality to tabs, such as better active tab functionality (flashes color slowly) with a rainy theme, suspicious about code? Check the code here: https://pastebin.com/KEE04TGz
```
