### ISSUE TITLE
[create-theme]: Uncenter URL Bar (2)

### ISSUE THREAD

**Issue by BowDown097** [zen-browser/theme-store#861]
### Name

Uncenter URL Bar

### Description

Reverts the centering of the URL bar on-click introduced in 1.0.2, making the URL bar function more like older versions or standard Firefox.

### Image

https://cdn.imgchest.com/files/739cxzbd2z7.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
/* revert centered URL bar */
@media not (-moz-bool-pref: "uc.urlbar.center") {
    #urlbar[open] {
        top: 0 !important;
        max-width: inherit !important;
        min-width: inherit !important;
        left: inherit !important;
        --urlbar-container-height: 36px !important;

        & #identity-box {
            margin-inline-end: 0 !important;
        }
    }

    @media not ((-moz-bool-pref: "browser.urlbar.searchModeSwitcher.featureGate") or (-moz-bool-pref: "browser.urlbar.scotchBonnet.enableOverride")) {
        #urlbar[open] #identity-box[pageproxystate="valid"]:is(.notSecureText, .chromeUI, .extensionPage) {
            margin-inline-end: 8px !important;
        }
    }
}

/* revert URL bar "breakout" (expansion on-click) */
@media not (-moz-bool-pref: "uc.urlbar.breakout") {
    #urlbar[open] {
        font-size: 1.05em !important;
    }

    #urlbar[breakout][breakout-extend] {
        width: var(--urlbar-width) !important;
        margin-left: 0 !important;

        & > .urlbar-input-container {
            padding-inline: var(--urlbar-container-padding) !important;
        }
    }

    #urlbar #identity-box.chromeUI:not([pageproxystate="invalid"]) #identity-icon-box {
        border-radius: 10px !important;
    }
}
```

### Readme

```markdown
# Uncenter URL Bar

## Description
Reverts the centering of the URL bar on-click introduced in 1.0.2, making the URL bar function more like older versions or standard Firefox.

## Preferences
- ``uc.urlbar.breakout``: Toggle "breakout" (expansion on-click). When disabled, the URL bar will look more akin to standard Firefox.
- ``uc.urlbar.center``: Toggle centering on-click.
```

### Preferences

```json
[
    {
        "property": "uc.urlbar.breakout",
        "label": "Toggle \"breakout\" (expansion on click). When disabled, the URL bar will look more akin to standard Firefox.",
        "type": "checkbox",
        "defaultValue": false
    },
    {
        "property": "uc.urlbar.center",
        "label": "Toggle centering.",
        "type": "checkbox",
        "defaultValue": false
    }
]
```
