### ISSUE TITLE
[create-theme]: No pinned tab reset btn

### ISSUE THREAD

**Issue by spicybackend** [zen-browser/theme-store#865]
### Name

No pinned tab reset btn

### Description

Hides the reset button that appears when hovering over pinned tabs.

### Homepage

https://github.com/spicybackend/zen-browser-no-pinned-url-reset

### Image

https://github.com/spicybackend/zen-browser-no-pinned-url-reset/raw/main/screenshot.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#tabbrowser-tabs {
  & .tabbrowser-tab {
    &[pinned]:not([zen-essential]):hover .tab-reset-button,
    &[pinned][visuallyselected]:not([zen-essential]) .tab-reset-button {
      display: none !important;
    }
  }
}
```

### Readme

```markdown
# No pinned tab reset btn

A zen browser mod that hides the reset button that appears when hovering over pinned tabs.
```
