### ISSUE TITLE
[create-theme]: Better Active Workspace

### ISSUE THREAD

**Issue by Tanay-Kar** [zen-browser/theme-store#870]
### Name

Better Active Workspace

### Description

Makes the active workspace indicator more cohesive for the rounded pill mode UI .

### Homepage

https://github.com/Tanay-Kar/Zen-Themes/tree/df6fcf4f10e95d1c1a08bcfd03f958d32d35c8cb/Better%20Workspace%20Indicator%20Pill%20mode

### Image

https://raw.githubusercontent.com/Tanay-Kar/Zen-Themes/77c8973f31166627482ee6fd4a4220f1b467d933/Better%20Workspace%20Indicator%20Pill%20mode/assets/image.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@media (-moz-bool-pref: "zen.theme.pill-button") {
  #PanelUI-zen-workspaces-list > toolbarbutton {
    &.zen-workspace-button[active="true"] .zen-workspace-icon::before {
      background-color: transparent !important;
    }
  }

  #PanelUI-zen-workspaces-list > toolbarbutton {
    & .zen-workspace-icon {
      border: 3px solid var(--zen-colors-border) !important;
    }
  }
  #PanelUI-zen-workspaces-list > toolbarbutton {
    &.zen-workspace-button[active="true"] .zen-workspace-icon {
      border: 3px solid var(--toolbarbutton-icon-fill-attention) !important;
    }
  }
}
```

### Readme

```markdown
# Better Workspace Indicator

Makes the active workspace indicator more cohesive for the rounded pill mode UI .
```
