### ISSUE TITLE
[create-theme]: Only Reset On Hover

### ISSUE THREAD

**Issue by TheCatRiX** [zen-browser/theme-store#877]
### Name

Only Reset On Hover

### Description

Show pinned tab's reset button only on hover, even on the active tab.

### Image

https://i.ibb.co/5FbYL0b/Only-Reset-On-Hover.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#tabbrowser-tabs .tabbrowser-tab:is([visuallyselected]):not(:hover) .tab-reset-button {
  display: none !important;
}
```

### Readme

```markdown
Show pinned tab's reset button only on hover, even on the active tab.
Zen browser always show the reset button on the active pinned tab by default, and this theme will disable that behavior and make reset button on the active pinned tab only visible on hover.
```
