### ISSUE TITLE
[create-theme]: Hide Workspaces Indicator

### ISSUE THREAD

**Issue by TheCatRiX** [zen-browser/theme-store#880]
### Name

Hide Workspaces Indicator

### Description

Hides current workspace indicator, saving space for more tabs.

### Image

https://i.ibb.co/KFskXPH/Hide-Workspaces-Indicator.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#zen-current-workspace-indicator {
  display: none !important;
}
```

### Readme

```markdown
Hides current workspace indicator, saving space for more tabs.
I find it pretty useless when you can use workspace icons in the toolbar.
```
