### ISSUE TITLE
[create-theme]: Pinned Tabs Max Height

### ISSUE THREAD

**Issue by TheCatRiX** [zen-browser/theme-store#883]
### Name

Pinned Tabs Max Height

### Description

Change max height of pinned tabs.

### Image

https://i.ibb.co/TYP6hRX/Pinned-Tabs-Max-Height.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#vertical-pinned-tabs-container {
  max-height: calc(var(--theme-pinnedtabsmaxheight-number_of_tabs) * (var(--tab-min-height) + 2 * var(--tab-block-margin))) !important;
}
```

### Readme

```markdown
Change max height of pinned tabs.
Go to Settings, Zen Mods, look up "Pinned Tabs Max Height", click the gear ⚙️ button, and set desired number of pinned tabs to fit.
```

### Preferences

```json
[
  {
    "property": "theme.pinnedtabsmaxheight.number_of_tabs",
    "label": "Number of pinned tabs to fit",
    "type": "string",
	"placeholder": "Number of tabs",
    "defaultValue": "5"
  }
]
```
