### ISSUE TITLE
[create-theme]: 

### ISSUE THREAD

**Issue by ajkuftic** [zen-browser/theme-store#886]
### Name

Tab Text Size

### Description

Change tab text size

### Homepage

https://github.com/ajkuftic/Zen-TabTextSize

### Image

https://raw.githubusercontent.com/ajkuftic/Zen-TabTextSize/refs/heads/main/image.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
:root:has(#theme-Tab-Text-Size[uc-tabtextsize-textsize="8"]) { .tab-text.tab-label{ font-size: 8px; }}
:root:has(#theme-Tab-Text-Size[uc-tabtextsize-textsize="10"]) { .tab-text.tab-label{ font-size: 10px; }}
:root:has(#theme-Tab-Text-Size[uc-tabtextsize-textsize="default"]) { .tab-text.tab-label{ font-size: 12px; }}
:root:has(#theme-Tab-Text-Size[uc-tabtextsize-textsize="14"]) { .tab-text.tab-label{ font-size: 14px; }}
:root:has(#theme-Tab-Text-Size[uc-tabtextsize-textsize="16"]) { .tab-text.tab-label{ font-size: 16px; }}
:root:has(#theme-Tab-Text-Size[uc-tabtextsize-textsize="18"]) { .tab-text.tab-label{ font-size: 18px; }}
:root:has(#theme-Tab-Text-Size[uc-tabtextsize-textsize="20"]) { .tab-text.tab-label{ font-size: 20px; }}
:root:has(#theme-Tab-Text-Size[uc-tabtextsize-textsize="22"]) { .tab-text.tab-label{ font-size: 22px; }}
```

### Readme

```markdown
# Tab Text Size

Set the text size for tabs in the sidebar

## What this extension does

Allows the text size for tabs to be changed without modifying themes.

Click the gear icon on the mod to change the text size.
```

### Preferences

```json
[
    {
    "property": "uc.tabtextsize.textsize",
    "label": "Set Tab Text Size: ",
    "type": "dropdown",
    "defaultValue": "default",
    "options": [
        {
            "label": "8",
            "value": "8"
        },
        {
            "label": "10",
            "value": "10"
        },
        {
            "label": "Default (12)",
            "value": "default"
        },
        {
            "label": "14",
            "value": "14"
        },
        {
            "label": "16",
            "value": "16"
        },
        {
            "label": "18",
            "value": "18"
        },
        {
            "label": "20",
            "value": "20"
        },
        {
            "label": "22",
            "value": "22"
        }
    ]
    }
]
```
