### ISSUE TITLE
[create-theme]: Hidden Reset Button

### ISSUE THREAD

**Issue by AlexCookieDev** [zen-browser/theme-store#900]
### Name

Hidden Reset Button

### Description

Hide the reset button behind the tab icon unless hovered.

### Image

https://i.imgur.com/1YgPxvw.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
/* Hidden Reset Button - Hide the reset button behind the tab icon unless hovered. */
.tab-icon-stack, .tab-reset-button {
    transition: scale .2s cubic-bezier(0.175, 0.885, 0.320, 1.275), opacity .1s ease-in-out, transform .3s cubic-bezier(0.175, 0.885, 0.320, 1.275);
}
.tab-reset-button {
    transform: rotate(-.5turn);
    width: 24px !important;
    margin: 0;
    margin-right: -24px;
    order: -1;
    z-index: 1;
    opacity: 0;
    scale: .5;
    overflow: hidden !important;
}
.tab-reset-button:hover {
    transform: rotate(0);
    opacity: 1;
    scale: 1;
}
.tab-label-container {
    padding-left: 6px;
}
.tab-icon-stack:has(~ .tab-reset-button:hover) {
    opacity: 0;
    scale: 0;
}
.tab-content .tab-icon-stack {
    padding: 4px;
    width: 24px;
}
.tab-icon-stack .tab-icon-image {
    padding: 0;
    margin: 0 !important;
}
```

### Readme

```markdown
# Hidden Reset Button
Hide the reset button behind the tab icon unless hovered.
```
