### ISSUE TITLE
[create-theme]: Show UniExtBtn on Hover

### ISSUE THREAD

**Issue by quinut** [zen-browser/theme-store#907]
### Name

Show UniExtBtn on Hover

### Description

Show UniExt Button(the jigsaw puzzle-shaped extension icon) only when hovered.

### Image

https://github.com/quinut/zen-css/blob/eba59164848d4466c845d2694d3bcfa23fe8b052/Show%20UniExtBtn%20on%20Hover/Show%20UniExtBtn%20on%20Hover.png?raw=true

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#unified-extensions-button {
  opacity: 0;
  transition: opacity 0.2s ease-in-out;
}

#unified-extensions-button:hover {
  opacity: 1;
}
```

### Readme

```markdown
# Show UniExtBtn on Hover
Show unified extensions button(the jigsaw puzzle-shaped extension icon) only when hovered.
```
