### ISSUE TITLE
[create-theme]:  Floating search

### ISSUE THREAD

**Issue by pokhrelashok** [zen-browser/theme-store#909]
### Name

Floating Search

### Description

A clean floating search activated using keyboard

### Homepage

https://github.com/pokhrelashok/zen-floating-search

### Image

https://raw.githubusercontent.com/pokhrelashok/zen-floating-search/refs/heads/main/demo.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#zen-appcontent-navbar-container {
  opacity: 0 !important;
}

#urlbar {
  display: none;
  opacity: 0;
  height: 0;
  padding: 4px !important;
  ;
}

#urlbar:is([breakout-extend][open], [open][usertyping][focused]) {
  opacity: 100;

  #urlbar-input {
    font-size: 17px !important;
  }

  min-height: 40px !important;

  .urlbar-input-container {
    min-height: 40px !important;
  }

  z-index: 2;
  position: fixed !important;
  bottom: auto !important;
  top: 30vh !important;
  padding-left: 6px !important;
  padding-right: 8px !important;
  left: 35vw !important;
  width: 30vw !important;

  &:after {
    content: "";
    position: fixed;
    pointer-events: none;

    width: 100vw;
    height: 100vh;

    top: 0px;
    left: 0px;

    background-color: rgba(0, 0, 0, 0.3);
    backdrop-filter: blur(5px);

    z-index: -1;
  }

  #identity-box {
    margin: auto 0;
    height: 30px;
    margin-right: 10px;
  }

  .urlbar-go-button {
    margin: auto 0;
  }
}
```

### Readme

```markdown
# Floating Search Mod for Zen Browser
Works best with `Compact Mode` with `Hide Top Bar` option.
Press `ctrl+l` to show search.
```
