### ISSUE TITLE
[create-theme]: Winter Spirit

### ISSUE THREAD

**Issue by Kaedriz** [zen-browser/theme-store#911]
### Name

Winter Spirit

### Description

Adds an animated snowflake overlay

### Homepage

https://github.com/Kaedriz/ZenMods/tree/main/WinterSpirit

### Image

https://i.imgur.com/Nz7YX4m.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
@keyframes snowing {
	from {
		background-position: 0px, 0px;
	}
	to {
		background-position: calc(var(--snowsize) * 2), var(--snowsize);
	}
}

#browser::after {
	--snowsize: var(--zen-mods-WinterSpirit-snowflakeSize, 350px);
	--snowfall: var(--zen-mods-WinterSpirit-duration, 30s);
    
	content: '';
	position: fixed;
	top: 0;
	left: 0;
	right: 0;
	bottom: 0;
	z-index: 0;

	background-image: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAfQAAAH0AgMAAAC2uDcZAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAMUExURQAAAP///////////zjAO6gAAAAEdFJOUwAuxHKQ3Q8qAAADW0lEQVR42u3dP26jQByGYUbaEe0Wi+jgKj5CirjFp9gGKXAfkOUmW+YOW2QvgdtN45XlHMAgB2aYz955nzrJp2AYM39/SYJrmTLcbDfK9MtvYbod3oXp6fCqTO8iTpdeeaNNP/1VprfKJy7ZPinTLV91AAAAAAAAAAD4kkkH/XfKCQ/TSCd7Tm/K9GHv9+89KdOzrTK9PM/68dpverXfzPnxxu9d1/Sz0ncfXtPreenZszLd+G1pq17Zchfz/nfPyoMyPT0r0802AQDMYZWt9uS7R5jWfOK9y7wEuSYT75z2EuQNph5/QU67IItrJ14S0+5dmv4aQfpBmT7RLUuHIGMO+XiXNNCCcjve1pk2TI9lIkW6lB8AAACITcxTza12qvmXMt3zdCvpX//clelJ/SZ93j+U6bl0J6+VtrQAAAAAAADwxz4r03PpGNtOOr7YLN2D8MNHer1w/4WfA00Xp3tZ8bk03R59DMo2C9PTzscUUHFYmu5j1WN+VqbbhWul/aSbhS2t5UBTFfGBppsEAAAA+Mp7qzJcW/Ik0J7QqZ7ioCy4EmhP6Kq9ZNKX3HXaEQLtwmjlEyfeE/qNrzoAc1+SmPQTaaQHj9U96RqVNF172F4uPe7OSlsbI21pAQAAAPyPjHSlWibt5WgPami0R2QwnhRleqMtn7BXpudn5ROnHTtPOJgFAIA7c58VQgL1wpT7xHxXpZvZ+a73MadH3Adc83+/OaRTrXnP39wrW6456nJzycCqvbCb1QFXHW0rxEtF3NbTun0whWNNJbfKiq7pblUlXa+8232TH9zuabdrZx2XCLmlu1bEdLxvvkvTXVvqXrrj5aJsK81P6fs+S8sAAAAAAAAAAAAAPJKYS3430pP3B0p+R5lOyW8VSn4DAAAAANbt80t3EljpLoqAO0hGLnPA3TMjGzoD7hwa2dAZMH1kY17A9KK/GlrJA6ZfR6XSdHtRpps22DhXOfJwh6sXkx6VA3pWeua7kRZAw0OSlnIK2CyNpf9TTj1oC5xri6dZ8TRrxOknadG8Vnpc0k7a48uULS0AAHhQDFiL5L2yn6o96irm9LzTFraXph/d0t1Oi3QdGcr+OP2646hYKa3VUEmrozRRV0eRfk/EXG1Xes8z7wMAAHAHPgHhchfsTyUPMgAAAABJRU5ErkJggg==),
		url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAfQAAAH0AgMAAAC2uDcZAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAMUExURQAAAP///////////zjAO6gAAAAEdFJOUwAXO2Yymfg6AAAId0lEQVR42u1dS27jOBA1gWFO0NTCcxkfwYtIwMjrXrS08FVmEd9gvIgMtG7Qukxn4dwgXljDIIOeWCYlip96nbjeMgH8bIksFlmvHhcLBuNTQq6Q7Pk9kr3cA8lFfQQ+etGe11D2v5HsPZJ9i2Rf1P0DcsYh3/sia4BjfiFzbKjlte5Drs/QFTJHjllR7IHzVVaPSPbDM/DFZ+0JuEpk3ZmGXSHZRW4aXgUVe/UAZJft3vjkTyRj/q47Gsf885qG/cUQU1XzOB1p5ToC+3llinW7aXYVnkFII7vIHT65dHg+07sO02fk009V1KfgR68/w/MXiG2ErNn7+en9SnhM8B87Mdj9cyjsbmkDZc9+INkldK8msHu1L7zvYTAYDAaDwWAwGAwGg8GAQ9iONBVFpV1+W5n/kecE52ZZYz6QFsUjQQUnsxyLyqohYF/2T2b2A0XNdNkfzezteUfB/mJ+I12/o3jvVnYCIZ+5akhVLxaHPZK9NL9eRaMTUOZpLRuSGoGwRGCoPkRAlTmLHKomUxcP3lLdIyrhWFZ7FbAMK/dVzFLVzf2XYTHj1W6MGmJRNt5BQRQ757dmrs2K6vyPd1I1Y0qb69Ky7r3Z1cFdgFL3P41JgD+7Ft84s2+isxczpD9LI00Ie9m7L6L/VcUHczSQ3fm3y7cMdxD8dfL34M/u/t7fJGvDOSqr5wl2e5dHMWPUvcn1hnNUR5u1b0Ar2rlL+HCOTkpUZbm3BTTV7GeuUFqWeT9Yhsc/QavKbF9PVbvZEWIwyqZkNSOKOjm78acwzlG1WvgMrdmLszlCjPyIOdPK77eLak/EborNoj3SsGft8frDZGfX0kVlN8oytYrRylB2x3jsRlmmGGEvvoerJMcD51jn1ruApsIPYkxzdEwJqcpfX7dIdBywsY+sdwGtjPgOLmbCyOf+vw7Uifr6nLqXkvW2CZfxFEWp6o+tfwoYY2xC2ZdYpWoDVap+QypVF1ilKoPBYDAYDAaDwWAwGAwGg8FgMBiMD4QRZQUBoL6wY8oKAvYt1hf2FIHd11R4TNuQfvBo9vDqtfSVRkdxeVLV3vPR1xHYM6uJ2ZRzWRlBs1NYpTdTrySLoOS3y46m9CAxfGGt7NOuYxEirZ19S+AyPcIeXY1yrWsq+6OVPbYq4boLp+xsgyu6c5morqgKq4I1unOZYV1SjU3BGt25zOCWrqyrTHTnMoPmTloVrNHbXkyzSNknyCI9e6LMx/Q+N1R+5cr02sj8yo1EMpGO8TqsmR6yoOow24AtHn9C2Z+A7H8Gsoug1CULZFeWQOv2pWQbJte0tPlLt84Gs/uz+4Mvzf2FynHnFWZRYGvzLxy7/2XY/s7ca6XbkAg64F97cHbG93ne49h10yMRu7Hlsu1997yfgp0iOWmN3ZlE7NLcxCZrCscLHW2M71dUJJpzS/OiDsAkmaE5ngsSj5mRpW+FI1fgnw4kBx+Lt8hj8bGGQ4Lf3kEva+tu+Kq4LfTCsvKEjDbZI3DMOxyLi5Sx+H76+yFrlKpBLgX64Bc4J0uSlNvGXvfHW2WXWPYt+LdjRx10xpEcbtjZkZE2/4pcgxW0vVdAL5+MM2+h7NDdoiiRlQ1RP0K3iy/Q7eKn2bDNdnKJuWETsw88Ym7YZLmbO4Yiuq+MeHfZsIxXL/a4DVPFy4/mmBH+Girxdt39CbjuzbEDTMGOPHJAsye6AVa6sSc603fKQepzmt2NUw4iUpVybK7ZgyUjkXm57BxykGSmVea7dodIZVrllgHVidjdMqBUllluqtdklllOOYjNMkuExqCycRh14q+1ZbcbmjQ5RTHLnjr4vDsoBymRWwbwRcc12DrvdjV4Syh71iHfu4TaBgro2VDS/j65Qv4ybO9gCRVJ1B+/dzBtzpfut2NlCj1SpoBln+rRSFson+jRkGmj/IRIQqWNhRP5boHUKIBrlhWyXoutVWtZ8NMNsyPfO5adRpBtnXHIbN7WEUOV8uZYjQIy3V/Mme3Qbyqx2vGvyBFa0KzG5mo1VS5gadag0W7pq6hMM0Gr5ihyAcvVeUSrsb6W6x7HnnXI9ihsa5j5Wi6qXMBycZ8guQjaphPQl2BTxHnb/WY07VHGa7nIcgHVIFsTjNdyEWYR0CQGe2rNYDAYDAaDwWD8TlBQ7QF0Z+DRLRF3RwjcmHh0SxCcBNDgtjsGbpg95k3n88d8izwByhpgfV2bfEPjPFRf9ymuO5bQEzyFHLt0nrbmoHXGmr1iZe5PN8sOlrlD2eV3qCS5Qs44cLniD/RKgzXwwJqXQEVREUxrpP8HyPACeOFfv7dYJM9ap/2ze9WGSg9EgItD1oU2E4c4WMRg928EtChR5iCEPXzUBbQhWiyS523nvb+/bIKz6sxfPivL4B1FwJ0pIlzwEnJnSv7xLbIYDAbjpgC931RAVw2sglBf2wZ89AX05F57POHYtW8y2Ll4DWVfMTtm1CWfcfkIe/LOnzEfjyJ5H8KYh0n6u0ruuv3IKpP6td/1R/s/vyySsyMdZu96pNcG+joUKDvUY2VRQqu39K2+772EBHkCkYP1fMg5XkE1Llg9X/fMqjJmvy12rJ4Pq6hDegXpRRV6rR9WIoH1DmEwGL8rBNYhFdtnj1UvIbNvWSEv/NJKDqBiMYKG5lOzSyR7wlTJgT1h2S5rJ3ceCVNkh73++PZAhoQLh3OOshsr26mQBzPds/latht5PGVQRXHyfGuibBd239WkT7hmHztkT+w7fF04u5BTb9NemXDNfiGn3qbtJXk1sF3ZE5LEnSy6bLcf/uHdo18m7qMZGhdfeotmP9KukUPTZnl4L2iWifunhmW7Sx85kfpE+n6YjF242BH3U6gO6acLZm+Rbr7ygEzCsRsQfYUE1CcW27TzoeTU/wJHgZKTCUhpgwAAAABJRU5ErkJggg==);

	background-repeat: repeat, repeat;
	background-attachment: scroll, fixed;
	background-origin: padding-box, padding-box;
	background-clip: border-box, border-box;

	height: 100vw;
	background-size: var(--snowsize) auto !important;
	animation: snowing var(--snowfall) infinite linear;

	transform: rotate(90deg);
}
```

### Readme

```markdown
Adds an animated snowflake overlay, that is displayed atop your background. Size and speed of snowflake falling is customizable.

Won't be as noticeable, if even, on whiter backgrounds.

Works as of `1.0.2-b.3`
```

### Preferences

```json
[
    {
        "property": "zen.mods.WinterSpirit.snowflakeSize",
        "label": "Changes scale of background",
        "type": "string",
        "defaultValue": "350px"
    },
    {
        "property": "zen.mods.WinterSpirit.duration",
        "label": "Changes background animation speed",
        "type": "string",
        "defaultValue": "30s"
    }
]
```
