### ISSUE TITLE
[create-theme]: Rose Pine Theme

### ISSUE THREAD

**Issue by seanPruss** [zen-browser/theme-store#923]
### Name

Rosé Pine

### Description

Rosé Pine colour scheme for Zen Browser. Forked from @feco to use main theme instead of Dawn theme,

### Homepage

https://github.com/seanPruss/zen-rose-pine

### Image

https://github.com/seanPruss/zen-rose-pine/blob/1b9b28c77c828addb4838f6fd7f056043e78c195/preview.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#zen-main-app-wrapper {
	background-color: #191724 !important;
}

#appMenu-mainView {
	background-color: #26233a !important;
}

#appmenu-moreTools {
	background-color: #26233a !important;
}

#PanelUI-button {
	--button-active-bgcolor: black !important;
}

toolbox#navigator-toolbox {
	background-color: #191724 !important;
}

#zen-appcontent-navbar-container {
	background-color: #191724 !important;
}

.menu-text {
	color: #e0def4 !important;
}

.menuitem-iconic {
	color: #eb6f92 !important;
}

:not(:not(menubar) > menu, #ContentSelectDropdown)
	> menupopup
	> menuitem:not(
		.menuitem-iconic,
		[type="checkbox"],
		[type="radio"],
		.in-menulist,
		.in-menulist menuitem,
		.unified-nav-current
	),
:not(:not(menubar) > menu, #ContentSelectDropdown)
	> menupopup
	> menu:not(
		.menu-iconic,
		[type="checkbox"],
		[type="radio"],
		.in-menulist,
		.in-menulist menu,
		.unified-nav-current
	),
#toggle_toolbar-menubar,
#PanelUI-history toolbarbutton,
#unified-extensions-context-menu menuitem {
	fill: #e0def4 !important;
}

html#main-window {
	--lwt-text-color: #e0def4 !important;
	--toolbarbutton-icon-fill: #eb6f92 !important;
	--toolbar-field-color: #31748f !important;
	--toolbar-field-focus-color: #31748f !important;
	--toolbar-field-background-color: #1f1d2e !important;
	--toolbar-field-focus-background-color: #1f1d2e !important;

	--zen-colors-primary: #d7827e !important;
	--zen-colors-secondary: #26233a !important;
	--zen-colors-tertiary: #191724 !important;
	--zen-colors-border: #191724 !important;
	--zen-dialog-background: #26233a !important;

	--arrowpanel-color: #e0def4 !important;
}
```

### Readme

```markdown
# `zen-rose-pine`

A theme around the Rosé Pine colors for the Zen-browser

Forked from [feco's](https://github.com/feco) [Rosé Pine Dawn](https://github.com/feco/zen-rose-pine-dawn) theme

![Rose Pine Preview](./preview.png)
```
