### ISSUE TITLE
[create-theme]: Download BG

### ISSUE THREAD

**Issue by different55** [zen-browser/theme-store#926]
### Name

Download BG

### Description

Add a background to the active download indicator.

### Homepage

https://github.com/different55/download.bg

### Image

https://github.com/different55/download.bg/blob/main/Download.BG.png?raw=true

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#downloads-indicator-progress-outer::after {
  content: '';
  display: block;
  position: absolute;
  inset: 0;
  z-index: -40;
  background: var(--toolbar-field-background-color);
}
```

### Readme

```markdown
# Download BG
Add a background to the active download indicator.
```
