### ISSUE TITLE
[create-theme]: Quitefy Audio TabIcon Plus Adapter

### ISSUE THREAD

**Issue by NikitaMikhaliuk** [zen-browser/theme-store#929]
### Name

Quitefy Audio TabIcon Plus Adapter

### Description

Allows to show site icon when both Quietify and Audio Icons Plus are on 

### Image

https://i.imgur.com/olY5L1c.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
.tabbrowser-tab:is([soundplaying], [muted], [activemedia-blocked]) img {
      opacity: unset !important;
  }
  #zen-essentials-container {
      .tabbrowser-tab:is([soundplaying], [muted], [activemedia-blocked]) img {
          opacity: unset !important;
      }
  }
```

### Readme

```markdown
# Quietify adapter for Audio TabIcon Plus
Allows to show site icon when both Quietify and Audio Icons Plus are on
```
