### ISSUE TITLE
[create-theme]: Larger icon picker

### ISSUE THREAD

**Issue by elbunuelo** [zen-browser/theme-store#941]
### Name

Larger icon picker

### Description

Makes the icons in the workspace icon picker larger

### Image

https://i.imgur.com/sXNdCnA.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#PanelUI-zen-workspaces-icon-picker-wrapper {
  font-size: 2.5rem;
  padding: 0.5rem;
}
```

### Readme

```markdown
# Description

I felt the icons in the workspace icon picker were too small, so this mod makes them a bit larger for a lovable icon picking experience.
```
