### ISSUE TITLE
[create-theme]: Better Tab Scrollbar

### ISSUE THREAD

**Issue by JSGRD22** [zen-browser/theme-store#943]
### Name

Better Tab Scrollbar

### Description

Makes the scrollbar track of the tab list transparent

### Homepage

https://github.com/JSGRD22/Zen-Themes/tree/main/Better-Tab-Scrollbar

### Image

https://github.com/JSGRD22/Zen-Themes/blob/main/Better-Tab-Scrollbar/image.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
scrollbox:nth-child(5) {
    scrollbar-color: grey transparent !important;
    scrollbar-width: thin !important;
}

/* Pinned Tabs */
#vertical-pinned-tabs-container {
    scrollbar-color: grey transparent !important;
    scrollbar-width: thin !important;
}
```

### Readme

```markdown
# Better Tab Scrollbar

The scrollbar of Zen Browser's tab list can look ugly with a grey background especially on light mode.

![image](https://github.com/JSGRD22/Zen-Themes/blob/main/Better-Tab-Scrollbar/image.png)

This mod simply tweaks the scrollbar to make the scrollbar track transparent and therefore more pleasing to the eye.
```
