### ISSUE TITLE
[create-theme]: Spotlight Search to access Settings, Extensions, Workspaces, Downloads

### ISSUE THREAD

**Issue by b3ll9trix** [zen-browser/theme-store#947]
### Name

Search Everything

### Description

A Spotlight Search that searches everything

### Image

https://imgur.com/a/JbuFkhn

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#navigator-toolbox {
    --toolbar-bgcolor: #2b2a33;
    --toolbar-color: #ffffff;
    --chrome-content-separator-color: #1c1b22;
  }

  /* Active tab */
  .tab-background[selected="true"] {
    background-color: #38383d !important;
  }

  /* Inactive tabs */
  .tab-background:not([selected="true"]) {
    background-color: #2b2a33 !important;
  }

  /* URL bar */
  #urlbar-background {
    background-color: #1c1b22 !important;
    border-color: #1c1b22 !important;
  }
}
```

### Readme

```markdown
A Spotlight Search Bar that searches across the browser. Accesses settings, extensions, downloads, workspaces, splits views, Zen Mods and more.
```

### Preferences

```json
{
  "search-everything": {
    "filters": {
      "include": {
        "settings": {
          "enable": true
        },
        "workspaces": {
          "enable": true
        },
        "extensions": {
          "enable": true
        },
        "downloads": {
          "enable": true
        },
        "split-view": {
          "enable": true
        }
      }
    }
  }
}
```
