### ISSUE TITLE
Add Theme:  Border-less Zen UI

### ISSUE THREAD

**Issue by immayurpanchal** [zen-browser/theme-store#976]
### Name

Border-less Zen UI 

### Description

Border less Zen browser in compact mode

### Homepage

https://github.com/immayurpanchal/Border-less-Zen-UI-

### Image

https://github.com/immayurpanchal/Border-less-Zen-UI-/blob/main/Thumbnail.png?raw=true

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
:root[zen-compact-mode='true']:not([customizing]):not([inDOMFullscreen='true']) {
	@media (-moz-bool-pref: 'zen.view.compact.hide-tabbar') or (-moz-bool-pref: 'zen.view.use-single-toolbar') {
		& #zen-appcontent-wrapper {
			margin-left: 0 !important;
		}
	}
}

:root[zen-compact-mode="true"]:not([customizing]):not([inDOMFullscreen="true"]) {
  @media (-moz-bool-pref: "zen.view.compact.hide-tabbar") or (-moz-bool-pref: "zen.view.use-single-toolbar") {
    & #zen-tabbox-wrapper {
      margin: 0 !important;
    }
  }
}

:root[zen-single-toolbar='true']:not([customizing]) {
	& #zen-appcontent-navbar-container {
		display: flex;
		-moz-window-dragging: drag;
		min-height: 0 !important;
		height: 0 !important;
	}
}
```

### Readme

```markdown
# Border-less Zen UI 
- Convert zen browser's compact mode to truly zen by making completely border-less (removes padding)
```

### Preferences

```json

```
