### ISSUE TITLE
[create-theme]: New Tab Page Design Change

### ISSUE THREAD

**Issue by XolifyDev** [zen-browser/theme-store#979]
### Name

New Tab Page Design Change

### Description

Changes to the new tab page

### Image

https://imgur.com/a/HzTmDJb

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
body {
  --newtab-background-color: #000000
}
.logo-and-wordmark-wrapper, .logo-and-wordmark {
  display: none !important;
}
```

### Readme

```markdown
- Updates the --newtab-background-color variable
- Removes the Zen Browser logo and name to make it more sleek and simple
```

### Preferences

```json

```
