### ISSUE TITLE
[create-theme]:   Zen Mac Traffic Light

### ISSUE THREAD

**Issue by lirena00** [zen-browser/theme-store#982]
### Name

Zen Mac Traffic Light

### Description

A zen mod for transforming classic windows exit menu into mac traffic light buttons. 

### Homepage

https://github.com/lirena00/zen-mac-traffic-light

### Image

https://github.com/lirena00/zen-mac-traffic-light/blob/main/images/icon.png?raw=true

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
.titlebar-buttonbox {
  display: flex !important;
  justify-content: center !important;
  align-items: center !important;
  height: 42px !important;
  margin-right: 8px;
}

.titlebar-button {
  padding: 1px !important;
  height: 16px !important;
  width: 16px !important;
  margin-left: 5px !important;
  border-radius: 50px;
  transition: all 100ms;
}

.titlebar-min {
  background-color: hsl(110, 54%, 49%) !important;
}

.titlebar-max,
.titlebar-restore {
  background-color: hsl(47, 78%, 56%) !important;
}

.titlebar-close {
  background-color: hsl(3, 100%, 66%) !important;
}

.titlebar-button > image {
  visibility: hidden !important;
}

.titlebar-button:hover > image {
  visibility: visible !important;
  filter: brightness(0);
  margin-bottom: 1px !important;
}

.titlebar-button:hover {
  opacity: 0.75 !important;
}
```

### Readme

```markdown
# Zen Mac Traffic Light

A zen mod for transforming classic windows caption buttons into mac traffic light buttons.

Thanks to [zen-minimal-exit-menu](https://github.com/Dinno-DEV/zen-minimal-exit-menu/tree/main) for the base code
```

### Preferences

```json

```
