### ISSUE TITLE
[create-theme]: Shy Switchy Sidebar

### ISSUE THREAD

**Issue by different55** [zen-browser/theme-store#985]
### Name

Shy Switchy Sidebar

### Description

Prevent compact mode sidebar from popping up when switching tabs by keyboard.

### Homepage

https://github.com/different55/ShySwitchySidebar

### Image

https://jaromino.com/Files/ShySwitchySidebar.png

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
:root[zen-compact-mode="true"]:not([customizing]):not([inDOMFullscreen="true"]) {
  @media (-moz-bool-pref: "zen.view.compact.hide-tabbar") or (-moz-bool-pref: "zen.view.use-single-toolbar") {
    &:not([zen-right-side="true"]) #navigator-toolbox[flash-popup] {
      left: calc(-1 * var(--zen-sidebar-width) + var(--zen-element-separation)) !important;
    }
    
    &[zen-right-side="true"] #navigator-toolbox[flash-popup] {
      right: calc(-1 * var(--zen-sidebar-width) + var(--zen-element-separation)) !important;
    }
  }
}
```

### Readme

```markdown
# Shy Switchy Sidebar
Prevent compact mode sidebar from popping up when switching tabs by keyboard.
```

### Preferences

```json

```
