### ISSUE TITLE
[create-theme]: Centered Floating URL Bar

### ISSUE THREAD

**Issue by logicsec** [zen-browser/theme-store#994]
### Name

Centered Floating URL

### Description

Mod that centers the URL bar

### Image

https://imgur.com/a/gqoSiIC

### Type

- [ ] JSON Color Theme

### Theme Styles

```css
#urlbar[open][zen-floating-urlbar='true'] {
  position: absolute !important;
  top: 50% !important;
  left: 50% !important;
  transform: translate(-50%, -50%) !important;
}
```

### Readme

```markdown
Zen Centered Floating URL Bar

This mod centers the URL bar (similar to the style seen in browsers like Arc) when it is in the "open" state and the custom attribute zen-floating-urlbar is set to "true". This gives your URL bar a clean, focused, and modern look.

Features

    Centered URL Bar: Positions the URL bar in the center of the screen.
    Conditional Activation: Activates only when the URL bar is open and the custom attribute is enabled.
    Customizable: Easy to tweak for additional styling or behavior.
```

### Preferences

```json

```
